== Prefacio a la Tercera Edición, 1837

Hay entre los Cristianos en el presente un sentimiento generalizado e imperante,
de que estamos al borde de grandes cambios, tanto en el mundo externo y visible,
como en el interno y espiritual; porque "`la noche está avanzada,
y el día está por llegar.`"

En realidad, muchos han sido despertados de su sueño, y según sus ideas,
son personas convertidas;
pero en lugar de '`desechar las obras de las tinieblas y vestirse de las armas de luz`',
han sido arrulladas nuevamente bajo el sonido de la tradición y enseñanza humana.
Se vuelven, es cierto, pero sólo de un lado hacia el otro;
y si previamente soñaban con los tesoros y placeres del mundo,
ahora sueñan que son espiritualmente '`ricos, y que están enriquecidos,
y que no tienen necesidad de nada`'; mientras que ante el ojo de Dios que todo lo ve,
todavía son '`desventurados, y miserables, y pobres, y ciegos,
y desnudos`'. Sueñan que '`pelean la buena batalla de la fe`',
que '`corren la carrera que tienen por delante`',
y que al morir recibirán una corona de gloria,
mientras todavía reposan en el lecho de su naturaleza no regenerada,
sin vencer a un solo enemigo espiritual, o erradicar una sola propensión terrenal.
Sueñan que están vestidos de la justicia de Cristo,
y que se presentan delante del rostro del Padre sin contaminación y sin mancha,
mientras que al mismo tiempo,
virtualmente niegan el poder de la sangre de Cristo para limpiarlos durante la vida
presente de la corrupción de sus naturalezas y de las impurezas que contrajeron.
Y finalmente, sueñan que tienen comunión con Dios y con Cristo,
y comunión con Sus santos,
mientras no creen en la posibilidad de oír la voz de Dios dentro de ellos,
y bajo la influencia de principios prejuiciosos y carnales,
se unen exclusivamente a alguna secta o partido en particular,
y rechazan todo lo que no sea de su forma de pensar.

Algunos, en efecto,
empiezan a abrir sus ojos y a ver la necesidad de un andar religioso más decidido,
y de un mayor fervor en la consecución de la santidad.
Ven también, que la unión hace la fuerza,
y que una '`casa dividida contra sí misma no puede permanecer`'; o en otras palabras,
que en tanto las sectas y divisiones continúen en la iglesia Cristiana,
el reino de Cristo sólo puede prosperar parcialmente.
De ahí que se escriba y se enseñe tanto, con el fin de alcanzar estos objetivos,
pero generalmente de una manera superficial.
Para que ellos sean realmente efectuados,
'`el hacha debe estar puesta a la raíz del árbol`',
la herida debe ser examinada hasta el fondo, '`las cosas viejas deben pasar,
y todas las cosas deben ser hechas nuevas`';
debe suceder una completa y total renovación de todo el hombre,
y una restauración a la imagen de Dios a través de la operación del Espíritu Santo.
Una vez que el árbol es hecho bueno, entonces naturalmente dará fruto bueno;
un solo espíritu animará entonces a todas estas personas, y al ser el Espíritu de Dios,
los llevará a la comunión con Dios y entre sí,
lo cual es el plan y propósito de Dios con respecto al hombre caído. (Juan 17)

La necesidad de esta total regeneración, los medios para alcanzarla,
y los caminos secundarios que se desvían de ella,
constituyen el tema de la siguiente obra.
Dos ediciones de la cual, tras haber tenido una rápida venta, se solicitó una tercera.
Al traductor le agradaría interpretar esta circunstancia como una prueba de que
el número de los que desean recorrer las sendas de la vida interior está en aumento,
y espera también que sea una señal del nacimiento de un mejor y más brillante día.

[.signed-section-signature]
Samuel Jackson, 1837
