== Sobre la Naturaleza y Utilidad de la Verdadera Piedad

[.blurb]
=== "`La piedad para todo aprovecha, pues tiene promesa de esta vida presente, y de la venidera`". 1 Timoteo 4:8

Es muy lamentable que en estos últimos tiempos oscuros y corruptos, la piedad, devoción,
o el verdadero servicio a Dios y religión (pues todos son una y la misma cosa),
se hayan convertido en algo tan raro y poco conocido sobre la tierra; más aún,
incluso entre los Cristianos,
o entre aquellos cuya profesión o carácter peculiar debe ser, según la Palabra de Dios,
dejar que su bondad brille como luces ante los ojos de otras
naciones sobre la tierra...que incluso entre estos,
digo, la verdadera devoción o piedad es tan poco conocida,
que universalmente manifiestan repugnancia ante el nombre mismo de la devoción;
o si hablan de la piedad, ni siquiera saben de qué están hablando;
y cuando otros se forman una idea de la piedad, pronto se percibe,
al examinarla de cerca en la luz de Dios,
que los conceptos que tienen de ella están muy lejos de
estar en concordancia con la naturaleza de la cosa misma,
y que a pesar de toda la apariencia externa y forma de piedad,
su poder es universalmente desconocido,
e incluso rechazado como mera imaginación y error.
Por lo tanto, me he sentido impulsado a darles una definición de ella, en esta ocasión,
con toda la brevedad posible, según la medida de luz y gracia que Dios conceda.
Si todavía se pudiera encontrar en algún lugar una iglesia de Cristianos primitivos,
tal como existía en los dos o tres primeros siglos,
la tarea sería innecesaria y me estimaría feliz de aprender de ellos,
y leer en ellos--como cartas vivas escritas por el Espíritu de Dios (2 Corintios 3:2-3)--algo
de aquello sobre lo que me estimo demasiado carente e indigno para escribir con tinta.

=== I. Lo que NO es la naturaleza de la verdadera piedad.

A fin de formarnos una idea de la naturaleza,
excelencia y esencia de la verdadera piedad, o describir a un verdadero hombre piadoso,
es razonable: En _primer lugar,_
que no dirijamos nuestros pensamientos a las cosas que el hipócrita
y el impío puedan tener en común con los que son realmente piadosos.
En _segundo lugar,_ a nada que sólo posean los piadosos, pero sólo algunos de ellos.
En _tercer lugar,_ a algo que todos posean, pero no todo el tiempo.
Sino que debemos buscar esas características que sólo poseen los verdaderos piadosos,
y todos ellos, y en todo tiempo.
Esto es tan evidente que nadie puede negarlo.
Veamos, con toda brevedad, qué resulta de estas proposiciones.

_En primer lugar,
la naturaleza de la verdadera piedad no consiste en algo que los impíos
y los hipócritas tengan en común con los verdaderamente piadosos._

De ahí, que cuando nos abstenemos de vicios grotescos, cuando no maldecimos,
ni nos embriagamos, ni robamos, ni peleamos, etc.,
sino que externamente llevamos una vida social sobria, justa, decorosa,
retirada y tranquila, no es prueba suficiente de que somos piadosos y devotos; más aún,
aunque tuviéramos todo esto, y nada más, o nada más sustancial,
sólo estaríamos al nivel de los impíos y de los hipócritas.

Podemos diligentemente asistir a ceremonias externas, que son buenas en sí mismas,
y realizar deberes piadosos; podemos ser bautizados,
e ir a la iglesia y cumplir el sacramento; podemos leer,
aprender y meditar sobre lo que es bueno, hacer oraciones externas,
ayunos y dar limosnas;
podemos elogiar y en alguna medida amar la piedad y a los piadosos;
podemos asociarnos con ellos, poseer mucho conocimiento literal de la verdad,
saber cómo conversar en un tono piadoso, y a pesar de todo esto,
todavía no ser realmente piadosos.

Podemos estar convencidos de Dios y de Su verdad;
podemos ser sensiblemente afectados por la tristeza o por la alegría;
podemos ser reprendidos y afligidos en nuestras conciencias;
podemos desear y tomar resoluciones para arrepentirnos,
y realmente cambiar y enmendarnos externamente, y evitar los pecados más evidentes;
más aún,
podemos incluso abandonar pecados secretos (que seguimos amando
en lo profundo) por angustia de conciencia y temor al infierno;
y todavía no ser verdaderamente piadosos.
Todo esto es evidente, y también ha sido detalladamente ampliado por otros;^
footnote:[Consulta "`__Almost Christian__`" de Mead,
"`__Nature and Grace__`" de Spener y "`__Saint`'s Pilgrimage__`"
de Wilkinson para más información sobre este tema.]
y sin embargo, si todos estos, los que sólo tienen esto, y nada más,
fueran tachados del catálogo de los piadosos,
probablemente no quedarían muchos piadosos en pueblos y países enteros.

_En segundo lugar,
la naturaleza de la verdadera piedad no consiste
en algo que algunos hombres piadosos posean,
o hayan poseído, pero que no todos tengan._

Bajo este encabezado pueden incluirse los éxtasis, revelaciones, dones de profecía,
una fe obradora de maravillas, una luz extraordinaria en misterios divinos,
dones brillantes, un celo manifestado externamente,
y cualquier otro don extraordinario de la gracia de Dios.
La piedad no consiste en nada de esto.

Por lo tanto, no debemos desear, particularmente, cosas tan elevadas como esas,
y de ninguna manera sentir envidia cuando las veamos u oigamos en otros;
porque el amor al yo a menudo piensa: "`Ah, si yo tuviera esos dones, esa luz y ese celo,
como esta o aquella persona,
entonces sería verdaderamente piadoso y capaz de edificar a otros`";
y nos impulsa a imitar una cosa u otra--a la que
no hemos sido llamados--y sin la gracia de Dios.
Todo esto se levanta de un principio de engreimiento y amor al yo,
y es una tentación muy peligrosa de Satanás,
contra la que debemos armarnos con la oración y la humildad,
y únicamente trabajar para alcanzar la sustancia de la piedad,
regocijándonos mientras tanto en los dones que Dios les ha concedido a otros.
El que posee esas cosas,
no tiene motivo para presumir de ellas o de enaltecerse sobre otros;
debe tener cuidado de no aferrarse a ellas, ni descansar en ellas,
ni deleitarse egoístamente en ellas; y además,
debe cerrar tanto su corazón como sus oídos contra la alabanza y el aplauso de los demás.
Dado que son sólo dones que (en sí mismos) no hacen que una persona sea más piadosa;
pero al poseerlos, la persona se encuentra en mayor peligro que otras que no los poseen.

_En tercer lugar,
la naturaleza de la verdadera piedad no consiste en algo que todos los piadosos poseen,
pero no todo el tiempo._

Todos los piadosos, o la mayoría de ellos, a menudo experimentan consolaciones,
deleites palpables, seguridades ocasionales, paz, dulzura espirituales y divinos,
y varias otras comunicaciones divinas y dones de gracia.
Digo que ellos experimentan estas cosas _frecuentemente,_
pero no todo el tiempo o sin variación,
de lo cual se deduce que la sustancia de la verdadera
piedad no puede consistir en estas cosas.

Por lo tanto, a mi parecer,
actúan imprudentemente los que habiendo recibido de Dios dones de este tipo,
hablan de ellos y los estiman casi más que la esencia de la piedad misma;
y parece que los presentan como señales inequívocas
y características esenciales de la fe y de la piedad.
E incluso, llegan a declararlos el verdadero fin que debemos tratar de alcanzar siempre,
y no darnos descanso hasta que lo hayamos logrado.

De ahí que muchas personas bien intencionadas, que leen y oyen tales declaraciones,
y que no han disfrutado aún de los mismos y palpables dones de gracia,
puedan caer en desesperanza, desaliento y duda acerca de su estado,
y ser obstaculizadas en el camino de la negación al yo y de la cruz,
al esforzarse con frecuencia, por motivos egoístas, en pos de alegría y consuelo,
buscando por todos lados señales y garantías de su salvación,
más que de las marcas y características de la verdadera piedad.

Los que poseen estos dones de gracia, generalmente piensan bien de sí mismos,
y a menudo secretamente imaginan que ahora son los
hijos favoritos de Dios--que ahora son santos,
sí, mejores que otros, y se sienten seguros de ir al cielo.
Aquí,
el alma a menudo olvida el verdadero y único camino
seguro de la negación al yo y de la cruz,
y se recuesta en el suave lecho de los goces palpables,
deseosa de erigir su tabernáculo antes de haber terminado su viaje.

Ahora bien, si el Señor, en Su sabiduría,
retira de tal persona la leche de la palpable consolación y dulzura,
dicha persona se entristece, desanima e intranquiliza, y busca regresar y poseer eso,
que--debido a que es un apoyo poderoso de la vida
del yo--es la voluntad de Dios quitar de ella,
para hacerla, como el Capitán de su salvación, perfecta a través de los sufrimientos.

Porque aunque es una verdad innegable,
que en el camino de la piedad generalmente se experimentan
muchos y varios dones de gracia,
e incluso se disfrutan de manera perceptible,
tal como es confirmado por todas las Sagradas Escrituras,
por innumerables testimonios de santos en cada época,
y por la experiencia real de este tiempo presente; aun así, tales dones de gracia,
digo yo, sólo se experimentan dentro del camino de la piedad, y son, por así decirlo,
los lugares de descanso y posadas en el camino, que no son ni el camino mismo,
ni el fin del camino, y por lo tanto, lugares donde no debemos permanecer siempre,
siendo sólo experiencias ocasionales que deben ser usados únicamente en caso de necesidad,
para alivio y recuperación de las fuerzas,
para que luego podamos continuar nuestro viaje con la mayor prontitud.
Si reflexionáramos un poco más en esta comparación y la aplicáramos,
descubriríamos bastante bien el uso apropiado de los dones de gracia,
de los que no diré más por el momento,
habiendo dado en otro lugar instrucciones completas sobre el tema.

=== II. La naturaleza de la verdadera piedad

Hasta aquí hemos examinado lo que es considerado como piedad o devoción, y de hecho,
lo es, para la mayoría de los hombres, lo cual, sin embargo,
de ninguna manera puede constituir su verdadera esencia y sustancia; por lo tanto,
la pregunta es, ¿en qué consiste la verdadera piedad?
Ahora, aunque no es difícil responder a esta pregunta en pocas palabras, es difícil,
si no imposible,
darle una idea adecuada de ella a aquel que no está en posesión de la verdadera piedad.
Porque son cosas del Espíritu de Dios que el hombre natural no puede entender.
¡Qué el Espíritu de Dios alumbre nuestro entendimiento con Su verdad,
y poderosamente persuada nuestros corazones a obedecer!

// lint-disable invalid-characters
La verdadera piedad (ευσέβεια) es ese estado interno, o disposición,
que es obrado por el Espíritu Santo, y la ocupación del alma que brota de él,
mediante el cual ella le vuelve a rendir el debido homenaje y adoración al Dios trino.
Consiste en un temor y veneración filiales, en una confianza y fe de corazón,
y en un ferviente apego y amor a Dios,
tres cosas que son como las partes esenciales del
templo espiritual en el que Dios es adorado.
Porque dado que Él es Espíritu, necesariamente se desprende que Él debe ser adorado,
no de una manera meramente externa, ceremonial e hipócrita,
sino internamente y de corazón, en Espíritu y en verdad,
si ha de hacerse de forma digna de Él, como el divino Maestro lo demuestra.
(Juan 4:24)

Repito, el Espíritu Santo produce este estado o disposición del alma,
mientras le da al individuo experimentar internamente (a uno más,
como de una vez y con gran poder,
y a otro más imperceptible y gradualmente) y de una manera sobrenatural, viva y poderosa,
la verdad, gloria y hermosura del omnipresente ser de Dios.

Esto produce de inmediato en el alma una veneración, admiración,
reverencia filial y humillación interna indescriptiblemente profundas,
de todo lo que hay dentro de ella, en la presencia de la exaltada Majestad de Dios.
Este glorioso Ser le parece lo único grande y bueno, y ella misma,
junto con todas las otras criaturas, completamente insignificantes,
pequeñas y despreciables.
Dios es exaltado y magnificado por ella,
mientras ella misma se humilla en la más profunda humildad.
Se estima a sí misma polvo y cenizas--incluso algo inferior;
y por eso no soporta verse honrada o estimada por otros.
Está consciente de que ante esta Majestad, toda rodilla en el cielo,
en la tierra y debajo de la tierra debe inclinarse y adorar,
y este es el objeto de su deseo.
Contempla al Ser divino, casi como el único Ser, y a todos los demás,
considerados en Su presencia, como nada.
Le parece una horrible e inhumana maldad ofender a tal Dios.
Despreciaría mil mundos, antes que cometer un mal tan grande.
De ahí, que sienta la más profunda vergüenza, con verdadera humildad y dolor de corazón,
al recordar sus pecados anteriores,
así como por las debilidades y amor al yo que todavía se adhieren a ella,
cuyos primeros y más sutiles movimientos le resultan repugnantes y muy angustiantes,
y cuya total aniquilación desea y espera ardientemente.

Esta veneración a Dios y esta idea despectiva, o más bien,
total desprecio de sí misma y de toda otra criatura, produce al mismo tiempo en el alma,
una total desconfianza de sí misma y de todas las cosas creadas,
y una verdadera fe y confianza en Dios en Cristo Jesús, a quien se rinde,
entrega y encomienda totalmente en cuerpo, alma y espíritu,
para que Él pueda hacer con ella,
en ella y de ella lo que le plazca en el tiempo y en la eternidad;
esperando y confiando en que Él es capaz y está dispuesto, y en que Él,
con seguridad señoreará sobre todo para el bien de ella y para Su gloria.
Asimismo produce en el alma un abandono de sí misma y de todo lo que no es Dios,
y ardiente hambre, sed y deseo de huir en busca de refugio, y más aún,
una verdadera entrada a Cristo--con quien se une
internamente--y mediante un continuo y creyente apego,
y retirándose y permaneciendo en Él, recibe gracia sobre gracia,
poder y fuerza esenciales, espirituales y vivos,
todo lo cual la penetra y anima plenamente; de modo que, todos los actos, palabras,
pensamientos e inclinaciones internos y externos son gradualmente
producidos e inspirados por este nuevo principio de vida.

Por cuyo motivo, con la mayor conciencia de su propia nadedad y depravación,
y con un sincero reconocimiento de la gracia gratuita de Dios,
de muy buena gana le adjudica todo bien que es encontrado en ella,
o que pueda proceder de ella,
a esta Fuente divina--al vivificante Espíritu del Señor Jesús en ella;
de modo que el alma puede decir con verdad, usando las palabras del santo Pablo:
"`Ya no vivo yo, mas vive Cristo en mí; y lo que ahora vivo en la carne,
lo vivo en la fe del Hijo de Dios`". (Gálatas 2:20)
Y aprende a entender en todo su significado,
las palabras de Cristo: "`El que permanece en mí, y yo en él, este lleva mucho fruto;
porque separados de mí nada podéis hacer`". (Juan 15:5) En verdad,
esta unión esencial de fe en Cristo Jesús, es la única base de toda verdadera piedad;
y la nueva vida que brota de ella es verdadera piedad,
por lo que es llamada enfáticamente, "`piedad en Jesucristo`" 2 Timoteo 3:12,
a fin de distinguirla como algo vivo, poderoso y esencial, de toda religión engañosa,
sombría y hecha por el yo.

Una consecuencia simultánea del conocimiento y visión
de Dios en el interior antes mencionados es,
que todo el corazón, por así decirlo,
es felizmente cautivado y enteramente inclinado a desligarse y
alejarse--mediante una total negación al yo--de todos sus deseos,
placeres, alegrías, deleites y de todo afecto de sí mismo, y de todo lo que no es Dios,
y dirigirlo y fijarlo todo en este único objeto que es totalmente digno,
y amarlo sólo a Él, aferrarse a Él con todo el corazón, con toda el alma, mente y fuerza,
y no amar nada fuera de Él que no pueda ser verdaderamente amado en Él.

Los impíos (_asebes_) y los piadosos (_eusebes_) están, en las Escrituras,
en directa oposición. Una persona impía es aquella que está
desligada de Dios y aferrada a sí misma y a la creación;
una persona piadosa es aquella que está desligada de sí misma y de la criatura,
y adherida a Dios con todo su afecto.
Todo su corazón dice a todo lo que no es Dios: "`No soy para ti, ni tú para mí;
no eres el objeto de mis deseos; puedo prescindir de todos ustedes.
Sólo Dios es suficiente.
Él es mi tesoro.
Él es mi todo.
Él es el centro de mis afectos.
En Él tengo suficiente`". Abraza a este hermoso Ser con todo los poderes de su amor,
y busca placer, gozo,
consolación y deleite sólo en Él. Se aferra a Él en los más profundo de su alma.
Se sumerge en Él, hasta que finalmente,
después de que cada estorbo y separación del pecado y del amor al yo es disipada,
mediante el ejercicio de una gran fidelidad y paciente resistencia,
y a través de la poderosa operación de la gracia de Dios,
llega a ser por completo una con Dios, o un espíritu con Él. (1 Corintios 6:17)

Esto, en conjunto, es llamado en las Escrituras: "`Andar delante de Dios,
o en Su presencia`", y en realidad, no es más que la verdadera piedad,
el verdadero servicio a Dios, o verdadera religión, en la que Enoc, Noé, Abraham,
y todos los santos y los profetas del Antiguo Testamento, así como también Jesucristo,
nuestro Salvador y Precursor, junto con los apóstoles,
los Cristianos primitivos y todos Sus verdaderos seguidores, en todas las épocas,
han servido a Dios,
como será evidente para aquel que se refiera a los
pasajes de las Escrituras que se adjuntan,^
footnote:[Génesis 5:24, 6, 8, 9, 17:1, 39:9; 1 Reyes 17:1, 1 Reyes 18:15; 2 Reyes 3:14;
5:16, 2 Reyes 20:3; Salmos 16:8, 25:15, 116:9, 123:1-2; Juan 8:29; Hechos 17:27-28;
2 Corintios 5:9; Filipenses 3:20; Hebreos 4:12-13, 11:22-23, 27; 1 Pedro 3:2-4.]
con un deseo de la verdad que es según la piedad.

Ahora bien, aunque la verdadera piedad, en lo que se refiere a su origen y esencia,
es totalmente interna, aun así, como luz divina,
es imposible que permanezca tan escondida,
como para no dejar que sus características vivas--incluso,
frecuentemente sin la voluntad o conocimiento del alma--brillen en toda la vida, habla,
porte y conducta de la persona,
que es totalmente diferente de la vida y conducta de los hombres de este mundo,
y diametralmente opuesta a ellos.
Y por el contrario, verifica aquel dicho de Cristo,
'`el buen árbol no puede dar malos frutos... haced el árbol bueno,
y su fruto será bueno`'. Donde la verdadera piedad mora en el corazón, allí reside Jesús,
y allí necesariamente se manifiesta también,
una vida en concordancia con la doctrina y vida de Jesús,
y brillan todas Sus virtudes--la humildad, la mansedumbre, el amor, la sobriedad,
el rechazo al honor, a la pompa y a los tesoros y placeres del mundo, la paciencia,
la fortaleza, la bondad, misericordia,
templanza y todas las otras virtudes de Jesucristo.
Porque aunque un hipócrita pueda, en alguna medida,
poseer la apariencia externa de dichas virtudes,
un hombre verdaderamente piadoso no deja que su luz brille menos por este motivo;
lo cual puede decirse a manera de advertencia, para los que en particular,
les gusta hablar de una piedad grande y meramente externa, y no obstante,
en otros aspectos, se permiten miles de libertades en conformidad con el mundo;
e incluso consideran y desprecian un caminar externo serio de negación al yo,
como hipocresía y disimulo.
"`El que dice que permanece en él, debe andar como él anduvo`". (1 Juan 2:6)

A partir de esta disposición interna del alma, o piedad, brotan de vez en cuando,
todos los ejercicios internos de virtud y actos de
piedad (porque los abarca todos en ella),
tales como los deberes de humillación delante de Dios, invocación, meditación,
contemplación, adoración, agradecimiento, alabanza, amor, rendición, etc.
Ya que todos los deberes externos, como oír, leer, conversar sobre cosas buenas, orar,
cantar y cosas semejantes, brotan, y deben necesariamente provenir,
de dicho fundamento y disposición de corazón,
para que sean practicados con provecho y merezcan el nombre de servicio a Dios.

De lo que se ha dicho,
puede ser fácilmente percibido que la principal distinción entre
la verdadera y falsa piedad radica en que esta última consiste,
únicamente, en una apariencia, forma y cubierta externas, mientras que el corazón,
en el ínterin, permanece sin cambios, lleno del amor al mundo, al yo,
y a toda abominación. Pero la verdadera piedad posee en sí misma un poder divino,
produce un cambio total en el hombre, retira poderosamente su corazón, afectos,
deleites y todos los poderes de su alma de todas las cosas creadas, lo une a Dios,
su origen, y lo traslada a una vida y caminar verdaderamente santos y divinos.

=== III. La utilidad de la verdadera piedad.

¿No debería ser bendito en Dios el que es piadoso de este modo?
Sí, él es verdaderamente bendito.
Conoce a Dios y a Jesucristo, a quien Él envió,
lo cual es la vida eterna (Juan 17:3). El entendimiento,
que con mucho cansancio y ansiedad había vagado por
mucho tiempo en la absoluta oscuridad natural,
palpando como un ciego en busca de la pared,
y había buscado la verdad mediante la engañosa luz de la razón,
y sólo había encontrado ideas, opiniones y conjeturas sin vida, frías e inciertas,
ahora ve sin mucho esfuerzo o búsqueda individual,
'`luz en la vida de Dios`'. (Salmo 36:9) Reconoce la verdad y Al que es verdadero;
y mediante la contemplación de esta verdad, el ojo del entendimiento es alumbrado,
alegrado y satisfecho, habiendo alcanzado entonces su objeto y su propósito.
Saber que Dios es, y que es lo que es,
(Éxodo 3:14) le ofrece una indescriptible felicidad
a aquel a quien el Hijo se lo revela (Mateo 11:27),
y no puedo hacer otra cosa más que asentir sinceramente y decir: "`¡Sí, Señor,
está bien que seas, y que seas el que eres.
Sí, amén!`"

Si es dicha, como realmente lo es, poseer todo lo que deseamos y anhelamos,
la persona que posee verdadera piedad, debe ser verdaderamente bendita,
porque une su voluntad con la de Dios, la cual siempre se cumple.
Anteriormente estaba afligida y atormentada en la infernal llama de su propia voluntad,
que muy frecuentemente la hacía sentirse insatisfecha,
porque una cosa u otra siempre estaba mal, en la opinión de la perversa voluntad del yo;
y así se retorcía y agonizaba día y noche, dentro de sí misma, en penoso temor,
preocupación, angustia, intranquilidad y ansiedad, como un gusano que carcome,
para perjuicio del cuerpo y del alma.
Pero ahora ha entregado completa e incondicionalmente
su voluntad en el ejercicio de la verdadera fe,
y a través de la negación al yo, en las manos de Dios, de manera tal,
que sólo la voluntad de Dios influye y opera en ella,
por medio de lo cual el alma es colocada en un estado tranquilo y muy pacífico.

Su voluntad no desea nada más que a Dios;
y debido a que lo posee (esencialmente y en la fe,
si no siempre de manera clara y perceptible), no puede querer o desear algo más,
ya que Dios, como su objeto propio e infinito,
llena y calma la infinita capacidad de sus deseos.
Ella puede decir con el piadoso patriarca Jacob, '`tengo todo,
tengo lo suficiente`' (Génesis 33:11 RVG), lo que nadie más,
aunque sea el más grande monarca sobre la tierra, puede decir con verdad.
Porque nadie sabe lo que es tener lo suficiente, salvo el alma verdaderamente piadosa,
porque nadie lo ha experimentado jamás. De hecho,
la gente supone que esta cosa o aquella satisfaría su hambre y deseo, y el pobre,
errante y separado espíritu de Dios piensa para sí mismo: "`¡Ah,
si yo estuviera en esta o aquella situación en particular; si tuviera esto o aquello;
si esto o aquello fuera quitado, entonces estaría tranquilo y contento`". Sin embargo,
¡con cuánta frecuencia y constancia nuestro fiel Creador hace que
el hombre sea consciente de que éstas son sólo cisternas rotas,
y que no pueden proporcionar alimento apropiado para el alma!
Una sola cosa es necesaria, y es Dios, en quien el alma verdaderamente piadosa,
al retirar todo su deseo, amor y afecto de cualquier otro objeto, los reúne en Uno.
Así llega el espíritu a su origen, centro y propósito al que pertenece, e igualmente,
a su reposo y verdadera felicidad,
que es también incrementada en la esperanza de su futura prolongación
y manifestación en gloria eterna (Colosenses 3:4);
así que en este aspecto, "`en esperanza somos salvos +++[+++o bendecidos^
footnote:[En Alemán,
salvación y bendición se expresaban con la misma palabra.]]`". (Romanos 8:24)

La consecuencia de todo esto es una mente despejada y alegre,
y un comportamiento bien regulado, armonioso, imperturbable y pacífico, viendo,
como se observó antes, que la voluntad del yo ha sido quebrantada;
y por eso los afectos y pasiones son moderados, y ordenados apropiadamente,
mediante lo cual el cuerpo, como es fácil de suponer, es más beneficiado que perjudicado.

No obstante,
se necesitarían mayores capacidades para intentar una descripción
de la suprema felicidad que acompaña a la verdadera piedad,
incluso en esta vida, aunque todo lo que pudiera decirse, sería sólo oscuro e inadecuado;
y por ello, para conocerla, el alma debe experimentarla realmente.
Pablo expresa todo esto en pocas palabras:
"`La piedad para todo aprovecha (el remedio y panacea infalibles),
pues tiene promesa de esta vida presente, y de la venidera`" (1 Timoteo 4:8).

Es al menos evidente por lo que se ha dicho,
que es erróneo considerar la verdadera piedad como algo melancólico, penoso,
difícil y molesto, ya que, considerada abstractamente, es todo lo contrario.
Es cierto que le causa severa aflicción,
agonía y muerte a la obstinada voluntad del yo y a la depravación natural,
pero es precisamente esta voluntad del yo y este estado natural,
lo que nos hace desdichados y miserables, y por lo tanto,
debe ser quitado del camino y necesariamente removido
por el poder y Espíritu de nuestro salvador Jesús,
para que podemos ser aquí y en la eternidad felices, gozosos y benditos en Dios.

Por lo tanto, examinemos aquí,
dos o tres de las principales razones por las que la piedad parece tan difícil y desagradable,
no sólo para la mayor parte de los hijos de este mundo, sino tal vez también,
para la mayoría de lo que profesan la religión.

La primera razón es,
porque algunos--y por desgracia demasiados--son muy negligentes
y tiernos consigo mismos a la hora de decirle no al mundo,
al crucificar la carne, al hacer morir sus propias voluntades,
sus deleites sensuales y todo placer, goce,
afecto y gratificación egoísta que ofrecen las cosas creadas;
por cuyo motivo es imposible que alcancen la verdadera paz con Dios,
y una experiencia sustancial de Su total suficiencia.
Es imposible servir a dos señores (Mateo 6:24). Aquel que quiera deleitarse en Dios,
ya no debe buscar placer en la creación; y el que busque su deleite en la creación,
no lo encontrará en Dios.

En algunos individuos la negligencia yace en una sutil pero muy peligrosa falta de sinceridad,
en secretamente--aunque a sabiendas--aferrarse con
afecto a algún pecado o cosa creada en particular,
con lo cual el Espíritu Santo es contristado, el corazón continúa intranquilo,
y la conciencia continúa sus acusaciones.
Otros carecen de una atención serena y estricta sobre el corazón,
y hacia las amonestaciones del Espíritu de gracia que mora en ellos,
y continúan viviendo en una estado de desenfreno mental,
y más en los sentidos y en la razón que en el espíritu (Romanos 8:1, 4, 5, 9, 13),
por lo que innumerables pecados y egoísmos no son reconocidos ni removidos.
Súmese a esto, que los hombres escuchando a la razón carnal,
a menudo ponen límites y fronteras a su negación al yo y a la santificación,
o dejan que otros lo hagan por ellos; y así,
se contentan bastante bien con un pequeño comienzo,
y con la negación de una cosa en particular; mientras que retienen todo lo demás,
apelando debilidad, sin resistirse seriamente a ello.

La segunda razón por la que una vida piadosa parece difícil y desagradable,
incluso a muchas personas piadosas, es que muchos,
que aunque están perfectamente deseosos de obrar con más sinceridad que los primeros,
corren hacia el lado contrario,
y son inapropiadamente muy activos en aquello en lo que otros actúan muy perezosamente;
ya que buscan, en sus propias fuerzas,
seguir y ser fieles a las amonestaciones y requerimientos
de ese Espíritu Santo a quien se han rendido,
en lugar de abandonarse inmediatamente con su propia actividad y habilidad,
y pasar en realidad--y no meramente de manera ideal e imaginaria--por fe y amor a Jesucristo,
y espiritual y dulcemente unirse y tener comunión con Él,
para que Aquel que obró en ellos el querer, pueda también obrar en ellos el hacer,
según Su beneplácito.
Por este motivo, lo que realizan no es puro, completo, sincero, ni permanente,
y de ahí que la mente, a pesar de todos sus esfuerzos legales,
yazca postrada bajo muchas dificultades, disgustos, reprensiones y grilletes.
Este es un punto muy importante, cuando es bien entendido,
y es más frecuente entre los piadosos, de lo que podría haberse supuesto.

La verdadera santidad y piedad son tanto impracticables como extrañas
para las leyes y los poderes naturales del hombre.
El Espíritu vivificante del Señor Jesús debe hacernos nuevas criaturas,
y animarnos e influenciarnos completamente,
para que llenos de esta gracia gratuita y poderosa del nuevo pacto,
podamos negar y vencer todo con deleite, valor y constancia,
y vivir en el ejercicio de la verdadera piedad,
en la presencia del Señor. Si todo aquel que se esfuerza por alcanzar la verdadera piedad,
se sumergiera en esta única fuente de toda gracia y piedad, es decir, en Jesucristo,
en la conciencia de su profunda depravación e incapacidad,
en sincera confianza y permaneciera en Él, verdaderamente creceríamos,
floreceríamos y llevaríamos fruto como árboles plantados junto a corrientes de agua,
y encontraríamos, por medio de una experiencia viva,
que "`sus mandamientos no son gravosos`". (1 Juan 5:3)

Pero que nadie suponga que con esto queremos pasar por alto el misterio de la cruz,
o excluir los benditos senderos de la aflicción,
por medio de los cuales Dios guía a Su pueblo del ámbito y camino de la piedad;
definitivamente no.
Porque si así lo hiciéramos,
condenaríamos a todos los hijos de Dios que fueron primero que nosotros (Salmo 73:15):
Abraham, Job, David, Hemán, Jeremías,
y a todos los santos del Antiguo y Nuevo Testamento;
todos los cuales (cada uno en su medida y grado) han sido ejercitados,
tratados y purificados por Dios, tanto en cuerpo como en alma,
por varias tentaciones y asaltos del enemigo, tinieblas, abandono, esterilidad,
angustia y varios otras aflicciones y sufrimientos.
Por el contrario, el divino dicho sigue siendo cierto hasta el día presente,
de que todo el que quiera vivir piadosamente en Jesucristo,
no sólo debe ser externamente odiado,
injuriado y perseguido por el mundo (2 Timoteo 3:12),
sino también internamente perfeccionado por una variedad de tentaciones,
cruces y sufrimientos, y así entrar en el reino de los cielos.
(Hechos 14:22)

Pero a pesar de todo esto, el sufrimiento,
las tentaciones y las aflicciones en el interior, gradualmente se volverían fáciles,
e incluso agradables para la persona piadosa,
y no serían capaces de perturbar su profunda paz en Dios,
si tan sólo aprendiera sabiamente a poner su fuerza, deleite, bienestar y salvación,
única y completamente en Dios y en Su beneplácito.
Digo _únicamente_ en Dios y en Su beneplácito, no en sí misma, ni en sus propias acciones,
ni en su propia comodidad y satisfacción; ni en la luz divina, dones, emociones,
seguridades y cosas semejantes,
porque todo esto puede y debe ser a menudo escondido y quitado.
Pero Dios y Su voluntad nunca se mueven ni cambian.
Y cuando el alma en sus sufrimientos, cualesquiera que sean,
sólo pueda rendirse a sí misma y a su salvación,
con una fe oscura y en la más profunda negación al yo, a este fiel Creador,
definitivamente alcanzará--en el grado en que lo practique,
y en el que toda justicia propia y auto asumida piedad sean aniquiladas--los
apacibles frutos de justicia y santidad (Hebreos 12:11),
incluso en esta vida.

No pretendo con esto,
poner más desaliento en el camino de los que son
sinceros en su hostilidad hacia el pecado,
y vagan cansados y cargados en dolor y contrición penitente,
ni hacer que desconfíen de su estado porque no les parezca fácil; de ninguna manera.
Todo lo contrario, deseo consolarlos y afirmarlos asegurándoles que no siempre será así,
y sólo quiero recordarles que con tal disposición de corazón deben acudir a Jesús,
conscientes de su miseria e incapacidad, para que Él los refresque,
y luego haga que su yugo sea fácil y su carga ligera (Mateo 11:28-30). Y dado que no
tienen poder en sí mismos para abrirse paso y alcanzar la verdadera esencia de la piedad,
mediante una incesante hambre y oración en el espíritu,
se acostumbren a aferrarse al Señor más fervientemente y a permanecer en Él, porque Él,
entonces, infaliblemente les concederá abundantemente,
por la impartición de Su poder divino,
todo lo que es necesario para la vida y la verdadera piedad.
(2 Pedro 1:3)

¡Qué Aquel que es el único Dios bendito por siempre y el único que puede hacernos piadosos,
toque viva y poderosamente por Su Espíritu los corazones de los que lean estas páginas,
de modo que no sólo decidan inmediatamente negarse
a sí mismos y negar todas las cosas creadas,
sino que realmente lo hagan y lo lleven a cabo por medio de Él,
para que puedan seguirlo y disfrutar la inefable y eterna felicidad de Su divina comunión!

Debemos abandonarnos a nosotros mismos para asirlo y ser asidos por Su Espíritu.
Debemos salir de nosotros mismos para entrar en Él. Esta salida
y esta entrada es el fundamento y el acto más esencial de la piedad,
porque por medio de ello, le devolvemos a Dios lo que es de Él, es decir,
nosotros mismos, completa, total e irrevocablemente.
Y al hacerlo, igualmente Lo reconocemos y aceptamos por lo que es, es decir,
nuestro Dios, Creador, Redentor, nuestro supremo Bien,
nuestro Uno y nuestro Todo para siempre.
Si se descuida esta única cosa, esta salida y esta entrada, nuestra piedad vale poco,
y es únicamente una sombra sin sustancia.
Pero ya que el compasivo amor de Dios en Cristo Jesús nos llama tan fielmente a ello,
sigamos esta inestimable vocación de gracia en humilde rendición,
abandonando todo lo que tenemos y somos,
para que podamos ser piadosos y benditos en Él en verdad, tanto ahora como para siempre.
Este es el deseo cordial y la más ferviente oración a la Fuente de toda piedad de,

[.signed-section-signature]
Un sincero buscador de la piedad.
