== Sobre la Diferencia del Progreso en la Piedad

[.blurb]
=== "`Muchos son llamados, mas pocos escogidos.`" Mateo 20:16

=== I. La Diferencia

A pesar de que Dios es todo suficiente en Sí mismo y no tiene necesidad de nuestra,
ni de ninguna adoración (Hechos 17:25),
es el propósito eternamente inmutable y la misericordiosa voluntad de Él que,
además de las miríadas de espíritus angelicales, que en varias jerarquías, legiones,
rangos y puestos rodean Su trono, y contemplan,
adoran y disfrutan Su muy gloriosa y hermosa Majestad,
también tenga una iglesia y verdaderos adoradores
entre la raza humana e hijos caídos de Adán,
con quienes pueda unirse de manera interna y recíproca, comunicarse con ellos,
y hacerlos partícipes de Su gloria y felicidad divinas.

Por lo tanto, esta Sabiduría eterna, cuyos deleites están con los hijos de los hombres,
va continuamente, por decirlo así, como una madre y esposa fiel y cariñosa,
buscando almas que adoren al Padre de una manera digna de Él, en espíritu y en verdad.
¡Pero ay!, no tiene éxito con la mayoría; en algunos encuentra algún grado de atención,
pero no exclusivamente en todas las cosas; y sólo en un número muy reducido,
encuentra libre entrada y permiso para llevar a cabo sin obstáculos Su obra divina.
En resumen, "`muchos son llamados, mas pocos escogidos`". A pesar de todo esto,
el propósito y consejo de Dios permanece inmutablemente firme:
"`El Padre tales adoradores busca que le adoren`". Y es realmente el caso,
que la Sabiduría siempre ha encontrado, todavía encuentra,
y siempre encontrará a algunos entre cada pueblo y nación,
en todo tiempo y en todo lugar,
en quienes poder entrar y a quienes poder hacer "`amigos de Dios`",
como se dice en el libro de Sabiduría, 7:27.

La consecuencia de este comportamiento tan variado de los individuos,
con respecto al misericordioso llamamiento de Dios,^
footnote:[Con esto no se pretende negar que Dios tenga Sus sagrados propósitos,
al llevar a almas individuales a estados particulares de santificación y unión;
pero si todos reconocieran en sí mismos el propósito y el llamamiento de Dios,
y respondieran fielmente a él, todos los hombres serían santos.]
es una muy notable diferencia que se observa entre los piadosos en la iglesia de Cristo
(porque ahora no me dirijo a la multitud de los de mente mundana y los hipócritas),
particularmente desde la apostasía de la iglesia de su primer amor y poder,
ya que la mayoría de ellos se detienen pronto en los comienzos del Cristianismo,
sin esforzarse seriamente por avanzar continuamente, y por eso llevan una vida más débil,
más común, y si me permiten expresarme así,
más _externa_ ante los ojos de Dios y del hombre.
Sin embargo, otros, los menos numerosos, han seguido adelante fielmente,
y han sido atraídos y conducidos por la gracia de Dios a algo más sustancial e interno,
en consecuencia de lo cual son diligentes en llevar una vida más santa,
estricta e interna.
Con respecto a esto, es cierto que podría haberme explicado y expresado más brevemente;
y en un modo de expresión muy común en las Sagradas
Escrituras y en los escritos de los padres primitivos,
podría haber denominado a los primeros individuos imperfectos,
y a los segundos (en su verdadero sentido) perfectos;
pero debido a que en estos tiempos Cristianos verdaderamente imperfectos,
hay muchos tan indispuestos a oír hablar de la perfección,
que es de temer que tengan tanto miedo a la cosa misma como a la palabra,
he tratado de evitar esta piedra de tropiezo.

En la presente ocasión, sólo me esforzaré, brevemente,
por hacer evidente esa diferencia que existe entre los piadosos de hoy;
por si acaso alguien puede aprender por ella a conocerse a sí mismo,
y bajo los varios puntos y diferencias externas menores,
de los que el Cristianismo está rodeado y envuelto actualmente,
comenzar a buscar el origen interior de la vida oculta.

La mayor parte de los que son llamados por Dios,
se detienen en su camino después de haber experimentado los primeros efectos del arrepentimiento,
como dolor y tristeza por sus pecados, ansiedad ante el peligroso estado de sus almas,
hambre y sed de la gracia de Dios en Cristo,
y al volverse de las obras muertas de los pecados más graves,
hacia una vida y conducta externamente virtuosas y piadosas;
suponiendo que una vez que ha ocurrido tal cambio,
ya se ha cumplido lo que las Escrituras llaman conversión
y regeneración. Y si además de esto,
el corazón ha sentido ocasionalmente una medida de consuelo, deleite y placer,
el hombre cree que su estado es más seguro, al suponer que ya ha encontrado el tesoro,
y que habiendo superado todos los obstáculos, ha alcanzado la comunión con Dios,
y por lo tanto, se apropia de las preciosas promesas,
títulos y privilegios que da Dios en Su palabra a los verdaderos Cristianos.

Aquí se detienen las ruedas de sus carros.
No quiero decir, que esto sea, invariablemente, el sentimiento,
propósito e intención de ellos,
como si hubieran alcanzado el fin de la santificación y pudieran tomarse un descanso,
sino que su supuesto avance es, en realidad, un estancamiento, si no un retroceso.
Observemos aquí, en qué consiste casi invariablemente este avance.
Ellos se ejercitan leyendo, escuchando, conversando, cantando,
haciendo oraciones vocales, y deberes y devociones similares,
(cosas que pueden ser beneficiosos en sí mismas);
reflexionan en las verdades de Dios y luchan por formarse un concepto de ellas,
o como se acostumbra decir, alcanzar una gran medida de conocimiento, y buscar,
en estas y similares actividades, su deleite y disfrute.
Y cuando son conscientes de alguna sensibilidad transitoria,
o buena inclinación en los afectos, se regocijan, lo estiman muy edificante,
y a menudo no saben cómo elogiarlo lo suficiente; pero si carecen de ésto,
se quejan como si Dios los hubiera abandonado,
e incluso están listos a comparar su situación con la de Job, David y otros santos,
en sus dolorosos sufrimientos internos.
No sé si la conducta y progreso de muchos de los piadosos consisten en algo más,
porque con respecto a esas irregularidades que permanecen después del primer cambio,
continúan en su fuerza anterior.
Creo que ocasionalmente son resistidas en algún grado, pero nunca vencidas,
y por eso consideran esas cosas como faltas y debilidades,
de las que no esperan ser liberados durante la presente vida.

Ahora, bien, si prestamos atención a la vida y conversión de tales personas,
las encontraremos tolerablemente devotas en sus ejercicios religiosos,
pero el resto del tiempo, y en la interacción diaria con los demás,
bastante libres y desenfrenadas.
No consideran como algo particularmente impropio,
tener sus mentes absorbidas por múltiples asuntos mundanos e innecesarios,
y acumular riquezas y tesoros para el futuro.
Se consideran en libertad de discutir ampliamente asuntos irrelevantes,
y de asociarse innecesariamente con personas del mundo.
Consideran permitido complacer sus sentidos viendo, oyendo, gustando,
y cosas por el estilo--no diré nada con respecto a los pensamientos,
porque son universalmente poco atendidos por ellos,
y se les deja vagar sin rumbo por horas y días seguidos, sin escrúpulos ni objetivo.
Y así, el corazón está en cierta medida dividido, aunque no siempre lo sepan.
¡Ah, qué poco cuidado manifiestan tales individuos bien intencionados,
para evitar que sus deleites o afectos se desvíen hacia algún objeto creado en particular,
y buscar en dicho objeto gratificación, consuelo y gozo! ¡Cuán negligentes son,
cuando siguen sus propias voluntades y sus propias opiniones,
primero en una cosa y luego en otra, frecuentemente bajo las más plausibles apariencias,
de modo que la diferencia entre ellos y el mundo es a menudo escasamente perceptible!

¿Acaso no es esto cierto?
Y muchos de los que leen esto, siendo convencidos en sus conciencias,
¿no se verán obligados a responder, sí? Porque díganme, ¿no es suficientemente evidente,
que tales personas realmente no sienten dentro de ellas
el poder de la fe y de la piedad para vencer el mundo,
tanto interno como externo; para la exterminación del pecado,
del desorden de los afectos y de las pasiones del amor al yo,
del egocentrismo y de la voluntad propia; y para la destrucción de la vida del yo?
¿Y que aún no poseen dentro de ellas el gran privilegio del nuevo pacto, que es,
que Dios mismo escribirá Su ley en lo íntimo (Hebreos 8:10),
y que en adelante deberán cumplir la voluntad de Dios,
no por la mera constricción y compulsión de una conciencia
cargada con respecto a algunas cosas en particular,
sino por amor y afecto fervientes, y por la libre inclinación del corazón?

Por lo tanto, estas personas no alcanzan la paz verdadera y duradera, ni el conocimiento,
ni la comunión con Dios en Cristo;
y por mucho que se haya hablado y escrito sobre el tema, y sobre el disfrute de la paz,
gozo y bienaventuranza en Cristo, aun así,
estas pobres personas saben muy poco al respecto por experiencia propia,
excepto quizás por haberlo leído o escuchado de otras personas piadosas; o más bien,
a pesar de todos sus deberes y ejercicios devocionales,
se mantienen en un estado interno de gran dificultad,
reproche secreto e insatisfacción de conciencia.
Pero cuando experimentan algún grado de placer y alegría
en la realización de algún deber y empresa en particular,
que es aparentemente bueno, es sólo superficial, momentáneo y mucho menos puro;
y no pasa mucho tiempo antes de las acostumbradas
acusaciones de conciencia comiencen de nuevo,
cuando se escucha su voz.
Porque todo lo que se hace en este estado,
son resultado generalmente--aunque a menudo inconscientemente--de
los propios poderes y esfuerzos naturales del hombre,
que pronto caen otra vez,
y sólo ocasionan ya sea abatimiento o mucha autocomplacencia en su propia justicia,
pero traen poca gloria a Dios, y ninguna paz verdadera y duradera a la mente.

Debemos, pues, no sin razón, reflexionar y preguntar con referencia a esto,
¿cómo es posible que los hombres que poseen luz y gracia de Dios,
y que desean no engañarse a sí mismos--porque aquí hablan únicamente de esas personas--puedan
pensar o creer que sus estados son correctos y aceptables para con Dios,
siendo que su miseria y debilidad son tan obvias en todo los aspectos?

Ciertamente, esto no puede ser atribuido a ninguna otra causa,
sino a la falta de observación y atención a lo que sucede dentro de ellos.
Porque debido a que se dejan arrastrar y seducir tan a menudo
de las reprimendas de la gracia y del Espíritu de Dios,
y a que después de haber obedecido una vez su llamado e impulso en su primer arrepentimiento,
salen de sus corazones (por decirlo así) hacia su parte pensante o razonadora,
y se forman o reciben conceptos e ideas del Cristianismo y de la verdad divina--según
la débil e insuficiente luz que han obtenido mediante los esfuerzos de su propia razón,
cuyas ideas y conceptos deben ser necesariamente muy débiles, limitados e insuficientes.
Y luego, consecuentemente regulan y limitan su Cristianismo, aunque con buena intención,
según las ideas que alguna vez se formaron,
en las que muchos se establecen tan firmemente,
que consideran erróneo y rechazan todo lo que no está de acuerdo con ellas,
o va más allá. Y viviendo así, vueltos del interior al exterior,
y de la luz y amonestación del Espíritu a la razón humana, nunca alcanzan,
ni un verdadero y completo conocimiento de su depravación interna,
y de la multitud de fallos secretos y egoístas en todos los puntos;
ni una percepción de la verdad conforme está en Jesús, y de esa vida estricta, santa,
retirada y escondida que es requerida en un verdadero Cristiano;
ni un conocimiento por experiencia del poder del
Espíritu de Jesucristo en Sus verdaderos seguidores,
por medio del cual son preparados para tal vida santa y piadosa.

Sin embargo,
no acusaré a tales personas de una infidelidad o falta de sinceridad consciente y deliberada,
y condenar así completamente su estado; sólo señalaré brevemente su gran deficiencia,
impureza e insuficiencia, con la esperanza de que una u otra,
mediante la cooperación de la gracia divina,
pueda volver en sí y preguntar más minuciosamente,
por el antiguo y único camino correcto de morir al yo y a todas las cosas creadas,
y por la vida escondida con Cristo en Dios.
Porque, ¡ay!,
¿no deberíamos afligirnos y dolernos al ver a tales individuos
bien intencionados corriendo en un círculo sin fin,
y satisfaciéndose de esta manera con la cáscara externa,
o con un mero conocimiento racional, y con algunos ejercicios corporales específicos,
deberes y rudimentos del Cristianismo, de modo que todo avance es olvidado,
y nunca es experimentado el verdadero fruto interno del Cristianismo,
ni disfrutada su bienaventuranza en ferviente comunión con Dios?

=== II. La Transición a un Mejor Estado

Sin embargo, alabado sea Dios, todavía hay algunos por aquí y por allá en la actualidad,
que no encuentran descanso ni satisfacción en un mero comienzo y estado mezclado,
sino que están deseosos, con el joven rico mencionado en los evangelios,
de ser _perfectos_ (para usar las palabras del Señor Jesús),
y con este fin se dedican y se entregan de manera particular al Señor Jesús,
para ser Sus verdaderos discípulos; quienes por Su gracia,
son también diligentes en la práctica de un Cristianismo real, interno y estricto,
y buscan ejercitarse en él con todo el corazón, como su única y necesaria ocupación;
aunque incluso entre ellos se observa de nuevo,
una gran diferencia con respecto a sus progresos y sus estados.
Me referiré un poco a la transición de ellos a un mejor estado,
y a sus propiedades; sobre lo cual, no obstante,
debo ser muy breve por mis estrechas limitaciones.

Este adelanto y transición de dichas almas a algo sustancial e interno,
generalmente toma lugar de la siguiente manera.
Todo empleo y actividad del yo, externos e internos,
sobre lo que el Cristianismo del hombre, aunque sin su conocimiento,
había descansado mayormente hasta ahora, se vuelve desagradable y es quitado de él;
lo que en algunos casos sucede más rápidamente que en otros.
Dicha persona ya no puede continuar leyendo, meditando, escuchando, conversando,
haciendo sus oraciones vocales, ni cosas similares; en parte,
debido a que el entendimiento que había sido previamente tan activo,
se vuelve gradualmente incapaz, perezoso y poco inclinado a funcionar,
reflexionar y deliberar como antes; y en parte,
porque la memoria ya no puede proveer los conceptos,
ideas y temas de los que estaba llena, ni recibir y retener otros.
Y todo lo que esta persona emprende o es capaz de emprender,
en cuanto a empleos y ejercicios internos o externos propios,
es llevado a cabo con mucha dificultad,
y ya no tiene el efecto sobre el corazón y la voluntad que tenía antes;
sino que en lugar del placer, sabor y dulzura anteriores, todo se vuelve estéril,
ineficaz, e incluso desagradable y molesto.
Y por el contrario, percibe dentro de ella, ya sea inmediatamente o con el tiempo,
una inclinación más que ordinaria, no sólo hacia la tranquilidad y soledad externas,
sino más especialmente, hacia la calma interna o pasividad,
con una simple y ferviente falta de interés y olvido de todo lo creado, y una secreta,
suave y tierna inclinación a Dios, y una atención infantil de fe a Su presencia en ella,
lo cual debe ser muy cuidadosamente apreciado.

Ahora bien,
cuando la persona se rinde a esta guía--que es tan extraña para la actividad de la razón,
y sin embargo tan dichosa--y a esta atracción interna y divina y es obediente a ella,
encontrará su salvación en este descanso y tranquilidad (Isaías 30:15),
ya que mediante esto,
es destetada de todas sus aberraciones anteriores y de las obras de la razón humana,
para que pueda poner atención en su interior y en humilde quietud,
a las secretas amonestaciones e instrucciones de la Verdad eterna en su corazón;
y en lugar de estar ocupada en una multitud de cosas menores,
ahora es dirigida hacia la vida escondida con Cristo en Dios, la cual,
no se puede alcanzar de otra manera sino por la continua
muerte con Cristo al yo y a todas las cosas creadas.

Con esto, por lo tanto, toda la credibilidad aparente,
presuntuosa y externa en la religión,
por medio de la cual la persona era capaz de mantener su prestigio,
ya sea en el mundo o ante sus propios ojos, se desvanece gradualmente por sí misma,
y el alma empieza a exhibir una disposición más infantil, y a seguir la vida simple,
despreciada, escondida y sufriente de Jesucristo,
en la que serán dadas lecciones muy diferentes a las anteriores.
Ahora debe aprender a amar los sufrimientos, pobreza y reproche de Cristo;
y por el contrario,
debe aprender a evitar y a huir--como de cosas de una naturaleza muy sospechosa--la
comodidad y satisfacción de la carne y de los sentidos,
las riquezas y tesoros de la tierra, junto con todo el honor o dignidad mundanos.
Tales personas entonces se sienten reprendidas, no sólo por las malas obras,
sino también por una intención no del todo pura, incluso en las buenas acciones.

El corazón debe ser total y completamente despojado del apego a todas las cosas creadas,
y de todo placer, gozo y deleite (incluido el más secreto),
y ser gradualmente alejado de todo lo que no sea Dios;
de manera que no pase por alto ni una sola palabra innecesaria o desconsiderada,
incluso en las cosas buenas y espirituales,
o un breve pero voluntario e innecesario vagabundeo de la mente,
de la atención o de la tristeza.
Así pues, el alma ya no tiene libertad de ver y oír, de ir o quedarse,
de actuar y hacer lo que le plazca y como le plazca;
ahora percibe que tiene a Uno sobre ella y en ella, a quien debe atender,
y a quien debe sujetar su voluntad en completa rendición. Una sutil obstinación,
las emociones desordenadas de la mente, la autocomplacencia,
presumir sobre lo bien que habla, realiza o disfruta,
puede afligir a este tierno Huésped.
Y por lo tanto, cada vez que se encuentra en la búsqueda de sus propios intereses,
debe apartarse de ella misma en una genuina negación y muerte al yo, por el amor de Dios.
En resumen, el lenguaje de tales almas es: "`Cada día muero`" (1 Corintios 15:31),
cada hora y a cada instante;
de modo que por las diversas aflicciones y sufrimientos
que le sobrevienen de afuera y de adentro,
según la omnisciente guía de Dios, la vida del yo es completamente destruida.

Esto suena duro y severo, es más, incluso parece que es imposible; pero observemos ahora,
cómo se vuelve fácil y placentero para tales almas.
Ellas viven, al mismo tiempo, en secreto con Cristo en Dios y en Su presencia;
y Dios vive y mora en ellas, e internamente las prepara y capacita para todo.
Eso que dejan de la naturaleza corrupta,
y lo que pierden en el exterior y en las cosas creadas,
lo encuentran de nuevo en Dios cien veces más (Mateo 19:29). Cuánto más se alejan
y mueren a las cosas creadas mediante una continua negación al yo,
tanto más necesariamente se aproximan a Dios y a Su vida,
y son conocidas por Él y aceptadas en un caminar y conversar escondido con Él. Previamente,
las cosas creadas vivía en ellas y ellas en las cosas creadas.
Dios estaba, por decirlo así, muerto a ellas, y como si no existiera.
Ahora, por el contrario, Dios vive en ellas y ellas viven en Dios;
mientras que todo lo demás,
así como ellas mismas--en lo que se refiera a sus
propias vidas y a sí mismas--es como si no existiera.
Antes buscaban y poseían vida en las cosas creadas y en sí mismas,
pero ahora mueren y están muertas a esa miserable vida,
encuentran en lo profundo de sus almas verdadera vida y ser, paz, gozo,
consuelo y deleite, a lo que deben fervientemente adherirse,
retirando sus afectos de todo lo demás,
volviéndose al interior en Dios y viviendo en esa escondida profundidad.

Y así, se verifican en ellas las palabras del apóstol mediante una experiencia viva:
"`Ciertamente no está lejos de cada uno de nosotros.
Porque en él vivimos, y nos movemos, y somos`" (Hechos 17:27-28),
no sólo según Su presencia universal,
sino también según Su presencia particular que mora en ellas.
Internamente viven en Dios y delante de Él, como un pez en el agua o un ave en el aire;
no por una mera idea e imaginación,
sino porque sus espíritus real y esencialmente beben--por medio de la oración incesante,
o el hambre de fe, y acercándose a Dios,
como una especie de respiración en el Espíritu--la vida divina y fuerza de Él;
por lo que, mediante esta permanente interacción de fe y amor,
la vida de Dios es impartida a ellas y llegan a ser partícipes de la naturaleza
divina (2 Pedro 1:4). Así viven con un espíritu manso y quieto,
en un estado simple, rendido, inocente e infantil en la presencia de Dios,
aunque no siempre en vista y disfrute, pero sí en fe y realidad;
de modo que así como mueren a todas las cosas con Cristo,
también viven de manera escondida con Cristo en Dios.

¡Sí, verdaderamente escondida!
De modo que la razón prudente pasa por alto esta vida;
los sentidos son ignorantes de ella, el ojo carnal no percibe nada de ella; la pobreza,
el desprecio y el sufrimiento son tres cubiertas que la ocultan externamente al mundo,
el cual no imagina ni cree que una hija del rey (Salmo 45:13),
vestida con una inefable gloria interna, esté escondida debajo ellas.
Por eso, la razón considera a tales personas como una raza pobre, miserable,
despreciada y afligida, como una secta contra la que se habla en todas partes,
como personas insignificantes, ciegas y tontas,
que sólo se causan a sí mismas una vida miserable y mucho sufrimiento y tribulación.
Y aunque la gloria que está escondida en el interior de ellas,
irrumpe en una variedad de virtudes divinas, como muchos rayos de luz,
de modo que la vida de negación al yo, y su renuncia al mundo, a sus riquezas,
honores y placeres; el comportamiento rendido, humilde, infantil, inocente,
ingenuo y transparente es evidente para todos, aun así,
esta es una forma y una belleza que no le agrada al mundo ni a la razón cegada, sino que,
por el contrario, a menudo ridiculizan.

Lo que es más, ellas a menudo les parecen,
incluso a otras personas piadosas--que juzgan más según los sentidos externos y la razón,
y que gobiernan sus vidas religiosas más por ello,
que por el Espíritu--morenas como las tiendas de Cedar,
como las cortinas de Salomón (Cantares 1:5-6);
ignorantes de que debajo de esta vestimenta externa,
han escondido internamente la belleza y hermosura;
de modo que los hijos de la madre de ellas, con frecuencia se enojan con tales almas,
quienes, sin hacer ningún gran espectáculo externo ni apariencia,
sólo se esfuerzan en silenciosa abstracción,
por guardar la viña de sus propios corazones,
y así continúan siendo "`los pacíficos`" (Salmo 35:20),
"`los protegidos`" (Salmo 83:3) de la tierra.
La mejor parte de ellas no se ve, su sabiduría divina está escondida (1 Corintios 2:7);
la comunicación de ellas con Cristo está escondida,
su andar íntimo con Dios y su vida en Dios están escondidas (Colosenses 3:3);
el disfrute de tanto deleite, paz, gozo y bienaventuranza que fluyen de ello,
está escondido.
En resumen, la vida de ellas es una vida en el Espíritu (Romanos 8:1,4, 9),
y toda la gloria,
posición y excelencia de ellas están internamente escondidas en Dios (Salmo 45:13).

Que tales almas divinamente santificadas,
que buscan seguir al Cordero lo más de cerca posible adondequiera que las conduzca,
mediante la más completa negación de sí mismas y de todo lo demás,
por la más ferviente y continua adhesión a Dios, por un andar retirado delante del Señor,
y dejando que su santificación sea perfeccionada aquí (2 Corintios 7:1)--que tales almas,
digo,
tienen segura e infaliblemente que esperar privilegios
y gloria extremadamente grandes y preciosos,
en el tiempo y en la eternidad,
es irrebatible a partir de muchos testimonio de las Escrituras, de los cuales,
por razones de brevedad, sólo mencionaré unos pocos,
solicitándole al lector devoto que se refiera a ellos y medite más sobre ellos,
en la presencia de Dios.
Números 12:6-8; Deuteronomio 10:8-9; Salmo 45:14-15; 65:5; Cantares 6:9-10; Jeremías 35;
Lamentaciones 4:7; Malaquías 3:3; Mateo 19:27-28; Lucas 2:37; Juan 14; 15:15;
1 Corintios 2:6; 15:41; Apocalipsis 14:1-5; etc.

Que nadie piense que es poca cosa, cuando es consciente en su corazón de una inclinación,
atracción y afecto secretos por una vida peculiarmente retirada, seria,
estricta e interna delante de Dios, sino que acepte todo ello,
como una gracia particular y un santo llamamiento de Dios,
y lo estime como un gran privilegio y como algo muy bendecido,
que Dios condescenderá en otorgarle en el tiempo y en la eternidad.
Y con este fin repetiré una vez más las señales de tal vocación, que,
entre otras que se podrían mencionar, son principalmente estas:
Cuando una persona no encuentra descanso ni satisfacción
en la vida mezclada de la generalidad de los piadosos,
sino que es reprendida,
y tiene repulsión incluso por los pecados e imperfecciones más latentes,
los secretos apegos a las cosas creadas, y a todo egocentrismo, amor al yo,
voluntad del yo y autocomplacencia.
Cuando, por el contrario, está internamente consciente de algo atractivo y seductor,
de modo que gustosamente se uniría con Dios de la manera más estrecha e íntima,
y viviría delante de Él en una estado de separación del mundo;
cuando el alma es despojada y privada de su actividad externa
anterior con respecto a la razón y a los sentidos,
y ya no siente dentro de ella ninguna inclinación, nutrición,
ni excitación en sus ejercicios y ocupaciones habituales,
ni en la reflexión y meditación, sino que en oposición a esto,
percibe dentro de ella una atracción e inclinación hacia la sencillez,
rendición y compostura internas,
y hacia una devoción y atención a Dios universales y tiernas,
quien está presente con ella,
sin ningún ejercicio en particular de sus facultades de pensamiento, etc.

Los primeros Cristianos, en los tiempos de los apóstoles y sus inmediatos sucesores,
fueron evidentemente "`linaje escogido, real sacerdocio, nación santa`" (1 Pedro 2:9),
y se dedicaron fervientemente a una vida sencilla, retirada y piadosa;
como podría demostrarse suficientemente a partir de los escritos de los apóstoles,
y de los testimonio de los padres primitivos.
Pero mis límites no me permiten ampliar este punto, y por lo tanto,
refiero al lector a "`__Arnold`'s Delineation of the Primitive Christians,__`"^
footnote:["`__Perfil de los Cristianos Primitivos__`" de Arnold.]
y especialmente a su "`__True Representation of the Inward Christianity of the Ancients,__`"^
footnote:["`__Verdadera Representación del Cristianismo Interno de los Ancianos__`".]
donde se pueden encontrar numerosas pruebas de esto.

Pero cuando gradualmente, el primer amor y el celo de muchos--y con el tiempo,
el de la mayor parte--comenzaron a enfriarse,
de modo que en todas partes se contentaron con la mera profesión externa, o bien,
con un pequeño comienzo de gracia;
y donde no se mantuvieron en un estado de vigilancia por la persecución, fuego y espada,
frecuentemente se dejaron seducir por el elemento externo de este mundo,
y por una multitud de preocupaciones y emprendimientos seculares,
de manera que sólo se podía percibir una pequeña diferencia
entre ellos y los paganos entre los que moraban.
Esta tibieza y declive obtuvieron, por decirlo así,
posesión y firme establecimiento en la iglesia durante
la época tan agradable para los sentidos y la razón,
del célebre emperador Constantino el Grande;
y la vida de la mayor parte de los Cristianos ya
no era la antigua vida escondida de Cristo en Dios,
sino una vida externamente espléndida y pomposa.
Ya no era el Cristianismo internamente real, sino un Cristianismo de apariencia externa.

Sin embargo,
en todas las épocas han habido unas pocas personas excepcionales y preciosas,
quienes al no encontrar descanso para sus almas y
conciencias en la vida tibia y corrupta de la generalidad,
se dedicaron y consagraron de una manera particular al servicio de Dios, e hicieron,
por encima de los demás, que toda su ocupación y profesión consistiera,
como lo únicamente razonable, en ejercitarse con diligencia en esta vida retirada,
piadosa y escondida,
despreciando todo lo que pudiera en alguna forma
impedirles o hacerlas perezosas en su caminar serio.
Entre estas, también había muchos jóvenes devotos de ambos sexos,
cuyo única preocupación era, cómo agradar al Señor y ser santos en cuerpo y en espíritu,
para así aferrarse al Señor con mayor libertad.^
footnote:[De tales personas se jactaba Justino Mártir ante el Emperador,
alrededor del año 130, en los siguientes términos: "`Entre nosotros hay muchos,
de ambos sexos, que viven una vida de soltería y castidad hasta su vejez,
después de haber seguido desde su infancia la doctrina de Cristo.
(Mateo 19:11) Por mi parte,
afirmo que puedo presentar ejemplos de esto entre personas de todas las clases.`"
Apol. 2. Otro, poco después de él, escribió abiertamente lo siguiente:
"`Hay muchos entre nosotros, tanto hombres como mujeres,
que envejecen en una vida soltera;
porque esperan en tal estado estar más cerca de Dios.`"
__Athenag.__ Apol. página 36.
Y Agustín dice: "`Ya apenas sorprende que tantos jóvenes, hombres y mujeres,
desprecien el matrimonio y vivan en castidad.`"
Ver. Relig.
Cap. 3. Ver también __Arnold`'s Delineation,__ sec, 5. cap.
5.]
También estaban los que eran generalmente llamados "`Ascetas`",
o los que se ejercitan en la piedad, quienes estando deseosos de ser perfectos,
según la exhortación del Señor Jesús (Mateo 19:21),
se abstenían de toda asociación innecesaria con la humanidad y de preocupaciones superfluas,
y frecuentemente, al llamado divino,
vendían lo que tenían y los distribuían entre los pobres,
y después vivían una vida pacífica, en una pequeña habitación o apartamento,
trabajando un poco con sus manos,
y empleando todo el resto de su tiempo en morir a todas las cosas,
mediante una total negación al yo, y llevando una vida escondida en Dios,
por medio de constante oración y comunicación con Él.

Y cuando la tibieza y declive hacia lo externo se hizo muy general y muy grande,
muchos miles, para no ser arrastrados por ello,
ni permitir disminución alguna en la manera estricta de su caminar,
por la vida perezosa y mundana de los otros Cristianos,
huyeron de la interacción común con los hombres,
y se retiraron a lugares remotos y desiertos, conforme a la voluntad divina,
y se ejercitaron día y noche, con mucha diligencia,
en una vida interna y escondida delante de Dios y en Su presencia.

No es mi objetivo ni mi intención presentar y recomendar el modo de vida externo,
los ejercicios corporales,
o ninguna otra peculiaridad de éstos o de los otros individuos santos antes mencionados,
dado que ellos mismos no tenían una regla general ni un método en particular,
y con el transcurso del tiempo, mientras la oscuridad se incrementaba continuamente,
poco a poco cayeron en observancias externas y locura humana.
Mi intención es meramente mostrar que fue por estas almas devotas y solitarias--como
continuaron siendo hasta el siglo V--que la religión primitiva,
interna y poderosa fue principalmente mantenida y propagada.^
footnote:[Como puede verse en las vidas de los padres primitivos, Antonio,
Hilarión y otros, y particularmente en los escritos de Macario, Efraín, Sirio, Nilo,
y también de Casiano, Clímaco, etc.]
Incluso, en los tiempos miserables que siguieron,
Dios siempre ha tenido "`sus protegidos`" (1 Reyes 19:18; Salmo 83:3),
como puede verse por la referencia en __Catal.
Testim. Veritatis__,^
footnote:["`__Catálogo de Testimonios de la Verdad__`".]
y en otros libros tales como __Arnold`'s Theol. Myst.__
Cap. 16-17.^
footnote:["`__Teología Mística__`" de Arnold.
Capítulos 16-17]

Entre esas almas escogidas y devotas de Dios, también deben reconocerse, particularmente,
las que son generalmente llamadas "`místicas`" (es decir, secretas o escondidas),
cuyos escritos, junto con las Sagradas Escrituras,
contienen una verdadera definición del Cristianismo real e interno,
y del auténtico conocimiento de Dios.^
footnote:[En una obra del autor titulada, "`La vida de los santos`", en tres volúmenes,
él ha recopilado una variedad de hechos e información sobre este tema,
a los que se remite al lector.]
Es verdad,
que la mayoría de ellas vivieron y fueron conocidas por sus escritos en la iglesia romana;
sin embargo, al dar testimonio de la verdad,
debo decir que las sinceras entre ellas eran más evangélicas
y reformadas que la mayoría de los protestantes;
quiero decir, eran verdaderos Cristianos interiores,
que no seguían aferrándose a lo externo,
sino que servían y adoraban a Dios en espíritu y en verdad,
retirando sus afectos y confianza de todas las cosas creadas, de sí mismos,
y de todas sus obras, a través de la verdadera fe y unión con Dios en Cristo.
Y aunque no apruebo ni defiendo todos los puntos menores,
ni los incidentes externos que ocurren en tales escritos, aun así, es cierto,
que en una simple página de los verdaderos escritos místicos, hay más unción, luz,
consejo, consuelo y paz divinos para el alma que está buscando a Dios,
que lo que a menudo contienen muchos volúmenes débiles y aguados de escuelas teológicas,
como testifican teólogos iluminados entre los mismos protestantes.^
footnote:[Ver "`Historia de la Teología Mística`" de Godfried Arnold, Capítulo 8. 38,
y prefacio No. 7 de Sofía.]
Pero, ¿por qué es que escritos tan valiosos son generalmente tan poco apreciados y utilizados?
¿No será porque una curiosidad inquisitiva no encuentra alimento en ellos,
y porque la naturaleza del viejo hombre y la vida del yo son atacadas muy severamente,
y porque no requieren ser razonados ni especulados como otros libros,
que son acomodados al gusto del viejo Adán,
pero insisten en la negación al yo y en llevarlo a la muerte?
No obstante, como muchos teólogos piadosos entre los protestantes mismos,
han rescatado y defendido las verdades divinas que se encuentran en estos escritos,
me vuelvo de nuevo a esas almas escogidas, que se sienten llamadas a esta vida interna,
escondida y más estricta.^
footnote:[Véase entre los escritores reformados, de Voetius,
"`Ejercicio de la Piedad y en los Ascetas`". De Lodenstein, "`La Contemplación de Sion`",
página 39 y siguientes.
De Franc Rous, "`Interiora Regni Dei`". De J. de la Roque, "`Últimas Horas`",
página 63. De Poiret, "`la Erudición de la Economía Divina`", etc.
Y entre los luteranos, Lutero, Johann Arndt, Varenius, Hoburg,
Jacob Spener en el prefacio de Tauler.
Arnold en "`Teología Mística`", Weismann en "`Introducción a la Historia Eclesiástica`",
parte 2, página 555 y siguientes, y Aletophili en "`Teología Mística`".]

=== III. Una Dirección Específica a Esas Almas Escogidas que se han Rendido a Dios y a Su Vida Internamente Escondida

A ustedes, elegidas y amadas almas,
a ustedes devotas Nazarenas--a ustedes mi muy queridos hermanos y hermanas,
que se han dedicado y consagrado sinceramente a una religión
más exacta y a la vida escondida con Cristo en Dios--^
footnote:[El santo mártir Cipriano,
al dirigirse a las mujeres que se habían dedicado a Dios,
les otorga los siguientes títulos: "`Flores entre las plantas de la iglesia;
belleza y adorno de la gracia espiritual;
retoños y niños agradables y nobles de alabanza y honor (de Cristo y su iglesia),
una obra completa y no consumada; imagen de Dios,
según la semejanza de la santidad del Señor Jesús;
// lint-disable invalid-characters
lo más excelente del rebaño de Cristo`". El erudito Sandæus,
en su prefacio a la Teología Mística, toma prestados estos apelativos y los aplica,
no inapropiadamente, a los místicos.]
a ustedes en particular,
tengo todavía que dirigirles en amor,
una palabra de amonestación y estímulo en esta ocasión. Porque aunque
algunas de ustedes ya poseen la unción del Espíritu (1 Juan 2:27),
la cual las guía a toda verdad; aun así,
la sabiduría que es de lo alto también se manifestará en este caso,
al recibir con gusto instrucción de otros (Santiago 3:17). Pero,
para que yo mismo no sea hallado falto,
procuraré mantener mi propia alma especialmente en cuenta, mientras me dirijo a ustedes.

Vemos a partir de todo lo que se ha dicho, que no debemos gobernarnos,
formarnos ni limitarnos según el ejemplo de otros, aunque sean personas piadosas;
sino que Dios ciertamente demanda de nosotros algo en particular (Mateo 5:46-48).
Me refiero a deberes más estrictos y a una vida y conducta más santas,
tanto interna como externamente, de lo que es, por desgracia,
manifestado por los demás. Por lo tanto, olvidemos lo que queda atrás,
y mantengamos en la mira la meta y el premio que nuestro llamamiento celestial nos ofrece.
Dejemos que los demás vivan como les plazca,
y aunque muchos de los piadosos no carezcan de faltas,
¿qué es eso para ustedes y para mí? Sólo miremos,
con una mente serenamente vuelta hacia el interior,
a Aquel que siempre nos llama a seguirlo (Juan 21:22).
Grande e indescriptiblemente glorioso es,
en realidad, nuestro llamamiento supremo;
pero recordemos las palabras de nuestro Salvador: "`Muchos son llamados,
más pocos escogidos`" (Mateo 20:16). No es mejor que otros,
el que tiene más luz o una percepción más profunda de los caminos de Dios,
sino el que tiene más amor y lleva una vida más exacta y santa.
En esto, mis amados,
consiste esa particularidad que debe ser hallada en nosotros por encima de los demás.

Si otros les sirven a Dios y a las riquezas al mismo tiempo,
y mientras profesan ser piadosos, buscan y acumulan tesoros en la tierra,
involucrándose en extensos intereses seculares;
nosotros miremos a Aquel que llama a todos los que resuelven seguirlo en serio:
"`Las zorras tienen guaridas, y las aves de los cielos nidos;
mas el Hijo del Hombre no tiene dónde recostar la cabeza`" (Lucas 9:58). Y recuerden,
que si los primeros son israelitas, nosotros debemos ser levitas, real sacerdocio,
con respecto a los cuales Dios ha dicho: "`De la tierra de ellos no tendrás heredad,
ni entre ellos tendrás parte.
Yo soy tu parte y tu heredad`" (Números 18:20; Deuteronomio 10:9;
Ezequiel 44:28). Debemos mostrar que estamos muertos
al mundo y que ya no miramos las cosas que se ven,
sino que nuestras vidas están escondidas en Dios;
y nuestro caminar retirado del mundo y negador de las riquezas,
deben ser como una fuerte voz que les dice a todos los hombres:
"`Sólo Dios es suficiente.`"
(Salmo 73:25).

Si otros se toman y se permiten libertades,
mediante un consentimiento inmoderado y buscando agradar
a los hombres--ya sea en las compañías que mantienen,
en sus conductas,
modas y similares vanidades--nosotros debemos ser particulares
en este aspecto y no ceder ante el mundo ni un ápice;
es mejor ser llamados obstinados que mundanos.
Cuán fácil es que el ceder se convierta en extravío,
y por demasiada complacencia a esta Dalila,
se pierda el poder interior como en un sueño. El celo del Esposo de nuestras
almas no permite que se haga tanto para complacer a Su rival,
y aquel que no quiera creer debe sentir su pérdida,
que "`la amistad del mundo es enemistad contra Dios`" (Santiago 4:4).

Si otros siguen sus apetitos sensuales y gastan y
malgastan su valioso tiempo en la variedad,
adorno y belleza de sus vestidos, sus casas y sus muebles;
si dedican mucha y valiosa atención a la comodidad y disfrute de sus cuerpos viles;
nos corresponde demostrar que no somos sensuales ni animales, sino hombres espirituales,
quienes, por eso, ya no viven según la carne ni los sentidos,
sino según el Espíritu (Romanos 8:1,4,9), y no buscan yacer aquí sobre rosas y comodidad,
cuando nuestra Cabeza y Precursor nació en un miserable establo y pesebre,
y murió en una cruz llevando una corona de espinas.
En efecto, no puedo creer, ni sé si el mundo creerá,
que la religión interior de los primeros sea grande
y correcta cuando tienen todo lo externo muy elegante,
muy conveniente y muy preciso para sus mentes,
aunque conozcan todos los misterios y hablen de la espiritualidad más exaltada.
Aquel que se sienta llamado a ser heredero del cielo y esposa del Rey de reyes,
deberá ser, por lo tanto, "`toda gloriosa en su interior`" (Salmo 45:13 RVG),
para que su parte interior pueda convertirse en una
morada y residencia adecuada de la divina Majestad;
y por lo tanto, encontrará que hay mucho que limpiar, adornar y embellecer ahí,
y pronto perderá todo gusto por cualquier gusto externo.

Si vemos que otros se vuelven hacia los sentidos, y por un oír, ver,
hablar y pensar trivial e innecesario abren sus corazones, por decirlo así,
a las cosas creadas;
que nuestros corazones sean como un jardín cercado
y como una fuente sellada a todos los objetos creados,
y solamente estén abiertos al Amado de nuestras almas.
Debemos esperar día y noche en los umbrales de Sus puertas,
como un sacerdocio espiritual, y por lo tanto,
estamos obligados--porque creemos que el Señor está presente en el templo de
nuestros corazones (Zacarías 2:13)--por esa reverencia que le debemos supremamente,
a mantener nuestras bocas, mentes y pensamientos en santo silencio y retiro.
Cuando hablemos, debemos hablar desde Dios, ante Dios, en Cristo Jesús,
y con palabras reales de Dios (1 Pedro 4:11). Porque ¿acaso pueden suponer ustedes,
mis amados, que nosotros--los que podemos contemplar y dirigirnos
al Señor de gloria dentro de nosotros--tenemos
libertad de faltarle el respeto tanto como para dejarlo ahí,
por decirlo así, y volvernos al exterior hacia las cosas visibles?
¡Oh, cuán irreverente sería esa conducta!
Nuestra vida y comportamiento silenciosos, considerados, abstraídos y retirados,
deberían más bien,
darles a todos una impresión de la santidad y del temor de Dios ocultos en nuestro interior.
Fue en referencia a esto,
// lint-disable invalid-characters
que Bernières elogió a su guía espiritual después de su fallecimiento diciendo:
"`El simple recuerdo de él,
recoloca mi alma en la presencia de Dios (si se hubiera alejado de Él),
y me da ánimo y audacia para esforzarme fervientemente
// lint-disable invalid-characters "è"
en pos de la verdadera virtud`". (__Lettres viè illum:__ litt. 35. page 283.)

Si otros fijan sus afectos primero en una objeto creado y luego en otro,
y buscan y encuentran en ellos disfrute, consuelo, gozo y deleite;
que nuestros corazones,
nuestros afectos y todo nuestro amor sean solo y eternamente dedicados,
en verdadera castidad virginal, al Esposo de nuestras almas.
Si todavía poseemos muy poco amor para amar suficientemente, al infinito y hermoso Bien,
¿cómo atrevernos a privarlo de alguna parte de él? Y además,
¿qué hay en la miserable y necesitada creación,
que no se pueda hallar en suprema perfección e infinita abundancia en el Creador,
y ser disfrutado cien veces más, incluso en esta vida?
(Mateo 19:29). Por lo tanto,
que la totalidad de nuestros corazones digan a todo bien que no es este y supremo Bien:
"`No te necesito`".

En general, debemos estar muertos a todas las cosas creadas,
y llevar una vida escondida con Cristo en Dios; una vida de santidad y piedad,
de humildad y mansedumbre, de sencillez e inocencia, de amor y misericordia,
de castidad y moderación; en resumen, una vida delante de Dios y en Dios.

Sin embargo, mis amados, además de todo esto,
guardémonos muy cuidadosamente en todo nuestro caminar y en nuestra conducta,
delante de Dios y de los hombres, de toda afectación, simulación,
santidad y formalidad externas, cuyo hábito se ha apoderado de nosotros de manera tal,
que frecuentemente y sin nuestro conocimiento, contamina nuestra vida y conducta,
si no en forma evidente, sí de manera sutil, lo cual despoja la mente de toda libertad,
paz y libertad de espíritu.
Nuestra conducta, modo de caminar, palabras y gestos,
así como también los pensamientos y la disposición del corazón,
deben ser juzgados y pesados, no por los hombres, que sólo ven lo externo,
sino por la purísima luz de Dios.
No debemos procurar parecer santos, sino _ser_ santos, y eso, sólo ante los ojos de Dios,
quien "`examina los íntimos pensamientos y el corazón`".
Debemos mantener lo más profundo de nuestras almas,
constantemente desnudas y abiertas a los rayos de este Sol eterno,
para que podamos caminar en sencillez y pureza, y en verdad y justicia.
(2 Corintios 1:12). Dios es un Dios de verdad; por lo tanto,
debemos caminar en la verdad y sencillez de corazón,
si queremos tener comunión con un Ser tan puro.

En consecuencia,
que también esté lejos de nosotros--al tener una percepción interna y encontrarnos llamados
a este camino Cristiano más estricto y particular--imaginar que somos algo especial,
y exaltarnos por encima de otras personas piadosas, o incluso,
atribuirnos algún privilegio espiritual o título de honor, y mentalmente menospreciar,
o incluso despreciar a otros.
Con tal conducta mostraríamos, que aunque tuviéramos luz, aun así,
no tendríamos la realidad ni la experiencia del Cristianismo genuino e interno;
porque la más profunda humildad y completa aniquilación del yo, son las propiedades,
características y objetivo esenciales de la verdadera vida interna.
Pero si realmente poseemos algún grado de experiencia y progreso en esta vida divina,
la unción divina nos enseñará, sin ninguna duda, que tenemos que atribuirlo,
no a nuestra diligencia y fidelidad, sino a la inmerecida gracia y poder de Dios.
¿Qué tenemos pues, que no nos haya sido dado?
Si llegamos a ser santos y felices, es por gracia y no por nosotros mismos;
es don de Dios (Efesios 2:8). ¿De qué pues nos jactamos?
Si hay algo bueno en nosotros, no procede _de nosotros_ ni _es nuestro,_
es y sigue siendo propiedad de Dios, quien tiene en Su poder tomar de nuevo lo Suyo.

Por lo tanto, si no podemos gloriarnos, ni siquiera en la menor medida,
en nuestra piedad y virtudes, ni considerarlas con autocomplacencia,
¡cuánta menos libertad tenemos de hacerlo, en referencia a los dones, dulzura,
gozo o iluminación espirituales o divinos, incluso si fueran éxtasis y revelaciones!
De hecho, debemos aceptar los dones de Dios con agradecimiento,
pero presumir tan poco sobre ellos,
como para ser capaces de devolverlos al Dador en cualquier momento y sin dificultad,
y buscar nuestro descanso sólo en Él y no en Sus dones.
¡Ah, cuántos, en posesión de tales dones y sensibilidades, se imaginan muy fervientes,
piadosos y santos, mientras que tal vez todavía están llenos del amor,
la voluntad y la opinión del yo,
en lugar de esa humillación y autodegradación muy necesarias delante de Dios,
y por debajo de toda criatura!
Está escrito: "`Regocijaos en el Señor`" (Filipenses 4:4);
"`Tened por sumo gozo cuando os halléis en diversas pruebas`" (Santiago 1:2);
pero de los dones se dice:
"`No os regocijéis`" (Lucas 10:20). Debemos ser perfeccionados y unidos a Dios,
no tanto por hacer y disfrutar,
sino por sufrir y por privaciones (Hebreos 2:10). Recordemos y retengamos bien,
que la sustancia del Cristianismo y de la verdadera santidad,
no consiste en cosas como esas;
sino en morir a nosotros mismos y a todas las cosas creadas,
y en llevar una vida escondida con Cristo en Dios y delante de Dios.

Digo, "`con Cristo`", porque ¡ah,
qué pronto se desvanece todo lo que no está fundado en Cristo!
La única base real e inmutable de la vida interior,
es la unión y comunión interna o mística con Cristo Jesús por fe.
Aquí, ni las buenas intenciones y resoluciones,
ni nuestro propio querer y correr (Romanos 9:16),
ni ningún esfuerzo lícito de nuestros propios poderes,
sirven como fundamento y establecimiento adecuados de nuestra santidad.
Nosotros sabemos lo que el supremo Maestro de la vida interior dice:
"`El que permanece en mí, y yo en él, este lleva mucho fruto;
porque separados de mí nada podéis hacer`" (Juan 15:5). ¡Ojalá
lo creyéramos firmemente y lo practicáramos continuamente!
Se nos manda a salir de nosotros,
en la más profunda convicción de nuestra propia incapacidad, con fervientes deseos de fe,
para aferrarnos en lo profundo de nuestras almas
a esta única fuente de toda gracia y santidad,
y '`tomar de esta plenitud,
gracia sobre gracia`' (Juan 1:16). Retirémonos continuamente en Él,
apartando nuestros afectos de todas las cosas creadas,
y dondequiera que vayamos o estemos, habituémonos a permanecer de manera infantil en Él,
y así, el poder vivo de Su Espíritu, que nos llena desde el interior,
santificará completamente cuerpo,
alma y espíritu (1 Tesalonicenses 5:23). Entonces veremos, si Marta,
con sus bien intencionadas obras y esfuerzos externos, o María,
sentada a los pies de su Salvador, alcanzará la mejor parte,
la única cosa necesaria (Lucas 10:42).

Pero ahora, mis muy estimados hermanos y hermanas,
si nos encontramos redimidos de la tierra, y hechos reyes y sacerdotes para Dios;
y si en lo profundo de nuestras almas tenemos libre acceso al lugar santísimo,
ante la presencia de Dios,
nunca olvidemos atribuir acción de gracias y honor
a la preciosa y expiatoria sangre de Jesucristo,
por la que solamente esta gracia ha sido comprada para nosotros (Apocalipsis
5:9-10) y abierta a nosotros (Hebreos 10:19-20). Porque ciertamente,
si Jesucristo no hubiera muerto y resucitado por nosotros,
el camino a la verdadera santidad y comunión con Dios habría
permanecido eternamente cerrado contra nosotros,
miserables criaturas; lo cual toco aquí particularmente,
porque aquellos que se aplican a una religión estricta e interna,
o dan testimonio de ella, son universalmente culpados, como si al hacerlo,
menospreciaran o incluso despreciaran la obra de
redención consumada por Cristo para nosotros.
Ahora bien, no negaré que es posible que muchos,
que hasta ahora no se han sentido particularmente humillados por aflicción,
pobreza y sufrimiento internos,
con buena intención y para resistir el abuso general de esta verdad,
hayan usado expresiones inmoderadas y desconsideradas, y llegado a extremos.
Sin embargo, todas las almas verdaderamente iluminadas,
incluso las llamadas místicas entre los Católicos romanos,
en realidad han estimado y glorificado más los méritos
de Jesucristo como nuestra expiación y justificación,
que quizás muchos de sus acusadores.

Pero mientras tanto, almas escogidas, reconozcamos con humilde gratitud,
que si no tuviéramos a Jesús _por_ nosotros, nunca habríamos tenido a Jesús _en_ nosotros.
Y que si alguna vez somos exaltados al estado de
la más elevada y pura contemplación de la Deidad,
en esta vida o en la siguiente,
esta consideración permanecerá siempre deliciosa y supremamente preciosa para nosotros.
El Cordero que fue inmolado, es digno de recibir el poder, la riqueza, sabiduría, fuerza,
gloria, acción de gracias y alabanza; porque fue inmolado,
y nos ha redimido para Dios por Su sangre de toda nación, lengua, linaje y pueblo,
y nos ha hecho reyes y sacerdotes para Dios.
¡Amén y amén!

"`¡Bendito salvador Jesús,
que por tu muerte y resurrección has traído a la luz esta vida divina y escondida,
te ruego que llegue el tan deseado y feliz momento,
cuando en lugar de todas las ordenanzas, especulaciones y controversias humanas,
esta vida genuina,
interna y Cristiana florezca de nuevo en su primera estima entre todas las naciones,
para que puedan voluntariamente someter sus corazones al dominio de Tu amor! ¡He aquí,
te ofrezco mi corazón, precioso Jesús, santifícame en esta tu verdad,
escóndeme cada vez más en el secreto de tu rostro! ¡Oh, mi sumo Sacerdote,
ocúltame contigo en Tu tienda de todo peligro! ¡Preserva,
continúa y perfecciona Tu bondadosa obra en mí,
para que toda la vida del yo muera y decaiga, hasta que no vea ninguna otra vida,
voluntad o movimiento en mí, que el que procede de Ti y de Tu Espíritu puro,
para gloria eterna del Padre! ¡Amén!`"
