== El Excelente Camino del Amor Verdadero

[.chapter-subtitle--blurb]
"`Dios es amor; y el que permanece en amor,
permanece en Dios, y Dios en él.`" 1 Juan 4:16

[.alt.centered]
=== I. El Ejercicio del Amor.

Nada es más hermoso, puro, placentero, poderoso y perfecto que el amor,
porque "`Dios es amor`". No hay mejor manera en la
que Dios pueda ganar posesión en el corazón del hombre,
sino por medio del amor,
ni hay nada con lo que el hombre pueda agradar más a Dios que con amor;
porque "`el amor es el cumplimiento de la ley`" (Romanos
13:10). Eso que el hombre no pudo,
ni puede cumplir mediante la severidad de la ley y todo temor al castigo,
es fácilmente cumplido cuando Dios encomienda Su amor al hombre en Cristo Jesús;
cuando le proclama el perdón de sus pecados, la redención y la salvación eterna,
y lo atrae, mediante estos motivos, al arrepentimiento, y a amarlo en respuesta.

Ahora que las tiernas compasiones del amor de Dios se han abierto nuevamente al hombre,
en el dulce nombre de Jesús Emanuel,
y hasta esta hora permanecen completamente abiertas en el alma
del pobre pecador (sea que esté consciente o no de ello),
el amor eterno está, por tanto, constantemente ocupado en el centro de nuestras almas,
ofreciéndose y recomendándose a nosotros,
e insinuándose y buscando entrada en nosotros de mil maneras distintas,
para nuestra felicidad eterna.
Todo buen pensamiento y deseo que se levanta en el corazón del hombre,
toda tristeza y dolor por el pecado, toda reprensión y amonestación,
la incitación a la oración y a la verdadera piedad, la total rendición a Dios,
y similares, son los efectos puros de este paciente amor de Dios.
Si el más vil pecador pudiera percibir la milésima parte de esto,
se sentiría instantáneamente constreñido a rendirse a este amor.

¡Oh, Amor, manifiéstale a los pecadores, aunque sea de manera remota, que Tú eres amor,
y ellos te amarán y te seguirán!

Ahora,
si una persona está dispuesta a ser llevada al arrepentimiento
por la bondad y amor de Dios:

Que a partir de ese momento crea sin vacilación,
que no puede agradar a Dios de mejor manera ni con
mayor facilidad por medio de alguna obra o ejercicio,
sino mediante el amor.

Que sólo atienda y aprecie debidamente la chispa escondida del amor de Dios en su corazón,
mediante un recuerdo cordial de Dios, un giro filial hacia Dios,
y ocupándose sencillamente de Dios y de Sus perfecciones.

Que se ejercite en amor.
Que, por amor a Dios, renuncie a todo lo que es más querido para ella y se rinda en fe,
a este amor puro.

Que se regocije cada vez que se presente una buena oportunidad de hacer,
negar o sufrir algo por el amor y la gloria de Dios.

Que se acostumbre a hacerlo todo por amor a Dios,
a recibir en amor todo lo que le ocurra, como proveniente de la mano de Dios,
y a soportar, en amor, todo lo que tenga que sufrir por amor al Señor.

Todo debe ser sacrificado al amor, por amor.

Por amor, los sufrimientos más amargo se vuelven dulces,
las más adversas circunstancias provechosas, y las más pequeñas obras grandes y divinas.

No se suponga que con esto, se está hablando de un amor perceptible y reconfortante;
poseer el amor y sentirlo no siempre van juntos.

El amor verdadero y constante consiste en una valoración interna de Dios;
en conocerlo y reconocerlo por fe como sumamente, sí, únicamente precioso.
Por lo tanto,
voluntariamente nos ofrecemos y rendimos--y todo lo que
está en nuestro poder--a Dios y a Su servicio y gloria.

Este amor, que el Espíritu Santo derrama en nuestros corazones,
puede existir incluso en medio de la sequedad,
la oscuridad y los más profundos procesos de purificación,
los cuales no son más que los benditos efectos del puro amor de Dios.

[.alt.centered]
=== II. Completa Rendición al Amor.

En verdad, cuando un pecador alcanza el arte del amor puro, de modo que,
mediante un completo abandono y renuncia de sí mismo se rinde en sinceridad
a Dios y le da plena libertad de hacer de él lo que quiera,
tanto en el tiempo como en eternidad,
no estimando ni considerando su propio perjuicio o ventaja, sino simplemente a Dios,
y que sólo Él sea glorificado, amado y complacido,
entonces la ira y el infierno no tienen más poder; pero sus pecados,
por grandes que sean,
desaparecen y son consumidos más rápido que un puñado de lino en un horno ardiente; sí,
este amor lo hace santo y semejante a Dios.

Ahora bien, es cierto, que por naturaleza,
estamos completamente arraigados en el pecaminoso amor al yo, y por ello,
tan inclinados por él a nosotros mismos, que no podemos ver, ni amar, ni confiar en Dios.
Por esta razón,
el propio Hijo de Dios debe derramar este amor en nuestros
corazones por medio de Su Espíritu Santo (Romanos 5:5),
y él está dispuesto a hacerlo, pues en Su encarnación tomó sobre Sí nuestros pecados,
y a través de este amor puro, nos ha reconciliado plenamente con Dios.

En servir a Dios con un amor tan desinteresado, consiste, propiamente hablando,
la verdadera religión. No obstante,
es profundamente lamentable que incluso personas piadosas anden a tientas tanto tiempo,
algunas incluso todas sus vidas, en una afanosa atención y solicitud por sí mismas,
sin una completa rendición de sus propios intereses, ni encomendándose a Dios,
ni buscando el amor puro en el corazón y rostro de Jesucristo.
¡Oh, amémoslo, porque Él nos amó primero! (1 Juan 4:19)

¡Oh, infinito amor! ¡Oh, adorable Trinidad! ¡Padre, la fuente del amor; Hijo,
la sublime luz; y Espíritu Santo, la llama viva y el santo ardor del amor! ¡Oh,
Dios--que eres amor puro y perfecto--eres un fuego ardiente y consumidor,
que debe consumir todo lo que no puede coexistir con el amor puro!
¡Destruye en nosotros por medio de Tu preciosa llama,
todo lo que es contrario a tu santidad!
Empieza, continúa y perfecciona en nuestras almas,
la gran obra de purificación y santificación, sin la cual,
nadie puede ver Tu rostro! ¡Concédenos, Señor, un poco de tu palpable y ardiente amor,
para despertarnos de nuestra insensibilidad y sueño mortal,
y danos una medida de temor a tus terribles juicios,
para que podamos abandonar a tiempo las sendas del error!
Derrama en nuestros corazones una gota de Tu poderoso amor,
que puede transformar el infierno en paraíso. ¡Sí, oh, Señor,
enciende pronto este fuego en la tierra,
el que viniste a encender y tanto deseaste que volviera a arder,
para que el reino de Tu amor sea eternamente establecido
y nosotros podamos ser en Ti--en unidad de corazón,
alma, palabra y acción--un espíritu con el Padre, Hijo y Espíritu Santo,
bendito para siempre.
Amén.

[.alt.centered]
=== III. Sobre el Amor Fraternal.

Del amor a Dios derivamos el amor hacia los hermanos, sí, incluso,
el amor hacia todos los hombres.
Tanto el primero como el segundo no son un asunto que pueda ser enseñado, o aprendido,
o producido por uno mismo; ambos son fruto y propiedad del nuevo nacimiento de Dios,
mediante el cual escapamos del dominio de la ira y de las tinieblas, y en cambio,
somos trasladados al reino del amado Hijo,
donde somos cada vez más impregnados de las dulces y deliciosas
fuerzas del amor que emanan del corazón de Dios.

En el primer nacimiento, puede haber una ternura emocional, adulación sensual,
y una complacencia egocéntrica hacia aquellos que
nos complacen y se conducen amablemente con nosotros;
pero bajo todo ello se oculta la naturaleza corrupta y el amor al yo.
Así, a pesar de toda la apariencia de amor,
el individuo sigue siendo en el fondo un hijo de ira,
que en realidad no ama nada más que a sí mismo,
y a Dios y a su prójimo sólo en referencia a sí mismo.

De aquí surgen esa intranquilidad, irritación, sospecha,
molestia y otras mil fuerzas ásperas, latentes y continuas,
que perturban y afligen el pobre corazón; primero una persona y luego otra,
incapaces de actuar de manera que complazcan su propia voluntad y arrogancia.
En tal condición, todos los términos de paz,
puntos de unión y las más solemnes obligaciones no son más que castillos en el aire.
Si no nacemos del amor, no podemos amar como debemos.
Entre los orgullosos siempre hay contienda.
(Proverbios 13:10)

Por lo tanto, debemos ardientemente anhelar ser liberados de toda esa miseria inherente,
y ser hechos partícipes del manso y gentil amor de Jesús,
dado que este eternamente amoroso bien está indescriptiblemente
cerca de nosotros y se inclina voluntariamente,
por el Espíritu de Su amor, hacia aquel que le pertenece y suspira por amor.
Debemos filialmente rendirnos a Su secreta persuasión,
incesantemente sumergir todo nuestro egoísmo, todos nuestros sentimientos altivos,
ásperos y desconfiados hacia Dios y hacia nuestro prójimo, en el amor de Cristo,
y no cansarnos de esta humilde hambre y espera,
hasta que el Amor se nos conceda y nos impregne con Sus influencias divinas.

Ahora,
cuánto más nos dejemos guiar por la secreta atracción del
amor divino hacia este estado de sincera devoción a Dios,
y más aprendamos a morar en él, en amor y sencillez, tanto más beberemos,
como un infante del pecho materno, la vida pura, inocente y tierna del amor; de modo que,
nuestra alma, en lo más profundo, es cada vez más saciada con deleite,
y todo el hombre se vuelve dócil, amable, lleno y rebosante de amor.

Entonces experimentamos que el verdadero amor fraternal
es un estado y obra de Dios no forzado,
sin falsedad, sin formalismo, un movimiento libre de la nueva criatura.
En este abismo y elemento de amor, una persona puede entonces encontrar, abrazar,
bendecir y disfrutar de otra, muy íntimamente, para la gloria de Dios.
Y debido a que hemos sido bautizados en y por este Espíritu de amor de Cristo,
en un solo cuerpo (1 Corintios 12:13), y hemos bebido de un mismo Espíritu,
disfrutamos comunión sustancial unos con otros, tanto en la ausencia,
como cuando nos reunimos en el nombre de Jesús.

Incluso,
así como este amor fraternal puro surge del amor
de Dios y en un estado de fervor plácido de corazón,
no obstaculiza el amor de Dios, sino que más bien lo promueve.
No nos atrae hacia lo carnal ni a una relación externa e inestable,
sino que recoge y tranquiliza la mente,
y nos fortalece en la intención de ser totalmente para Dios.

En resumen, donde el amor nace en el corazón, allí manifiesta sus frutos,
que ellos son los correctos,
y todo su comportamiento y conducta hacia su prójimo se vuelve
una exposición viviente de aquello que el Espíritu de Dios,
mediante el apóstol Pablo, manda de él en 1 Corintios 13, y que aquí adjuntamos.

"`_El amor es sufrido._`"
La naturaleza busca lograr todo de inmediato o lo abandona por completo.
Si el hombre no ve una enmienda de inmediato en la mente de otro, lo rechaza por completo.
Si otro no puede comprender de inmediato sus perspectivas y seguir sus consejos,
lo descarta.
Pero el amor verdadero es sufrido, observa por un tiempo, no incomoda a su prójimo,
puede trabajar por mucho tiempo, soportar por mucho tiempo, enmendar por mucho tiempo,
esperar por mucho tiempo, tratar por mucho tiempo y tratar de nuevo,
amar por mucho tiempo y amar de nuevo.

"`_El amor es benigno;_`" de modo que su comportamiento atento y amable,
sus palabras y obras de amor, alegran y benefician a todos,
y abiertamente muestran cómo se entrega a sí mismo, y todo lo que está en su poder,
para uso y beneficio de otros.

"`_El amor no tiene envidia,_`" sino que desea que otros, al igual que él mismo, sean,
tengan,
se gocen y sean capaces de hacer algo--ya sea en
lo temporal o espiritual--y se regocijen en ello;
tan cordialmente, como si él mismo lo hubiera realizado o tuviera que disfrutarlo.
No se apresura a juzgar a otros, no es impulsivo, ni conflictivo,
ni rencoroso en la compañía de otros, sino que es sincero y modesto; lo que hace,
lo hace de corazón, con una intención humilde y recta.

"`_El amor no se envanece;_`" no pasa orgullosamente por encima de otros;
prefiere servir y estar sujeto a otros.
No desea que sus obras sean vistas, ni que se le rinda mucho agradecimiento por ellas.
La razón y el motivo del por qué ama, es el amor.
Él es su propio galardón y corona.
Por tanto, el amor siempre piensa que otros hacen demasiado por él,
pero que él mismo hace poco o nada.
(Mateo 25:27)

"`_El amor no hace nada indebido,_`" ni con dureza,
cuando otros no actúan en concordancia con su parecer.
El amor es como un niño pequeño; se complace pronto.
Está muy lejos de avergonzar a otros con una conducta impropia,
reproches o cosas similares; pero condesciende y se adapta a los más débiles,
más miserables y más pobres personas, sin avergonzarse de ellas.

"`_El amor no busca lo suyo,_`" como hace siempre la naturaleza,
incluso en sus mejores obras.
El verdadero amor no considera su propia ventaja o conveniencia,
ni la aprobación de otros; lo arriesga todo.
Si sólo puede dar, agradar, complacer y ser servicial a otro, se olvida de sí mismo.
Se regocija si aquel a quien ama se complace,
y estima su bienestar temporal o espiritual, como propio.

"`_El amor no se irrita,_`" aunque a menudo sea injustamente tratado, provocado, agraviado,
e incluso, aunque interpreten de la peor manera posible su amor y sus buenas obras.
Si otro tiene fuego,
el amor tiene suficiente agua en su fuente de mansedumbre para apagarlo,
mediante un comportamiento humilde y amigable, en silencio y haciendo el bien.
No se enciende en enojo por el mal que ve en otros; sino que se compadece.

"`_El amor no piensa mal._`"
No sospecha, no saca conclusiones malignas ni maliciosas,
ni malinterpreta la conducta de otro,
sino que la excusa y la interpreta de la mejor manera posible, en sencillez de corazón,
hasta donde es capaz.
Tiene en cuenta el mal que hace a otros, y el bien que recibe de otros;
pero no considera el bien que hace a otros, ni el mal que recibe de otros;
todo eso es como nada para él, como un cero.
Ha perdonado y olvidado, sin que se le haya pedido.

"`_El amor no se goza de la injusticia,_`" ni cuando otros tropiezan,
para así parecer el más piadoso.
No ve con gusto, sino con tristeza, cuando se comete una injusticia o se hace daño a otro.
Y si alguien que le es adverso, o que previamente lo había criticado,
tropieza y se deshonra a sí mismo, no se goza en secreta venganza,
sino que se aflige profundamente.

"`_El amor se goza de la verdad_`" siempre que prospera,
ya sea en lo que respecta a sí mismo o a otros.
Cuando ve a muchos hijos caminando en la verdad, cuando la virtud,
la piedad y la rectitud de otros son reconocidas y elogiadas,
se alegra por ello junto con los demás,
aunque él mismo sea olvidado y menos estimado por causa de ello.
Ama la verdad cuando la encuentra, incluso si está en sus adversarios.

"`_El amor todo lo sufre._`"
La naturaleza esconde toda su maldad y es dada a hablar de las faltas de su prójimo,
pero el amor divino sólo ve lo que es bueno en otros, y cubre sus miserias y debilidades.
Excusa a esas personas tanto como es posible, ante sí mismo como ante los demás,
en total sencillez.
Después, habla de los fallos de ellos con reticencia,
excepto cuando es necesario hacerlo para el beneficio de otros.
Lo bueno es su verdadero objetivo; de ahí que se dice:

"`_El amor todo lo cree;_`" porque es bueno, fiel y sincero,
y cree con gusto lo mejor de los demás. Si escucha buenas noticias de su prójimo,
no busca dudas ni escrúpulos, como hace la razón corrupta.
No cree con facilidad lo malo de los demás; en tales casos, demanda completa certeza.
Pero como él ama, y desea lo que es bueno y lo que puede glorificar a Dios,
también lo cree de buena gana.

"`_El amor todo lo espera,_`" y no abandona fácilmente
la esperanza de la enmienda de los demás;
en esta esperanza ora y trabaja, tanto como le es posible.
Aunque vea el mal delante de sí, aun así espera y piensa que la persona ya lo lamenta,
que tal vez ya se ha arrepentido o que aún lo hará. Que Dios puede restaurarlo.
Que todavía puede llegar a ser mejor, etc.
El amor espera, incluso cuando no hay motivo aparente para esperar.

"`_El amor todo lo soporta,_`" aunque sea ridiculizado y oprimido por soportarlo todo,
creerlo todo, esperarlo todo y amar siempre; aun así todo lo soporta.
Cualquiera que sea la prueba o sufrimiento que se imponga sobre él en su obra de amor,
incluso por parte de aquellos a quienes ama, no se cansa en su fidelidad y paciencia,
aunque la prueba sea prolongada.
Soporta hasta el fin.
Sí, es invencible en el sufrimiento y finalmente es victorioso sobre todo; porque,

"`_El amor nunca deja de ser,_`" ni cae, por qué,
¿dónde caería dado que ya está en el más profundo abismo de la humildad,
por debajo de todo?
Un hombre puede tener mucho de lo que es bueno, pero si no tiene amor, de nada le sirve;
vuelve a caer.
Antes bien, mucho de lo que es bueno debe caer del justo, para que lo mejor, es decir,
el amor puro, ocupe su lugar.
Este amor no se marchita, permanece para siempre; es oro puro,
es la vida de Dios en el alma, derramada en el corazón por el Espíritu Santo.
Ahora, aquel que permanece en el amor permanece en Dios y Dios en él, por lo tanto,
jamás caerá. Amén.
