[#chap14, short="El Amor de Cristo que nos Constriñe"]
== Un Sermón sobre El Amor de Cristo que nos Constriñe.

[.chapter-subtitle--blurb]
Predicado en Mülheim, Junto al Rhur, 14 de octubre de 1751

[.blurb]
=== "`El amor de Cristo nos constriñe`". --2 Corintios 5:14

[.salutation]
Mis queridos oyentes,

Si deseamos ver una verdadera representación de nosotros mismos,
tanto de lo que somos por naturaleza, como de lo que debemos ser por gracia;
así como también de la apariencia que hemos presentado,
y seguimos presentando mientras continuamos muertos en pecado;
y qué clase de personas debemos llegar a ser mediante
la impartición de esa vida que viene de Dios;
debemos volvernos al capítulo treinta y siete de la profecía de Ezequiel,
donde el Señor le mostró a ese hombre de Dios "`un valle que estaba lleno de huesos,
y por cierto secos en gran manera`".

De hecho, si al Señor le placiera abrir los ojos de nuestros espíritus,
como hizo con los del profeta, al amplio valle de este mundo inferior,
(y ojalá no me viera obligado a añadir además,
al valle del llamado mundo religioso) éstos presentarían exactamente la misma apariencia.
Veríamos, ¡lamentablemente!, en cada rincón y lugar, apenas algo más que huesos muertos,
corazones muertos, formalismos muertos, palabras muertas, obras muertas,
un camino muerto y adoración muerta.
Y entre esta multitud de huesos muertos nos encontraríamos a nosotros mismos también,
en tanto continuemos en nuestro estado natural.

Estos huesos no le pudieron parecer a Ezequiel más miserables, secos y desdichados,
que el aspecto que presentan _nuestros_ corazones, mientras nos aferramos a la tierra,
estando vacíos y separados de la vida que viene de Dios,
y desprovistos del poder vivo de la piedad.
¡Quién habría podido pensar, al contemplar esos huesos secos que vio el profeta,
que alguna vez habían constituido la hermosa figura del hombre!
Ha perdido tan completamente su forma original por causa de la caída,
se ha convertido tan completamente en un horrible monstruo,
que ya no es visible ninguna semejanza con él. Nadie diría que ese era el noble Dios-hombre,
que anteriormente había salido de las manos de su Creador,
con una belleza extraordinaria.

Es cierto que el hombre caído todavía posee una especie de vida;
pero es una vida similar a la que se suele hallar en los cadáveres y huesos de los muertos.
En los cuerpos muertos no se presenta una vida natural ante nuestros ojos,
sino una vida antinatural;
viven y se retuercen con la vida de gusanos y alimañas. Una vida
igualmente extraña y antinatural ha penetrado en nuestros corazones,
los cuales están muertos a Dios; es decir,
se retuercen con todo tipo de deseos y afectos mundanos, pecaminosos y desenfrenados,
como una gran cantidad de horribles alimañas, serpientes y escorpiones;
de modo que nos hemos convertido en algo merecidamente repugnante ante los ojos de Dios,
de los ángeles y de los hombres iluminados,
de la misma manera que un cadáver nos resulta repugnante.
Es más, estoy persuadido de que si nos conociéramos bien a nosotros mismos,
en este estado de deformidad antinatural,
nada nos resultaría más abominable que nosotros mismos,
y nos aborreceríamos tanto como aborrecemos una masa de putrefacción.

"`Hijo de hombre`", le dijo el Señor al profeta:
"`¿Crees que estos huesos secos pueden vivir de nuevo?`"
Y él le respondió: "`¡Oh, Señor Dios, tú lo sabes!`"
Esto es como si hubiera dicho: "`Es imposible para mí como hijo de hombre, saberlo;
por lo tanto, debo dejarlo a Tu sabiduría y omnipotencia`". "`Profetiza`", dijo el Señor,
"`sobre estos huesos secos y diles: Huesos muertos,
oíd palabra de Jehová. Así ha dicho Jehová el Señor a estos huesos: He aquí,
yo hago entrar espíritu en vosotros, y viviréis. Y pondré tendones sobre vosotros,
y haré subir sobre vosotros carne, y os cubriré de piel, y pondré en vosotros espíritu,
y viviréis; y sabréis que yo soy Jehová`". Con lo cual, el profeta profetizó, y he aquí,
se produjo un ruido y un temblor, y los huesos se juntaron,
y los tendones y la carne subieron sobre ellos;
pero aún no había espíritu o alma en ellos.
Hay tan poca posibilidad, o apariencia de posibilidad de renovación en el hombre caído,
como la que presentaban esos huesos secos.

Y en nuestro caso actual--habiendo sentido la influencia de la
gracia divina entre nosotros (algunos de nosotros hace poco tiempo),
mientras todavía estábamos en nuestro estado y conducta corruptos--muchos
de los que nos conocían antes podrían haberse preguntado:
"`¿Creen que esos huesos secos y esos cadáveres repugnantes,
aún pueden convertirse en un hombre vivo?
¿Creen que un pecador tan vano y descuidado,
o que un tizón abominable y rebelde del infierno,
todavía puede convertirse en un hijo favorecido de Dios?`"
¡Dios mío,
qué poca esperanza o expectativa de un cambio así habríamos ofrecido en ese momento!

Sin embargo,
se nos ha profetizado en el nombre del Señor. El Señor envió
Su palabra y la acompañó con el poder de Su Espíritu.
Un ruido, un rumor y un temblor han sido despertados entre nosotros en este lugar.
El mundo ha oído hablar de ello y se pregunta qué resultará de esos huesos secos.
El príncipe de las tinieblas se ha sorprendido ante ello y teme
que un gran número de sus súbditos escapen de las regiones de muerte.
Los huesos secos se han juntado, hueso con hueso; y así es como estamos aquí hoy.
Ahora el mundo nos considera personas vivas; tenemos la apariencia de hombres, es decir,
de Cristianos; al menos se ha producido una forma, un cuerpo.
Pero, ¿hay una verdadera alma, hay un aliento, una actividad viva y libre en este cuerpo?
Así como un hombre no consiste sólo en un cuerpo,
un verdadero Cristiano tampoco consiste en la mera forma y apariencia,
en simplemente asociarse con otros, en hablar como hablan ellos,
o en una conducta controlada.

Es cierto, ¡gracias a Dios!, que la vida también ha entrado en nosotros;
pues de otro modo, ¿de dónde viene esa agitación, ese agrupamiento de huesos secos?
Porque por naturaleza,
no hay en nosotros el más mínimo impulso o inclinación hacia lo que es bueno.
Pero, ¿es un sentimiento vivo, completo, libre y sin restricción lo que nos impregna,
o es sólo una especie de existencia a medias, denigrante y miserable?
Tal estado no puede ser ni placentero ni satisfactorio; no debe continuar así en nosotros.

Un cambio, sí, incluso un cambio notable, ha ocurrido en muchos de nosotros.
Pero mis queridos oyentes, ¿acaso no sentimos,
acaso no somos conscientes de que todavía falta algo, y de que todavía falta mucho?
El corazón aún no se mueve ni late correctamente en el cuerpo Cristiano;
todavía somos incapaces de amar, confiar y aferrarnos a Dios correctamente,
y de deleitarnos en Él y en Sus caminos.
Estamos dispuestos, es verdad, pero somos incapaces de realizarlo;
el corazón todavía está reacio, frío y muerto,
se hunde fácilmente impotente en la tierra.
El caso debería ser diferente en nosotros.

¡Cuánto trabajo y esfuerzo se requieren para trasladar un cadáver,
o a un hombre desmayado,
a sólo unos pocos metros del lugar donde cayó! ¡Cuántos
esfuerzos son necesarios para moverlo! ¡Lamentablemente,
mis queridos oyentes!,
¿no hay muchos en el mismo estado con respecto a la obra y carrera de la piedad?
¡Cuánto tiempo y cuán penosamente arrastran el cuerpo de muerte con ellos!
Se abstienen de algunas cosas en particular, pero no totalmente;
se requiere tal esfuerzo que les cuesta mucho.
Se ejercitan en este o aquel deber en particular, que reconocen que es esencial;
¡pero cuánto deben esforzarse y obligarse para lograrlo!
Les gustaría ser firmes, fieles y santos, pero lamentablemente, hacen poco progreso.
Tal es el caso, y no puede ser de otra manera,
en tanto poseamos un cuerpo Cristiano que sólo está medio vivo.

Finalmente, un cadáver puede ser levantado y sostenido, aunque con mucha dificultad;
pero,
¿de qué sirve a menos que la vida y un alma entren
en él? No consideremos como algo insignificante,
que la bondad de Dios nos favorezca con muchos medios de gracia para nuestro despertar,
aliento y refrigerio,
sino reconozcámoslos humildemente como favores y beneficios divinos e inestimables.
Aun así,
si en el uso de todos esos medios no estamos principalmente
preocupados por obtener el espíritu,
fuerza y amor de Cristo, podemos, teniendo los sentidos afectados,
ser levantados como un cadáver de la manera antes mencionada,
pero en poco tiempo la masa insensible volverá a caer postrada sobre el suelo,
con todo su anterior letargo y acostumbrados malos hábitos.

Es totalmente diferente para aquellos que poseen la vida espiritual;
ellos también pueden sentirse desanimados, débiles y perezosos,
y ser otra vez despertados, vivificados y poderosamente asistidos en sus caminos,
al reunirse de esta manera, y por otros medios de gracia.
Pero, ¡mis queridos amigos!, los mejores apoyos no sirven de nada, ni por mucho tiempo,
para aquel que no ha obtenido vida y alma con su correspondiente piedad; es decir,
dichos apoyos pronto pierden su influencia sobre nosotros.
Aquellos que se satisfacen con simplemente asistir y oír,
sin preocuparse por el poder interior de la piedad, no permanecen,
ni pueden permanecer firmes por mucho tiempo.
El cadáver más hermoso pronto se descompondrá, corromperá y producirá gusanos,
a menos que le sea impartida un alma.

En una palabra,
tan necesario como fue que el profeta Ezequiel profetizara
por segunda vez en el nombre del Señor,
y dijera al viento o Espíritu: "`Espíritu,
ven de los cuatro vientos y sopla sobre estos muertos, y vivirán!`",
y entró espíritu en ellos y cobraron vida; así de indispensable es para nosotros,
los que hemos sentido dentro de nosotros los primeros movimientos de la vida espiritual,
que se nos profetice nuevamente en el nombre del Señor,
para que entre en nosotros el verdadero espíritu del Cristianismo,
y seamos vivificados y llenados.
"`¡Ven, Espíritu!`" debe clamar todo corazón, "`¡ven y sopla sobre mí,
que estoy espiritualmente muerto, para que entren en mí, espíritu y vida!`"
Ahora bien, esta alma, esta vida y poder de piedad,
no es más que el amor de Cristo que nos hace Cristianos vivos y activos.
¡Oh, es por la posesión de este amor que debemos ser solícitos!

No sólo los apóstoles fueron Cristianos vivos, activos y santos;
los creyentes en general también lo fueron en los tiempos de los apóstoles.
Si volvemos nuestra atención a los primeros y fervientes Cristianos,
y nos preguntamos cómo fueron capaces de hacer cosas tan grandes,
sufrir tanto y vivir de la manera que vivieron,
el santo apóstol Pablo nos responde en el nombre de todos ellos,
con las palabras de nuestro texto:

[.centered]
"`El amor de Cristo nos constriñe`". 2 Corintios 5:14

Conforme a la dirección que se nos da en estas palabras divinamente inspiradas,
consideremos, con la ayuda divina, en esta presente ocasión:

[.numbered-group]
====

[.numbered]
1+++.+++ El amor de Jesucristo, y

[.numbered]
2+++.+++ El divino poder de dicho amor.

====

"`¡Bendito Salvador, mira a tu siervo,
que en este momento se atreverá a testificar de Tu maravilloso amor.
¡Oh, no mires mi indignidad ni mi incapacidad! ¡Acércate a mi corazón y enciéndelo;
toca mis labios incircuncisos con un carbón encendido de Tu altar,
para que no hable de Tu ardiente amor de manera fría o débil!
Amén`".

=== El amor de Jesucristo.

No le ha placido al Espíritu Santo indicar más claramente,
si con las palabras de nuestro texto, "`el amor de Cristo`",
se refiere al amor con el que Cristo nos ama,
o al amor con el que el corazón creyente ama a Cristo; tal vez por esta sencilla razón,
para que lo consideremos como una unidad.
De hecho, ambos están muy estrechamente relacionados entre sí;
uno es producido por el otro, y son originalmente uno.
Porque, ¿cómo podríamos poseer siquiera una chispa del amor de Cristo,
si Él no nos hubiera amado primero?
Y el amor con el que estamos capacitados para amarle, es tanto Su amor,
como el amor con el que Él nos ha amado tanto en el tiempo como en la eternidad.
Cristo es quien inicia amando, por lo tanto, en nuestra presente meditación,
debemos comenzar también considerando Su amor hacia nosotros.

[.offset]
_1+++.+++ Cristo nos ama con un amor que sobrepasa el más fiel y ferviente afecto de un amigo._

La amistad entre los hombres consiste en una inclinación libre e interna de corazón,
por virtud de la cual, el individuo le desea a su amigo la posesión de todo bien,
y gustosamente se lo procura; mientras que, por otro lado,
busca defenderlo de todo daño e infortunio, y ayudarlo y asistirlo en cada necesidad.
Es con tal afecto amistoso,
que Cristo está realmente unido a nosotros en el más alto grado.

Si queremos formarnos una idea de la amistad más fiel,
debe ser una amistad que permanezca firme en la hora de necesidad.
¿Pero dónde encontramos entre los hombres a un amigo en la necesidad?
Y si deseamos describirnos ese afecto del alma, en su más sublime ejercicio,
debemos suponer el caso de un amigo que pone su vida por el otro.
¿Pero dónde se encuentra a un amigo así, o una amistad tal entre los hombres?
En Cristo, realmente tenemos tal amigo, y en Su corazón, tal amistad para con nosotros.
Él dice: "`Nadie tiene mayor amor que este,
que uno ponga su vida por sus amigos`". (Juan 15:13) ¡Ah, amadísimo Salvador!,
¿por qué hablas de amigos?
¡Nosotros éramos enemigos y rebeldes, y sin embargo,
entregaste Tu vida por nosotros! "`Cristo`", según la expresión de Pablo,
"`murió por los impíos`" (Romanos 5:6). "`Dios muestra su amor para con nosotros,
en que siendo aún pecadores, Cristo murió por nosotros`" (Romanos 5:8). Por tanto,
con la debida reflexión, he denominado el amor de Cristo,
como un amor que sobrepasa el más fiel y ferviente amor de un amigo.

¡Oh, la asombrosa intensidad del amor de Cristo!
Ustedes y yo, mis queridos amigos, habíamos caído de la amistad, luz,
amor y comunión con Dios, a las profundidades de la miseria, desdicha e infierno.
Ya no éramos amigos, sino enemigos; ya no éramos dignos de ser amados,
sino de ser odiados y merecedores de ira.
Sin embargo, Dios, en Su eternidad, tuvo compasión de nuestra gran e ilimitada miseria.
Dejó que le costara lo que Él consideraba lo más querido.
Por nuestra salvación entregó a Su unigénito Hijo, al Hijo de Su corazón, y en Su Hijo,
el corazón de Su amor.
Ningún hombre, ningún ángel puede comprender o desentrañar esto.
Debemos creerlo, debemos adorarlo, y con el propio Cristo exclamar asombrados:
"`¡Dios amó al mundo de tal manera`"; a este miserable mundo! (Juan 3:16)

La insuperable amistad de Cristo por nosotros, lo constriñó a dejar el cielo por nosotros.
¡Escuchen el gozoso y maravilloso relato; no es una fábula,
sino un hecho cierto! ¡Escuchen este glorioso evangelio del Dios siempre bendito;
no como algo con lo que ya están familiarizados y han aprendido desde su juventud,
de sus Biblias o del catecismo; sino escúchenlo como noticias importantes;
escúchenlo hoy, por una vez, como si nunca antes lo hubieran escuchado en sus vidas!
La insuperable amistad de Cristo lo constriñó a dejar el cielo para salvarnos y liberarnos;
y para hacerlo, y para que no temiéramos Su aparición,
se revistió de nuestra miserable humanidad y forma pecaminosa.
Como nuestro Redentor y pariente cercano,
realmente tomó sobre Sí la carga de nuestros pecados y transgresiones,
como si hubieran sido propios.
Durante casi treinta y cuatro años trabajó, oró y luchó por ustedes, mis amigos,
y por mí. Bajo la más terrible conciencia y agonizante sentimiento de esa ira divina,
que el pecado había provocado, se angustió terriblemente, sudó grandes gotas de sangre,
experimentó los tormentos del infierno y el ocultamiento del rostro de Dios;
en una palabra, sufrió y soportó todo eso, lo que ustedes y yo, mis amigos,
hubiéramos tenido que sufrir eternamente; sí, sufrir eternamente por nuestros pecados.
E hizo todo esto a partir del voluntario afecto de un amigo, y para poder,
por medio del inestimable valor de Su sangre, reconciliarnos de nuevo y comprarnos,
para que llegáramos a ser Sus amigos.

¿Podemos imaginar un amor más grande?
¿No es Cristo un verdadero amigo en la necesidad, un amigo real, incluso hasta la muerte?
Él sufrió todo esto, no por nosotros en general,
sino por cada uno de nosotros en particular.
Pablo lo consideró desde este punto de vista: "`Cristo me amó`", dice él,
"`y se entregó a Sí mismo por mí`". ¡Ah, Pablo!, ¿qué estás diciendo?
¿Murió Cristo entonces sólo por ti?
"`¡Oh, sí, sólo por mí, y sólo por ti!`"
Así debemos ver el tema, para poder contemplarlo de la manera más ventajosa;
y así es como Cristo ama a cada uno con un afecto particular.

[.offset]
_2+++.+++ Cristo nos ama, y nos ama voluntariamente, con el más compasivo,
atento e incansable amor maternal._

Cuando un bebé está enfermo, o se cae y se lastima,
y yace delante de los ojos de la madre llorando y con dolor--en
lugar de odiarlo por causa de su lastimoso estado,
ella mira al pobre bebé con sincera compasión,
y busca aliviarlo y consolarlo de todas las formas posibles.
Cristo se reviste de similares entrañas de amor maternal hacia nosotros,
hijos caídos y pecadores,
especialmente cuando sentimos y lamentamos penitentemente nuestros pecados.
Entonces nos mira con sentimientos de la más tierna compasión. ¡Pobre alma penitente!;
es probable que no creas que Cristo te ama así, y que te mira de esa manera;
crees que eres completamente abominable,
y que habiéndote sumergido voluntariamente en toda esta miseria,
Él ya no te presta más atención. ¡Escuchen, por lo tanto,
lo que Él dice sobre este tema en Ezequiel 16:6: "`Yo te vi sucia en tus sangres`";
y tan ciertamente como te ve, así también te dirá cuando llegue Su hora: "`¡Vive!
Sí, te dije: ¡Vive!`"
Sólo mirémoslo por fe, como los niños enfermos suelen mirar con ojos llorosos a su madre.

Una persona penitente y angustiada,
a menudo encuentra imposible de creer que su llanto
y sus lamentos son escuchados y respondidos.
Tengan seguridad, mis amigos, de que el Señor oye cuando Efraín se queja, y dice:
"`¿No es Efraín hijo precioso para mí? ¿no es niño en quien me deleito?`"
(Jeremías 31:20) Si esta no es una expresión del afecto maternal más compasivo,
no conozco ninguna.
No nos atreveríamos a atribuirle a Dios tan tiernos sentimientos de afecto maternal,
si el Señor mismo no lo hubiera hecho.
¡Ah, ustedes almas penitentes!, si pudiéramos creerlo, si pudiéramos verlo,
nuestros corazones también se derretirían con sentimientos de afecto filial recíproco.

Cristo nos ama, y nos ama voluntariamente, con el más persistente y maternal amor.
El niño obtiene su vida natural de su madre,
y por medio de ella es traído a este miserable mundo;
Cristo nos regenera para un mundo de luz y gozo eterno,
y nos imparte una vida que es incorruptible.
Una madre alimenta a su hijo con sus propios pechos; pero Cristo se da a Sí mismo,
Su carne y sangre, para ser la comida de sus hijos regenerados.
Esto no lo hace ningún padre humano.

Una madre baña a su hijo, lo cuida, lo lleva con ella, lo cría hasta que crece;
ella está constantemente haciendo algo por su hijo,
y su amor maternal hace que nunca se canse de atenderlo.
¡Quién puede reflexionar sin vergüenza y asombro,
cómo el siempre amoroso Dios está obligado a tener paciencia con Sus obstinados hijos,
hablando en términos humanos! ¡Cómo lo cansamos con nuestras transgresiones!
De hecho, es imposible decir cuánto tiene que hacer para criar una sola alma.
El Señor mismo expresa este amor activo, ayudador y maternal en Isaías 46:3-4 donde dice:
"`Oídme, oh casa de Jacob, los que sois traídos por mí desde el vientre,
los que sois llevados desde la matriz...hasta las canas os soportaré yo, etc.`"

La madre de un niño trata de protegerlo de todo accidente,
y busca su bienestar en la medida de sus posibilidades.
Cristo, nuestro siempre amoroso padre vigila y protege a Sus descendientes,
con incomparable mayor atención, para que el Maligno no los toque.
Es más, ni siquiera un cabello de sus cabezas caerá sin Su voluntad.
Todo lo que les sucede a estos lactantes de Su gracia, ya sea pequeño o grande,
interna o externamente, está tan guiado y gobernado por el amor paterno de Cristo,
que todas las cosas deben ayudar para bien de ellos.

Así como un niño nacido de padres humanos,
se preocupa poco de cómo puede llegar a ser grande, de la misma manera,
un hijo de la gracia debe preocuparse poco de cómo
puede crecer y llegar a ser fuerte y santo.
El amor paternal de Cristo provee para todo esto;
sólo es necesario que el niño permanezca en el regazo de la madre,
y que mediante la oración, la fe y el amor, busque de los pechos de la gracia divina,
alimento y fuerza para su vida y crecimiento.
Y mientras esté en el regazo de amor,
el bebé más débil y necesitado no tendrá que temer ningún peligro.

No obstante,
este amor destina a los hijos de la gracia a experimentar una variedad de pruebas,
tentaciones y sufrimientos, para el bien de ellos;
y son a menudo dejados en tal estado de esterilidad y tinieblas,
que los hace exclamar con Sion: "`Me dejó Jehová,
y el Señor se olvidó de mí`". ¡Pero cuán ampliamente se desvía
el alma de la verdad con tal suposición! El Señor mismo pregunta:
"`¿Se olvidará la mujer de lo que dio a luz,
para dejar de compadecerse del hijo de su vientre?
Aunque olvide ella, yo nunca me olvidaré de ti.
He aquí que en las palmas de las manos te tengo esculpida`". ¡Oh, mis queridos oyentes,
esto hace referencia tanto a ustedes como a mí! ¿No deberíamos, por tanto,
encomendarnos en cuerpo y alma al amor y cuidado maternal de Cristo,
tanto en el tiempo como en la eternidad?

[.offset]
_3+++.+++ Cristo nos ama, y nos ama voluntariamente, con el más tierno,
ardiente y feliz amor de un esposo._

¡Oh, sí;
el amor de Cristo realmente suplica por los corazones de los pobres y perdidos pecadores;
y cuánto tiempo nos tiene que cortejar frecuentemente,
antes de recibir de nosotros el consentimiento deseado! ¡Cuán a menudo, ustedes y yo,
hemos vergonzosamente despreciado y rechazado Su bondad y amor ofrecidos; y sin embargo,
Él no se ha cansado de buscarnos! ¡Cuán tiernamente ama,
incluso antes de ser amado! ¡Más aún, cuán infinitamente más tierno es Él,
cuando ha alcanzado Su objetivo y puede desposarse para siempre con el alma,
como Su esposa, y prometerse a ella en justicia!
Esto con frecuencia es seguido por muchas preciosas e incluso
palpables comunicaciones de Su amor al alma.
Cristo le presenta muchas joyas invaluables y bendiciones celestiales,
y la hace experimentar, según la medida de ella, "`justicia,
paz y gozo en el Espíritu Santo`".

Y dado que Cristo encuentra a Su esposa tan completamente desamparada y vestida de harapos,
mediante Su amor y santificada aflicción,
Él la despoja de sus vestidos inmundos y harapientos, la viste con Su justicia, derrama,
junto con Su amor, toda Su mente, imagen y semejanza más y más en ella,
de modo que es revestida de Su humildad, mansedumbre, pureza,
sencillez y toda virtud divina.
Y después de haberla embellecido con Él mismo,
entonces se regocija por ella "`como el gozo del esposo
con la esposa`" (Isaías 62:5). "`He aquí que tú eres hermosa,
amada mía`", dice Cristo, el esposo celestial.
(Cantar de los Cantares 1:15-16) "`No`", replica la esposa, "`sólo Tú eres hermoso,
porque incluso la belleza que ves en mí,
es Tuya`". Estas no son palabras vacías o vanas imaginaciones,
sino poderosas maravillas del amor de Cristo.
¡Quiera Dios que podamos leerlas, no sólo en Cantar de los Cantares,
sino también en nuestros corazones por medio de una feliz experiencia!

Es imposible, mis queridos oyentes, expresar el profundo y ardiente afecto,
y el intenso deseo que hay en Cristo de recuperar la posesión de nuestros corazones,
para tenernos nuevamente cerca de Él, y atarnos y unirnos eternamente a Él,
y Él a nosotros.
Ni los ángeles ni los hombres pueden comprenderlo,
pero adorarán este misterio con la más profunda admiración por toda la eternidad.
El Espíritu de Cristo que mora en los creyentes nos desea, incluso hasta los celos.
Él no puede soportar que un corazón que le ha costado tan caro;
que un corazón que ama a tal grado,
aún se aferre a otros objetos y no permanezca completa
y únicamente dedicado a Él. Él ama el alma,
como si no amara nada más; y ella debe amarlo a Él de la misma manera en respuesta;
porque el amor de Cristo--el profundo y ardiente afecto de Cristo por el alma--suscita
en ella un afecto igualmente ardiente por Él. El amor de Cristo toca el alma,
y la atrae a sí,
y ella sigue esta atracción. "`Atráenos y correremos
tras de Ti`". El corazón de ella y todo su ser,
al apartarse de todo otro objeto,
anhela y se inclina hacia una unión más cercana con su Amado.
Los tiernos encuentros, caricias, abrazos, conversaciones y uniones que ocurren luego,
bien pueden ser experimentados por corazones puros y absortos,
pero no pueden ser expresados;
porque estos son temas que pertenecen más a la eternidad que al tiempo.
En resumen,
el amor de Cristo es un gran misterio de piedad y
una fuente inagotable de felicidad pura.

Así pues, ustedes, queridos inmortales, todos los cuales, al igual que yo,
hemos sido creados, redimidos y llamados con el propósito de amar, y de amar a Dios.
¡Contemplemos--oh,
ojalá que nuestros ojos estén realmente abiertos
para verlo--contemplemos cómo nos ama Dios en Cristo,
y cuán tiernamente nos ama Él! ¡Cuán avergonzados deberían estar todos
aquellos que tratan de presentar a Dios como un tirano y un desalmado!
No hay ira en Dios, excepto contra lo que es malo.
Dios no nos ha creado para odiarnos, o para ser odiado por nosotros;
sino con el único propósito de amarnos, y ser eternamente amado por nosotros.
Pero, ¡ay, ay!, ¿dónde están los corazones que aman a Dios?
¡Qué triste que haya un Dios así, un Cristo así,
un Cristo que tenga tal amor por los hombres, y que haya un amor de Cristo así,
y sin embargo, que sea tan poco conocido, experimentado y disfrutado, y además,
por tan pocos!

=== El divino poder de dicho amor.

Cuán frecuentemente repiten los hombres las palabras:
"`¡Querido Señor! ¡Querido Salvador!`";
pero... ¿cómo se inclinan sus corazones hacia Él? ¿Qué han experimentado
nuestros corazones del poder de este amor de Cristo?
Porque no debemos imaginarnos el amor de Cristo, como una especie de amor caprichoso,
inoperante e injurioso para Su carácter, como si Él pudiera amarnos, o debiera hacerlo,
mientras permanezcamos en nuestras prácticas viciosas,
tal como lo hacen muchos padres que tienen un afecto tan insensato por sus hijos,
que ceden ante toda la perversidad de sus voluntades,
y les permiten sumirse en la perdición. La mente rastrera y pervertida del hombre,
desearía un amor así por parte de Cristo,
y una misericordia divina así también. Desearía que en los días de salud,
Cristo le permitiera disfrutar las vanidades y placeres del mundo según toda su voluntad,
y que después, al acercarse a la muerte y decirle unas cuantas palabras buenas a Dios,
Él fuera tan misericordioso, y Cristo lo amara tanto,
que lo llevara directamente al cielo.
¡No, hombre insensato!
Tal amor de Cristo y tal cielo no son más que el resultado de tu propia imaginación;
no hay nada de eso en Dios.
Cristo te ama, incluso en contra de tu voluntad, mucho más de lo que te amas a ti mismo.
Él preferirá causarte dolor y salvarte, que adularte y dejarte perecer.

El amor de Cristo no es, pues, una vana imaginación, sino el poder vivo,
activo y poderoso de Dios,
que realmente nos levanta y restaura de nuestros errores y corrupciones,
del pecado y de la muerte; nos imparte una vida nueva y real; nos dispone,
alerta y capacita para la realización de todo lo que es bueno;
y nos hace verdaderamente felices.
El amor de Cristo es el comienzo, el fundamento y el alma del Cristianismo,
y de toda religión real.
El que no tiene el amor de Cristo, o no tiene piedad o devoción del todo,
o sólo tiene una devoción hipócrita y muerta.
Cristo, para poder salvarnos, no puede permanecer lejos de nosotros;
debemos experimentar el poder de Su amor en nuestros corazones y darle cabida;
de lo contrario, a pesar de lo que hablemos y oigamos del amor de Cristo,
continuaremos en un estado de tinieblas y miseria espirituales.

Es indudable que Cristo lo inicia todo al amarnos primero.
Cuando, por ejemplo, _el amor de Cristo persuade al hombre al arrepentimiento;_
entonces el Espíritu de amor lo reprende por su injusticia,
lo convence de la necesidad de arrepentimiento y conversión,
lo alarma por motivo de sus pecados y por el peligroso estado de su alma.
Hay algo que parece perseguir al hombre y presiona sobre él,
constriñéndolo a arrepentirse, a entregarse a Dios y a convertirse en otro hombre.
Es cierto que el mortal ciego, en su ignorancia,
lo considera una tentación del diablo a la que debe resistir, o bien,
lo mira como algo que procede de sus propios pensamientos inquietos y casuales,
y como algo de naturaleza maligna o melancólica.
Sin embargo, aunque él a menudo desea ser libre de ello,
eso sigue regresando para demostrar que no procede del hombre mismo.
Por desgracia, muchos dejan que pasen días y años así,
y no se dan cuenta de que es el amor salvador de Cristo lo que los constriñe.

Tengan seguridad de que es el compasivo y siempre amoroso Jesús,
el que está llamando a la puerta de sus corazones.
Él suplica y ruega por sus corazones, como si realmente los necesitara, diciendo:
"`¡Dame, hijo mío, dame tu corazón! ¡Reconcíliate con Dios!`"
Así es como el amor de Cristo nos constriñe. ¡Cuántas veces y por cuánto
tiempo ha tratado así con nosotros! ¡Cuántas veces nos habría juntado,
como la gallina junta sus polluelos debajo de sus alas;
pero al no llegar en un momento que nos pareciera conveniente, no quisimos!
En nuestro estado natural, estamos corriendo directo a la perdición; ¿no es amor,
por tanto, cuando el Salvador se interpone en nuestro camino?
Caminamos, por decirlo así, al borde del infierno; ¿acaso no es amor,
cuando nos agarra y nos hace retroceder,
incluso mediante los dolores que nos hace sentir?
¡Ah! ¿Qué beneficio obtiene el Dios todo suficiente por seguirnos así a ti y a mí? ¿Somos
nosotros de algún beneficio para Él? ¿Tiene Él alguna necesidad de nosotros?
¡Oh, amada alma!
Si conocieras el Don de Dios,
y Quién es ese que con tales influencias apremiantes te habla, diciendo: "`¡Ríndete a Mí,
no te demores más!`"; ciertamente no te resistirías más, ni buscarías escapar de Él,
sino que caerías a Sus pies en ese mismo momento,
y te arrojarías a los brazos de Su amor.

Ahora, si el alma tuviera la fortuna de quedarse quieta,
de prestarle oído y darle entrada a este atrayente y restaurador amor,
y por ello el corazón fuera abatido,
inclinado y quebrantado por el verdadero arrepentimiento,
y tuviera que buscar refugio en la misericordia de Dios; este sería nuevamente,
el amor de Cristo,
mediante el cual el alma es constreñida a experimentar tales sentimientos dolorosos.
En realidad, su naturaleza carnal expulsaría gustosamente de su mente el tema,
y viviría el día como antes, libre, jovial y alegre,
pero ha caído sobre su corazón tal carga, que no puede librarse de ella;
siente sus pecados, sus necesidades, su peligro, y los siente todo el tiempo.
Es el amor de Cristo lo que la constriñe a sentirse así,
aunque el alma aún no sepa nada de este amor,
sino que sólo sea consciente de la ira y de la condenación. Ha oído y reconoce,
que es ella, quien por sus pecados, ha crucificado a su amoroso Salvador.
Esto la traspasa hasta el corazón y le causa dolor.
Es necesario que lo sienta un poco aquí, para que no lo sienta muy severamente después;
¿no es esto amor?

El amor de Cristo impresiona al alma con un sentimiento de su estado perdido.
Esto, con el fin de que esta pérdida y su consiguiente miseria,
la humille y constriña a buscar el amor de Cristo,
y en dicho amor encuentre alivio y una cura.
Porque esta es la única intención de Dios al llevarnos a este estado de angustia;
no para alejarnos de él y sumirnos en la perdición y desesperación,
sino para impulsarnos a buscar Su amoroso corazón. Para
que mediante un penitente anhelo tras el amor de Cristo,
escapemos de toda nuestra pecaminosidad y su consecuente miseria,
y nos lancemos a la sangre expiatoria, preciosos méritos y eterna gracia de Cristo;
no por medio de una apropiación ineficaz hecha por nosotros mismos,
sino por un anhelo humilde y aspiración de corazón,
en pos de las influencias de la gracia y del amor de Cristo,
de la manera en que éstas pueden ser realmente experimentadas
para tranquilizar al corazón y a la consciencia angustiados.
En tal situación, todo lo que tiene que hacer el alma es humillarse profundamente,
confesar su culpa, echar fuera cualquier otra confianza,
y no desear conocer cosa alguna sino el amor de Cristo y Su misericordia eterna.
Y cuando el pecado y la culpa del pecado,
y la ira y la condenación presionan con todo su peso sobre la mente,
la persona no debe hacer otra cosa sino sumergirse aún más profundamente,
en este abismo abierto de eterna misericordia y amor de Cristo.
Así es como debemos dejar que el amor de Cristo nos constriña al arrepentimiento;
y a través del arrepentimiento, al amor.
Después, de seguro y eventualmente sucederá,
que el amor de Cristo cubrirá multitud de pecados, de modo que después,
la persona _se avergüenza_--como lo expresa el profeta
(Ezequiel 16:63)--con humilde agradecimiento y confusión,
cuando el Señor le perdona todos sus pecados y le paga, por decirlo así,
sólo con Su amor; y también sucede, que aquellos a quienes se les ha perdonado más,
aman más que otros.

_El amor de Cristo también constriñe al alma convertida, a apartarse del pecado,
del mundo y de todas sus vanidades._
El hombre ya no puede correr con la multitud como antes, sin sentirse restringido.
¿Cuál es la razón? ¿Quizás porque teme ser castigado por sus padres, amos o magistrados?
¡No!
El caso es que el individuo se vuelve más consciente de sus pecados,
de los que ningún hombre sabe o puede saber algo; incluso,
se vuelve consciente de las cosas más pequeñas,
las cuales no caen bajo la jurisdicción de la magistratura o del hombre.
¿Pero, por qué es esto?

Consideremos además,
¿es probable que una persona sea despreciada y ridiculizada cuando
vive una vida de vanidad y no está bajo la influencia de la piedad?
¡De ninguna manera!
Muy por el contrario,
el mundo ridiculiza y calumnia a la persona que ya no corre "`en
el mismo desenfreno de disolución`". (1 Pedro 4:4) Ellos preguntarán:
"`¿Por qué no actúa como los hombres del mundo, y por qué vive tan retirada?`"
Si una persona convertida respondiera a esto y expresara la verdadera razón,
se vería obligada a decir: "`El amor de Cristo me constriñe a abandonar estas cosas;
no me atrevo, ni quiero seguir más a mi depravada naturaleza.
El tiempo pasado de mi vida es suficiente para haber hecho la voluntad de los gentiles.
He crucificado por mucho tiempo a mi amado Salvador con mis pecados--a ese Salvador,
a ese Cristo que me amó tanto, que no sólo dejó el mundo,
sino que incluso abandonó el cielo por mí. ¿No debo, pues, por causa de Él,
negarme un odioso pecado, una lujuria mundanamente vana y transitoria?`"

Sí, el amor de Cristo no sólo nos constriñe a negar los vicios más evidentes del mundo,
y las obras muertas del pecado,
sino que también nos exhorta a renunciar verdaderamente
al amor al mundo y al apego a las cosas creadas,
que aún permanezcan en el corazón. Nos exhorta a abandonar
la falsa y profundamente arraigada vida del yo;
a hacer morir las pasiones lujuriosas e iracundas;
al sacrificio de nuestra propia voluntad, nuestro propio yo y autocomplacencia,
tanto en las cosas pequeñas como en las grandes,
y en las cosas naturales como en las espirituales.

¡Cuán sombrías y aterradoras ideas nos formamos a menudo de la negación al yo! ¡Cuántas
débiles e inexpertas almas son frecuentemente disuadidas de ello sin causa!
Se dicen a sí mismas: "`¡Ay, qué vida más triste,
cuando ya no podamos disfrutar de una simple hora más de felicidad en el mundo!
Es imposible para nosotras vivir así;
nunca podremos separarnos de este o aquel objeto en particular, etc.`"
¡Ah, mis queridos amigos, cuán erróneas ideas se están formando continuamente de su Dios!

Él no necesita nuestra negación al yo--en lo que
se refiere a Sí mismo--pero nosotros sí la necesitamos.
Él no es un hombre severo,
que hace que nuestra vida y el camino al cielo sean dolorosos y trabajosos para nosotros,
ni nos impide tener algún disfrute en el mundo.
Sin embargo, nosotros necesitamos la negación al yo, porque somos niños tan tontos,
ciegos y degenerados que desconocemos nuestra verdadera felicidad y salvación,
y llamamos gozo y placer a lo que en realidad es nuestra destrucción,
tormento e infierno.
Somos como un niño que juega con un cuchillo, y que en su ignorancia,
llora y se resiste cuando el amor cuidadoso de la madre le ordena dejar el cuchillo.

No debemos considerar el impulso interno a negar al yo como algo de naturaleza legalista,
sino como la influencia del amor de Cristo que nos
constriñe. Él busca persuadirnos amigablemente,
como niños sencillos, a soltar el peligroso instrumento de nuestras manos;
y si Su amistosa persuasión no funciona, a veces deja que nos hiramos a nosotros mismos,
para que dejemos a un lado el peligroso cuchillo.
¡Esto es amor puro!
Cristo desea tener la totalidad de nuestros corazones,
y por medio de Sus persuasiones internas,
quitar del camino todos los obstáculos y hacernos partícipes de Su gozo,
amor y deleite reales, perfectos y eternos.
Sí, cuanto más guía el Señor a un alma a negarse a sí misma,
y cuanto menos le permite tener, más especial es Su amor hacia ella.

Entonces, así como no debemos atribuirle la negación al yo al legalismo,
sino al amor de Cristo,
tampoco debemos actuar de manera legalista en el ejercicio de dicha negación,
sino dejar que el amor de Cristo nos constriña a ella.
Cuando la constante exclamación del alma es:
"`¡Debo hacer esto o pereceré eternamente!`";
y luego se entrega así a la negación al yo sin Cristo, en su propia fuerza, ¡ah, sí,
esa vida es ciertamente cansada!; pero esto también debe ser entendido por experiencia.
Es cierto, _debemos hacerlo,_ o de lo contrario estaremos perdidos; pero,
¿no es ya parte de la condenación actuar siempre por obligación,
y nunca a partir de un corazón dispuesto?
¿Estar siempre forzados y no poder realizarlo nunca?
Debemos, entonces, anhelar el amor de Cristo;
buscar la voluntad y el poder para negarnos a nosotros mismos en el amor de Cristo;
y buscarlo hasta que lo encontremos;
hasta que el amor de Cristo nos constriña a renunciar voluntariamente
a nosotros mismos y a todas las cosas creadas;
hasta que nos estimemos felices al negarnos a nosotros mismos,
al arriesgarnos a la perdida de algo por amor a Aquel que es nuestro amigo,
nuestro padre y nuestro esposo; y a vivir de manera que podamos complacerlo mejor a Él.

Si me dirigiera específicamente a aquellos que están en estado de gracia,
a aquellos que gustosamente se negarían a sí mismos, pero encuentran, a su pesar,
que en todas partes quedan cortos, les diría: "`No piensen tanto en negarse a sí mismos,
en ser fieles, o en vivir de manera santa y estricta; sino busquen amar, anhelar el amor,
y ejercitarse a sí mismos en amor.
El amor siempre ejercita la negación al yo,
sin gustar su amargura y casi sin pensar en ella.
Sólo piensen en cómo pueden amar a Cristo,
cómo pueden amarlo más cariñosamente que nunca,
y hagan todo para agradar y satisfacer Su amor`".

_El amor de Cristo constriñe al creyente al sufrimiento y a través del sufrimiento._
Esto suena extraño, y sin embargo es verdad.
El individuo es con frecuencia colocado tan maravillosa
e inesperadamente en alguna situación dolorosa,
que no sabe cómo sucedió; es, por decirlo así, presionado hacia ella.
Algunas personas en particular sólo nos hablan o actúan hacia nosotros de cierta manera;
alguna expresión o circunstancia es tomada bajo una luz equivocada;
las cosas suceden y se siguen una tras otra de manera tal,
que experimentamos una pequeña prueba, cruz o sufrimiento.
No es necesario que esas cosas siempre sean grandes o importantes;
el amor de Cristo a menudo utiliza una nimiedad,
y sabe cómo tocarnos con ella en la parte más sensible.
Así sucede con respecto al cuerpo y a las cosas externas,
y así también ocurre con respecto a las cosas espirituales,
de innumerable maneras diferentes; y es el amor de Cristo el que lo hace,
aunque estamos listos a adjudicarlo a algunas otras causas.

Las almas débiles y tímidas a menudo se angustian a sí mismas mucho,
por una incrédula anticipación de sufrimientos y tentaciones futuros,
externos o internos, y no sé qué clase de pruebas más,
que quizá nunca les lleguen a suceder.
Su lenguaje es: "`Si alguna vez tengo que sufrir lo que tal persona tiene que soportar;
o si yo tuviera que caminar por este o aquel camino difícil,
sé que para mí sería imposible aguantarlo`". ¡Ah, mis amigos!
No se atormenten a sí mismos con preocupaciones y tristezas inútiles.
Confíen en el amor que los impulsará a la cruz y a través de la cruz; quiero decir,
no se preocupen por el futuro.
El amor distribuye sabiamente las aflicciones; las entiende mejor que nosotros.
En tanto permanezcamos como niños pequeños y débiles,
no impondrá sobre nosotros ninguna carga pesada.

Pero sea lo que sea que tengamos que sufrir en el presente,
debemos recibirlo como si viniera directamente de la mano del amor de Cristo,
y no como si viniera de alguna persona en particular.
Cuando Cristo sufría, no consideraba que Sus sufrimientos vinieran de los judíos,
de los fariseos, o de Pilato; sino que venían directamente de la mano de Su Padre,
diciendo: "`La copa que el Padre me ha dado, ¿no la he de beber?`"
Por lo tanto, no piensen tanto en la aflicción,
como en Aquel que la envía. Si este es el caso, mi amigo; es decir,
si crees que es el propio Cristo quien te envía alguna aflicción en particular,
¡cuán precioso,
cuán estimable y agradable debería ser para ti todo lo que procede de una mano tan querida!
Piensa cuánto ha sufrido Él por ti; ¿no soportarás, pues,
una leve aflicción para complacerlo?

No piensen tanto en la aflicción, como en el amor de Cristo.
Ámenlo y podrán soportar todas las cosas.
¿Qué no puede hacer el amor?
¡Cuánto han soportado y han podido soportar tantos
miles de mártires y tantas otras almas santas,
sólo porque estaban constreñidas a ello por el amor de Cristo!
El amor de Cristo imparte una creciente disposición a sufrir,
y secretamente mantiene al alma como clavada en la cruz; de modo que frecuentemente,
cuando la persona está en una situación dolorosa,
no descendería de la cruz para dejar que la naturaleza carnal respire,
aunque se le diera la libertad de hacerlo.

_El amor de Cristo debe constreñirnos a la santificación._ Cuán repulsiva
e impracticable consideran muchas personas su santificación. Vivir
tan estrictamente como lo indican las Escrituras,
volverse tan mansas, tan devotas, tan humildes, tan puras,
tan irreprensibles y tan santas, lo consideran imposible,
y creen que no pueden soportarlo o alcanzarlo por ningún medio.
Es verdad, mis amigos,
es imposible cuando las severas reprimendas de Moisés
en la conciencia los obligan a ello;
y es inalcanzable, cuando se obligan y se fuerzan a sí mismos a ello;
pero puede ser alcanzado, y muy fácilmente,
cuando dejamos que el amor de Cristo nos constriña a la santificación.

¡Ah, cuánta ansiedad muestran muchos,
y cuántos esfuerzos se imponen para llegar a ser santos por sus propias fuerzas! ¡Oh,
mis queridos amigos; todo lo que tienen que hacer es amar a Cristo,
y unirse a Él mediante la fe, el amor y la oración,
tal como se une el pámpano a la vid! ¿Encuentra el
pámpano dificultad para llevar uvas dulces?
¿Es necesario obligarlo a que lleve fruto por medio de órdenes, amenazas y malos tratos?
¡No!
Todo el proceso ocurre muy tranquila, fácil y naturalmente;
el pámpano simplemente permanece en la vid y bebe su noble savia,
y luego florece y lleva fruto sin más dificultades.
Así debemos actuar nosotros.
"`Permanezcan en mí`", dice Cristo, "`y llevarán mucho fruto`". Sólo tenemos que amarlo,
permanecer internamente retirados en Su amor,
y como pámpanos estériles en nosotros mismos,
dejar que la influencia y el poder puros y divinos del precioso
amor de Cristo penetren toda nuestra alma.
Entonces, nos convertiremos, de manera natural, en un pueblo querido y acepto para Dios,
y lleno de todos los preciosos frutos de justicia para alabanza de Jesucristo.
Las virtudes se volverán fáciles y naturales para nosotros,
y nos consideraremos felices de ser capaces de vivir para Cristo,
según todo Su beneplácito.

Y si realmente fuera posible (que no lo es) que pudiéramos
llegar a ser santos por nuestros propios esfuerzos,
aun así, todo sería sólo un fantasma imperfecto, sin vida y sin valor,
que procedería de la voluntad y del poder del hombre,
y en el que únicamente nos consideraríamos y amaríamos a nosotros mismos.
El amor de Cristo es el que debe impartir la verdadera vida,
poder y valor a toda nuestra piedad, obras y virtudes.
Por eso, Pablo no sabe cómo recomendar suficientemente esta excelente manera,
cuando dice: "`Si yo hablase lenguas humanas y angélicas, y no tengo amor,
vengo a ser como metal que resuena...`" Y así continúa hasta el final del capítulo,
que encontrarán en la primera epístola a los Corintios y que pueden leer en casa.

_El amor de Cristo constriñe a toda diligencia, vigilancia y actividad en toda buena obra,
y durante todo el camino de piedad._
Muchos que duermen seguros en el sueño mortal del pecado,
pueden ser aterrorizados y despertados por el temor y el castigo.
Las emociones fuertes y las más serias decisiones pueden ser producidas en un hombre,
por los juicios de Dios, por una enfermedad, por temor a la muerte,
el fallecimiento de parientes cercanos, o por otras reprensiones de conciencia,
de manera que uno podría llegar a pensar que algo realmente bueno resultará de ellas;
¡pero cuán pronto pasan, cuando no van acompañadas por la gracia que renueva el corazón,
y por el amor de Cristo!
La angustia, la muerte y el infierno pueden constreñir como quieran,
pero si el amor de Cristo no constriñe al mismo tiempo, el hombre vuelve a dormirse.

Los medios externos de gracia pueden servir también para
despertar y animar a las almas perezosas y adormecidas;
pero si deseamos ser efectiva y permanentemente despertados
por los medios de gracia que Dios pone en nuestras manos,
debemos permanecer cerca de nuestros corazones y prestar
atención al amor de Cristo que obra junto con nosotros,
que internamente despierta,
anima y busca que su influencia sea sentida en los rincones más profundos
del corazón. Aunque el amor no conoce la ansiosa y distractora preocupación,
está igualmente lejos de la pereza y de la somnolencia.
Su poseedor está ansioso a lo largo del día,
tratando de hacer algo para complacer a su Amado.

Aquí debo también aludir a la pereza y a la pesadez externas.
Hay muchos que se quejan de ser fácilmente dominados por el sueño,
cuando están solos y llegando a la noche.
Debe admitirse que esto tiene sus causas naturales en algunos,
quienes están debilitados y fatigados por el trabajo, en cuyos casos,
la persona debe tener paciencia consigo misma; pero me temo,
que a muchos lo que les falta es amor.
He sido testigo de cómo muchos han sido vencidos por el sueño al anochecer,
cuando se leía o se decía algo bueno, pero que se despertaban inmediatamente,
cuando se introducía algún tema preferido y de otro tipo.
¡Qué vergüenza! ¡Si tuviéramos un poco más de amor por Cristo, no seríamos tan perezosos!

_El amor de Cristo constriñe a las buenas obras._
Los eruditos disputan de todas las formas posibles,
sobre las buenas obras y sus méritos--si son necesarias
para la salvación y hasta qué punto,
y cosas semejantes.
El alma que ama a Cristo no se inmiscuye en tales controversias; el amor,
como es natural para él, constriñe incesantemente a toda buena obra hacia Dios,
hacia los hermanos, hacia nuestros vecinos, e incluso, hacia nuestros enemigos.
El amor no puede actuar de otra manera;
busca hacer el bien a todos y a entregarse a todos.

Siempre tiene suficiente--es rico, es amable, es generoso;
y si no tiene dinero o algo más para dar,
todavía tiene un corazón que entrega en simpatía,
compasión y prestando toda la ayuda posible.
En una palabra, el amor siempre está haciendo el bien, casi sin pensar en ello.
Realiza mil obras buenas, sin preguntar si debe hacerlas o no,
y nunca se le ocurre pensar en el mérito de las buenas obras.
Incluso, cuando ha hecho mucho, piensa que hasta ahora no ha hecho nada,
y que ya es hora de empezar.
Así es como constriñe el amor de Cristo.

_El amor de Cristo constriñe a un continuo progreso en la santificación y en la piedad._
También son completamente innecesarias aquellas controversias
que se entablan sobre la perfección;
si los mandamientos de Dios pueden ser guardados; si tal estado particular es alcanzable,
y cosas por el estilo.
¡Dios, mío; la gente discute sobre la perfección,
pero sería más razonable primero preguntarse, si han dado un paso hacia ella!
Me parece que sólo exponen sus corazones sin vida
y sin amor con discusiones de esta naturaleza.

El amor no conoce límites; invariablemente busca avanzar más, ser más fiel,
piadoso y aceptable ante los ojos de Dios.
No pregunta mucho si la cosa es practicable o no, la intenta con mucha seriedad;
necesariamente debe seguir Su impulso y Su influencia que constriñe. El apóstol Pablo,
sin ninguna duda, estaba más avanzado que cualquiera de nosotros, sin embargo,
¿qué dice en el tercer capítulo de Filipenses?
"`Olvidando ciertamente lo que queda atrás, y extendiéndome a lo que está adelante,
prosigo al blanco,
al premio del supremo llamamiento de Dios en Cristo Jesús`". Y si se le dijera: "`Pablo,
¿no eres suficientemente piadoso?
Tú ciertamente ya no le temes al infierno`". "`¡Ah`", replicaría él,
"`no es ni el infierno ni el cielo lo que me constriñe;
lo que me constriñe así es el amor de Cristo`".

_El amor de Cristo entra voluntariamente en todos nuestros intereses._
Quiere y debe participar, no sólo en las cosas más grandes,
sino incluso en las más pequeñas. Todo lo que hacemos,
en lo que se refiere a nuestra vida natural, por muy grande e importante que parezca,
es en sí mismo una tontería sin valor,
y no merece la atención de un espíritu nacido del cielo; pero mediante el amor,
todas esas pequeñeces pueden llegar a ser verdaderamente grandes,
y un medio para servir a Dios.
Aquel, por decirlo así, que por amor a Cristo recoge una brizna de paja del suelo,
realiza una gran obra.

Hay muchos que se quejan fuertemente diciendo,
que sus ocupaciones externas y necesarias les causan mucha distracción,
estorbo y desventaja.
¿Cuál es la razón, mis queridos amigos?
Quizás porque realizan lo que les corresponde, como si fuera un asunto meramente mundano.
Cuando están sentados en la habitación, en la iglesia, o en una reunión, o pueden leer,
o hacer algo bueno, piensan que están sirviendo a Dios;
pero cuando están ocupados en el campo, en la cocina, o en alguna otra parte,
adondequiera que los lleven sus vocaciones, se imaginan que están sirviendo al mundo.
¡Qué lamentable si ese fuera el caso!
Entonces nos veríamos obligados a pasar la mayor parte de
nuestro tiempo en el inútil servicio al mundo.
Hagan todo lo que tienen que hacer, como un servicio rendido al amor de Cristo,
y entonces ya no les será una desventaja.

Cuando el amor al mundo, la preocupación, la incredulidad,
o cualquier otro de los poderes de la naturaleza,
nos constriñe a los negocios y es nuestro motivo principal en ello,
la mente naturalmente se oscurecerá y se distraerá cada vez más;
pero si el amor de Cristo nos constriñe al trabajo,
y nos dejamos constreñir por él en nuestros asuntos,
de modo que los realizamos de manera infantil, únicamente para Su amor y gloria,
entonces ya no serán un estorbo,
sino que se convertirán en un verdadero servicio rendido a Dios.
A esto se refiere el Espíritu Santo cuando dice:
"`Y todo`"--observen cómo dice _todo_--"`Y todo lo que hacéis sea de palabra o de hecho,
hacedlo todo en el nombre del Señor Jesús`". (Colosenses 3:17)

El amor de Cristo con gusto nos mantendrá todo el
día cerca de sí mismo y dentro de Su influencia,
nos impulsará en nuestro camino, y mediante su poder que constriñe,
nos preservará de desviarnos a la izquierda o a la derecha.
¡Ojalá nos mantengamos cuidadosamente dentro de sus límites!
Las personas a menudo se establecen a sí mismas una variedad de buenas máximas,
reglas y normas de conducta, las cuales no rechazo completamente.
Sé que el orden y la disciplina son necesarios para restringir la naturaleza indómita,
de lo contrario, se desbocaría;
lo único lamentable es que todas esas buenas reglas y máximas se quebranten tan pronto.
No hay mejor regla, norma o precepto, que el amor de Cristo,
el cual está internamente muy cerca de nosotros.

_El amor de Cristo nos guiará como una madre guía a su hijo._
Un niño que camina dirigido con cuerdas, es cuidadosamente sostenido y guiado;
porque aunque camina libre y sin restricciones, aun así,
si estuviera a punto de correr hacia el lodo, o se temiera que está en peligro,
inmediatamente sentiría que algo lo sostiene desde atrás.
El amor de Cristo busca guiarnos de la misma manera,
a fin de que podamos ser atraídos "`con cuerdas de amor`" (Oseas 11:4). Cuando
por causa de la ignorancia estemos a punto de caer en algo inapropiado o peligroso,
deberíamos percibir, como un niño dirigido con cuerdas,
que algo nos sostiene y nos restringe; a saber, el amor de Cristo.

_El amor de Cristo debe constreñirnos y nos constreñirá a orar._
Orar sin el corazón y a partir de la mera obligación del hábito, no es orar.
Orar, cuando el peligro y la angustia del alma,
y cuando el sentimiento del pecado y de la necesidad nos constriñen,
es una muy buena oración; pero cuando el amor de Cristo nos constriñe a orar,
esa es la más noble y la más excelente oración. A
menudo nos quejamos de que no sabemos orar,
que no tenemos el debido deseo para orar,
y que el tiempo que dedicamos a ella parece largo, etc.;
pero esto proviene de la falta de amor a Cristo.
Démosle paso al amor, y el amor nos constreñirá a orar.
Nos alegra estar a solas con verdaderos amigos;
y si amamos a Cristo y lo amamos de corazón, estaremos dispuestos a estar a solas con Él,
y el tiempo que pasemos en Su compañía, con facilidad no nos parecerá largo.
Si amamos a Cristo, siempre tendremos algo que decirle; y si no tenemos nada que decirle,
todavía tenemos algo que amar, y eso es orar.
¡Oh, amar y estar en silencio en la presencia de Dios, es una excelente oración!

Sí, mis queridos amigos,
no podemos creer cuán excelente maestro de oración es el amor de Cristo,
el cual despierta en el corazón del alma perdonada, innumerables e inefables suspiros;
¡ojalá sólo fuera más cuidadosamente apreciado!
Hace que muchos tiernos anhelos asciendan desde el fondo del corazón, frecuente,
involuntaria y casi inconscientemente.
Aunque los labios estén en silencio,
aun así el corazón exclama con sinceridad en un momento: "`¡Oh, Dios mío! ¡Oh,
mi Señor Jesús!`" En otro momento: "`¡Soy tuyo para siempre; mi Dios y mi todo!`"
Una sola de estas sinceras exclamaciones es de más valor a los ojos del Altísimo,
y realmente incluye en ella más que una larga oración de otro tipo,
una que es dicha a partir de un libro, o que proviene sólo del entendimiento;
y la razón es, porque es el lenguaje de la verdad.
Estamos dispuestos a decir: "`Dime, amiga,
¿de qué libro has aprendido estos hermosos deseos?
Me gustaría obtener una libro de oración como ese para mí`". Entonces el alma responde:
"`El amor de Cristo es mi libro de oración;
el amor de Cristo me constriñe a proferir estas exclamaciones`".

El amor de Cristo no sólo es el más excelente maestro de oración,
sino también la oración misma.
El amor es como un fuego continuo, que desciende del cielo sobre el altar del alma,
en el templo del corazón, donde el dulce incienso de la devoción silenciosa y espiritual,
deliciosa y amablemente asciende del santuario interno en mil actos de alabanza,
amor y ofrenda, en actos de elevación y humillación, y de veneración,
adoración y admiración del siempre bendito Dios;
donde uno solo de esos dichos actos internos de fe y amor, incluye más vida, paz,
deleite y bienaventuranza en él, que todo lo que el mundo puede ofrecer.
Esto no lo produce el alma por sí misma, ni es capaz de producirlo; entonces,
¿qué lo hace?
El amor de Cristo que la constriñe.

_En resumen, el amor de Cristo constriñe al alma más y más,
por una bienaventurada atracción, a una completa y eterna unión con el Amado._
Ella ha bebido del agua del amor que Cristo le ha dado,
y ésta se convertirá gradualmente en el alma,
en una fuente de agua que salta para vida eterna.
Siente que aquí abajo, ya no hay más felicidad para ella en nada de lo creado y temporal.
Todo se vuelve muy extraño para ella y muy inútil ante sus ojos.
Todo lo que está dentro de ella anhela a Cristo y la eternidad; y Cristo,
el divino centro de atracción, no puede dejarla mucho tiempo aquí en la tristeza;
la atrae, y finalmente la toma para Sí mismo: "`Padre, aquellos que me has dado,
quiero que donde yo estoy, también ellos estén conmigo,
para que vean mi gloria`". (Juan 17:24)

Mis amigos, esta bienaventuranza de la que hemos hablado imperfectamente ahora,
está reservada para ustedes y ofrecida a ustedes en Cristo; sí, es para ustedes,
y para los más débiles y más desdichados entre ustedes.
¡Oh, mis queridos oyentes, amen a Dios, quien los ama así y los amará eternamente!
Ríndanse incondicionalmente a la influencia de este beatificante amor de Dios,
que los constriñe y atrae.
No le pongan límites a este amor,
pues lleva más allá de lo que el entendimiento humano puede alcanzar;
y en el que hay mayores maravillas y bendiciones
para experimentar y disfrutar durante la vida presente,
de lo que la lengua de los hombres o de los ángeles puede expresar.

¡Oh, la lamentable ceguera e ignorancia de la humanidad en general,
al ser tan indiferente hacia Dios y tan apasionada en la búsqueda de otros objetivos,
y al dejar que el amor al mundo,
al pecado y a la vanidad tenga más influencia sobre el corazón que el amor de Cristo!
El amor al mundo sólo necesita hacer una insinuación,
y el hombre está inmediatamente alerta;
mientras que el amor de Cristo constriñe por mucho tiempo, y sin embargo,
las personas no lo siguen ni se rinden a él. ¡Oh,
cuántos infelices mundanos se dejan constreñir por el pecaminoso amor al mundo,
y son llevados de un pecado, vicio y vanidad a otro!
Es como un esclavo, que está tan constreñido por su duro amo,
que es casi incapaz de abandonar sus viejos hábitos.
Satanás y el amor al mundo lo gobiernan y lo constriñen,
y lo conducirán al infierno mismo,
sí no recapacita a tiempo y se deja constreñir al arrepentimiento por el amor de Cristo.

Por lo tanto, amigos míos, examinemos qué es lo que amamos.
¿Qué tiene el mayor peso para nosotros?
¿En qué objeto pensamos primero en la mañana y con más frecuencia durante
el día? De este modo podemos determinar dónde está nuestro tesoro.
¿Comenzamos dejando que el amor de Cristo tome posesión de nuestros corazones;
o todavía estamos en nuestro estado natural sin vida y sin amor, sin Cristo y Su amor?
¡Oh, qué indescriptiblemente infeliz estado! ¡Oh,
qué terriblemente peligrosa condición! Si no estamos en el amor, estamos en la ira,
en el horrible reino de tinieblas, donde la ira de Dios se cierne sobre nosotros,
y donde sostenidos sólo por el frágil hilo de la vida,
colgamos sobre el abismo sin fondo.
¡Oh, qué miseria eterna morir en tal estado!

¡Oh, almas inmortales!
Ustedes están escuchando ahora al amor de Cristo, ¿pero quién sabe por cuánto tiempo?
En este momento, Cristo mismo lo proclama, recomienda y ofrece a nuestros corazones.
Sí, Jesús los ama a todos ustedes, sin importar cuán pecadores puedan ser,
y tengan que confesar que hasta ahora han sido esclavos
del pecado y de Satanás. No tienen que perecer,
Cristo gustosamente los salvará; Él les ruega.
¡Ah, ríndanse a Él!

Si la miseria y el peligro, si la ira de Dios,
el temor a la muerte y el terrible día del juicio,
junto con la propia desdicha y perdición eternas, no los constriñen y afectan,
entonces dejen que el amor de Cristo lo haga.
Déjenme presentar delante de sus ojos al sufriente Salvador.
¡Mírenlo postrado en Su sudor sangriento y terrible agonía de alma,
como si estuviera en el piso delante de ustedes,
llorando y suplicándoles! ¡Véanlo colgando del madero fatal,
en la más grande agonía de alma y cuerpo,
con Sus brazos extendidos para recibir a los pecadores que
regresan! ¡Mírenlo mostrándoles Sus heridas sangrientas,
y encomendándolos a Su gracia y a Su amor!
Tan cierto como estas palabras son dirigidas a ustedes,
así de cierto es que el compasivo amor de Cristo
se ocupa de sus corazones y se hace sentir.
¡Oh, sométanse a Él! ¡Háganlo _ahora,_ para que eventualmente,
no sea demasiado tarde contemplar a Aquel que ha
sido traspasado por los pecados de ustedes!
Aférrense al amor, no sea que la ira se apodere de ustedes; aférrense al amor,
mientras aún está cerca.

Pero nosotros,
que por gracia nos hemos convertido en recipientes de una chispa de este amor de Cristo,
estimémosla altamente; es una perla invaluable; y por pequeña que sea esta perla,
aun así es de más valor que la totalidad del mundo; y por pequeña que sea la chispa,
todavía puede convertirse en un calor ardiente, en una llama del Señor,
cuando se aprecia y atiende cuidadosamente.
Presérvenla cautelosamente mediante un caminar verdaderamente prudente,
eviten toda interacción, amistad y enredo innecesarios con los hombres de este mundo,
y cualquier otra ocasión de tentación. En tales circunstancias,
debemos conducirnos como quien camina contra el viento con una candela encendida,
o como quien atraviesa un bosque con una joya preciosa;
porque los enemigos de nuestras almas, que acechan nuestro tesoro,
están en todas partes queriendo emboscarnos.
Por lo tanto, debemos estar constantemente en guardia y orar,
como el himno que hemos cantado recientemente,

[verse]
____
¡Oh, haznos de noche y de día vigilar,
para el precioso tesoro del amor con esmero cuidar,
y ante esas infernales huestes no sucumbir,
que desde el abismo se levantan con fuerza para perseguir!
____

Somos propensos a pensar que esta es una precaución innecesaria,
y que cuidaremos bien de nosotros mismos; ¡pero, ah!,
no estamos suficientemente familiarizados con las artimañas del enemigo,
ni con nuestra propia debilidad a la hora de la tentación. No necesitamos
citar el ejemplo de Pedro como una advertencia para nosotros;
pues tenemos suficiente experiencia dolorosa de ello a mano.
Así que cuidémonos de toda ligereza,
desenfreno y de las sugerencias incrédulas de nuestra razón carnal.
Sé muy bien que el amor de Cristo nos constriñe a
todo lo que se ha recomendado hasta ahora,
y nos instruye en ello según nuestra necesidad; ¡pero desafortunadamente,
no siempre estamos en un estado adecuado para escucharlo!
Por lo tanto, debemos permanecer cerca de nuestros corazones,
donde el amor lleva a cabo Su obra, en un estado mental tranquilo, piadoso y recogido.

Ahora, pues, una palabra más de ánimo para todos nosotros, y con esto concluyo.
Escuchemos y aceptemos este glorioso evangelio del siempre bendito Dios,
que ha sido anunciado a nosotros hoy, aunque en debilidad,
pero en el nombre del Señor. Cristo nos ama y continuará amándonos;
nos impartirá el poder de Su amor,
y junto con él todo lo que es bueno en el tiempo y en la eternidad.
Cristo nos ama, nos ama a todos nosotros; entonces, ¿qué estamos haciendo;
por qué deberíamos desanimarnos; por qué seguimos dormidos?

Cristo los ama a ustedes, _almas jóvenes,_
que en sus florecientes años están buscando algo que amar.
¡Ah, cuánto me afligiría, cuánto se afligiría el Salvador,
si se dejaran cautivar por un amor falso y engañoso! ¿No sería para siempre lamentable,
si se dejaran seducir, corromper y avergonzar por el amor vano de este mundo;
por el amor a aquellas cosas que realmente no tienen nada encantador,
nada verdaderamente placentero en ellas; las cuales pronto, muy pronto,
se marchitan y causan disgusto y se desvanecen como el humo?
Cristo los ama a ustedes, ¿están conscientes de ello?
¿Reflexionan en ello?
Sólo para Él les han sido dados sus corazones;
sólo para Él les ha sido impartida muy profundamente
en sus corazones la noble inclinación a amar.
¡Oh, si supieran correctamente lo que es ser hallado en Cristo y en Su amor,
ciertamente se enamorarían y serían cautivados por Su incomparable belleza!

Cristo los ama a ustedes, _corazones arrepentidos, angustiados y temerosos,_ y no lo saben,
y no lo creen.
Cristo los ama de verdad; ¿continuarán entonces en su abatimiento?
¿No los debería animar este alegre mensaje?
Si aún no lo pueden creer plenamente, hagan el intento por una vez;
aventúrense como la reina Ester cuando dijo: "`Si perezco,
que perezca`". Ella se aproximó al rey con temor,
y cuando pensó que todo había terminado para ella,
el misericordioso cetro le fue extendido y el rey la abrazó. ¡Vengan, entonces, ustedes,
temerosas almas, y experimentarán que su suerte no será menos favorable que la de ella!

Cristo nos ama a todos los que como yo, _participamos del llamamiento celestial._
¿No deberíamos, pues, despertarnos del sueño, levantar los ojos de nuestros corazones,
amar a Cristo en reciprocidad, y andar en Sus caminos con la mayor prontitud?
¡Qué honor es para la gente cuando son amadas por un rey o por un príncipe,
o por un noble o por un grande,
aunque sea con un amor que no le imparte a su objeto nada sustancial o permanente!
Y he aquí que Cristo, el Hijo de Dios, nos ama como Su esposa! ¿Deberíamos, entonces,
dejar que las locuras sin valor de este mundo capturen nuestra
atención? ¿No deberíamos dejar que Su amor nos constriña
a desapegar nuestros corazones de todo ídolo y rival indigno,
y dedicarlos eternamente a Su amor divino?
En el corazón de Jesús, no veo nada más que amor hacia nosotros.
¡Oh, qué vergüenza, qué lástima,
que en nuestros corazones se vea algo más que el amor de Cristo!

A partir de ahora, sin embargo, que sea diferente con nosotros.
¿Por qué no terminamos renovando de una vez nuestro
pacto de amor con Cristo ahora en Su presencia?
¿Estamos dispuesto a unirnos y a rendirnos de nuevo al más Hermoso entre diez mil,
en amor sincero y mutuo, y con asentimiento y consentimiento no fingidos, y quiera Dios,
irrevocables?
¿Lo haremos?
¿Es la determinación madura de nuestros corazones?
Vamos, entonces, y démosle la mano de nuestros corazones a Jesús,
quien está presente con nosotros,
y digamos en el espíritu de verdadera devoción y con todo el corazón: "`¡Sí y amén!`"

[verse]
____
¡Señor, me rindo de nuevo a Ti,
dispuesto a renunciar a todo por Ti,
y juro serte fiel para siempre a Ti!
Tu hermoso nombre confesaré,
sin importar lo que el mundo burlón pueda decir,
y en la fidelidad de Tu pacto confiaré,
para que en el último gran día me puedas recibir.
____
