== Prefacio a la Primera Edición. 1832

Hay una especie de instrucción que se deriva de la
lectura atenta de las vidas de destacados santos,
la cual, en la actualidad, se ha vuelto más valiosa e importante que nunca;
porque aunque la edad en la que vivimos se caracteriza por un celo
inusual por la extensión externa del reino de Dios en el mundo,
aun así, los ejemplos vivos del completo predominio de este reino en el corazón,
son raros y poco frecuentes.
Mientras se aplica toda la energía a la propagación de los primeros principios del Cristianismo,
el gran fin y objetivo de éste--a saber,
la conformación a la imagen de Dios mediante el incremento
en la participación de la naturaleza divina,
y la muerte de la voluntad de la carne--es en gran medida descuidado y pasado por alto.

Este lamentable declive en la piedad ha traído como consecuencia,
que cuando leemos en la Biblia de aquellos que "`por la fe conquistaron reinos,
hicieron justicia, obtuvieron promesas,
fueron hechos fuertes,`" estamos dispuestos a considerar que fueron dotados
por Dios para algún propósito particular que ya no existe hoy,
y que los Cristianos en nuestros días no están autorizados a esperar
manifestaciones tan extraordinarias del favor divino,
a pesar de la exhortación del apóstol a ser seguidores "`de aquellos que por la fe y
la paciencia heredan las promesas;`" y de las palabras de nuestro Señor mismo:
"`El que en mí cree, las obras que yo hago, él las hará también; y aún mayores hará,
porque yo voy al Padre.`"

Por lo tanto,
los que sinceramente desean crecer en la gracia y conocimiento de la verdad,
no pueden dejar de cosechar consecuencias beneficiosas,
al ver en la historia de los piadosos que han muerto,
la manifestación de esa fidelidad y favor divino que no hace acepción de personas,
sino que en cada época,
está dispuesto a conceder sus inestimables bendiciones
a todos aquellos que diligentemente las busquen;
y al ver que incluso en los últimos tiempos,
el mismo Espíritu que habitaba tan ricamente en los miembros de la iglesia primitiva,
es todavía dado a los que se someten a sus enseñanzas y se dedican completamente a Dios.
El traductor considera que estos benditos resultados son ejemplificados en grado sumo,
en la vida del individuo de quien se adjunta un breve relato.

La historia de la vida de Tersteegen no sólo establece la excitante verdad de que Dios,
en la dádiva de Su Espíritu, es "`el mismo ayer, y hoy,
y por los siglos,`" sino que también muestra la manera de experimentarla.
Como todo verdadero seguidor de Cristo ejemplifica en su medida, la vida de Cristo,
y dado que una característica destacada de esa vida era la aflicción,
así encontramos que el peregrinaje terrenal de este devoto siervo de Dios,
especialmente al comienzo de su recorrido espiritual,
estuvo marcado por el sufrimiento y la prueba;
porque "`es necesario que a través de muchas tribulaciones entremos en el reino de Dios.`"
Hay muchos que se jactan de su adopción en la familia del cielo,
pero el que no haya soportado los castigos paternales de Dios,
no tiene derecho de hacerlo;
porque es imposible que el cuerpo de pecado dentro
de nosotros sea destruido de alguna otra forma,
o de que la voluntad pervertida del hombre sea conformada a la divina voluntad,
sino por la sumisión a ella bajo las circunstancias más difíciles y dolorosas.

La total rendición a la voluntad de Dios es, por tanto,
la primera lección que tenemos que aprender.
Sin embargo, a fin de alcanzar una completa renuncia del yo,
no es necesario que sigamos el modo particular de vida que otro haya encontrado de beneficio;
sino que nos encomendemos por completo a la Guía divina,
con la firme convicción de que la situación en la que nos coloque,
por mucho que difiera de nuestras opiniones y deseos,
es la que mejor se adapta a nuestro avance en la santidad.
Con respecto a nuestra conducta en ella, el Espíritu Santo nos instruirá suficientemente,
si sólo escuchamos atentamente sus dictados.

Tal como la lectura atenta de la historia de Tersteegen puede ser ventajosa para arrojar
luz sobre las dispensaciones externas de la providencia de Dios hacia Su pueblo,
así también, el estudio de sus escritos mostrará, de una manera muy clara,
las operaciones internas del Espíritu sobre el corazón,
y el progreso de la vida de Dios en el alma.
Además de la palabra de Dios,
hay pocos autores cuyas obras haya leído el escritor con mayor satisfacción y beneficio,
y cuyos escritos están tan evidentemente impregnados de la unción divina
que los distingue notablemente de las obras religiosas en general,
las cuales, especialmente en el presente,
llevan más el sello del ingenio y habilidad humano,
que el de la sabiduría que viene de arriba.
Apenas es necesario agregar,
que sus obras continúan siendo leídas y apreciadas en Alemania por aquellos que
tienen apetito de comida espiritual y ya no se contentan con las producciones
superficiales e insatisfactorias de los que,
aunque sean verdaderamente versados en el conocimiento de la letra de las Escrituras,
en realidad, poseen poco de su espíritu.

--Samuel Jackson

Norwood, 7 de agosto de 1832
