== Vida y Carácter de Gerhard Tersteegen

Gerhard Tersteegen nació el 25 de noviembre de 1697,
en la capital del principado de Moers.
Su padre, Henry Tersteegen, era comerciante y ciudadano de dicho pueblo,
y murió poco después del nacimiento de su hijo Gerhard.
Parece haber tenido inclinaciones religiosas, y por sus papeles,
de haber tenido correspondencia con personas piadosas de otras partes.

Gerhard era el más joven de los ocho hijos, seis hijos y dos hijas.
Uno de sus hermanos era predicador, los otros estaban involucrados en negocios.
De los últimos, uno de ellos llamado Johannes, estaba muy apegado a su hermano menor.
Poseedor de considerables habilidades,
Gerhard fue enviado por su madre a la escuela de latín, donde pasó por todos los niveles.
Se aplicó con gran diligencia igualmente al griego y al hebreo,
así como también al latín; e hizo tal progreso en el último, que en una ocasión,
durante una solemnidad pública, declamó una oración en latín en verso,
que fue aplaudida por todos,
lo cual indujo a uno de los principales magistrados a aconsejarle a su
madre que le permitiera a su hijo dedicarse enteramente al estudio.
Su madre declinó la propuesta debido a las circunstancias de la familia,
y lo destinó a la vida mercantil.
Por lo tanto,
a los quince años fue contratado como aprendiz por
un período de cuatro años por su cuñado,
un comerciante en Mülheim junto el Ruhr.

Fue aquí, cuando sólo tenía dieciséis años,
que recibió las primeras impresiones religiosas,
pero no se sabe con certeza a través de qué medio; excepto,
que en Mülheim conoció a un comerciante piadoso de quien recibió muchas excelentes amonestaciones.
También se le oyó decir,
que una vez había sido profundamente afectado al leer una oración de acción de gracias,
de un clérigo moribundo.
Por estos y otros medios similares, fue llevado, por la sabiduría de Dios,
a buscar con fervor un cambio de corazón; por lo que pasaba noches enteras leyendo,
orando y en otros ejercicios devocionales.

La siguiente circunstancia parece haber tenido un efecto muy beneficioso sobre su mente.
En una ocasión, que fue enviado a Duisburg,
se apoderó de él un cólico tan violento en los bosques de Duisburg,
que no esperaba nada más que la muerte.
Se salió un poco del camino,
y fervientemente le rogó al Señor que lo librara de su dolor y prolongara su vida,
a fin de tener tiempo para prepararse de mejor manera para el mundo eterno.
Con lo cual, el dolor súbitamente lo dejó,
y se sintió muy poderosamente impulsado a dedicarse sin reservas a Dios,
quien había sido tan bueno y misericordioso con él.

Por este tiempo,
le fueron hechas muy evidentes la vanidad y mutabilidad
de todo lo de esta naturaleza terrenal,
y la infinita importancia de las cosas celestiales y eternas.
También percibió que la vida de comercio y la continua asociación con todo tipo de personas,
distraían mucho sus pensamientos y obstruía su crecimiento en la gracia.
Por esta razón, cuando expiró el tiempo de su aprendizaje,
tomó la decisión de dedicarse a una ocupación más retirada.
La relación que tenía en ese tiempo con un tejedor piadoso,
lo determinó a aprender ese oficio; pero su habitual debilidad corporal,
frecuentes jaquecas y dolores en los intestinos lo obligaron a abandonarlo.
Posteriormente eligió el arte de hacer cintas, y no tenía a nadie con él,
excepto a la persona que torcía la seda.
Continuó viviendo en Mülheim junto el Ruhr, donde pasó el resto de su vida.

En esta nueva situación vivió en la práctica de la más grande negación al yo;
su ropa era tosca y su comida, que a menudo preparaba él mismo, era de lo más común,
y consistía principalmente de harina, agua y leche.
En los primeros años de su reclusión, sólo comía una vez al día,
y no bebía té ni café. Aunque sus ingresos eran muy limitados,
aun así se mostraba extremadamente generoso con los pobres.
Al anochecer, cuando no podía ser reconocido,
entraba en las viviendas de los enfermos y necesitados,
y dividía entre ellos todo lo que podía ahorrar de sus ingresos.
En la división del patrimonio de su padre, los herederos le asignaron una casa,
para evitar que donara todo;
pero en diferentes momentos recibía de su hermano
Johannes el valor del edificio en moneda corriente,
e igualmente daba la mayor parte de ésta a los pobres.
Por esta razón sus parientes estaban más indignados con él que nunca;
y estando él frecuentemente enfermo por varias semanas seguidas, sin poder ganar nada,
cayó en la mayor pobreza y necesidad.

La siguiente carta que le escribió a un amigo personal, fechada 24 de octubre de 1766,
atestigua la veracidad de esta afirmación. "`Es fácil,`" dice,
"`hablar de pobreza mientras estamos rodeados de
amigos ricos que están dispuestos a ayudarnos.
El que escribe esto ha experimentado el momento en que no
sabía dónde encontrar comida para el día siguiente;
y no tenía un amigo que estuviera al tanto de la situación. Trabajaba
desde la cinco de la mañana hasta las nueve de la noche,
y ocasionalmente pasaba en cama o en el desván diez o doce semanas,
sin que aquellos con quienes se alojaba se molestaran en enviar
a uno de sus ociosos sirvientes a darle un trago de agua.
Pero siempre pensé que era necesario.`"

En otra carta escribe: "`Una vez estuve enfermo en cama con una fiebre ardiente,
y pensé que moriría de sed.
Le rogué a la criada de mi hermano, en cuya casa me encontraba enfermo,
que me llevara el valor de medio stiver^
footnote:[Una moneda holandesa de aproximadamente
el valor de medio centavo de libra esterlina,
o el centavo de los Estados Unidos.]
de cerveza de mesa;^
footnote:[La cerveza de mesa era un tipo de cerveza con
poco alcohol que bebían personas de todas las edades,
ya que en general se consideraba más limpia y segura
que el agua disponible en aquella época.]
pero como la joven estaba distraída y su señora le dio algo más que hacer,
se olvidó por completo de mí. Yo estaba en una habitación en la planta alta,
y nadie pensó más en mí. Por tanto,
me vi obligado a permanecer acostado desde la mañana hasta bien entrada la tarde,
sin una gota de algo que me refrescara.
Finalmente escuché a la criada en las escaleras,
y le pedí a Dios que me guardara en el espíritu de mansedumbre.`"

En esta y otras pruebas similares,
su confianza filial en el cuidado de su Padre celestial permaneció firme e inquebrantable,
y sentía un estímulo interno y poderoso hacia ella.
En una ocasión, al observar que parte de su ropa estaba desgastada,
y que no sabía dónde podría encontrar dinero para reemplazarla,
quedó fuertemente grabado en su mente que no debía '`estar afanado por nada`'
(Filipenses 4:6). Esto lo fortaleció grandemente a esperar en la bondad divina;
y la tierna misericordia de Dios, como se mostrará a continuación,
cuidó abundantemente de él y no permitió que le faltara nada bueno.
En ese tiempo, nuestro difunto amigo disfrutó verdadero contentamiento.
"`No puedo expresar,`" dijo en una ocasión,
"`cuán feliz fui durante el tiempo que viví sólo. A menudo pensaba que ningún
monarca sobre la tierra podía vivir tan felizmente como yo en ese tiempo.
Cuando comía, no sabía qué era lo que estaba comiendo, ni a qué sabía,
y con frecuencia no veía a nadie por una semana seguida,
excepto a la joven que me llevaba la comida.`"

Este período de contentamiento fue seguido por un estado de aflicción interior,
al que el Señor lo condujo gradualmente.
Tuvo que pasar a través de muchas pruebas y tentaciones, y por muchas tinieblas internas.
El Señor retiró de él la percepción sensible de Su favor,
a fin de poner su fidelidad y sufrida paciencia a prueba,
y prepararlo también para futura utilidad.
Este estado espiritual de tinieblas continuó por cinco años; hasta que al fin,
mientras viajaba a un pueblo vecino, la Aurora de lo alto lo visitó nuevamente,
y la misericordia expiatoria de Cristo se hizo tan
profunda y convincentemente evidente para él,
que su corazón quedó en completo reposo.
En esta ocasión compuso ese hermoso himno, "`Mi gran Sumo Sacerdote,
cuán bondadoso es Tu amor, etc.`"

Esto me hace recordar la siguiente sorprendente circunstancia que a menudo relataba.
Reflexionando sobre las diversas divisiones en la iglesia Cristiana,
fue atacado por una tentación tan poderosa,
que casi empezó a dudar de la existencia de Dios;
pero el Señor pronto lo liberó de esa tentación,
no sólo iluminando completamente su entendimiento,
sino también a través de una comunicación divina,
la cual le resultaba imposible de expresar con palabras.
Por este medio fue tan confirmado en el conocimiento esencial de Dios nuestro Salvador,
que posteriormente pudo hablar y escribir sobre esto de manera poderosa y por experiencia,
y con mucha unción divina.
Es probable que por esta época haya compuesto esa noble dedicación de sí mismo a Dios,
que aparece en el prefacio del primer volumen de sus cartas.

Aproximadamente un año después de la fecha de esa dedicación, (1725), accedió,
tras repetidas solicitudes, a recibir en su alojamiento a un joven llamado Sommer,
que deseaba aprender el arte de hacer cintas.
Lo hizo, no sin considerable vacilación,
al estar muy indispuesto a renunciar a la soledad que había encontrado tan agradable.
En compañía de este joven amigo--por recomendación del piadoso difunto señor Hoffmann,
un candidato al ministerio--llegó a ser menos rígido en su manera de vivir,
y se acostumbró a tomar café con él. En dichas ocasiones,
después de haber cantado un himno, leían una porción del Nuevo Testamento;
y después del café, Tersteegen ofrecía una breve oración,
y luego ambos se dirigían en silencio a trabajar.

Ellos dividían el día de la siguiente manera:
Se reunían a las seis de la mañana y trabajaban hasta las once,
cuando se separaban por un hora con el propósito de orar.
A la una, retomaban sus labores, que continuaban hasta las seis de la tarde,
después de lo cual quedaban libres y pasaban nuevamente una hora en oración privada;
un estilo de vida que duró casi tres años. Tersteegen empleaba
su tiempo libre en la traducción de obras edificantes,
tales como The Compendium of True Godliness,^
footnote:[Compendio de la Verdadera Piedad.]
y The Hidden Life with Christ in God,^
footnote:[La Vida Escondida con Cristo en Dios.]
// lint-disable invalid-characters
etc., del eminente piadoso Bernières de Lauvigny.
Por este tiempo también escribió The Pious Lottery,^
footnote:[Lotería Piadosa.
Su Lotería Piadosa era un juego de cartas compuesto por 365 naipes
que contenían palabras de sabiduría y consejos para los creyentes.
Seleccionando al azar una carta de la baraja,
el jugador piadoso realizaba dos actividades al mismo tiempo:
jugar a un juego de cartas aleatorio y practicar una devoción de mentalidad cristiana.
El libro de oraciones de Tersteegen tuvo éxito gracias a la popularidad
de la práctica de la lotería profana del siglo XVIII,
de la que su juego se apropió y adaptó para los propios fines de Tersteegen.
Él anunciaba su juego como una lotería sin peligro de perder.]
y preparó materiales para The Spiritual Flower Garden.^
footnote:[Jardín de Flores Espirituales.
En 1724, cuando instruía a los hijos de su hermano y de su hermana, escribió para su uso:
"`Esbozo imparcial de los principios del Cristianismo.`"
Nunca publicó esta pequeña obra,
pero su valor puede inferirse de la siguiente circunstancia.
Un piadoso ministro reformado vio este tratado después de la muerte de su autor.
Solicitó permiso para leerlo, y luego le testificó a un amigo,
quien lo encontró ocupado leyéndolo, que había obtenido no poco beneficio de él.]

No mucho después, en el año 1727, empezó a hablar en reuniones privadas.
La persona que ocasionó esto, fue el difunto señor Hoffmann mencionado antes.
Este piadoso hombre no sólo hablaba en la reunión que había sido
instituida en Mülheim por el difunto reverendo Theodore Undereick,
sino también en otras ocasiones, durante el año 1725 y especialmente en el año 1727,
cuando se produjo un gran despertar en esa vecindad, principalmente en el ducado de Berg.
Estando Hoffmann muy familiarizado con el profundo conocimiento y experiencia de Tersteegen,
lo instó a que dijera una palabra de edificación en Mülheim y en otros lugares.
El resultado demostró los benditos efectos que tuvo esto.
Muchos que no estaban despiertos, fueron tan afectados por sus poderosos sermones,
que experimentaron una completa y permanente conversión; mientras que otros,
que ya estaban despiertos,
fueron inducidos por sus impresionantes disertaciones a acudir a él con mayor confianza,
en busca de consejo en toda clase de tentación, prueba y sufrimiento;
y por sus sabios consejos, fueron confirmados en su confianza y dependencia en Dios.

El gran número de los que acudían a él por consejo,
no sólo personalmente sino también por carta, junto con su debilidad corporal,
que se había incrementado considerablemente por sus estudios nocturnos, lo obligaron,
por este tiempo, a renunciar a su empleo.
Cabe preguntarse,
¿de dónde obtenía entonces su sostén? Hasta entonces había rechazado
de manera afectuosa muchas ofertas generosas que le habían hecho.
Una vez lo visitó un comerciante, y debido a la gran estima que le tenía,
le ofreció una anualidad de por vida.
Una piadosa dama, que nunca lo había visto,
lo nombró en su testamento albacea de su patrimonio, que ascendía a 40,000 florines,
con la condición de que tomara de ellos lo que necesitara.
Un caballero holandés le ofreció un bono de 10,000 florines,
y le rogó con lágrimas que los aceptara.
Él declinó todas estas y otras ofertas del mismo tipo,
pero al ser cada vez más incapaz de trabajos manuales,
aceptó las ofertas de amor de unos pocos amigos, por quienes era cordialmente estimado,
y a quienes él a su vez amaba con especial confianza; además de lo cual,
otros amigos le legaron ciertas sumas en sus testamentos.
Por estos medios, no sólo quedó en posición de suplir sus propias necesidades,
sino también de mostrar su generosidad a los pobres en variedad de formas.
Incluso a su muerte, quedó un poco de dinero disponible, que él, sin embargo,
ordenó en su testamento que fuera inmediatamente
repartido entre algunos seguidores pobres de Jesús,
y del que sus parientes recibieron también una parte, junto con su mobiliario.

Aunque él había dejado de lado su anterior empleo,
mantuvo una especie de labor manual hasta el fin de su vida.
Al tener un valioso conocimiento de medicina,
preparaba ciertas medicinas que les administraba
gratuitamente a unos pocos amigos y a algunos pobres,
y que al final eran tan solicitadas,
que se vio obligado a aceptar los servicios de un ayudante.

Alrededor del año 1740,
cuando se suspendieron las reuniones de los jueves
que habían sido iniciadas por el reverendo T. Undereick,
Tersteegen se hizo más conocido por la publicación de varias obras,
lo que le ocasionó muchas visitas.
También recibió la petición de hacer un viaje una vez al año a Holanda.
Cierto hombre en ese país, que lo había conocido a través de sus escritos,
se encariñó tanto con él que lo invitó a ir a verlo;
pero como Tersteegen retardaba su visita,
el caballero aludido decidió hacer él mismo el viaje a Mülheim.^
footnote:[Este caballero holandés era de alto rango
y ocupaba una posición destacada en el gobierno;
no obstante, puso su rango, posición, equipo, etc. a los pies de nuestro amado Redentor,
y llevó una vida retirada y escondida con Cristo en Dios,
en una pequeña y pobre habitación en Ámsterdam hasta su muerte.]
Habiendo recibido información secreta de esto,
y temiendo que pudiera inclinarse a pasar más tiempo con él del que podía disponer,
Tersteegen decidió no esperar su visita, sino ir él mismo a verlo,
y después de una corta visita, regresar a casa.
Posteriormente, fue cada año a Holanda a disfrutar, en compañía de este amigo,
de unas pocas semanas de tranquilidad y reposo; pero esto no duraba mucho tiempo.
Por lo general, pronto se sabía de su llegada,
y llegaban amigos de varios lugares a visitarlo y
a conversar con él del estado de sus almas.
También había muchos a los que amaba cordialmente,
y con quienes mantuvo una correspondencia regular y una amistad íntima hasta su muerte.

Tersteegen se alojó en una casa hasta el año 1746,
en la que había dos habitaciones en el piso superior, y adonde le llevaban la cena.
Ese año rentó una casa completa, pero siguió viviendo en la parte de arriba con su amigo;
una conocida suya--junto con el hermano de ella y
su cuñada--ocupaba la planta baja de la casa,
le preparaba la comida,
y cocinaba a su cargo para un número de personas pobres y enfermas.

El mismo año, su querido hermano Hoffmann cayó enfermo de un trastorno en el pecho,
el cual, después de un confinamiento de varias semanas,
terminó su carrera terrenal y lo condujo a una feliz eternidad.
En esta ocasión, Tersteegen le dio muchas pruebas de su amor y afecto.
Lo asistió vendando sus heridas, y animándolo mediante sus frecuentes visitas,
consoladoras conversaciones y fervientes oraciones hasta su muerte.^
footnote:[Hoffmann le había pedido a Tersteegen que después de su fallecimiento,
le diera gracias a Dios en su casa por su feliz salida,
junto con algunos de sus más íntimos amigos.
El siguiente relato, que Tersteegen le dio a un amigo en el campo, fechado 30 de agosto,
mostrará la manera en que esto sucedió. "`Como mi difunto amigo Hoffmann,
quería que pocos días después de su muerte yo invitara a sus amigos
más íntimos a reunirse en la casa donde había vivido y muerto,
para agradecerle al Señor los favores que le había mostrado y su liberación final,
cumplí con su pedido.
Sin embargo, me tomó por sorpresa.
Uno se lo contó a otro, por lo cual, en dos horas se supo el asunto, y hallé en el lugar,
según mi cálculo, más de ciento cincuenta personas reunidas,
lo que al principio me confundió; pero como me sentía obligado a cumplir,
en lugar de una oración de acción de gracias,
hablé durante dos horas seguidas sobre Judas 20-21.
Todos los presentes quedaron profundamente afectados,
pero la emoción de los sentidos es, en el mejor de los casos, sólo flor sin fruto.
Aun así, puedes inferir de esto que la gente aquí tiene hambre del pan de vida.
Si yo lo hubiera dado a conocer dos días antes, en lugar de dos horas,
no habría habido espacio suficiente para contener a toda la gente.
Pero no me siento llamado, ni enviado, a hacer ejercicios de esta naturaleza,
porque yo mismo sólo soy un pobre infante ignorante, y no sé, ni poseo nada,
excepto en el Señor, y no tengo control sobre lo que le pertenece a otro.`"]
A su muerte, Tersteegen alquiló de sus parientes, la cabaña en la que él había vivido,
donde se alojaba y hospedaba a sus amigos que llegaban a verlo desde lejos,
por cuya razón obtuvo el nombre de cabaña del peregrino, que lleva hasta hoy.

Además de los muchos conocidos que Tersteegen tenía en el ducado de Berg, Mettman,
Homberg, Heiligenhaus y otros lugares, también era bien conocido en Barmen,
lugar que visitó por primera vez en el año 1747,
tras una apremiante invitación. Con la bendición divina,
muchas almas fueron despertadas ahí a través de él, a quienes visitó los siguientes años,
y fue igualmente visitado por ellos en repetidas ocasiones.
Ellos no podían admirar más sus distinguidos dones espirituales.
Su amor, longanimidad y paciencia con el débil y vacilante,
la especial sabiduría que desplegaba al llevar a
cada uno a un franco descubrimiento de su estado,
su mano amiga en todo tipo de pruebas y dificultades,
así como también su poderosa manera de interceder en oración,
quedó indeleblemente impreso en sus corazones.
Él le hizo a un amigo íntimo el siguiente relato del mencionado viaje.

Me he dejado inducir a aceptar las incesantes invitaciones de una pareja de ancianos,
que residen a casi veinte millas de este lugar,
y que creen haber llegado a la convicción por medio de mis escritos,
y debido a que ellos mismos son incapaces de venir aquí,
me han presionado por año y medio para que les haga una visita.
Los dos hijos de ellos son también decididamente piadosos,
y ocasionalmente han venido a verme.
Mi intención era hacer el viaje de incógnito, pero me resultó imposible;
porque en el lugar adonde estaba no sólo había muchos a quienes no había visto antes,
sino que fueron despertados y tan profundamente afectados,
que me resultó difícil permanecer firme,
en medio de las muchas lágrimas derramadas por los
nuevos convertidos y al momento de separarme de ellos,
pues también fui constreñido a viajar por el ducado de Berg por once días seguidos,
y estuve rodeado de personas desde la mañana hasta la noche.
En una ocasión, cuando estaba a unas millas de cierto lugar,
descubrí que unas personas me estaban esperando en el camino.
Me llevaron a un granero, donde encontré a unas veinte personas,
la mayoría de ellas desconocidas para mí,
y que estaban deseosas de oír de mí una buena palabra.
Puede que pienses, querida hermana, que me olvido de mí mismo a menudo,
en lo que se refiere a mi cuerpo y a mi alma,
pero sería muy desagradecido si no reconociera que el Señor me sostiene en ambas cosas,
y al menos en apariencia, me concede Su bendición. Hacia el final,
experimenté ataques de fiebre y cogí tal resfrío,
que mi voz escasamente podía ser oída. Entonces,
el Señor me mostró que debía regresar a casa.
Pero por la mañana, hacia las ocho, cuando estaba a punto de montar en mi caballo,
encontré al menos a veinticinco personas reunidas,
a quienes sólo pude dirigirles una muy breve palabra.
Algunas de ellas habían llegado desde varias millas de distancia,
porque estaban en el campo.
Puedes ver por medio de esto, cuán extraordinaria es mi presente manera de vida,
y cuán opuesta es a mis inclinaciones.
Mi ardiente amor por el retiro y el reposo parece
haberme sido dado para hacer más pesado lo contrario,
y tal vez,
para que también sirva como contrapeso y me guarde de entrar
demasiado hondo y vivir mucho en los ejercicios externos.
En todas partes encuentro hambre entre las personas, y no hay quien les brinde alimento;
la comida acostumbrada ya no los satisface.
El que tenga gracia para orar, que le ruegue al Señor de la mies,
que envíe obreros a Su mies.

3 de octubre de 1747

Después de que sus predicaciones públicas habían sido descontinuadas durante algún tiempo,
por el año 1750 se despertó un joven estudiante de Duisburg,
y celebró reuniones en Spelldorf, Styrum y también en Mülheim,
en donde llamó fervientemente a las personas al arrepentimiento.
Por este medio muchas de ellas fueron llevadas a
una saludable preocupación por sus almas,
y muchas fueron a Tersteegen para exponerle sus estados pecaminosos,
y para ser instruidas por él en el camino de santidad.
Su conversación tuvo tal bendito efecto sobre muchas,
que a través del sincero arrepentimiento obtuvieron fe en nuestro Señor Jesucristo;
y por Su gracia, han continuado firmes hasta hoy.
Los relatos que él hizo sobre este tiempo en diferentes ocasiones,
en confidencia a una amiga, merecen ser vistos aquí.

Por algunos días me he sentido otra vez bastante mal,
y creo que es por el resfrío que cogí, o tal vez también,
por el poco descanso que he tenido durante las últimas tres o cuatro semanas;
porque el despertar que parece haber tomado lugar en varias personas,
me ocasionan muchas visitas.
Como el segundo día de Navidad me sentía bastante bien,
sentí la libertad de ir a una reunión y predicar un sermón,
algo que no había hecho por más de un año. Nunca había visto
tantos presentes aquí en una ocasión similar.
Por este sermón,
parece que ocasioné que me visitaran aún más. Siento que debo gastarme y ser gastado.
Sería algo insignificante poner la salud e incluso la vida misma en la balanza,
con el fin de cumplir la buena voluntad de Dios y ser de utilidad para los demás;
pero confieso que no tengo certeza en este asunto.
Hago lo que puedo en el momento, y le pido perdón a Dios,
no sea que haya sido de algún modo perjudicial para otros.
Una cosa sé,
que si yo siguiera mi propia inclinación y encontrara la libertad de hacerlo,
preferiría retirarme por completo.
¡Que el Señor nos dirija en todas las cosas!

14 de enero de 1746

En otra carta dice:

Hay, gracias a Dios,
un gran despertar y agitación entre las personas aquí. Por algunas semanas seguidas,
desde la mañana hasta la noche, se vieron obligadas a esperar, una detrás de otra,
para tener una oportunidad de hablar conmigo.
Muchas tuvieron que regresar cinco o seis veces,
antes de que pudieran encontrar un cuarto de hora para conversar a solas conmigo;
y en ocasiones, tuve diez,
veinte e incluso treinta almas ansiosas conmigo al mismo tiempo.
Los sermones de N+++_____+++, aunque sencillos,
son de ventaja para aquellos que son despertados por estos medios.
A su solicitud, y de muchos que estaban hambrientos del pan de vida,
me permití ser inducido a celebrar una reunión con él a principios del presente mes.
Hacía mucho tiempo que no hablaba en público.
Se reunieron tres o cuatrocientas personas;
y como la casa estaba llena desde la misma puerta,
colocaron escaleras contra las ventanas para poder oír. Esto produjo una gran sensación,
y confío en que no haya sido sin bendición. Nuestros clérigos, los tres Reformados,
así como también el Luterano,^
footnote:[La iglesia Protestante en Alemania está dividida bajo dos cabezas,
los Luteranos y los Reformados.]
dieron la voz de alarma sobre esto.
Dos de los primeros fueron a ver a los magistrados para presentar sus quejas,
y rogaron que se pusiera fin a las reuniones.
Yo no sabía nada de esto, pero sospeché algo por el estilo,
y me sentí obligado a escribirle a nuestro juez de paz,
con el fin de darle cuenta de nuestra reunión y pedirle
que no tuviera nada que ver en el asunto.
Y en efecto,
el secretario ya había recibido la orden que debía ser copiada y publicada al día siguiente.
El juez, quien me tiene mucho afecto y no sabía que yo estaba involucrado en el asunto,
hizo que la orden fuera devuelta desde la secretaría,
y me la envió privadamente con una carta muy amistosa escrita de su puño y letra.
Tras lo cual, les escribí a tres de nuestros ministros y les hablé,
de manera seria aunque amigable, de su comportamiento desagradable, ofreciéndoles además,
junto con N+++_____+++, hablar en presencia de ellos,
con la seguridad de que si daban su sincero consentimiento,
la iglesia se llenaría de nuevo,
porque la gente vería entonces que ellos estaban unidos a la buena causa; mientras que,
por el contrario, en la actualidad la iglesia permanecía vacía. Entonces,
parece que ellos confiaron en el alcalde, quien era enemigo de las reuniones.
Por lo tanto,
le escribí una carta bastante fuerte y le expuse cuán contradictoriamente actuaría,
si prohibía reuniones de esa naturaleza, y al mismo tiempo permitía curanderos,
charlatanes, casas de juego y tabernas;
preguntándole cómo esperaba reflexionar sobre estas cosas en su lecho de muerte.
En resumen, el alcalde, así como también los otros magistrados,
cedieron y reconocieron que yo estaba en lo correcto.

1 de enero de 1751

En otra ocasión escribe:

El despertar aquí y en otros lugares, continúa. Cada vez se añaden más,
y me veo obligado a dedicarme casi desde la mañana hasta la noche,
a conversar con personas piadosas, sea individual o colectivamente.
Desde la última vez, sólo he hablado en una ocasión fuera de casa en una reunión pública.
Considero que había cuatrocientos oyentes.
Estoy ocupado constantemente con un individuo o con varios a la vez.
El pasado jueves, a las ocho, cuando apenas me había levantado de la cama,
y eso a duras penas, para responder una carta que había recibido en entrega inmediata,
me avisaron que estaba entrando en la casa toda una tropa de campesinos,
que deseaban hablar conmigo; y antes de que hubiera pasado media hora,
se habían reunido casi cincuenta, que me pidieron que les predicara,
lo que hice en consecuencia de Isaías 55:10 etc.
Mientras hablaba, una poderosa emoción se manifestó en el auditorio,
y si yo no la hubiera evitado de manera imperceptible e indirecta,
se habría producido una confusión,
porque dos personas fueron presa de un violento temblor y se tumbaron en el piso;
pero este tipo de cosas, si me es posible, trato de detenerlas en silencio.
Durante el sermón, uno de nuestros predicadores llegó a visitarme,
y abajo se le dijo que yo me estaba dirigiendo a
un número de amigos que habían llegado inesperadamente,
y se le pidió que subiera las escaleras y me oyera hablar,
ya que al parecer tenía prejuicios contra tales reuniones.
Al oír esto se ofendió y preguntó quién había dicho
que él tenía algo en contra de que yo hablara,
y se fue.
Pero esa misma tarde regresó. Le dije que yo había hablado en la mañana, y de qué texto.
Ante lo cual, me aseguró que él no tenía nada en contra de que yo hablara;
que ellos de buena gana me darían permiso, pero no N+++_____+++, etc.

Anteriormente,
me había negado a admitir tal número de personas un domingo durante el servicio,
por lo que parecía que se habían unido para tomarme por sorpresa.
Después de hablar, les permití a algunas de ellas,
que estaban en un estado de gran ansiedad sobre sus almas, conversar conmigo en privado.
Entre esas había una viuda que parecía terriblemente agitada.
Ella se lanzó a mis pies sobre el piso,
pero yo inmediatamente le dije que se pusiera de pie.
Ante esto, ella me confesó sus pecados sin que yo se lo solicitara,
los cuales reconocí que eran grandes.
Como me pareció que ella estaba en gran desesperación,
la animé a decirme todo lo que estaba en su mente,
asegurándole que yo mantendría el secreto.
"`¡Qué!,`" dijo ella, "`¿mantenerlo en secreto?
¡Cuéntaselo al mundo entero!
Yo no temo ser deshonrada ante la opinión de la humanidad.
Gustosamente soportaría los tormentos más severos, y estoy dispuesta a ser consumida,
incluso hasta convertirme en un esqueleto,
con tal de encontrar el favor ante los ojos de Dios.`"
Puedes formarte una idea de lo que se tiene que hacer y sufrir,
entre tantas pobres almas de este y de los lugares vecinos.

Niños de diez, doce y catorce años se están despertando.
Sólo me referiré a un ejemplo.
Una mujer que un tiempo antes había sido despertada y estaba preocupada por su alma,
vino recientemente a verme junto con otras catorce personas,
y trajo con ella a su hijo que tenía cerca de once años. Después de estrecharle la mano,
antes de que partiera con los demás, también le di al niño mi mano,
y le pregunté si él también deseaba convertirse en un joven piadoso,
añadiendo unas pocas palabras en concordancia con la capacidad del niño;
pero parecía que él no deseaba escucharme.
Sin embargo, al llegar a la casa le dijo a su madre:
"`El diablo me quiso estorbar para que no atendiera a lo que Tersteegen decía;
sin embargo, escuché cada palabra muy bien y resistí al diablo, etc.`"
Desde ese momento, el muchacho se ha vuelto muy silencioso,
y a menudo se va sólo a los campos o a cualquier otro lugar,
donde puede esconderse para orar; y llora en secreto por sus pecados, de manera tal,
que incluso su padre, que antes se oponía a la verdad,
parece estar muy afectado y golpeado por ella.

En estas ocasiones, debo esforzarme fuertemente para evitar hundirme.
No puedo negar que el Señor ha sido bueno y misericordioso conmigo de varias maneras,
y que me ha concedido más paz interior y entrega de corazón,
en medio de cada perturbación y distracción de afuera,
de las que habría podido esperar alguna vez; pero en cuanto a las emociones agradables,
no puedo decir nada; a veces vivo como si estuviera muerto.

23 de febrero de 1751

Además escribe lo siguiente:

Desde mi última carta, la gente apenas me deja descansar.
Ocasionalmente trato de retirarme a la fuerza, pero es en vano.
El pasado domingo, escasamente me había levantado de la cama,
cuando me vi obligado a dirigirme a más de sesenta
personas que se habían agolpado dentro de la casa,
lo que hice a partir de Mateo 25:5. Después de que había hablado,
tuve que conversar con varias personas hasta la noche.
Y ayer por la mañana, después de que había pasado la noche con fiebre,
al menos doscientas cincuenta personas se reunieron
en el granero y en la habitación contigua,
a quienes les hablé, con la misericordiosa ayuda del Señor,
de Gálatas 1:3-5. También me he visto obligado a hablar esta mañana temprano,
sin saberlo un cuarto de hora antes; y ahora me siento bastante cansado.
Hoy hablé de las últimas palabras del Señor Jesús:
"`¡Consumado es!,`" y me he consolado con la esperanza de
que mis fatigas y dificultades también terminarán pronto.
Sin embargo, ahora espero arreglar los asuntos de manera tal,
que me vea libre de la necesidad de pronunciar un sermón formal.
Si las reuniones se celebraran regularmente, no encontraríamos suficiente lugar.
Entre una y otra me dedico a recibir visitas,
o a escribirles a los amigos que están lejos.

9 de abril de 1751

En otra dice:

Desde mi última carta han ocurrido eventos tan extraños,
que no he podido responder tu agradable carta del 9 de julio antes de hoy.
Ya has sido en parte informada por nuestro amigo S+++_____+++,
de lo que sucedió durante mi viaje al ducado de Berg,
donde estuve detenido una semana más de lo que yo había previsto,
como consecuencia del número de personas que se congregaban.
Me vi obligado, en contra de mi deseo, a hablar ahí varias veces en público.
Después de mi regreso, reflexioné en un plan para aligerar la carga en alguna medida;
para lograrlo, decidí celebrar una reunión cada quince días, si el Señor lo permitía,
porque de otro modo,
me vería en la necesidad de hablar tan a menudo como las personas me llegaran a ver.
Pero como ellas saben en sus propias mentes cuándo me propongo hablar,
la asistencia es tan numerosa que no tengo dónde acomodarlos.
El día después de la partida del señor S+++_____+++ de aquí, el número aumentó,
de modo que no tenía espacio suficiente,
aunque pude acomodar a cerca de seiscientas personas;
pues llegaron de distancias hasta de quince o veinte millas con
el ferviente deseo de oír. Los magistrados ya dieron la alarma,
pero ya pasó.

Yo les dije, que si ellos tenían la libertad de consciencia de prohibirme hablar,
en ese mismo instante me encontraría en la libertad de obedecerlos, cosa que no haría,
si tuviera la certeza de haber sido llamado divinamente a hacerlo.
Ellos respondieron que no tenían el deseo de impedírmelo,
pero que la gente que se congregaba era demasiado numerosa.
Yo les respondí, que yo no les pedía que vinieran, ni le diría a ninguna que se fuera.
Finalmente, estuvieron dispuestos a dejarme hablar, no así N+++_____+++ y otros.
Me mantengo tranquilo; en realidad, no fui a ver a los magistrados por causa mía,
ni porque me mandaran a llamar; sino voluntariamente,
y para evitar el mal que iba a caer sobre otros.

20 de agosto de 1751

En una carta posterior le dice a la misma persona:

Todavía tengo algo particular que relatar.
El día después de que envié la última carta,
los amigos de C+++_____+++ enviaron inesperadamente un coche a las orillas del Rin para recogerme.
Como estaba muy débil y confinado en la cama,
envié a nuestro amigo S+++_____+++ allí con una nota; y decliné por completo ir.
Entonces los amigos vinieron aquí con el coche,
y al día siguiente me vi obligado a acompañarlos.
Tan pronto como se informó que yo estaba en el pueblo,
el Consejo Directivo Menonita se reunió, sin que yo me diera cuenta,
y me enviaron a sus dos predicadores a pedirme que
fijara un día para predicar en la iglesia de ellos,
ya que sabían que yo me quedaría hasta el domingo.
La petición, como puedes fácilmente suponer, me pareció extraña; sin embargo,
decidí aceptarla en el nombre de Dios, como indicación de la voluntad divina.
El miércoles 25 de agosto por la mañana,
los ministros llegaron y me condujeron al púlpito.
Al entrar en la iglesia, la encontré llena de personas de todas las persuasiones,
pero principalmente de las persuasiones Reformada y Menonita;
y el Señor me capacitó para hablar de 2 Pedro 3:2. Si le
he agradado a Dios con esta temeridad tanto como a los oyentes,
todo irá bien.
Las personas estaban profundamente afectadas, y algunas tanto,
que es de esperar que las impresiones sean duraderas, etc.

A medida que aumentaba el número de los despiertos y de los hambrientos del pan de vida,
nuestro difunto amigo era inducido una y otra vez a hablar en público.
Todavía viven muchos que pueden atestiguar, con cuánta impresión,
poder divino y unción lo hacía. En 1751 escribió
su sermón sobre las palabras de 2 Corintios 5:14,
"`El amor de Cristo me constriñe,`" y lo publicó.^
footnote:[Una traducción de este sermón se encuentra en el cuerpo de este trabajo.]
Con lo cual, la demanda por sus sermones era tan grande,
que ocho escritores se colocaban en las escaleras, donde podían oír claramente,
y escribían las palabras que salían de sus labios.
Por este medio se recopilaron treinta de sus sermones,
y posteriormente fueron publicados bajo el título Spiritual Fragments (Geistliche Brosamen.)^
footnote:[Fragmentos Espirituales (Geistliche Brosamen.)]
Las siguientes cartas dan cuenta de los muchos sermones que predicó,
y de las visitas que tuvo que recibir en ese tiempo.

Hasta el día de hoy apenas puedo usar mi cabeza o mis ojos, y mi mano tiembla mucho;
el poco descanso que he tenido debido a la afluencia de personas,
puede ser la razón principal de ello,
a lo que también se debe añadir las muchas cartas que tengo que escribir.
No puedo pensar qué buscan las personas en una criatura tan pobre.
Hace poco, una persona totalmente desconocida para mí, pero un verdadero Natanael,
vino a visitarme tras caminar doscientas millas a pie, con mal tiempo,
y a quien sólo le pude dedicar un par de horas;
pero ¿quién puede retirarse completamente en tales ocasiones?
El 25 de febrero recibí nuevamente la visita de unas doce personas del campo.
Tan pronto como nuestros amigos aquí se enteraron, se llenó la casa,
de modo que tuve que dirigirme a cientos de personas sobre el cántico de Simeón: "`Ahora,
Señor, permite que Tu siervo se vaya en paz, conforme a Tu palabra;
porque mis ojos han visto Tu salvación`" Lucas 2:29-30. Algunos dicen,
pero ignoro por qué razón, que he predicado mi propio sermón fúnebre.

Es al menos mi deseo,
apartarme de toda consolación humana y encomendarme
completamente a la guía del Espíritu de Dios,
y ser hallado exclusivamente esperando la salvación de Israel.
Si yo tuviera incluso la justicia, piedad,
revelaciones de Simeón y los dones que él poseía, yo, con él,
de buena gana los habría olvidado y abandonado, vivo o moribundo,
con el fin de cambiarlos por el niño Jesús, la única consolación de Israel.
Es motivo de asombro, adoración y deleite,
ver cómo el Señor puede inducirnos a dejarlo todo.
Todo parece tan frívolo, insatisfactorio, trivial y superficial,
incluso las cosas buenas y espirituales que anteriormente nos proporcionaban
tanta gratificación y de las que éramos muy tenaces,
pero que, por esa misma razón, sólo servían para interponerse entre nosotros y Dios,
y eran perjudiciales porque las sosteníamos muy firmemente.
Jesús solo es suficiente, y sin embargo insuficiente,
cuando no es completa y exclusivamente abrazado.
¡Oh,
que le plazca al Señor confirmar y establecer los corazones de
todos aquellos que están preocupados por sus almas inmortales,
y les permita encomendarse enteramente a la guía e influencias de Su Espíritu Santo,
quien a Su debido tiempo, los conducirá al verdadero templo de Dios,
donde podrán estrechar sustancialmente al Salvador en los brazos de sus espíritus!

20 de marzo de 1753

Contemplé la cercanía de la Navidad con sentimientos de ansiedad,
estando temeroso de recibir muchas visitas, y por eso,
ocasionalmente daba a conocer que estaba demasiado
indispuesto para tener compañía. No obstante,
unos pocos días antes de Navidad, me sentí algo mejor;
entonces vinieron de lejos muchas personas que no esperaba,
y entre ellas había varias a quienes no había visto antes.
El Señor me permitió hablar con mucha compostura en dos ocasiones diferentes,
sobre Isaías 9:6, "`Porque un niño nos es nacido,
etc.,`" aunque durante la noche había estado con mucha fiebre.
El lugar estaba bastante lleno de personas,
y entre ellas estaba presente el magistrado principal.
Él había mandado a preguntar si yo tenía la intención de hablar;
le respondí que pensaba hacerlo; con lo cual,
envió a su sirviente a pedir que se le reservara un asiento.
Después del sermón, me dijo, entre otras cosas:
"`No se me escapó ni una sola palabra y te escucharé mañana.`"
Él se refirió a las divisiones del sermón, y me aseguró que estaba muy complacido.
También escuché que le dijo a otros: "`Los que injurian, sólo deben hacer como yo,
venir y oír por sí mismos.`"

No puedo decir que tenga algún presentimiento o impresión
particular en mi mente de parte de Dios,
con respecto a mi partida de este mundo.
Hablo y pienso según siento en el momento,
o según contemplo con el ojo de la razón las consecuencias de esta o aquella enfermedad,
aunque en tales ocasiones, a menudo quedo muy corto de la verdad,
y no puedo comprender la maravillosa manera con la que el Señor trata conmigo.
¡A Él sea la gloria!
El gran número de amigos aquí y en otros lugares, me ocasiona continuo trabajo,
y encuentro difícil apartarme de ellos,
especialmente de las personas enfermas y afligidas, por las que me tomo el riesgo.
Como somos un espectáculo tanto para los ángeles como para los hombres,
y como fácilmente se puede suponer que ocurren toda clase de casos,
no siempre puedo ser indulgente conmigo mismo, ni cuidar de mí mismo.
Se me ocurre decirte, que en nuestra última reunión, que fue la primera del presente año,
me expresé de la siguiente manera en el saludo de año nuevo: "`Si es, pues, mi porción,
continuar un poco más como una pequeña y brillante
estrella en el firmamento de esta nuestra iglesia,
no me retiraré del todo.
Sé lo que soy y cuánto dependo completamente del Señor, pero ni el temor del hombre,
ni las sugerencias de la carne, podrán detener mi boca.
Espero que las consciencias de todos ustedes testifiquen ahora,
y en la presencia de Dios, que los he dirigido a Cristo y no a mí mismo.
Denme, entonces, como en la presencia del Señor, la mano de la comunión nuevamente,
y apóyenme por medio de sus intercesiones y su fiel caminar con Dios.
Sin embargo, aún debo decir, mis queridos amigos,
que durante el año pasado algunos entre ustedes me
afligieron a menudo hasta el corazón y me desanimaron;
eso no fue correcto; ¡que el Señor lo expíe!`"

Estas últimas palabras conmovieron a algunos de ellos,
quienes después llegaron a pedir perdón.

Alrededor del año 1756, cuando la asistencia era tan numerosa,
que se veía obligado a alcanzar cinco o seis habitaciones de la casa con su voz,
nuestro difunto amigo sufrió una lesión corporal debido a su esfuerzo al hablar;
lo que lo obligó a interrumpir sus sermones públicos y sus viajes al campo,
excepto por una cabalgata ocasional por los alrededores de Spelldorf, Duisburg y Essen,
para darle a su debilitado cuerpo un poco de ejercicio,
y al mismo tiempo visitar a sus amigos ahí. Cuando hacía buen tiempo,
en primavera y verano,
también hacía un poco de ejercicio a pie en compañía de otros pocos inválidos,
especialmente cuando era visitado por amigos del campo.
Él, generalmente iba con ellos a un bosque que estaba a poca distancia, donde tomaban té,
mientras oían su edificante conversación, y ocasionalmente cantaban un himno,
después de lo cual terminaban con una oración.

Aquí podríamos terminar la historia de la vida de Tersteegen,
e inmediatamente seguir con el relato de sus últimos momentos, pero no cabe duda,
que será de gran utilidad para el lector,
si en alguna medida lo colocamos en condiciones de conocer mejor sus dones especiales,
la notable gracia que le fue impartida,
y la espiritualidad de sus opiniones y sentimientos.
Sus escritos, en especial sus sermones,
impresos bajo el título de "`Fragmentos Espirituales,`" en los que el lector
no es detenido por mucho tiempo con la cáscara de la sabiduría humana,
sino que es llevado de inmediato al grano,
muestran suficientemente cuán iluminado estaba su entendimiento,
y el profundo conocimiento de la palabra de Dios que le había sido concedido.

Sus escritos también evidencian, de manera igualmente luminosa,
su íntimo conocimiento de Dios y Sus caminos.
Entre otros que podrían mencionarse,
se dirige al lector a ese magnífico himno que comienza: "`Oh, Dios,
Tú no eres conocido correctamente,`" y a otro que escribió algunos años después:
"`Alégrense, el Señor es Dios supremo.`"
En ambos, cuando las divinas y elevadas opiniones del escritor, su ser,
características y perfecciones son contempladas en silenciosa devoción,
se encontrarán las más hermosas evidencias de su conocimiento por experiencia.
Él podía decir, y en varias ocasiones hizo uso de la muy sugestiva expresión:
"`Le agradezco a Dios que me haya permitido vivir
el tiempo suficiente para llegar a conocerlo;`" palabras,
que entre otras,
le repitió con gran énfasis a un amigo que le daba el último
adiós--cuando se encontraba enfermo en el año 1738,
y sin la más mínima esperanza de recuperación--y añadió: "`Con respecto a mí mismo,
estoy perfectamente tranquilo en Dios, y también con respecto a mis escritos,
los cuales te dejo.
Con respecto a ellos, no siento ningún tipo de ansiedad o reprensión interna,
como si tuvieran algo dudoso o erróneo.
Todo lo que he escrito, yo mismo lo he experimentado como verdades importantes,
y por ello, puedo entrar en la eternidad con consuelo.`"

En otro lugar escribe: "`Cuando deje este mundo,
entraré al siguiente como una criatura pobre e indigna,
que desea y confía plenamente en ser aceptada sólo a través de la gracia,
y de manera más que la usual.
Mientras tanto,
le agradezco a Dios que me haya permitido vivir tanto
tiempo como para llegar a conocerlo internamente;
esto, a pesar de mi miseria, no lo niego,
y por esto deseo alabar la gratuita gracia de Dios.
Anhelo una eternidad para poder alabarlo adecuadamente por Su gracia.
¡Oh, qué tesoro es dejar a un lado toda luz espiritual y los dones de la gracia,
con el único fin de conocer que Dios es lo que es; que conocerlo a Él es, en efecto,
vida eterna!
El deseo de los hombres por tener mucho conocimiento, incluso de las cosas espirituales,
es una poderosa prueba de que no conocen a Dios en realidad.
Dios es en todos los sentidos todo-suficiente;
sólo Él puede satisfacer y alegrar las amplias capacidades del alma,
y eso entera y eternamente.`"

No puede ser sino agradable para el lector,
que se le presenten los siguientes extractos de ciertas cartas de nuestro difunto amigo,
como obvios testimonios de su conocimiento superior y por experiencia.

Te informo en este momento, que le ha placido al Señor visitarme con una enfermedad.
Al principio de mi condición, yacía y me sentaba estupefacto, sin sentimientos, incluso,
casi sin ningún recuerdo de Dios o de mi propia alma.
Actualmente mi mente es conducida con silencioso
placer a contemplar la existencia de Dios,
Su bondad, sabiduría, poder, santidad, etc.;
todas estas infinitas perfecciones son en grado sumo amorosas y adorables,
de modo que es verdad, que Dios y lo que hay en Él, y todas Sus obras y caminos,
son el alimento y la felicidad propios de un espíritu creado.
En Él está todo mi tesoro.

1 de febrero de 1746

Sabemos que sólo Dios es supremamente bueno;
que Él soporta a Sus criaturas y a Sus hijos en Cristo,
los prepara para disfrutar de Él mismo con incomprensible misericordia,
y los ama con especial ternura.
Nosotros, sin embargo, estamos tan inclinados a descansar en nosotros mismos,
y a volvernos hacia nosotros mismos, que a menudo me asombro de mi propia debilidad.
He ido a la escuela por mucho tiempo con el mejor de los maestros,
y ya estoy empleado para darles a otros sus lecciones, y sin embargo,
sigo siendo un infante indefenso.
En la actualidad, según todas las apariencias, puedo en sencillez de corazón,
encomendarme a mí mismo y todo lo que tengo al Señor. Puedo dejarlo todo,
y aún sentirme tranquilo.
Soy pobre, y sin embargo, en un lugar rico.
Estoy débil, pero contento.
Esos trabajos, fatigas, aflicciones, pruebas y peligros,
que en otro momento me parecerían insuperables si
el Señor no me impidiera contemplar el futuro,
puedo olvidarlos fácilmente ahora, y no me causan aquella ansiedad mental,
que normalmente es tan característica en mí. Pero
no debo representar el cuadro demasiado bonito;
tal vez parezca diferente ante los ojos del Señor. Se lo dejo a Él, sea como sea.
Importa poco cómo sea, si es como Dios quiere.
No puedo ni quiero depender de nada excepto de Él.

9 de febrero de 1748

Si yo tuviera que explicarte cómo me siento en mi estado de debilidad,
te diría que no lo sé; y tal vez nunca haya sido menos consciente de éste.
Creo profundamente en la total insuficiencia del yo y de todo bien creado,
tanto interna como externamente; pero en el fondo, no estoy intranquilo, ansioso,
ni asustado, aunque no sé la razón de ello.
Por motivos de la debilidad de mi cabeza,
a menudo soy incapaz de pensar en Dios o en mi propia alma; pero sé que Dios existe,
que Él es el grande, bueno y siempre bendito Dios.
El mero recuerdo de esto, cuando el Señor me lo concede,
me refresca mucho y hace que toda dificultad desaparezca inmediatamente.
¡Cuánto debemos regocijarnos de que Él sea un Dios así; que sea todo bondad, perfecto,
infinitamente glorioso y feliz,
y suficiente para hacer que todo en nosotros sea bueno y feliz!

8 de marzo de 1748

¡Cuán maravillosos,
cuán incomprensibles son los caminos de Dios! ¡Cuán contrarios a nuestras expectativas!
Tan pronto como pensamos en recuperar un poco el aliento, somos nuevamente confrontados.
Nunca dejamos de perder,
hasta que nos volvemos tan pobres que ya no tenemos nada más que perder;
y tan avergonzados, que ya no nos atrevemos a mirar a nuestro alrededor.
¡Perseveremos sólo en el nombre de Dios! ¡Que sólo Él sea exaltado,
glorificado y complacido, para que al abandonarnos por completo,
podamos entrar a Su felicidad, Su reposo, Su gozo!
Debemos ser llevados finalmente,
a mirar las cosas tan inocentemente como un bebé en la cuna.
Nos conviene afirmar alegremente, adorar profundamente y decir cordialmente:
"`El Señor es bueno y misericordioso;
todos Sus caminos son misericordia y verdad,`" sin examinar sobre qué está fundada
la expresión. Aún en plena consciencia de nuestra total pobreza y miseria,
no podemos evitar desear que todas las almas sean igualmente pobres.
¡Oh, cuán raramente nos encontramos con aquellos que son completamente de Dios,
y cuán felices son tales personas!
El Señor de buena gana se convierte en la porción, el tesoro y el todo de ellos.
Mi más sincero deseo es que este sea nuestro caso.
Ora también por mí, mi querida hermana, y ruega al resto de tu familia que haga lo mismo,
porque lo necesito.

22 de octubre de 1751

Me pierdo en adoración,
cuando pienso que el camino que Dios ha escogido hacia la felicidad eterna,
quita todo de la criatura y lo da todo a Dios, y en consecuencia,
dulcemente nos obliga a unirnos más estrechamente a Él, a permanecer y vivir en Él,
a depender de Él,
y a continuar siempre pobres para que podamos poseer en realidad todas las cosas;
un camino para niños,
pero sólo para niños desnudos--un camino que el sabio pasa por alto.
Mientras queramos poseer y retener, el camino será estrecho; y el que lo busque de lejos,
pasará de largo; pero el que sigue la pista del amor que se le lanza, lo encuentra cerca.
¡Que el Señor Jesús mismo les proclame a los pobres el año agradable!

Rara vez nos vemos cara a cara,
pero aun así nuestros corazones nos dicen que nos pertenecemos el uno al otro,
y que pertenecemos a una misma familia.
Nuestros corazones se gozan de que todavía estemos juntos en el camino,
y de que poseamos el uno en el otro lo que poseemos; al menos así lo encuentro en mí;
y además de Dios, lo atribuyo a las oraciones de Sus hijos que yo siga siendo lo que soy.
Dios debe ser el bien todo suficiente;
porque sé que todos los que por experiencia han llegado a conocerlo un poco,
no pueden hacer otra cosa más que amarlo y alabarlo cordialmente,
aunque después caminen por años seguidos en esterilidad y tinieblas.
Yo, de hecho, puedo decir algo sobre este tema,
pues en ocasiones he tenido que suspirar bajo mi carga a lo largo del camino,
encontrándola a veces muy pesada de llevar;
y la parte más pesada de ella se ve muy poco externamente.
En la actualidad, tengo mucho que soportar, tanto interna como externamente,
aunque los que me oyen, podrían ser llevados a suponer que gozo continuamente de sol.
Sin embargo, qué puedo decir de Dios sino que es bueno,
que en las más severas pruebas de la fe puede sostener el alma, y que en verdad lo hace,
para que no desmayemos en el camino.
(1 Reyes 19:8) Aquel que se encomienda completamente a Dios y le confía todo a Él,
nunca quedará corto; y cuando lo hacemos, lo honramos.
En nosotros no hay nada sino debilidad y miseria,
pero en Jesús hay abundancia de todo lo que necesitamos.
¡Cuán cierto es esto, y sin embargo,
sólo se experimenta en el grado en que la debilidad y la miseria sean realmente sentidas!

8 de marzo de 1754

¡Hasta aquí me ha ayudado el Señor!
Y Su ayuda hasta este momento me anima a esperar que Él me ayudará hasta el fin.
¡Qué Dios tan bueno y fiel! ¿No deberíamos amarlo totalmente,
arriesgarlo todo en Su nombre,
y con los ojos cerrados encomendarnos ciegamente a Su guía? El Señor sabe
muy bien que nuestros corazones se pueden vencer mejor por medio del amor,
por cuya razón hace tanto por nosotros; y cada uno de nosotros puede por sí mismo,
echarle un vistazo a la larga cuenta de amorosa bondad y fidelidad de Dios.
Dios muestra Su amor hacia nosotros en tantos detalles,
y éste es Su último y más grande intento para recuperar al hombre.
Si el amor de Dios y las bendiciones que fluyen de él no
nos constriñen a un amor recíproco y cordial hacia Él,
y a un progreso valiente en el camino de santidad,
ciertamente ningún otro medio lo logrará. Mi corazón
todavía rebosa de gratitud por toda la bondad,
refrigerio y sostén divinos que he disfrutado en mi último viaje y en
tu compañía--es esto lo que me inclina a escribir de esta manera;
y observo por tus tiernas cartas, mi querida hermana, que tú y otros sienten lo mismo.
¡Que el Señor mismo afine nuestros corazones para
alabarlo y glorificarlo en todas nuestras acciones!
Siento que más de mi corazón permanece contigo que antes,
y que la ausencia corporal no nos separa, ni puede separarnos.

5 de julio de 1754

No puedo expresarte, querida hermana,
cuán inútiles y despreciables me parecen esta vida y las cosas del tiempo,
y con frecuencia me aflijo como un niño, de que la humanidad,
e incluso las personas piadosas, sean tan triviales y no empleen mejor su tiempo.
A menudo me duele ver que Dios, que es un omnipresente bien, sea tan poco buscado,
conocido, amado y glorificado como se merece.
En un momento la compasión me hace hablar de ello;
y en otro me siento inclinado a renunciar a todo,
a fin de no perder mi propio tiempo y vivir más para Dios y la eternidad.
Pero la voluntad de Dios debe ser mi comida y mi bebida.
Con frecuencia puedo perderme en ella, y olvidar todo mi dolor infantil.
Todavía hay bastantes personas por aquí en quienes
puedo pensar con gozo y con gratitud a Dios.
En verdad el Señor es bueno y misericordioso con Su pueblo.
Él es hermoso en Sí mismo y hermoso en Sus hijos.
(Salmo 16:2)

1 de noviembre de 1754

Sus puntos de vista de las verdades evangélicas que
pertenecen a la economía de la redención humana,
eran tan puros como grandes eran su intuición y experiencia.
Para convencerse de esto, sólo se necesita leer en conjunto sus escritos,
particularmente The Way of Truth,^
footnote:[El Camino de la Verdad]
con una mente imparcial.
Incluso, al principio de su conversión,
él contemplaba las verdades fundamentales de la religión en la luz pura y escritural.
Lo siguiente son pruebas de esto.
Una persona fidedigna, que aún vive, relata que la primera vez que lo visitó en 1727,
la acompañó parte del camino de regreso, y al despedirse de él,
le recomendó expresamente las siguientes cuatro cosas: La expiación de Jesús,
las palabras de Jesús,
el Espíritu de Jesús y el ejemplo de Jesús. Una prueba
obvia de que dirigía a aquellos con quienes se asociaba,
solamente a Jesucristo, y Lo proclamaba en todo momento,
como la única causa procuradora de nuestra salvación y completa redención. Otro ejemplo:
Una vez cierto individuo lo acusó de que sus puntos
de vista y sus motivos no eran suficientemente puros,
a lo que él respondió: "`¡Cuán sinceramente me regocijo, cuán feliz me considero,
cuando soy tenido por digno de dar testimonio de las verdades seguras,
esenciales y preciosas de la religión interna,
que es considerada con tanto recelo por muchos piadosos,
así como también por personas impías!
Creo que sería de indecible consolación para mí,
si a la hora de mi muerte y comparecencia ante la presencia de Dios,
yo pudiera proclamar una vez más a todo el mundo, que sólo Dios es la fuente de vida,
y que no hay otro camino para encontrarlo y disfrutarlo,
sino el camino estrecho de la oración interna,
la negación al yo y la vida escondida con Cristo en Dios,
abierto para nosotros y consagrado por la muerte del Salvador.`"
Muchos de sus himnos en The Spiritual Flower Garden,^
footnote:[Jardín de Flores Espirituales]
muestran que los sentimientos y opiniones del autor, y el fundamento de su fe,
eran puros y no adulterados.

Él estaba bien cimentado y establecido en las doctrinas de la salvación,
de las que tenía una percepción muy clara.
La perspectiva espiritual que le fue concedida,
tras la experiencia de sus cinco años de oscuridad interna,
permaneció después ininterrumpida,
excepto porque de vez en cuando obtenía más conocimiento práctico de ella.
Si se leen sus cartas detenidamente,
se hallará que prevalece una íntima armonía desde la primera hasta la última,
excepto que las últimas parecen más tiernas y poseen más unción divina.
Nuestro difunto amigo era buscado por todos los partidos, y aun así,
no se unía a ninguno,
excepto a los que sinceramente se esforzaban por
vivir de acuerdo con la palabra escrita de Dios,
y las enseñanzas de Su gracia.
Nunca ocultó la luz y el conocimiento de la verdad que poseía,
incluso cuando eran mal recibidos.
Le escribió lo que sigue a un ministro Reformado,
que había tomado a mal una carta de advertencia contra los moravos.

¿Debo decir lo contrario a lo que siento, como es ahora tan habitual?
He releído y examinado la carta en la presencia de Dios, pero no puedo, no debo,
ni voy a decir, que reconozca que contiene sentimientos erróneos;
aunque todo el mundo (como tú pareces hacer en tu carta),
considere este aferramiento a las verdades fundamentales,
como sectarismo y falta de pobreza de espíritu.
¡Oh, Señor. No permitas que incremente la pecaminosidad que ya ves en mí,
con una infidelidad tan vergonzosa, como la de renunciar o apartarme,
por debilidad o hipocresía,
un cabello del querido depósito de esa verdad que Tú me has encomendado,
porque este u otro buen hombre, o grupo de personas estén opuestos a ella!

Él podía estar así de confiado en la expresión de
sus sentimientos en temas de esta naturaleza,
porque se le había concedido un don particular para probar los espíritus.
Unos pocos ejemplos de esto pueden resultar agradables para el lector.
En sus primeros años,
él fue frecuentemente atacado por espíritus extraños e influencias sobrenaturales,
que atribuía a haberse asociado con algunos que estaban relacionados con ellos.
En este período, cuando dejaba su trabajo para orar en privado,
se apoderaba de él tal temblor, que todos sus miembros se estremecían. Consciente,
sin embargo, por su conocimiento del carácter divino,
de que esto era contrario a dicho carácter, nunca cedió a esa influencia extraña,
desordenada y aterradora, sino que simplemente regresaba a su trabajo.
Después de repetir esto unas cuantas veces, el temblor cesó y la tentación llegó a su fin.

Otro ejemplo: Una mujer que estaba en mal estado de salud,
creía oír una voz sobrenatural que la llamaba a levantarse y orar, pero al ser invierno,
su débil cuerpo apenas podía soportar el esfuerzo.
Por lo tanto, consultó a Tersteegen sobre el asunto,
quien la aconsejó que no se levantara en el frío,
sino que cuando creyera que la llamaban de nuevo, en lugar de levantarse,
reanudara sus devociones en la cama.
Hecho esto, la mujer no oyó más la voz sobrenatural; y otras cosas singulares,
que habían ocurrido anteriormente, también cesaron.
A esto puede añadirse el siguiente relato.

Una vez lo visitó un amigo,
que era muy cercano a una persona que poseía un alto grado de devoción filial con Dios,
pero que había visto muchas visiones extraordinarias,
y a quien le habían ocurrido muchas cosas extrañas. Ella
también decía muchas cosas edificantes y predecía eventos,
algunos de los cuales iban a ocurrir después de su muerte.
El amigo antes mencionado le contó esto a Tersteegen,
quien le dio la siguiente respuesta:
"`No prestes atención a todas esas cosas extraordinarias,
que sólo son peligrosas y tienden a estorbar el crecimiento en la gracia.
Admiro sinceramente el cambio sustancial que la gracia divina ha obrado en ella,
pero tú y yo viviremos lo suficiente para ver que nada resultará de todas esas cosas,
por muy deseables que sean.`"
El resultado confirmó esta opinión. Después de su muerte,
el amigo arriba mencionado lo visitó de nuevo,
y expresó su pesar por no haberle prestado más atención a su consejo; a lo que dijo:
"`Este suceso será útil, y servirá para preservarte en el futuro,
y guardarte de ser arrastrado por cosas singulares y extraordinarias, y dejarlas pasar.`"
El buen hombre, no obstante, no despreciaba los dones extraordinarios, luz o visiones,
sino que su consejo fue, que debían ser cuidadosa y completamente examinados,
porque las personas que se entregaban a ello,
podían ser fácilmente engañadas por la influencia de espíritus extraños.

El don de Tersteegen para probar espíritus se manifestó
particularmente con referencia a los Moravos.
Esa secta de Cristianos se había tomado todas las
molestias posibles para llevarlo a sus principios,
con la esperanza de que muchos otros lo siguieran;
pero Dios no lo dejó sin la asistencia de Su luz,
y le concedió la gracia necesaria para probar a ese pueblo.

El conde Zinsendorff hizo todo lo que pudo para ganárselo.
Al principio lo intentó por medio de cartas escritas a él de la manera más tierna,
que le fueron enviadas abiertas por algunos de los hermanos.
Finalmente, en el año 1737, uno de sus principales maestros, y hombre muy capaz,
llegó donde él, se arrojó a sus pies y le imploró su bendición,
para ganar su afecto de esta manera.
Pero a pesar de todo esto, Tersteegen permaneció firme en sus principios,
y no se dejó engañar por halagos de esta naturaleza.
Por el contrario,
llevó a muchos que ya se habían unido a la secta a un mejor entendimiento,
al exponerles tan claramente las peligrosas consecuencias
que fácilmente podrían levantarse de ella,
que no dudaron en abandonarla.^
footnote:[Al principio,
los Moravos eran culpables de muchas inconsistencias que luego fueron enmendadas.]

Las opiniones que Tersteegen tenía de los Moravos,
provocó una correspondencia desagradable con un amigo suyo,
un ministro Reformado en el norte de Alemania, que estaba relacionado con esa secta.
El 6 de marzo de 1750 le escribió, entre otras cosas, lo que sigue:

Creo que la secta de los Moravos no es agradable a los ojos de Dios;
creo de ellos lo que te mencioné personalmente, y lo que te he escrito al respecto.
Y a fin de ser breve, y no fastidiarte y entrar en detalles,
creo que es verdad y no una fábula,
lo que Abbot Steinmetz dice de ellos en su última publicación, y que tú también conoces;
y por esta y muchas otras cosas, ellos son justamente censurables,
cuya clase de errores e insensateces nunca podré aprobar, ni consentir.
No es porque me avergüence de su presunto nombre,
por lo que no mantengo más correspondencia con los Moravos,
mucho menos para excluir de su sociedad a toda persona bien intencionada,
como tú erróneamente supones; sino en parte,
por repugnancia a sus principales errores que son suficientemente conocidos, y en parte,
por temor a andar por un camino más ancho que el que mi
Redentor y todos Sus santos han pisado y enseñado.

La razón por la que no mantengo más correspondencia
con aquellos que se asocian con los Moravos mucho,
o están relacionados con ellos,
es porque como les escribo en un estilo fraternal y familiar,
afirman por todas partes que me he unido totalmente a ellos,
y porque mis cartas sirven para atraer a su sociedad a los que están unidos a mí, etc.
Este ha sido con frecuencia el caso conmigo y con otros.
Sinceramente espero que poco a poco se den cuenta de su error y se enmienden,
para lo cual el misterio de la cruz interior y exterior,
que les es completamente desconocido,
quizás pueda servirles como una medicina saludable para su humillación. Es cierto
que he recibido información directa de La Haya sobre el estado de las cosas ahí,
y que se han establecido nuevas reglas y medidas con respecto a mejoras.
Sin embargo,
como sus más graves errores no sólo son dados a conocer
al mundo por sus oponentes a través de la prensa,
sino que son audazmente sostenidos por sus principales maestros en un lenguaje inequívoco;
y dado que la burda ligereza de sus ministros y miembros es, por desgracia,
manifiesta e innegable, para oprobio de la preciosa sangre y heridas de Jesucristo,
les resultará difícil librarse de la manera habitual.

La negación rotunda, las respuestas tortuosas, el evadir de manera agradable,
ni siquiera, las mejoras superficiales,
les ayudarán a salir en lo más mínimo del laberinto,
pero si realmente desean devolverle a Dios Su gloria, alcanzar la paz de consciencia,
y encontrar el favor de los hombres de entendimiento, deberán humilde y abiertamente,
confesar y retractarse de sus errores y equivocaciones,
y suplicar perdón por la ofensa que han causado.

A pesar de todo,
él les dejó ver a los Moravos su imparcialidad hacia
aquellos que se convertían a la verdad,
cualquiera que fuera la denominación a la que pertenecieran.
En una importante ocasión, en el año 1741,
se sintió inclinado por la comunidad antes mencionada, que tanto cortejaba su atención,
a expresar brevemente esta imparcialidad en una carta,
de la cual lo siguiente es un extracto:

Mis convicciones y mi religión son estos:
Como alguien reconciliado con Dios a través de la sangre de Cristo,
permito que el Espíritu de Jesús, mediante la obra de la cruz, la aflicción y la oración,
me aleje del yo y de todo bien creado, para vivir seguro para Dios en Jesucristo;
y aferrándome por fe y amor a Él, espero llegar a ser un espíritu con él,
y obtener la felicidad eterna a través de Su misericordia sólo en Cristo.
Tengo la misma religión con todos aquellos que son de la misma mente,
y los amo como hijos de Dios tan cordialmente,
como a aquellos que pertenecen a la misma persuasión
y son de las mismas convicciones que yo.

En otros aspectos, estoy perfectamente satisfecho,
cuando en lo que se refiere a lo no esencial,
cada uno escoge un camino particular para sí mismo que considera
que es el más adecuado para alcanzar el fin que tiene en la mira;
y puedo amar a todos aquellos que no andan en hipocresía y sectarismo.
Por tanto, sinceramente aprecio a todos aquellos entre los Moravos,
que tienen los sentimientos arriba descritos, y estoy unido a ellos como hijos de Dios.
Pero no tengo nada que ver con lo que distingue a
los Moravos del resto de los hijos de Dios;
ni concuerdo con ellos de ninguna manera.
Me aflige mucho que ya hayan tantas divisiones en el mundo religioso,
pero me aflijo mucho más, cuando se crean nuevas divisiones.

Tersteegen manifestó invariablemente esta imparcialidad.
Siendo interrogado en una ocasión por uno de los tres piadosos
ministros Reformados--con quien mantenía una relación muy cercana,
y con quien estaba asociado y mantuvo correspondencia fraternal hasta
su muerte--sobre la religión de las personas que llegaban a verlo,
respondió: "`No les pregunto de dónde vienen, sino hacia dónde van.`"

El íntimo conocimiento de Dios y de la verdad divina que poseía Tersteegen,
influyó en sus sentimientos hacia Él. La presencia de Dios parecía estar profundamente
impresa en su corazón. Él sabía que Dios veía todo lo que pasaba en su interior;
por tanto, le abrió lo más íntimo de su alma a este Sol de justicia, para ser iluminado,
calentado y renovado por Sus rayos.
De ahí que sus acciones no procedieran de una obediencia forzada,
ni de un impulso de su propio espíritu,
sino que eran el resultado de la influencia del amor de Dios.
Además de esto, él se ejercitaba constantemente a sólo dirigir su mirada a Dios,
para que por la contemplación de Él,
pudiera ser cada vez más iluminado y recibir renovado
vigor de la presencia directa de Su Dios y Salvador.
También les recomendaba a otros la presencia divina en el alma como un favor especial,
y al mismo tiempo les recordaba,
que la luz que es de arriba no era el resultado de nuestros propios esfuerzos,
sino que debía ser producida en nosotros por la dulce,
poderosa y vivificante presencia de Dios;
y en todos sus escritos se esforzó tanto como pudo,
por imprimir esto en las mentes de sus lectores.
En esas ocasiones también les recordaba,
que además de la presencia especial de Dios dentro de nosotros,
debíamos igualmente creer en Su presencia universal,
que Dios llenaba el cielo y la tierra, que estaba en nosotros y a nuestro alrededor,
y que tenía Su mano en todos los eventos y circunstancias que nos ocurren.
"`Es cierto que hay épocas,`" decía,
"`en las que Dios retira Su amorosa presencia de nosotros por un tiempo,
o en los que Se esconde de nosotros mediante una adversidad extrema, profunda aflicción,
temor y pavor; entonces, es necesario creer, ante la ausencia del sentimiento,
que Dios está presente, incluso bajo tales circunstancias;
que Su amor paternal domina todas las cosas para nuestro bien,
nos defiende de variedad de males,
y misericordiosamente nos sostiene bajo tales pruebas.`"

Al mismo tiempo vivió en habitual dependencia de Dios y de Su guía,
como se desprende de la siguiente carta:

¡Qué la promesa divina en Oseas 2:6, "`Por tanto,
he aquí yo rodearé de espinos su camino, y la cercaré con seto,
y no hallará sus caminos;`" sea cumplida en nuestra experiencia!
Prefiramos sufrir mil aflicciones con Dios, que andar en nuestros propios caminos,
aunque sólo sea en grado mínimo.
Yo he experimentado el cumplimiento de la mencionada promesa de Dios, en varios momentos,
en varias situaciones y en varias formas.
Al principio, a menudo sentía mucha ansiedad,
angustia y temor después de haberme descarriado,
hasta que me quedaba quieto y era consciente de que
había hecho algo que desagradaba a Dios.
Después, experimentaba un sentimiento interno, que por su unción,
me calmaba y contentaba completamente; y la insatisfacción que hallaba en todo lo demás,
era la barrera, lo que hacía que me volviera de nuevo a Dios.
Actualmente, no puedo decir nada sobre el tema;
paso mi vida de la mejor manera que puedo, y tengo, en general,
poca certeza de si voy bien, y qué es lo que me preserva y cerca mi camino; aun así,
todavía creo que soy realmente preservado.
Cuando puedo estar contento con mi pobreza e insuficiencia,
y con la situación en la que me encuentro en el momento,
me parece que estoy en casa y en reposo.
En tales momentos estoy muy contento,
aunque no sea claramente consciente de la operación de la divina influencia
dentro de mí. Pero si no permanezco en mi estado de nadedad,
o si busco y deseo ser algo más de lo que soy,
me confundo (por así decirlo) en todo lo que hago, y todo me parece sombrío y difícil,
sin saber por qué, hasta que vuelvo.
Esta confusión, dificultad, etc. son, pues, los espinos por los que soy preservado,
cuando más incapaz soy de hacer nada por mí mismo.
Entonces seré con gusto débil, para no correr sin Dios,
a fin de que Su poder y Su gloria se perfeccionen en mi nadedad.
¡Gracias, alabanzas y adoración a nuestro Dios, que es nuestro fiel guía,
y que hace que nos adhiramos cada vez más a las saludables
verdades de nuestra nadedad y de Su toda-suficiencia!

15 de enero de 1745

¡Que Jesús mismo, mediante Su Espíritu,
nos guíe por el camino de toda verdad! (Juan 16:13) Porque somos como niños insensatos,
que cuando se dejan solos, se extravían del camino continuamente,
y no pueden depender de la luz de ayer.
Creo que cada día me vuelvo más tonto e ignorante, y por tanto,
estoy asombrado de que todavía sea bueno para algo, o haga algo de manera apropiada.
Pero la experiencia nos enseñará, que una dependencia incesante de nuestro Guía interno,
nos conducirá absolutamente bien, aunque no nos lo parezca;
y que lo ensuciamos y estropeamos todo cuando no confiamos plenamente en Él,
y deseamos guiarnos por medio de nuestra propia luz y sabiduría.

14 de enero de 1746

Deseo ser hallado fiel y no negligente en aquello que el Señor me deja ver que
requiere de mí. También deseo estar en continua disposición a sacrificar,
abandonar y perder en Dios, por así decirlo, todas mis supuestas buenas intenciones,
buena voluntad y buenas inclinaciones.
¡Oh, cuán profunda paz resulta de voluntariamente dejar ir todo lo que poseemos,
aparte de Dios!
Entonces disfrutamos todas las cosas, mientras no deseamos nada,
o mientras sólo anhelamos a Dios.
Creo y a veces digo: "`¡Qué me priven de todo lo que deseo,
más allá de lo que necesito en este preciso momento y lugar!`"
Los que son naturalmente perezosos e infieles, a menudo se imaginan en dicho estado,
y se esfuerzan por imitarlo, pero sabes tan bien como yo,
que el Espíritu de Jesús es el único que puede impartir verdadera rendición,
y cualquier otra virtud fundamental.
La influencia pura de este poder vivificante, que está extremadamente cerca de nosotros,
es la única que puede destruir el yo,
y suavizar y aplacar el ardiente fuego de la naturaleza,
para que podamos correr con paciencia (Hebreos 12:1)
y sentarnos quietos sin estar ociosos (Juan 11:28-29);
porque de esta manera, Cristo mismo se convierte en nuestra voluntad,
nuestra vida y nuestro deleite.
Por tanto, ¡cuán felices son aquellas almas que caminan por la senda del corazón,
y se retiran silenciosamente en su interior, esperando,
orando y dándole lugar a la operación de Aquel que es el único que da vida!
Tal vez, sólo un poco de tiempo más,
y nos encontraremos en esa bienaventurada eternidad--que
es nuestra patria natal--con indecible gozo,
para alabanza y gloria infinitas de nuestro Dios,
que nos ha llamado y nos ha permitido encontrarnos en esta tierra de exilio.
¡Amén, Jesús!

3 de agosto de 1753

¡Cuán tranquilamente me puedo sentar cuando mi trabajo está terminado!
¡Cómo será entonces ese descanso que disfrutaremos finalmente!
Por tanto, no nos cansemos de servir a ese Amo tan bueno y fiel,
cuyo servicio ya es en sí mismo nuestra felicidad.
Es verdad que todas nuestras acciones son pobres,
sin importancia e imperfectas--por lo tanto, no las tomemos en cuenta,
sino considerémoslas, no tanto como un deber,
sino como nuestra felicidad y salvación. Si demoráramos
el hacer el bien hasta que pudiéramos hacerlo perfectamente,
tendríamos que esperar demasiado.
Es una máxima para mí, que un hombre debe seguir adelante, aunque sea imperfectamente;
que el tal sólo persevere en orar, sufrir, negarse a sí mismo, ser fiel, etc.,
aunque todavía se mezcle con ello mucho que requiere ser separado.
Estos deben ser siempre nuestros sentimientos.
Un corazón de niño se esfuerza diariamente y de buena gana por mejorar,
y se regocija cuando alguien le muestra sus fallos.
'`El Señor guía a los mansos (a saber,
los que se alegran de que se les digan sus faltas) y les enseña Su camino.
Es un escudo para aquellos que caminan rectamente`'. (Proverbios
2:7) La firme y sincera decisión y determinación de servir al Señor,
es en sí mismo suficiente para alegrar el corazón;
¿qué hará entonces el progreso y la finalización? Es una tentación peligrosa del adversario,
cuando las mentes rectas se dejan abatir completamente,
ante la vista incrédula (casi digo orgullosa) de
sus debilidades en la realización de buenas obras;
tales individuos sólo deben declararse culpables, humillarse y seguir adelante.
El que ama y se ejercita en la oración,
a su debido tiempo será gradualmente trasladado del yo a
Dios--de la obra impura e imperfecta en su propia fuerza,
a la obra a través de Dios y para Dios.
Sólo deseo que todos, desde el comienzo mismo de su camino,
consideren la piedad o el servicio a Dios en la luz apropiada, es decir,
como la felicidad y salvación a las que estamos llamados y que Dios condesciende darnos;
y que cuanto más pronto y más se abandonen a sí mismos,
y abandonen las cosas creadas mediante la oración y la negación al yo,
más pronto se acercarán a Dios, incluso cuando no lo vean ni lo sientan,
y consecuentemente sean más felices;
porque Dios mismo es esencialmente nuestra salvación y nuestro fin.
Cuánto más cordial y completamente vivamos para Dios,
más felices seremos a partir de ese momento.
¡Oh, esto es extremadamente cierto!
Sin embargo, el que no busca la comunión con Dios a través de la oración,
no puede entenderlo correctamente.

11 de marzo de 1755

Él también se rindió completamente a Dios.
Sobre este tema escribe lo siguiente:

No puedo decir mucho de mí mismo, pues es un tema demasiado oscuro para mí;
se lo dejo todo a Dios.
Me veo constantemente obligado a escribir, hablar y hacer muchas cosas,
lo cual no parece concordar con mi estado de ánimo.
No busco nada, pero no deseo escapar de nada.
En todos los casos, sólo deseo seguir al Señor, pero no puedo decir que lo logre,
y estoy lejos de pensar que obro sólo en el Señor, aunque lo desee.
Tal vez me estorbe asociarme y tener demasiada correspondencia con otros,
pero no me atrevo a pensar en esto.
Debo entregarme por completo.
Si algún mérito tengo, ese consiste en mi debilidad y miseria,
porque parece que éstas me han ayudado mucho,
y todavía me ayudan a encomendarme totalmente a Dios,
después de haber buscado en vano apoyo en mi propia fidelidad.
No veo nada más dentro de mí, pero no estoy perturbado por ese motivo; todo lo contrario,
poseo una impresión muy tierna, pero a la vez general,
de la infinita bondad y belleza de Dios, aunque no se me conceda el deleite de ello.

Jesús, cierra nuestros ojos en la vida y en la muerte,
para que ya no nos contemplemos a nosotros mismos, ni lo que nos concierne,
sino que nos encomendemos desnuda, ciega y enteramente a Ti,
consintiendo voluntaria y sinceramente nuestra propia nadedad, y así,
en la ingenua despreocupación de la fe, vivamos y muramos Contigo y en Ti. Amén.

29 de agosto de 1741

Cuanto más se separen el alma y el espíritu por la
Palabra viva y eficaz de Dios (Hebreos 4:12),
y por Sus dispensaciones purificantes,
más imperturbable será nuestra paz en medio de los cambios y vicisitudes,
cuando Dios nos conduzca a ello.
No obstante, en cuanto a mí mismo, encuentro que soy deficiente en todos los puntos.
Hago, o me esfuerzo por hacer, lo mejor que puedo.
Deseo vivir y seguir, no a mí mismo,
sino al Señor. Experimento que Él es indeciblemente bondadoso conmigo en todas las cosas.
Ocasionalmente percibo que mi mente está en paz,
pero en otros momentos no soy consciente de ello y debo contentarme.

25 de enero de 1748

Mientras la unión con Dios es perceptible,
la comunicación sólo se hace a través de los sentidos.
Me hallo tan débil y miserable, que con respecto a mí mismo,
preferiría no escribir nada sobre el estado de mi alma.
Pero sin embargo es verdad,
que ocasionalmente me parece experimentar algo de la comunicación divina,
que es sobremanera preciosa, pero que sólo dura unos momentos.
Debemos procurar no hacer nada y no retener nada, sino entregarnos a nosotros mismos,
y entregar todo lo que tenemos y somos en las manos del Señor. Todo lo bueno viene de Él,
y Él puede dar o quitar según Su beneplácito.
A veces pienso que lo que es realmente bueno,
no me parecería así si estuviera en mi posesión;
pero estoy infinitamente complacido de que sólo el Señor sea bueno.
En esto--tal vez hable demasiado de mí,
aunque no es mi intención hacerlo--ni me atrevo a preocuparme; el Señor, sin embargo,
me capacita para entregarme a mí mismo,
entregar todo lo que soy y tengo tranquilamente en Sus manos.
¡Qué Él sea amado y glorificado por toda la eternidad!
Amén.

4 de noviembre de 1742

Te deseo mucha gracia, que te permita, con un espíritu de niña,
olvidarte y abandonarte a ti misma, para que seas recibida en y por el Señor,
y seas guardada hasta el fin.
Sí, mi querida hermana, sólo en el Señor está nuestra salvación y nuestra gloria.
¿No lo sientes así? ¿Qué más requiere Él de su sierva sino que se entregue, tal como es,
en Sus manos, y que en adelante se considere insignificante,
como algo que ya ha sido entregado?
¿No cuidará Él suficientemente de nosotros?
¿No nos redimirá y santificará Él, mejor de lo que nosotros podemos hacerlo?
¿Careceremos de algo en Sus manos?
¡Ojalá que todos los que están en circunstancias de prueba
y aflicción se sientan persuadidos de esto! ¡Oh,
Señor, concédeles esto, y concédenoslo a todos nosotros hasta el fin!
Amén.

8 de mayo de 1753

Mira, mi querida hermana, ¿no hace el Señor todas las cosas bien?
¿No trata Él conmigo amablemente y como un padre?
Oh, sí; yo en realidad estaría en buena medida tranquilo y en reposo,
si me dejaran más en paz externamente.
Pero aun así no debería decirlo,
a menos que tuviera más de la mente y temperamento de un niño,
que considera poco lo que es bueno o dañino, o lo que es capaz o incapaz de hacer.
Debería encomendarme a Dios en sencillez de corazón,
continuar viviendo a expensas de Su gracia, y creerme capaz en Él y con Él,
de hacer y de sufrir todo lo que Su providencia de
tiempo en tiempo me dé a realizar y soportar.
En mi presente estado de debilidad,
no experimento ninguna comunicación interna perceptible,
y ocasionalmente no pienso con frecuencia en mí; sin embargo, qué el Señor sea alabado,
estoy bastante bien y tranquilo en Él.

20 de mayo de 1755

Estoy en circunstancias singulares, incluso más de lo que soy consciente,
o de lo que puedo expresar,
y tal vez sería mejor si del todo no supiera ni dijera nada al respecto.
A veces estoy tan asombrado de mi pobreza y debilidad, que nadie lo creería;
en otro momento estoy asombrado de mi fuerza y de lo tranquilo que estoy.
A veces, y de hecho en general, soy tan ignorante de todo,
que si me pusiera a reflexionar en ello,
me sentiría bastante perdido en la circunstancia más pequeña; y antes de darme cuenta,
empiezo a hablar y actuar otra vez como quien va
a trabajar con un gran grado de luz y certeza.
Desconozco por completo mi camino, y no sé si alguna vez he leído algo similar.
No siento tanto cuando cometo un evidente error,
como cuando hago una simple consideración de mi propio estado,
cuando cuido de mí mismo o cuando intento ayudarme.
En tales ocasiones, sólo resultan reprensión y desasosiego;
pero cuando me olvido de mí mismo y simplemente continúo viviendo en la gracia de Dios,
instantáneamente estoy tranquilo y contento, como quien está en su puesto.
Incluso parece como si algo grande y excelente estuviera cerca--una fuerza en la debilidad,
un conocimiento en la ignorancia, una unidad en la variedad.
Sé muy bien que algunos de los santos han atravesado estados
en los que tal vez se habrían expresado de la misma manera;
pero este no es el caso conmigo.
No sólo soy miserable, sino extremadamente miserable,
y esto lo sabe bien el Señor. Estaría aterrado,
si comparara mi estado con los de estos hombres santos; y mientras escribo esto,
verdaderamente temo, querida hermana,
que concibas ideas demasiado exaltadas de mi estado.
¿No es maravilloso ver cosas tan diferentes en sí mismas y en aparente contradicción,
en la misma persona?
¿Qué harías con ello, o cómo lo explicarías? Por lo tanto,
sólo debo cerrar el relato diciendo: "`Dios es un perfecto todo;
la criatura una pobre nada;`" y regresar a lo que reconozco como lo mejor,
y que produce la mayor paz mental, es decir,
olvidarme de mí mismo tanto como pueda y continuar
viviendo simplemente en la gracia de Dios.
¡Oh, Señor, confírmanos en esta renuncia de nosotros mismos,
para que nunca regresemos a nosotros mismos,
y para que todo lo que está dentro de nosotros cante con tu sierva Ana:
"`No hay santo como Jehová; porque no hay ninguno fuera de ti`"! (1 Samuel 2:2). Amén.

Julio de 1747

Él tranquilizaba su mente en todas las ocasiones en la sabia y buena voluntad de Dios:

Este es mi empeño sin fatigarme, poder reposar en mi propia nadedad y pobreza,
como las siento en el presente, deseando vivir únicamente en y por amor.
Me veo diferente en diferentes momentos.
En un momento me parece que en diferentes aspectos soy un guerrero, y en otro,
soy la debilidad y la pobreza mismas, de modo que me apiadaría de mí mismo,
si continuara albergando tales pensamientos.
Pero alabado sea el Señor, que no me permite hacerlo por mucho tiempo,
y a menudo despierta en mí una secreta satisfacción al pensar lo que Él es,
y que sólo Él es bueno.

11 de octubre de 1746

Todo dentro de mí me inclina al retiro, a la tranquilidad,
a la inactividad de la imaginación y a la unidad en Dios y con Dios.
Poder vivir así, es en realidad la vida.
Creo que ésta es mi posición, mi comida, el objeto de mi llamado--vivir retirado,
ser despojado de todo, estar sólo con Dios en el Espíritu y separado del mundo,
en reposo y silencio, dándole lugar a Dios y a las cosas divinas,
de las que sólo resultan la verdad, la fuerza,
la vida y la salvación. ¡Cuán queridos son para mí
los momentos que puedo dedicar a ese fin!
Pero parece que no me permitieran disfrutar mi comida en paz y quietud.
Mientras doy, o más bien, parece que le doy a otros,
ocasionalmente imagino que yo mismo recibo unas pocas migajas.
Estoy bastante consciente de que la voluntad de Dios puede y debe ser mi comida, pero,
¿cuándo poseo la voluntad de Dios?

Quiero decir, que no siempre sé cuál es la voluntad de Dios; y al contrario,
a menudo se me ocurre preguntar,
si una criatura hace bien en dar mucho de su tiempo a otros.
Pero ya estoy cansado de quejarme,
y espero inducirte por este medio a que me presentes mucho más en tus oraciones a Dios,
para que pueda agradarle en todas las cosas, porque no deseo otra cosa; sí, lo repito,
no deseo otra cosa más que agradarle,
ser Suyo y vivir para Él en el tiempo y en la eternidad.
Y prefiero esto, con todas las cargas, dolores e inconveniencias que lo acompañan,
a vivir para mí mismo, poseyendo todos los placeres y gratificaciones,
si tal cosa fuera posible.
En este asunto, no pregunto si esta determinación es enteramente pura y sincera,
o si en lo profundo de ella yace algo muy diferente.
Le dejo eso a Dios, de quien solamente es mi salvación;
y mi espíritu se alegra de que la salvación y la gloria
de mi alma sólo vengan de Él y estén en Él. ¡Así pues,
sigamos adelante, confiando solamente en Su gracia,
con la sencillez de los niños pequeños,
y haciendo para el Señor lo que nuestras manos encuentren para hacer,
sin tener mucha consideración de nosotros mismos o de nuestras propias obras!

5 de octubre de 1748

Deseo vivir y sufrir según la voluntad de Dios.
Puedo recordar el tiempo cuando podía sufrir, por decirlo así, con el valor de un héroe;
pero ahora debo actuar como un niño que llora de vez en cuando,
cuando tiene dolor y no tiene la menor noción de la paciencia.
Y cuando mi cabeza está muy débil, a menudo no sé dónde está mi mente,
sino que debo vivir una vida meramente natural.
Ocasionalmente soy consciente de que estoy en buenas manos, pero por lo general no lo sé,
y en esos momentos no debería desear nada más. No sé si tengo algún deseo en la tierra,
o si deseo albergar otro que el de Pablo--el deseo de agradar a Dios,
ya sea en el hogar celestial o en el cuerpo.
De esta circunstancia percibo que hay una santa ambición;
porque el original literalmente se traduce: "`Tenemos la ambición de partir, etc.`"
El amor al yo piensa,
"`¿qué puedo hacer mejor que estar en el cielo?,`"
y no escatimará el precio con tal de conseguirlo;
pero el amor divino no considera tal cielo; porque su cielo, su honor,
su gloria es la complacencia de Dios.
Es a esto, estrictamente hablando, a lo que el amor divino,
en su naturaleza y propiedades, tiene respeto; y la santa ambición de este amor,
le impulsa suave pero poderosamente a buscar continuamente complacer más y más a Dios;
no es consciente de un mayor honor o felicidad en
el tiempo o en la eternidad que el de complacerlo,
ya sea en el hogar celestial o en el cuerpo.
¡Oh, Señor, danos este amor Tuyo y concédenoslo más abundantemente,
para que podamos servirte de manera digna,
y no nos privemos de Ti ni de Tu paz celestial, por aferrarnos a nosotros mismos!
Amén.

14 de agosto de 1750

Nuestro difunto amigo tenía al mismo tiempo, una firme confianza en Dios;
de lo que la siguiente carta da testimonio:

Sigo viviendo internamente en la gracia divina.
Siento que no debo hacer nada, ni desear nada,
y dejar que Dios haga lo que a Él le parezca bueno,
y estar contento como un niño. La visión de mí mismo me confunde,
a menos que el Señor me lleve a ella.
Es extraño que nosotros podamos ser tan miserables y buenos para nada, y sin embargo,
ser capaces de confiar de tal manera en Dios.
¡Oh, qué Ser tan benévolo! ¡Oh, qué Bondad tan grande!
Mientras nos ama, no considera lo que somos en nosotros mismos; y al amarlo,
es Su voluntad que nos olvidemos de nosotros.
Él es todo lo que puede hacernos pacíficos y felices.
En un momento nos deja ver y experimentar lo que
Él es para nosotros y lo que obra en nosotros;
y en otro, nos deja vernos y sentirnos a nosotros mismos; y luego,
vuelve a esconder de nuestra vista Su camino y Su propósito para con nosotros,
con el fin de simplificarnos y limpiarnos, y animarnos a no considerar nada salvo a Él,
y rendirnos más enteramente en Sus manos.

3 de diciembre de 1745

Toda verdad la experimentamos como verdad,
según nuestra medida de fe y de los misericordiosos
propósitos de Dios en Cristo para con nosotros.
Por muy miserable que pueda ser yo,
debo confesar que en los tratos de nuestro gran Redentor con nosotros,
haciendo que gradualmente todo sea quitado de la criatura y restaurado a Dios,
por lo que todo motivo de confianza y expectativa en nosotros mismos es destruido,
y sólo Dios se convierte en nuestro único sostén, expectativa y salvación eterna;
veo cada vez más, y a veces podría decir también, que gusto algo extremadamente dulce,
deseable y celestial.
¡Cuán excelente es esto, cuánto debería deleitar nuestros corazones!
Si fuera posible encontrar en nosotros algún motivo de confianza,
¡cuán razonable sería desear su destrucción,
para tener la felicidad de confiar sólo en Dios!
Recibir la salvación como un mero don gratuito, es, creo,
la única salvación. ¡Pero Señor, quién de nosotros entiende esto como debe ser entendido!
En cuanto a nosotros, ¡quién sabe, según nuestra medida,
que el camino del Señor que nos conduce a ella no siempre es según nuestras
ideas y gustos! ¡Cómo debería inducirnos esto a entregarnos ciega,
desnuda e incondicionalmente a Dios y sin mirarnos a nosotros mismos,
para dejar que nuestro Redentor trate con nosotros como a Él le parezca bien!
Bueno,
es Él quien debe concedérnoslo y obrar en nosotros aquello a lo que estamos llamados.
¡Bendito sea Su nombre por toda la eternidad!
Amén.

17 de Noviembre de 1750

Creo que el niño Jesús nos invita amablemente a ir a Él,
mostrándonos Su plenitud y preguntándonos, si no encontramos en Él lo suficiente.
¡Oh, si pudiéramos cerrar mejor nuestros ojos vagabundos,
abandonarnos y renunciar a todo, pronto encontraríamos, en la desnuda inocencia de la fe,
otro modo de existencia, y al no contemplar ni encontrar nada en nosotros,
sino pobreza y necesidad, nos deleitaríamos en el Señor,
en quien encontraríamos todo lo que nuestros corazones desean,
y a quien podríamos encomendarle nuestro camino sin vacilar! (Salmo 37) Pero aun así,
mi querida hermana,
no debes formarte una opinión demasiado favorable de mí a partir de esta carta,
como si yo viviera continuamente en abundancia y deleite.
¡Oh, no, ciertamente lo sabes mejor! ¡Pero, alabado sea Dios!
Tengo suficiente, aun cuando no poseo nada;
tampoco puedo decir que desee particularmente disfrutar mucho aquí en la tierra.
Mi pan de cada día es suficiente; sé que Dios lo es; ¡gracias a Su nombre!
Sé que Él es el Dios de nuestros corazones,
y que todas las cosas están en Él. Por lo tanto, a menudo me gozo con sencillez,
como si todas esas riquezas, que sé que posee mi Señor, fueran mías,
si bien deseo que Él sea el dueño exclusivo de ellas;
y ocasionalmente les recomiendo estas riquezas a otros de manera tal,
que de seguro me consideran rico, mientras que al mismo tiempo soy pobre y miserable,
e incluso, a veces me hago aún más pobre, cuando no puedo con suficiente sencillez,
olvidarme de mí mismo; porque eso tampoco está en mi poder.
Tú me entiendes bien, y no te olvides, junto con los otros queridos hijos de Dios,
de recordarme delante del Señor, algo de lo cual tengo mucha necesidad.

31 de diciembre de 1753

Yo soy débil, pero el Señor es poderoso,
y puede manifestarse como tal dentro de nosotros, según Su beneplácito.
Creo que lo mejor para nosotros y más apropiado para nuestra condición,
es que seamos pobres, desvalidos, nada;
y que todo lo que hay dentro de nosotros se incline ante Su nombre,
¡el Único que puede decir "`Yo soy`"! ¡Ojalá pudiéramos sólo mirarle a Él,
y buscar para siempre en Él nuestro deleite, y nuestro verdadero y único reposo!

10 de agosto de 1753

La magnitud de las riquezas que Tersteegen encontró en Dios,
era igualada por la pobreza que él encontró en sí mismo.
Esto se hace evidente a partir de muchas de las cartas precedentes,
e igualmente de las siguientes:

No sé cómo me encuentro.
Dios no me permite retener nada en lo que pueda colocar dependencia; quiero decir,
ya no puedo apegarme a nada con algún grado de afecto o placer.
Estoy como suspendido en el aire.
No tengo, al parecer, un lugar estable, ni una ocupación fija.
No se me permite mirar o reflexionar más allá del suelo que piso.
Por decirlo de alguna manera, estoy siendo apresurado hacia adelante.
Estoy lleno de miseria y enfermedad, pero no se me da tiempo para mirar a mi alrededor.
Desearía servirle al Señor y complacerlo,
pero ignoro si el deseo es completamente puro o no.
¡Ves, mi querida hermana, cuán sorprendente es mi camino,
y cuán necesario es que tú y los demás oren por mí! Soy visto como
una persona muy distinta de la que en realidad soy--Dios los sabe.
¡Qué Él gobierne todas las cosas para Su gloria!

15 de agosto de 1749

No puedo decir otra cosa sino que Dios ha sido bueno conmigo, y que lo sigue siendo,
concediéndome continuamente gracia para pasarme por alto y olvidarme de mí,
como algo inútil; y mediante un alegre asentimiento a mi propia nadedad,
por decirlo de alguna manera, escapar de mí mismo,
descansando y gozándome con sencillez en que Dios es tal como es.
¡Esta es una verdad tan grande e importante, y un tema tan hermoso,
que es lo único capaz de satisfacernos y contentarnos total y perfectamente!
Querida hermana,
¡cuán pobres y despreciables y pecadores somos en nosotros
mismos! ¿Quién lo creería y quién podría soportar verlo,
si Dios no nos diera una visión de Sí mismo por la fe, que cubre, por decirlo así,
nuestra pecaminosidad y compensa ampliamente nuestra indignidad?
Podemos mirar el tema desde cualquier punto que queramos,
el fundamento firme sobre el cual debemos edificar y confiar es sólo Dios,
y Él eternamente.
Cuando al aceptar alegremente nuestra propia pobreza, le damos realmente la gloria,
Sus entrañas se mueven, incluso hacia el más miserable.
¡Gloria sea dada a nuestro Dios por los siglos de los siglos!
Amén.

3 de diciembre de 1751

¡Ah, mi querida hermana!
No estoy en posesión de lo que tú supones que soy; y cuando lo tengo,
que quizás sea el caso a veces, es sólo por un tiempo.
Antes y después, soy como un pobre hombre, que no tiene nada en reserva;
pero no siempre como un pobre niño, porque entonces desearía no saber ni poseer nada.
No siempre tengo esta disposición,
pues de buena gana miraría un poco delante de mí. ¡Quiera
el Señor que esto también tienda hacia mi humillación!

A menudo he deseado ardientemente,
no haber sido nunca infiel o culpable de un solo pecado;
pero después de una mirada retrospectiva del asunto,
y después de haber hallado una expiación en Cristo, mis pecados de omisión y de comisión,
que aborrezco,
sólo deben servir para una mayor exaltación de la gloria de Dios y de Su gracia.
Tengo razones palpables para humillarme y confesar, que en verdad,
no hay nada bueno sino Dios.
Tengo obvios motivos para abandonarme y dejarme caer,
para que sólo pueda ser hallado en Jesús. Tengo evidentes causas para
acercarme a Dios en la más grande desnudez y pobreza de espíritu,
y consecuentemente, mucho más puramente,
incluso más que si pudiera recordar todo un registro de fidelidad y virtud.
¡Por desgracia, el poder y las riquezas de los méritos de la sangre de Jesús,
rara vez son reconocidos de la manera que deberían reconocerse!

1 de noviembre de 1754

Es increíble lo pronto que comenzamos a depender en alguna medida de nosotros mismos,
en momentos de luz y fuerza y comunicación discernible con Dios;
y a esto es a lo que tú como yo mismo, le tememos tanto,
al considerarlo el más grande de los males;
porque entendemos nuestra salvación como sólo en glorificar a Dios.
El primer título aplicado a nuestro Señor y Salvador es, "`Admirable`" (Isaías 9:6),
y así es también Su manera de tratar con nosotros.
Para llevarnos a la salvación recién mencionada,
Él a menudo nos despoja (después de haber obtenido un firme
control sobre nosotros) de nuestra luz y fuerza,
y de las gloriosas bendiciones que por tanto tiempo habíamos anhelado tan ardientemente,
para que las busquemos más puramente en Él,
mientras nos regocijamos en nuestra propia nadedad y en Su total suficiencia.
Debemos, pues, sin demora, abandonarnos a nosotros mismos,
para que olvidándonos así de nosotros mismos podamos obtener verdadero reposo y paz.

10 de enero de 1755

Nuestra mutua unión y comunión en espíritu compensa la interrupción
que por un tiempo ha ocurrido en nuestra correspondencia.
Sin embargo, para mí, dicha unión y comunión fueron suficientes,
y a menudo resultaron refrescantes para mi corazón.
Te encontré y te encuentro todavía muy cerca de mí;
y a veces te digo mucho más de lo que la pluma o la lengua pueden expresar.
No puedo dejar de pensar, que a veces el Señor comunica algo de esto a tu espíritu,
y hace que te acerques a Dios conmigo para adorarle, glorificarle,
amarle y perdernos en el abismo de Su bondad,
la cual no tiene en cuenta nuestra total indignidad.
Esta indignidad me parece un abismo, y si no la viera en la luz de la divina gracia,
haría que me sintiera reacio a entrar en comunión social con Dios y con Sus hijos;
pero desde este punto de vista, me parece deseable,
porque la encuentro muy útil para mi humillación;
un estado de ánimo que es requisito indispensable para verdaderamente
ser capaces de acercarnos a Dios como debemos.
Cuanto más pobres, más humildes y más desposeídos seamos, más incondicional,
libre y puramente podremos unirnos a Dios y a Sus hijos,
y más capaces seremos de participar del favor divino.
Una vez fue susurrado en mi corazón: "`Ven como un niño desnudo,
y entonces te recibiré en mi seno.`"
El amor al yo nos hace temer los sufrimientos y las privaciones,
y los presenta delante de nosotros en una luz melancólica; pero lo opuesto es la verdad,
porque tan pronto como nos sometemos alegremente a ellos,
los hallamos placenteros y saludables; pero cuanto más les negamos la entrada,
más tristeza producen de corazón y de semblante,
y con frecuencia son la razón de muchos sufrimientos tediosos.

Cristo "`se humilló a sí mismo,`" (Filipenses 2).
Nosotros no podemos humillarnos a nosotros mismos,
pero debemos dejar que se nos humille.
Cristo nos humilla guiándonos y por medio Su Espíritu;
y así Él nos hace aceptos para con Dios en y a través
de Él. Esto debe ser una gran consolación,
incluso para los más miserables; porque sólo necesitan acercarse como tales,
para recibir de Dios toda gracia y virtud necesarias.
E incluso para los que ya están más o menos en posesión de estos favores divinos,
la humillación que Cristo obra en ellos debe ser altamente apreciada y valorada;
porque por medio de ella son hechos verdaderamente grandes (2 Samuel 22:36).
Su comunión con Dios se hace así más pura y se cimienta más firmemente,
y aprenden por experiencia a doblar sus rodillas ante el nombre de Jesús,
lo cual es el comienzo de la salvación. Debemos aborrecer
sinceramente toda infidelidad y pecado pasado y presente,
y toda clase de mal; debemos anhelar ardientemente ser liberados completamente de ello,
y fervientemente seguir en pos de la santidad,
sin la cual nunca contemplaremos el rostro de Dios.
¡Pero cuánto me regocijo al examinar tanto el bien como el mal,
al encontrar que la conclusión del asunto es,
que después de aceptar plenamente nuestra nadedad,
debemos darle el honor y la gloria sólo a nuestro Dios por medio de Jesucristo!
Sí, amén. ¡Porque oh, Señor, tuyo es el reino, y el poder,
y la gloria por los siglos de los siglos!
Amén.

12 de septiembre de 1755

Su pobreza de espíritu le permitió caminar en humildad no fingida.
Por estas conversaciones y escritos vemos que él fue, sin lugar a duda,
de bendición para muchos; sin embargo, él hizo tan poco caso de esto,
que una vez en la primera parte de su vida, sinceramente confesó,
que nunca había pasado por su mente creer que Dios lo usaría para el beneficio de otros.
Sólo una vez se expresó en el siguiente sentido,
cuando hablando de cierto individuo--que nunca lo había visto y vivía a más de cien
millas de distancia--dijo que si Dios alguna vez lo había usado para algún propósito,
sería para esa persona.
A otro, que lo consideraba muy piadoso y dijo algo muy elogioso de él, le respondió:
"`He tenido que retirarme a una casucha para llorar mis pecados.`"

Él evidenciaba en todas las ocasiones esta humildad genuina,
acompañada de una sinceridad que le era propia.
Cuando estaba en compañía de personas despiertas, solía decir al despedirse:
"`Mis queridos hijos, cuando me siento entre ustedes,
me siento como si fuera indigno de ello, y lo mismo debería ocurrir en ustedes.`"
Estando una vez en Holanda, en compañía de varios amigos, uno de ellos,
que tenía una elevada reputación por su piedad,
le contó muchas cosas acerca de las persecuciones que había sufrido,
sus duras pruebas y experiencia personal.
Tersteegen con mucha modestia replicó: "`Si ya hemos gustado y experimentado mucho,
y pasado por muchas pruebas, el resultado debería ser un espíritu bajo,
sencillo sin artificios.`"

La siguiente mansa respuesta que le dio a cierto amigo que lo acusaba de parcialidad,
amor al yo y vanidad,
también convencerá suficientemente al lector imparcial
de cuán miserable era ante sus propios ojos,
a pesar de todos los dones y gracias que poseía. La respuesta fue:
"`Confieso delante de Dios, con toda sencillez,
que nunca me he considerado ni he declarado estar
completamente libre del amor al yo y de la vanidad,
pero que me entristecería creer que estaba apreciando algo de ese tipo,
por latente que esté. Sé que todavía necesito muchas cosas, y no pretendo como supones,
estar profundamente cimentado en la pobreza de espíritu,
aunque a través de la gracia he alcanzado el deseo de serlo.
Por tanto, créeme, que tu actual deseo de que yo crezca a la estatura del varón perfecto,
es mucho más agradable para mí,
que tu aparente suposición de que soy casi un hombre y un padre en Cristo, cosa,
que gracias a Dios, nunca ha pasado por mi mente afirmar;
pero si lo que ahora escribo te parece una pretensión de humildad,
debo callar y contentarme con esto: que mi corazón me absuelve en la presencia de Dios,
y que en realidad y en concordancia con la verdad, pienso así de mí mismo.
¡Oh, Dios, tú ves que sé que soy un pobre,
débil e indefenso niño! Permíteme regocijarme siempre de
que los demás me conozcan así y no me tengan en cuenta.
Pero aunque soy tal como Tus ojos ven que soy, Tú me has dado, sin embargo, amarte,
aunque mucho menos de lo que debería, e infinitamente menos de lo que mereces,
pero tengo esta confianza: que en Tu luz he llegado a conocerte a Ti y a Tu verdad,
y contemplo y coloco en Ti solamente toda mi felicidad.
¡Oh, Tú que escudriñas lo más íntimo del corazón,
juzga si esto no es en realidad y sinceramente la verdad!`"

Otro ejemplo de su humildad que se puede citar,
es de una respuesta confidencial que dio cuando se le preguntó si era
apropiado llamar a ancianos y a experimentados Cristianos "`padres y madres.`"
Él escribe: "`Siempre me ha disgustado sinceramente y humillado delante de Dios,
cuando ocasionalmente y muy inmerecidamente me han llamado padre.`"

En otra ocasión dice: "`Me considero totalmente indigno,
y me siento humillado cuando un hijo de Dios me llama hermano,
y deseo mucho menos el apelativo de padre.`"

Él sólo le daba a Dios toda la gloria.
Era su deleite, y su comida y su bebida alabarlo y magnificar Su grandeza,
excelencia y total suficiencia.
Nunca omitió testificar de Él cuando podía hacerlo,
ya fuera por escrito o en una conversación. En este
sentido él gustosamente habría hecho aún más,
pero su estado físico debilitado y otras circunstancias,
no se lo permitían. Lo que dice sobre este asunto en el prefacio de uno de sus himnos,
es muy notable.

Durante mi corta carrera,
por gracia he experimentado muchos favores de la
mano de Dios mientras estaba bajo la cruz,
y se me enseñaban muchas cosas con respecto a Él. Obsérvese, por gracia.
Tuve, pues, hace veinte años, la intención de componer antes de mi deceso,
cien himnos de acción de gracias,
como sacrificio de alabanza a Dios por las misericordias
que Él me ha mostrado y dejado experimentar.
Pero muchas otros deberes y las debilidades de mi avanzada edad,
me privan de la esperanza de lograrlo en este lado de la eternidad.
Deseo que el último acto de estos labios en este mundo sea alabar a este Dios bondadoso,
y espero, por Su misericordia, una eternidad interminable y feliz,
en la que pueda cumplir mis votos a Dios y ofrecerle junto con todos los santos glorificados,
más de un centuplicado tributo de alabanza.
Amén. ¡Aleluya!

Una vez le dijo a un amiga,
que él invariablemente había recibido las más grandes
bendiciones y manifestaciones del favor divino,
en la enfermedad y en otras privaciones externas e internas;
y cuando la misma amiga una vez le mencionó, que el tiempo apartado para la oración,
era para ella tan pesado como si estuviera en un campo de batalla,
le hizo esta seria pregunta: "`¿Es extraordinario que los ángeles alaben a Dios?`"
Ella respondió: "`No, porque si nosotros estuviéramos en su lugar, haríamos lo mismo.`"
"`Esa es mi opinión también,`" replicó él, "`pero cuando Job alababa a Dios,
mientras estaba sentado en su muladar, era algo noble,
y esta alabanza le complace más que la de los ángeles.`"

A su humildad, arriba aludida, puede añadirse con razón,
su sorprendente paciencia en los sufrimientos,
su mansedumbre e indulgente disposición hacia sus adversarios,
y su compasión y benevolencia para con los que habían caído.
Continuamente tenía oportunidad de ejercitar la paciencia.
Por lo que ya se ha dicho y por sus cartas,
es suficientemente obvio que desde su juventud,
trabajó bajo muchas enfermedades y dolencias;
y estuvo particularmente sujeto a ellas durante los últimos treinta años de su vida,
lo que hizo que sus muchas ocupaciones, como atender a los enfermos, recibir visitas,
su extensa correspondencia,
y una variedad de enojosas circunstancias que las acompañaban,
fueran tal vez mucho más opresivas.
En resumen, toda su vida no fue sino una continua y dolorosa enfermedad;
de la que aquí se citan unos ejemplos.
"`Hace una semana,`" cuenta él en una carta a un amigo,
"`fui atacado por un resfrío que se instaló en el lado izquierdo de la cabeza--en,
detrás y alrededor de la oreja--con un dolor tan agudo y continuo día y noche,
que mi cabeza palpitaba convulsivamente en todo momento.
A esto se unió fiebre.
Me vi obligado a permanecer acostado, pero apenas podía hacerlo.
Uno o dos días después, sufrí una severa debilidad;
el resfrío se bajó a mi cuello y pecho, y me hizo toser mucho, lo cual fue muy doloroso,
tanto para mi cabeza como para mi cuerpo.
El final de nuestras lamentaciones es: ir a casa.`"

En otra ocasión, le escribió a un amigo como sigue:
"`El viernes por la mañana antes de Pentecostés, tuve que escribir una carta urgente,
y mientras lo hacía, se apoderó de mí un temblor de la cabeza a los pies.
Por la tarde fui atacado por la fiebre y por un fuerte dolor en las extremidades,
el cual, durante la noche,
se convirtió en un reumatismo confirmado en la parte gruesa de la pierna,
de modo que no sabía donde ponerme debido a la agudeza del dolor,
y esto fue acompañado por una gran repulsión a toda clase de alimentos.
Sin embargo, en esta situación me vi obligado a recibir,
mientras estaba confinado en cama, a cuatro amigos de C+++_______+++,
a tres de E+++_______+++. Gracias a Dios, que me ha ayudado hasta ahora.
No he sufrido como un héroe, sino como un enfermo.
Pero debo interrumpir aquí; un sudor frío que me ha sobrevenido,
no me permite escribir más.`"

A un amigo que lo visitó, le dijo una vez: "`Tengo una erupción en todo mi cuerpo,
y mi espalda está tan irritada, que se me pega la camisa; además de lo cual,
tengo una herida en el cuerpo por la que sufro mucho dolor.`"
La persona a quien le contó esto, manifestó mucha compasión por él, pero dijo:
"`El viejo hombre ha pecado, y por lo tanto, debe sufrir.`"
En los últimos años de su vida, por causa de su debilidad estomacal,
soportaba tan mal la comida, que decía: "`Siempre me aflijo cuando me suben la cena,
porque la comida más liviana me causa mucho dolor y dificultad.`"

Además de sus aflicciones corporales, tuvo que sufrir mucho en sus últimos años,
no sólo por parte de un mundo desdeñoso y blasfemo, sino también por parte de amigos,
de cuyas imperfecciones hizo uso el Señor para perfeccionarlo más. A algunos,
les parecía que hacía demasiado; a otros, que hacía muy poco;
otros lo envidiaban por causa de sus dones, y porque era muy amado y estimado por muchos.
Pero él llevó todo esto con ejemplar paciencia.
Cuando sufría los dolores más agudos, los soportaba con tanta sumisión,
que apenas se notaba que sufría bajo ellos.
En el ejercicio de la paciencia manifestaba tal fortaleza,
que durante un violento dolor de muelas, una vez dijo que tenía necesidad de paciencia,
y sin embargo, cantó el himno, Venture Boldly, etc.

Un amigo relata el siguiente ejemplo de su paciencia,
benevolencia y compasión con los caídos.
"`En compañía de Tersteegen, había disfrutado por varios años muchas bendiciones,
por su edificante conducta y conversación;
pero después de un tiempo fui desobediente a la gracia de Dios,
de modo que mi corrupción y las artimañas del adversario,
me ocasionaron una grave caída. Habiendo afligido tanto al buen hombre con esto,
y estando avergonzado de mí mismo, y temeroso de recibir una reprimenda de él,
dejé de visitarlo.
Después de haber observado esto por un tiempo, me mandó a llamar.
Fui donde él con la plena expectativa de ser duramente reprendido por él,
de lo cual yo estaba completamente consciente que merecía; en su lugar,
me recibió con el afecto de un padre y me abrazó tiernamente,
por lo que mi corazón se afectó profundamente,
y mi amor y confianza en Dios y en su querido siervo se despertaron de nuevo.
Él me dio, al mismo tiempo, las instrucciones necesarias respecto a mi conducta,
y me exhortó a obedecer la gracia de Dios.
Después de esto, mantuvo una vigilancia más estrecha sobre mí hasta su muerte.
En otro momento me dijo a mí y a otros tres amigos: "`Hijos,
estén alerta y eviten toda ocasión de pecar.
Los hombres del mundo,
a menudo pueden guardarse más fácilmente de caer por medio de sus poderes racionales,
que aquellos que han llegado a ser piadosos por la gracia,
a menos que eviten cuidadosamente la oportunidad de ofender,
porque el enemigo trata de atraparlos, más que a los primeros.`"

Cuando Tersteegen se enteraba de que alguno de sus amigos había regresado al mundo,
o había sido en algún grado infiel en su conducta externa,
a menudo le provocaba noches de insomnio y arrancaba de él los más tristes suspiros.
En una ocasión se expresó de la siguiente manera: "`¡Oh,
qué carga de ansiedad y preocupación me ocasionan los que son divinamente llamados,
y caminan infielmente delante del Señor!
Me provoca tanto dolor,
que con frecuencia me veo obligado a arrojarme sobre mi rostro delante del Señor. ¡Si
sólo supieran la aflicción que me provocan los que viven en un estado de tan falsa seguridad!`"

Su disposición mansa y pacífica hacia sus oponentes era igualmente notable.
Él tuvo que soportar mucha oposición, amargura y enemistad por parte de ellos,
aunque cuando llegaban a criticarlo, sabía muy bien cómo recibirlos tan afectuosamente,
que era imposible para ellos mostrar algún grado de pasión en su presencia.

A pesar de todo,
nunca se desvió ni un ápice cuando se trataba del
honor de Dios y del testimonio de la verdad.
Dios le concedió tanta sabiduría y mansedumbre,
que la mayoría de las personas fueron convencidas de la verdad,
se avergonzaron de sí mismas,
y fueron positivamente vencidas por su comportamiento afectuoso y pacífico.
Nunca se ha oído decir de él, que hubiera tratado a sus adversarios con pasión,
ni personalmente ni por escrito.
Este hecho será corroborado por los siguientes ejemplos.
Él le escribió a un amigo lejano la carta que se adjunta,
quien lo había atacado con mucha amargura:

En el futuro, deja de atacar a un hermano de la manera en que lo has hecho,
o de desear que se avergüence en la presencia de
Cristo por cosas que nunca han entrado en su mente.
¡Dios sabe que es algo realmente rudo y desconsiderado!
Lo olvidaré. En el nombre de Jesús y en humilde confianza en Su misericordia,
auguro para ti y para mí mismo algo mucho mejor; a saber,
que aunque no seamos unánimes ni nos entendamos en este asunto, aun así,
si nos amamos el uno al otro,
y nos esforzamos por alcanzar el objetivo de nuestro llamado,
pronto nos abrazaremos en la presencia de Jesucristo con el más tierno y sincero afecto,
sin ser avergonzados; y no tendremos nada que perdonarnos,
ni nada que reprocharnos el uno al otro.
¡Bendito Jesús, este querido hermano quiere que me avergüence ante Tus ojos! ¡Mi Dios,
mi Salvador,
sólo Tú sabes cuánta razón tengo para estar verdaderamente
avergonzado y profundamente humillado en Tu gloriosa presencia,
por causa de mi nadedad y multiplicada miseria por naturaleza!
Pero, ¿no cayeron sobre Ti mi pecado y mi vergüenza?
¿No me permitirás, por tanto, contemplarte,
y eso con tal calma y libertad que mi rostro no se avergüence?
(Salmo 34:5) ¡Queridísimo Amigo, que eres el más cercano a mi alma,
mi gozo y toda mi gloria, permítele ver a mi hermano para su consuelo,
que Tu rostro no me condena por lo que su pluma me imputa.
Llena su corazón de gracia y paz, y bendícelo eternamente!
Amén.

El año anterior, estando en Holanda, una persona de alto rango lo invitó a ser su huésped.
Esta persona creía haber alcanzado un estado particular de paz interior, y por tanto,
aprovechó la oportunidad durante la cena,
para criticar a Tersteegen por ser demasiado activo,
y por no conocer suficientemente el terreno sobre el que trabajaba.
Tersteegen atendió mansa y silenciosamente todo lo que se dijo,
pero cuando terminó la cena ofreció una ferviente oración,
en la que encomendaba a su anfitrión al Señor en términos de tal afecto y compasión,
que este gran hombre de temperamento apasionado se impactó y afectó tanto por ello,
que lo abrumaron sus sentimientos y cayó sobre el cuello de Tersteegen y le pidió perdón.

En otra ocasión mientras estaba en Ámsterdam,
asistió a una numerosa asamblea de varios amigos,
algunos de los cuales eran sus más allegados, pero otros eran de diferente tipo.
Entre estos había un anciano piadoso a quien se le prestaba mucha atención,
y que además era un hombre de mucho talento y respetabilidad.
La simpleza, franqueza y falta de artificio de Tersteegen,
parecieron extrañas y sospechosas a los ojos de este individuo, por lo tanto,
empezó a hacerle diversas preguntas y a plantear toda clase de objeciones.
Tersteegen las respondió breve, clara y prudentemente, y condujo al interlocutor,
sin que nadie lo observara, de la circunferencia al centro del círculo.
Finalmente, concluyó todo con una afectuosa oración de despedida y con una bendición,
de modo que todos lo saludaron y se despidieron de él muy amablemente.

Esto brinda una oportunidad muy adecuada para decir algo,
de la manera en la que él trataba a los que estaban buscando la salvación. Se
le haría una gran injusticia suponer que buscaba que ellos se asociaran con él,
o que se esforzaba por procurarse seguidores; se puede inferir,
incluso a partir de sus propias palabras, cuán lejos estaba de eso.
Una vez,
cierta persona quería que él mandara a llamar a una
piadosa dama que vivía lejos y deseaba conocerlo,
ante lo cual envió la siguiente respuesta, fechada 19 de septiembre de 1766.

La hermana N+++_____+++ es una de las personas que más amo y estimo en H+++_____+++;
ella tiene una mente noble e inquisitiva, pero no puedo invitarla aquí,
porque la situación era muy diferente cuando yo cantaba,

Sabes cuándo me regocijo al ver

Las almas que se entregan a Ti.

Yo en ese tiempo vivía en el anonimato,
incluso cuando inesperadamente tenía compañía, y amaba, por decirlo así, a distancia,
sin ceder ante ello, puesto que no se esperaba nada de mí. Pero, por mucho que los amara,
no recuerdo un momento en el que mi principal deleite
estuviera en la compañía o labores de otros.
El conocimiento vivo de tan todo-suficiente y omnipresente Dios,
producía en mí una inclinación profunda y habitual
a vivir retirado y a estar a solas con Dios.
Lo que he hecho, por deficiente que haya sido su ejecución,
ha sido hecho únicamente en concordancia con las indicaciones
de la Providencia y con lo que creía que era mi deber.
¡Ah, nuestros semejantes a menudo son un obstáculo para nosotros y nosotros para ellos!
Mi máxima sigue siendo, "`alegrarse de disfrutar la compañía de los hijos,
pero mucho más la del Padre.`"

Él le escribió a la misma persona, bajo la fecha 3 de abril de 1767, como sigue:

Esta semana ya he recibido cuatro visitantes del ducado de Berg; y un amigo de S+++_____+++,
que tiene el objetivo correcto en mente,
ha estado aquí algunos días. El proverbio en latín, Qui bene latuit,
bene vivit (quien vive retirado, vive bien), cobra más importancia para mí,
día con día. ¡Oh,
de cuánto tiempo y fuerza nos privan nuestros semejantes!
¡Cuán fácilmente nos hacemos daño,
aun cuando pensamos que somos útiles para otros!
Las pruebas y aflicciones que lo acompañan,
bien pueden servir como un remedio y conservador adecuado.
El Señor gobierna todas las cosas para bien, y nos atrae poderosamente a Sí mismo,
y nos concede verdadera fidelidad en el ejercicio
de la oración ferviente y del retiro interior,
para que podamos darle lugar a las operaciones e influencias divinas,
desde donde debemos obtener, entera y únicamente, nuestra fuerza, vida y ser,
tanto en la adversidad como en la prosperidad.

En otra ocasión: "`¡Dios,
qué ventajas poseen aquellos que no tienen otra cosa
más en qué pensar que en sí mismos y en Ti;
y cuán sucia se vuelve con frecuencia la perla,
cuando pasa por tantas manos! ¡Qué Tu beneplácito sea nuestra constante comida,
y Tu hermosa presencia nuestra fuerza!

Lo que Tersteegen expresó en estas cartas con palabras, lo demostró con hechos.
Para escapar del apego y compañía de los hombres, durante el verano,
a menudo se retiraba a un bosque donde podía tener comunión con su Dios en soledad.
Así solía pasar días enteros, lo que con frecuencia llamaba su tiempo más dulce,
y sólo se sostenía con una pequeña merienda que llevaba con él.

Yendo en una ocasión con un amigo a una reunión, donde se esperaba que predicara,
le dijo: "`Preferiría esconderme de todo el mundo,
que dejarme ver y oír.`" Y en otro momento dijo: "`Yo sinceramente deseo,
que el nombre de Tersteegen sea olvidado por todos, y por el contrario,
que el nombre de Jesús quede impreso en todos los corazones.`"

Adjuntamos otro notable pasaje,
de una carta que le escribió a un amigo Moravo que lo acusaba de sectarismo:

Espero nunca haber mostrado, durante todos los años de mi llamado,
que buscaba formar un partido o conseguir seguidores.
Hasta hoy, continuamente oigo quejas de cerca y de lejos,
de que me retraigo mucho.
¡Oh, Dios, luz que nunca adula, Tú me conoces!
Sospecho de mi propio corazón en todas las ocasiones, y ante Tu vista no puedo,
ni quiero justificarme--¡pero mira cómo me juzga un hermano!
Sabes cuán doloroso ha sido para mí el sacrificio de renunciar a mi tiempo, fuerza,
tranquilidad,
y de mi amada soledad por el bien de los demás. ¿Acaso no lo he hecho sólo por Ti,
por imperfecto que pueda ser, y por temor a desagradar a otros haciendo lo contrario?
¿Acaso no busco más que conducir almas hacia Ti y no hacia mí mismo?
¡Oh, si esto último es el caso, destiérralo lejos de mí. Luego,
aparta de mí los corazones de los hombres en este sentido,
y déjame vivir despreciado y olvidado, sólo Contigo!
Porque sé y puedo apelar ante Ti, la verdad de la afirmación, de que sé que Tú, Dios mío,
eres lo único todo suficiente para mí.

6 de marzo de 1750

Pero a pesar de sus intentos de escapar del apego de sus semejantes,
el resplandor ampliamente divulgado de su piedad y dones superiores,
causaba que lo visitaran muchos de cerca y de lejos.
Recibía visitas de Suiza, de todas partes de Alemania, Holanda, Inglaterra,
Suecia y otros países.
Su correspondencia con personas que habían sido despertadas,
era igualmente extensa y considerable.
Era visitado por persona de todos los rangos, desde los más altos hasta los más bajos,
y también por teólogos y piadosos,
algunos de los cuales
se servían de su consejo en casos y asuntos de importancia.
A un amigo suyo que lo visitó en una ocasión, le dijo: "`Anteayer el Conde W+++_____+++,
junto con su mayordomo y amigo, me visitó de incógnito.`"

Pero de todos los que llegaban a verlo, ninguno le proporcionaba mayor placer,
que aquellos que se habían ofrecido enteramente a Dios,
y que llevaban en sus amigables temperamentos y disposiciones,
las características distintivas de Sus hijos--éstos eran su único deleite en la tierra.
Visitaba ocasionalmente a algunos de estos que vivían
en el campo y estaban débiles o enfermos,
y hasta sus últimos momentos,
sintió especial gratificación y alivio en compañía de ellos.

Él había recibido del Señor un don notable,
que se manifestaba en la sabiduría de su conducta hacia las almas despiertas y piadosas.
Un corazón herido rara vez salía de su presencia, sin sentirse consolado y vigorizado.
A la misma vez era tan humilde, tan insignificante ante sus propios ojos y tan afectuoso,
que los que llegaban a verlo le confesaban, sin reservas,
los pecados con los que estaban cargados;
ante lo cual los dirigía admirablemente hacia el Salvador de los pecadores,
y sabía bien convencerlos completamente,
de que la misericordia y perdón sólo se encuentran en Él. Les decía además,
que si ellos querían alcanzar entera paz para con Dios,
también debían ser obedientes a las invitaciones y amonestaciones de la gracia divina.
Todos sus esfuerzos estaban dirigidos a que el Espíritu
de Jesús viviera y reinara en el corazón.

Él se oponía totalmente a los meros intentos humanos de formar y restringir la mente,
y a menudo decía, que aquel que tiene que ver con las almas de los demás,
debe actuar como una niñera, que sostiene al niño con cuerdas,
y se limita a prevenir que se caiga y se haga daño, pero por lo demás,
lo deja ir a donde quiera.
Cuando alguna persona se retrasaba demasiado y era negligente en su caminar y conducta,
él le podía mostrar con mucha mansedumbre y sabiduría su falta,
y hacer que Dios y la eternidad fueran más importantes que nunca para ella.

Cuando estaba en compañía de los que realmente estaban rendidos a Dios,
parecía estar en su elemento; entonces eran muy afectuoso y comunicativo;
y cuando se planteaba una pregunta que le abría una oportunidad,
sus labios rebosaban de sabiduría celestial.
Todo lo que decía estaba lleno de gracia y poder, y era tan profundo y comprensivo,
que sus oyentes se veían obligados a decir, "`sí y amén,`" a todo lo que afirmaba.
Siempre recreaba a los
que estaban presentes con una conversación edificante,
a menudo motivado por objetos externos.
Él los usaba como ejemplos espirituales, y en tales ocasiones,
a menudo decía cosas maravillosas.
Por este medio, toda conversación inútil era evitada en su presencia,
y por esta razón algunas consciencias tiernas eran inducidas a abstenerse de compañía,
a menos que él estuviera presente.

La siguiente declaración de un amigo,
servirá para dar una idea de su conducta cuando estaba acompañado.
"`Cuando acudía a él con mi mente
distraída--lo que era frecuentemente el caso--su presencia,
que era muy impresionante, o un corto tiempo en su compañía,
era suficiente para recoger mis pensamientos dispersos.
Y cuando tenía algo en mi mente, por lo general sucedía, que después de contárselo,
mis dificultades se desvanecían antes de dejarlo,
o bien quedaba libre de ellas en el transcurso de unas pocas horas,
por la misericordia divina y la intercesión de nuestro noble amigo.
Sus oraciones, cuando estaba en compañía de otros,
eran extraordinariamente poderosas.
¡Cuán a menudo me siento renovado cuando pienso en ellas! ¡Cuán sinceras,
tranquilizadoras y desapasionadas eran,
y cómo se sentía uno internamente recogido y poderosamente vigorizado por ellas!
Nunca he oído a nadie más orar de manera semejante.
En resumen, todo lo que se dice de él es insuficiente.
Su vida estaba escondida con Cristo en Dios.
¡Oh,
cuánto brillaba la imagen del Señor Jesús a través de él--de modo que yo a menudo pensaba,
que si un rayo pequeño emitía tal resplandor, cómo sería el Señor mismo,
que es la fuente de la luz divina!`"

No sólo era de gran beneficio para los que gozaban de salud,
sino también para los enfermos.
Su cuidado paternal, su conversación consoladora y oraciones eficaces,
edificaban y fortalecían a tantos,
que por ello eran capaces de confiar más firme y filialmente en su Dios y Salvador.
Cuando era necesario, se quedaba con ellos la mitad de la noche, y a veces toda.
Citamos sólo un ejemplo,
del que él le dio cuenta a un amigo con su propia mano,
con respecto a una querida hermana en Cristo que visitó durante su última enfermedad:

Durante la cena del jueves,
me llamaron repentinamente a+++_____+++. El ataque pasó en unas pocas horas.
Me quedé toda la noche con ella, y reflexioné en su partida;
también fui capacitado para decir y orar muchas cosas con ella.
Continuó serena, tranquila y en posesión de su infantil confianza hasta el final.
Ella no sólo entendió mis palabras y clamores,
sino que también las selló con un "`sí y amén.`"

Las últimas palabras a las que ella asintió, fueron los dos últimos versos del himno:
"`Adelante paso a paso, etc.`"
Después agregué: "`¡Recibe bondadoso y querido Salvador, el espíritu de esta tu hija,
a quien Tú has redimido! ¡Deja ahora que Tu sierva parta en paz,
para que sus ojos te contemplen a Ti, su Salvador!`"
Y cuando sus ojos se cerraron el miércoles a las diez de la mañana,
le agradecí sinceramente a Dios su bondadosa liberación,
sostén y misericordia que le habían sido concedidos.
Esto lo sobrellevé con tolerable fortaleza, pero después,
mientras les decía unas palabras al hermano de ella y a la familia,
y les recomendaba su ejemplo,
me venció la debilidad y me vi obligado a interrumpirme abruptamente.^
footnote:[Cuando posteriormente se le preguntó cómo
había podido ser tan infantil como para llorar,
respondió: "`Confieso que fue infantil; pero créanme,
que me siento cada vez más deprimido en el mundo,
cuando aquellos que están tan enteramente dedicados
a Dios se van de él.`" En otra ocasión también dijo:
"`No deseo la indiferencia de los estoicos,
y participo voluntariamente en las alegrías y tristezas de mis hermanos.`"]
Ella sufrió mucho y por mucho tiempo, por lo que mis sentimientos también se afectaron,
aunque no se lo dejé ver, y por el contrario, fui capaz de ser un medio de fortaleza.
Durante todo esto, su tranquila y alegre paciencia fue tal,
que uno no puede pensar en ello sin admiración y acción de gracias.
La serenidad de su mente y la inquebrantable confianza en Dios hasta el final,
siguen siendo de grande y continua consolación para mí. ¡Gloria a Dios, que lo dio todo!

De esta manera animó y consoló Tersteegen a muchos enfermos y moribundos,
y fue usado como un instrumento para la consolación,
sostén y edificación de ellos hasta la muerte.
No sólo ministró a sus amigos en sus enfermedades, sino también a otros,
aunque fueran depravados.
Es más, cuando los judíos estaban enfermos, le mandaban a pedir medicinas;
y se cuenta que durante su enfermedad,
ellos convocaron una reunión para orar por su recuperación.

Nuestro difunto amigo se comportó con amabilidad hacia todos los hombres.
Trabajó con todas sus fuerzas para hacer la obra
de Aquel que le había asignado su lugar en el mundo,
y para promover su propia salvación y la de los demás. Puede decirse con verdad de él,
que era un siervo de siervos, y que se hizo de todo para a todos,
a fin de ganarlos para Cristo; y que para este propósito no escatimó trabajo ni dolor,
e incluso, que sacrificó su propia salud;
y que particularmente en los últimos años de su vida, se esforzó mucho.
Apenas se levantaba por la mañana y reunía un poco sus débiles fuerzas,
se veía rodeado de los que buscaban consejo y ayuda de él, unos para sus almas enfermas,
otros para sus cuerpos enfermos; y con respecto a lo último,
podría llamársele con propiedad, "`el médico de los pobres y necesitados.`"
Tan pronto era libre de estos visitantes,
tenía que responder una gran cantidad de cartas; y cuando éstas eran despachadas,
escribía o traducía algún libro edificante,
y así gastaba sus facultades mentales y físicas al servicio de Dios y de su prójimo.
En cierta ocasión,
le dijo a una amiga que lo visitó y observó su rostro cubierto de un sudor frío:
"`Estoy muy débil, tengo muchas visitas, ya he escrito mucho,
y todavía quedan seis cartas sin abrir ahí.`" Como ella
estaba a punto de irse para no molestarlo y dejarlo en paz,
él le dijo: "`¡Oh no, quédate; no debemos preocuparnos por Tersteegen;
Tersteegen no debe tener descanso!`"
Y al ver que ella se sentía angustiada,
se levantó y caminó por la habitación cantando un par de versos con voz alegre,
tratando de animarse a sí mismo y a su visitante,
lo cual continuó haciendo después de entablar conversación con ella.
Una prueba evidente, de que servir a su prójimo y serle útil era su ámbito natural.

Tersteegen no se relacionaba con los hombres del mundo,
excepto cuando había necesidad de hacerlo;
pero cuando se veía obligado a estar en su compañía, sabía comportarse de manera tal,
que ellos se sentían edificados por ello,
e impulsados a sentir gran veneración por él. Un posadero,
que vivía en el lugar donde moraba Tersteegen,
una vez le hizo una observación a un amigo con respecto a esto:
"`Todo el tiempo que paso por la casa de ese hombre,
un sentimiento de reverencia se apodera de mí, y el mero recuerdo de él,
a menudo me causa una impresión tan profunda, como la de muchos sermones.`"
A esto, puede que haya contribuido en gran medida su comportamiento servicial y amigable,
unido a las nobles y brillantes cualidades de su mente.

En otros aspectos, Tersteegen,
por lo general guardaba silencio en compañía de personas con mentalidad mundana;
pero cuando encontraba una oportunidad para decir una palabra de edificación,
nunca dejaba de aprovecharla.
Lo siguiente es un ejemplo de esto:

En una ocasión, durante un viaje a Holanda,
y encontrándose en el barco con un grupo de comerciantes y personas de respetable apariencia,
inclinó su cabeza hacia atrás y cerró sus ojos, como si estuviera dormido.
Después de que habían sido relatadas toda clase de historias,
y se había pospuesto un juego de cartas, abrió los ojos y dijo,
que él tenía un excelente mazo de cartas en su equipaje.
Cuando le pidieron que las mostrara, sacó un Nuevo Testamento, y al verlo,
le dijeron que ese libro enloquecía a las personas.
Entonces respondió:
"`¿No son ustedes los que están locos?,`" y repasó toda su conversación tonta e improductiva,
y trató de convencerlos con las propias palabras de ellos,
de cuán tontamente actuaban al desperdiciar su valioso tiempo con cosas tan inútiles.
Algunos aprobaron lo que dijo; y los demás,
al menos se abstuvieron de llevar a cabo la intención que tenían.

Los sentimientos de Tersteegen
con respecto al uso de los medios externos de gracia,
pueden ser suficientemente comprobados a partir de las cartas de él que han sido publicadas.
Tenía en gran estima lo que servía para dirigir a los hombres a Dios y a Jesucristo,
y recomendaba un uso sabio y fiel de ello.
Si alguno lo acusaba de mantener
a las personas lejos de la iglesia y de los sacramentos,
dicha acusación era infundada--nadie que hubiera sostenido
una relación con él habría podido afirmar lo contrario.
Él dejó a cada uno en perfecta libertad de hacer
lo que le pareciera mejor ante los ojos de Dios.

Si alguien tenía escrúpulos y le pedía consejo, él lo daba según la naturaleza del caso.
Por ejemplo,
a un amigo que no se sentía en libertad de participar del sacramento--pero era presionado
por el ministro para que lo hiciera--después de examinar su estado le dijo:
"`Ve a ver a tu ministro y dile: '`Señor, te pido de manera amigable,
que me des libertad con respecto a la comunión,
porque en este momento no puedo participar de ella apropiadamente,
pero si tú no puedes hacerlo,
me acercaré a la mesa del Señor a tu orden`'.`" El ministro, inducido por esta sujeción,
lo dejó actuar como él pensaba que era apropiado.
A otros, que tenían escrúpulos más fuertes, los dejó en paz, diciendo:
"`Un hombre no debe hacer nada contrario a la consciencia; lo que no proviene de fe,
es pecado.`"

Algunos han creído también, que era enemigo del estado matrimonial,
pero esto tampoco tiene fundamento; porque él les aconsejó a muchos,
según las circunstancias del caso, que lo contrajeran;
por no mencionar la entrañable e íntima amistad en que vivía con muchas personas casadas.
Con respecto a sí mismo, pasó su vida soltero,
porque creía que así podría amar a Dios más y servir mejor a su prójimo,
que si tenía que proveer para una esposa e hijos.
En muchas de sus cartas pueden verse claramente cuáles eran sus
sentimientos en otros aspectos relacionados con el estado matrimonial.

Llegamos ahora al periodo de la feliz partida de Tersteegen de este valle de lágrimas.
Durante toda su vida estuvo externamente enfermo, débil y afligido.
Esto tuvo tal efecto sobre su cuerpo, que a menudo se veía como un cadáver.
Sus obras y su fidelidad, que sólo cesaron con su vida, son, por tanto, más admirables.
De esto resulta evidente,
que el Señor lo sostuvo de la forma más extraordinaria,
y lo preservó por mucho, contra todas las expectativas,
como un instrumento escogido para emplearlo en Su servicio y en el de sus semejantes.
Pero la vida que vivió en el espíritu, escondida con Cristo en Dios; la lucha,
vigilancia y oración, la angustia, ansiedad de alma, aflicción,
agonía y sufrimiento que soportó,
con respecto a muchos con quienes estaba relacionado y mantenía correspondencia,
no puede contarse, porque sólo se conoce la parte más pequeña de ella.

Su última enfermedad parece haber sido un tipo de hidropesía,
que se manifestó hacia finales de marzo de 1679,
y le causó mucho dolor y falta de aliento.
El 30 de marzo, estaba externamente muy débil, pero internamente rebosaba de amor,
y estaba rendido a la voluntad y beneplácito de Dios.
El 31, a la una de la tarde,
sufrió un severo ataque que le produjo convulsiones en las extremidades.
A partir de ese momento, parecía estar muriendo poco a poco.
Pasó la noche siguiente en una silla cómoda con gran dolor,
especialmente por su respiración entrecortada.
Sin embargo, cuando algunos de sus queridos amigos,
que percibían los indicios de que el fin se acercaba
y se despidieron de él para la eternidad,
les habló a cada uno de ellos, según sus circunstancias particulares,
en una forma tan edificante, afectuosa y consoladora,
que todos se conmovieron profundamente, incluso hasta las lágrimas.
Él permaneció internamente firme y completamente rendido a Dios,
y a Su santísima voluntad.

Entre estos amigos y conocidos, también estaba el reverendo E+++_____+++,
quien le pidió al santo moribundo una bendición, ante lo cual,
sonriendo levantó su mano y dijo: "`¡Jesucristo, nuestro gran Sumo Sacerdote,
que se sienta a la derecha de Su Padre celestial,
levante Sus manos desde Su santuario y te bendiga con amor y paz en tu corazón,
y te otorgue gracia y sabiduría en tu ministerio!`"
Este predicador poco después siguió a Tersteegen al mundo eterno.
A otra persona, que se despidió de él, le dijo: "`¡Oh, hermana.
El camino es un buen camino; sigue al Cordero con alegría,
adondequiera que te guíe!`" A un tercero, le habló así: "`¡Te encomiendo por la gracia,
al amor de Jesús! Deja que el momento presente también sirva para
animarte a rendirte completamente a nuestro querido Salvador,
y a suplicarle Su gracia,
como hizo la mujer de Caná. Esta gracia debe ser
solicitada sin tener en cuenta las cosas temporales,
que son de menor valor de lo que generalmente se supone.
Y cuando nos veamos obligados a separarnos de ellas,
¡qué gran felicidad será para nosotros experimentar que, en Cristo,
tenemos un Dios tan misericordioso!`"
Les habló de esta manera, a todos los que estaban presentes con mucha energía,
afecto y unción divina.

Del 1 al 3 de abril,
por causa del asma se vio obligado a permanecer sentado
por cuarenta y siete horas seguidas en su sillón. A veces,
se inclinaba hacia atrás por unos pocos minutos en él,
y luego se inclinaba de nuevo hacia adelante sobre un almohadón que estaba sobre la mesa.
Pasó estas cuarenta y siete horas en gran agonía, y sin embargo,
nunca se le oyó quejarse, excepto después de haber dormido unos pocos minutos,
y al despertarse de nuevo decía: "`¡Oh Dios! ¡Oh Jesús! ¡Oh, dulce Jesús!`"

Durante todos sus sufrimientos extremadamente dolorosos,
no hubo ni la más pequeña expresión de impaciencia visible en su semblante.
Esta extraordinaria paciencia y completa rendición a la voluntad y beneplácito divino,
fue de gran consolación para los que estaban a su lado,
como también su filial confianza en Dios,
Cuya voluntad era perfeccionarlo así a través de los sufrimientos,
y hacerlo semejante al Capitán de su salvación. Sin esta consolación,
habría sido imposible para ellos, como ellos mismos afirman,
haber soportado la visión de sufrimientos tan agudos, en alguien a quien tanto amaban.
Hacia el mediodía del 2 de abril, era evidente que se aproximaba su partida;
los ratos de sueño se hicieron más profundos y se
acortaron los ratos en que estaba despierto.
Era necesario recordarle constantemente lo que tenía que tomar.
Durmió casi continuamente a las seis y a las siete,
y a las nueve fue casi imposible despertarlo para que tomara lo que se le había recetado.
Su sueño se fue haciendo poco a poco más profundo,
y a medianoche no se le pudo despertar más. Continuó dormido hasta las dos de la mañana,
cuando exhaló su alma en los brazos de su Dios y Salvador,
y murió feliz el 3 de abril de 1769.
Los que estaban presentes, se imaginaron rodeados por una multitud de ángeles,
que recibían con gozo al espíritu que partía y lo conducían
triunfalmente al reino eterno de éxtasis y deleite,
donde ahora él, junto con todos los santos ángeles y las huestes redimidas,
le atribuyen eterna aleluya a Dios y al Cordero,
y en la plenitud de la bienaventuranza celestial, se une a sus más exaltados cánticos.
¡Amén! ¡Alabanza, honor, acción de gracias,
sabiduría y gloria sean dadas a nuestro Dios y al Cordero,
por los siglos de los siglos! ¡Amén!
