== Sobre la Sombra y Sustancia, Forma y Poder de la Piedad, en una Carta a un Amigo

[.blurb]
=== "`Teniendo la apariencia de piedad, mas negando el poder de ella.`" 2 Timoteo 3:5 (RV1602P)

[.salutation]
Querido amigo,

Si tuviera que comunicarte mis pensamiento sobre
el contenido del manuscrito que me ha sido enviado,
debería decir brevemente, que todo lo que no es interno,
ni tiene a Dios mismo en Cristo como su fundamento y fuente,
sólo puede ser llamado mera sombra, y no sustancia y esencia de la piedad.
A partir de esta proposición general,
no es difícil deducir todo lo que tengo que decir sobre el tema.

I+++.+++ Cuando nos conducimos o mostramos delante de los hombres, en conversación,
acto o gesto, de manera distinta a lo que queremos decir,
o diferente a lo que somos en realidad, o deseamos ser,
por muy secreta o sutilmente que esto suceda, no caminamos en sencillez;
es falsedad y no verdad; o al menos, algo asumido y simulado;
una sombra y no la sustancia; una abominación ante los ojos de Dios.
No sólo es erróneo mostrarnos _mejor_ de lo que somos,
sino que además es una pretensión inapropiada,
o incluso un vano deseo de ser mejor considerados,
cuando nos presentamos (ya sea en palabras o de otra manera) más pobres,
más miserables y peores de lo que realmente creemos y sentimos ser.

He empleado a propósito la expresión "`somos o deseamos ser`" anteriormente,
porque una persona que es mala, orgullosa, irritable, etc.,
pero que sinceramente desea poseer las virtudes opuestas,
según la ley divina y su propia conciencia,
debe resistir el mal y reprimirlo para que no se manifieste; y al hacerlo,
tal persona ni simula ni actúa como hipócrita.
Por el contrario, sería culpable de simulación, si permitiera que el mal se manifestara,
dado que se propone y desea en su corazón lo que es bueno y no lo que es malo.
Pero si la persona que reprime el mal que está dentro de ella--por ejemplo,
la ira--se comporta mansamente,
e imaginara que por ello ya posee esencialmente la virtud de la mansedumbre;
o buscara ser estimada por otros como una persona mansa, se estaría engañando a sí misma.
Tiene la apariencia, pero aún no posee la sustancia de esta virtud.

¡Dios mío, cuánta hipocresía,
formalidad y simulación impregnan al hombre caído y pervertido! ¡Cuán
pocos estamos conscientes de esta abominación en nosotros mismos,
ya que por causa de la densa oscuridad y confusión que llenan nuestras almas,
no percibimos lo que hay en ellas,
pues permanecemos muy poco con nosotros mismos y aún menos Contigo! ¡Enséñame Dios,
que estás indescriptiblemente cerca de mí, tanto externa como internamente;
enséñame a caminar bajo la observación de Tu ojo, en la luz pura de Tu verdad,
para que pueda practicar la sencillez en todas mis acciones y comportamiento!

II. De la proposición general anterior se deduce,
que todos los deberes que están incluidos en el servicio a Dios,
y que no tienen como su base y origen la devoción real de corazón,
ni la adoración a Dios en espíritu y en verdad, no son más que una sombra,
apariencia externa, una forma de piedad, pero no la sustancia.

Por lo tanto, hago la observación, de que no es bueno que una persona devota,
que camina en el Espíritu, se involucre en demasiados ejercicios religiosos,
porque por este medio,
el poder interior y el sentimiento de devoción fácilmente se debilitan y se cansan;
sino que debe atender y dedicarse con mucha más prudencia y sincera
devoción a los pocos y más moderados ejercicios que tiene.

No obstante,
si hay una sincera devoción de corazón en todos nuestros deberes religiosos externos,
nuestras obras no son entonces mera y vana sombra,
sino que son aceptables a Dios en su medida;
incluso si aún no hemos alcanzado la adoración a Dios en espíritu y en verdad en su
sentido más completo--algo a lo que no podemos llegar por nuestros propios esfuerzos.

III.
Podemos inferir de aquí,
que toda luz o conocimiento de Dios y de la verdad divina que se nos comunique,
ya sea indirectamente desde afuera,
o que alcancemos por los esfuerzos de nuestra propia razón;
o si después de recibir de Dios alguna luz sustancial
de la verdad en nuestro centro o entendimiento,
la trasladamos a nuestra imaginación y razón, y nos formamos ideas de ella,
sacamos consecuencias o conclusiones de ella,
y obtenemos alguna medida de luz o conocimiento por nuestros propios
esfuerzos--aunque se trate incluso de los caminos más espirituales
e internos de la religión--toda esa luz y conocimiento,
por muy profundos, hermosos, placenteros e internos que nos parezcan,
puesto que sólo son una forma y no la sustancia de la verdad,
son en realidad una falsificación e imitación, un retrato,
la obra de nuestras propias manos,
en la que el amor al yo a menudo toma más deleite que en el original, o que,
tomados en su mejor sentido, sólo son una verdad especulativa--es decir,
cuando el conocimiento sustancialmente adquirido de la verdad en el interior,
se refleja y se representa en el espejo de la imaginación,
y así la persona contempla un objeto hermoso en ese espejo, pero no al objeto mismo.

Con esto no intento rechazar en modo alguno, toda clase de buenos medios externos,
o cualquier conocimiento adquirido que se utilice correctamente y a su debido tiempo,
ya que esto sería ir demasiado lejos.
Sólo deseo mostrar que hay una diferencia entre los medios y el fin,
entre la forma o imagen, y la sustancia.
La forma puede representar para nosotros la sustancia u origen e incitarnos a amarla;
los medios pueden conducirnos al fin propuesto, sin los cuales,
quizás nunca llegaríamos a él. Hacer uso de ellos
en el orden y grado apropiados es muy útil y loable,
pero es imprudente y peligroso detenerse ahí,
como si fueran el fin y la sustancia de la cosa misma.

El conocimiento especulativo o reflexivo es producto
de nuestra razón (nuestro entendimiento operativo),
y existen varios tipos de dicho conocimiento, según el estado de la persona;
pero el conocimiento sustancial y espiritual es resultado del entendimiento puro o pasivo.
El conocimiento reflexivo de la verdad es un pensamiento especulativo más o menos laborioso,
un esfuerzo o una operación de nuestro entendimiento o razón,
y no tiene la verdad esencial delante de sus ojos, sino una mera imagen de la verdad,
como en un espejo.
Pero el conocimiento espiritual de la verdad es una visión muy fácil y directa,
y un acto extremadamente sencillo de nuestro entendimiento, si puede llamarse acto,
cuando nuestros ojos ven y disfrutan la luz.
Aquel que posee este conocimiento espiritual también tiene la sustancia de la verdad,
según la medida de su gracia e iluminación.

A pesar de todo esto, obsérvese bien,
que de ningún modo rechazo el conocimiento reflexivo en su totalidad y sin distinción;
porque Dios nos ha dado una capacidad para este propósito,
la cual es nuestra imaginación y razón. Un alma que busca a Dios y Su verdad,
puede ocasionalmente recibir mucho apoyo y ayuda en su camino por medio de este tipo
de meditación. Tampoco podrían las almas iluminadas dar a conocer la verdad a otras,
si en alguna medida no hacen uso de su entendimiento activo,
y declaran la verdad de manera más o menos figurativa.

Es cierto, que durante los estados o caminos de sufrimiento purificador,
todo conocimiento reflexivo previamente adquirido, parece, por decirlo así,
caer y desvanecerse; porque donde se va a producir fruto, la flor debe caer primero.
Si la sustancia va a entrar en el corazón y la verdad presentarse ahí,
la imagen en el espejo debe ser cubierta,
para que la vista se aleje de ella y se vuelva al interior.
Sin embargo, incluso ésta frecuentemente nos es devuelta en la divina y buena voluntad,
y también de una manera mucho más pura, hermosa y viva.
Y después de que nosotros mismos, y los poderes de nuestras almas con sus operaciones,
hemos sido purificados,
Dios nos concede ocasionalmente una santa desviación y excursión de este tipo.
Sí, Él a veces nos lleva _afuera_ para mirar Sus pinturas y descripciones,
y luego _adentro_ otra vez, para que contemplemos la sustancia original de la verdad;
y así, entrando y saliendo con nuestro Pastor, encontramos alimento en todas partes.

Pero obsérvese:
1+++.+++ Que un alma interior no debe quedarse demasiado tiempo
o con demasiada frecuencia en este tipo de actividad,
ni dedicarse demasiado poderosamente y con toda su energía a ella,
sino que debe dejar que el Señor la guíe a ella,
en lugar de emprender algo por su propia voluntad.
2+++.+++ Además, debería ocasionalmente, e incluso con frecuencia,
interrumpir por completo este tipo de actividad y especulación mental,
para que pueda abrirse toda, ferviente,
desnuda y pasivamente ante Dios y ante la luz esencial de Su divina verdad;
de lo contrario, estaría en peligro de perder imperceptiblemente la verdad,
si siempre buscara su imagen y sombra, y deseara asirla como si fuera algo sustancial.

IV. La proposición general con la que comenzamos, nos enseña que toda piedad,
virtud y buena obra, que no brotan de la unión de la fe con Dios en Cristo,
como raíz interna de ellas, y por lo tanto,
no proceden del fondo de un corazón que ha sido cambiado por gracia,
no son lo que se les llaman ser, sino únicamente una semejanza,
una máscara y forma hechas por el yo, y no la sustancia de la cosa.
Más aún, cuando son contempladas en la luz de Dios, todo parece,
por causa de la depravación natural de su fuente, ser más malo que bueno;
"`pecados espléndidos`", como los llamó alguien.

Pero con esto no quiero decir, que todo lo que no es perfectamente bueno sea malo;
o que no debemos comenzar a practicar las virtudes,
antes de que puedan ser realizadas sin error,
o hasta que estemos seguros de un cambio real y universal de corazón. Cuando
un alma que busca a Dios hace el bien con toda la sinceridad posible,
con la intención de obedecer y agradar a Dios,
en verdad esto no está sin la gracia de Dios, ni es ninguna maldad,
o forma hecha meramente por ella misma; incluso,
suponiendo que aún no haya alcanzado un cambio total de corazón, y que por lo tanto,
la virtud no proceda puramente de Cristo.
El alma hace en ese momento, lo que la ley requiere de ella,
y lo que es capaz de hacer con la cooperación de la gracia capacitadora.
En definitiva, es necesario que no ponga demasiado énfasis en sus acciones,
virtudes o fidelidad, ya que todo es aún, sin duda alguna, muy humano e imperfecto,
e incluso son sólo la apariencia de virtudes,
en comparación con las virtudes espirituales,
las cuales el Espíritu de Dios produce en el alma en Su tiempo.
También es necesario que desestime todas sus acciones,
y se sumerja con humilde confianza en la gracia de Dios,
con anhelo interior y paciencia creyente,
prosiguiendo adelante hacia la unión con Cristo,
y esperando la operación de Su Espíritu en ella.
Pero es innecesario y muy peligroso para ella,
que se angustie con incesantes escrúpulos y abatimiento
en todos sus intentos de hacer el bien.
¡Que haga el bien que pueda, por muy imperfecto que sea,
y espere que el Señor la purifique y perfeccione! "`Ninguno hay bueno sino uno: Dios`".

V+++.+++ Cuando buscamos mediante nuestros propios esfuerzos, trabajo o actividad,
destruir y erradicar el mal, el pecado o el yo dentro de nosotros,
lo que es malo no es esencialmente matado ni destruido
en nosotros por tales esfuerzos bien intencionados,
sino únicamente en apariencia.
A veces parece estar muerto, pero aún no lo está, sólo está dormido y escondido,
y después sale a la luz de manera más peligrosa y terrible.
A fin de que el mal sea esencial y completamente matado y erradicado en nosotros,
Dios debe hacerlo y nosotros debemos estar pasivos bajo Su operación.

No obstante, lo primero precede a lo segundo.
Estamos obligados, según requiera nuestro estado y la gracia que hayamos alcanzado,
a resistir lo que es malo, suprimirlo y alejar totalmente nuestra voluntad de él;
y a anhelar internamente, completa redención a través de Cristo.
"`¡Oh, que de Sion saliera la salvación de Israel! ¡Oh,
que el Señor redimiera a Su pueblo de su cautividad!`"
Esto es, por lo tanto, una verdadera negación, crucifixión y sujeción del yo,
pero no es la verdadera muerte y disolución de la vida del yo,
lo cual es sólo obra de Dios,
un favor gratuito y una impartición de la muerte de Jesucristo.
Sin embargo, nadie muere con Cristo, si no está crucificado con Él.

"`¡Sí, oh Señor!
Cualquier cosa que pueda llamarse verdadera bondad, virtud, santidad,
es todo obra Tuya y un don gratuito de gracia.
(__Sin tu nombre, no hay nada en el hombre.__)

[verse]
____
Mi corazón, sin tu poder y gracia,
Un verdadero bien, nunca podrá poseer.
____

Cuán fácil es decir esto, pero cuánto cuesta aprender a practicarlo,
si sinceramente buscamos adquirirlo y no nos contentamos
con el mero exterior de este conocimiento.
"`¡Deseo, oh Señor, experimentar a través de Tu gracia, su sustancia y realidad.
Por tanto, que toda mi obra y virtud perezcan y desaparezcan de mí;
que en el día de prueba sólo Tu obra permanezca y reciba honor.
Sólo deja que Tu gracia nunca se aparte de mí,
no sea que Tu mano sea demasiado pesada sobre mí; porque sin Ti no puedo hacer nada,
no soy nada, y no tengo nada, sino pecado y miseria!`"

VI. Todo lo que tiene que ver con la religión del corazón,
o la vida y la devoción internas,
que no tiene como fundamento al Espíritu de Cristo y la
verdadera negación de nosotros mismos y de todas las cosas,
sino que lo producimos por nuestros propios esfuerzos,
y por el mero ejercicio de nuestros propios pensamientos,
es sólo una religión imaginaria, una sombra y una forma vacías, pero no la sustancia;
una falsa vacuidad.

Todo el misterio y la esencia de la verdadera religión
del corazón consiste en esta única cosa:
en vivir con Dios y en Su presencia;
pero nadie puede hacerlo si no muere a sí mismo y a todas las cosas.
Es verdaderamente muy bueno para el que lucha en pos de esta vida interna,
someter y controlar sus sentidos; no permitir que sus pensamientos,
especialmente los pensamientos de su corazón, vaguen sobre objetos innecesarios;
retirarse ocasionalmente, incluso externamente,
con el propósito de un recogimiento santo en la presencia de Dios; y en otros aspectos,
esforzarse en todas las cosas por vivir una vida separada del mundo.
Sin embargo, que sepa que con todo esto, nunca se convertirá en un hombre interior,
a menos que a través del poder y enseñanza del Espíritu, aleje su corazón,
deseos y afectos de todo, y los centre en Dios;
entregue dócilmente toda su voluntad en las manos de Dios;
y busque con sencillez poner al Señor delante de él en todas las cosas.
Ahora bien, cada vez que se esfuerza por entrar realmente a este estado mental,
esperando al mismo tiempo que la operación de Dios lo guíe sustancialmente a ello,
practica lo que se denomina "`recogimiento especial`". En otros aspectos,
es innecesario y peligroso tratar de colocarnos en un estado de devoción mental forzado,
unido con el ejercicio de las facultades de pensamiento.
La cabeza y todo lo demás seguirán, a su debido tiempo y sin dificultad,
si sólo el corazón y los afectos van delante.

No digo que un alma no pueda volverse al interior,
antes de que realmente se haya negado a sí misma
y esté muerta a sí misma en todas las cosas,
porque el volverse al interior y permanecer con Dios, antes mencionado, es el mejor,
más aún, el único medio de llegar a estar así de separada y humillada.
Sólo digo que, con toda su voluntad,
el hombre debe apartarse sinceramente de todo lo que no es Dios,
para poder retirarse a Él en su corazón. Aquel que actúa así,
no corre peligro de vacuidad falsa, y cuando continúa así con Dios, hace mucho,
sin hacer nada.

VII.
Otra inferencia de la proposición mencionada al principio es que,
si en nuestros ejercicios internos no nos mantenemos desnudos y abiertos delante de Dios,
en toda sencillez, humildad y rendición sumisa, tal como somos,
sino que nos mostramos de alguna manera diferentes,
o hacemos algo de nosotros que no tenemos ni deseamos tener;
entonces somos culpables de simulación,
y nuestras obras son una sombra creada por nosotros, y no realidad;
una forma y no sustancia.

Así actúan no sólo todos los que son manifiestamente hipócritas, que se acercan a Dios,
como Su pueblo, con sus labios, mientras sus corazones están lejos de Él,
sino que además hay personas sutiles y de doble ánimo,
que tampoco exponen toda su alma delante de Dios en sus ejercicios y oraciones más íntimos,
sino que en alguna medida, siguen cubriendo su desnudez con hojas de higuera.
¡Ah, cuánto se requiere,
antes de que los hombre se presenten totalmente desnudos y sinceros delante de Dios!
Puede que incluso los que son sinceros, por falta de atención,
ocasionalmente digan o piensen algo en sus oraciones,
que probablemente no encuentran o perciben en sí mismos;
o se presentan frecuentemente delante de Dios bajo un aspecto
y forma diferentes a lo que son y sienten ser;
lo cual, a veces proviene de lo que es llamado "`buena intención`",
mientras tratan con Dios como si fuera un hombre, que cuando es buscado,
a menudo se complace más si se usan algunas expresiones en particular,
o si la persona se presenta delante de Él con algún vestido específico.
Así, por ejemplo, el hombre puede presentarse, aunque sea inconscientemente,
con el manto de su propia virtud o piedad; en otro momento,
puede tratar de hacerse muy pobre y pequeño; y en otro,
colocarse en un estado de gran aflicción y contrición de corazón, etc.
Si la gracia de Dios produjera esto, estaría bien;
pero si intentamos lograrlo por nuestros propios esfuerzos,
y no esperamos que venga de Dios, entonces es algo hecho por nosotros mismos;
es una sombra, pero no la sustancia.

Pero para descubrir y evitar tales faltas y egoísmos en nosotros, no es necesario,
sino más bien perjudicial, estar siempre examinándonos de manera ansiosa y escrupulosa,
y considerando retrospectivamente todos y cada uno de nuestros actos internos.
Todo esto puede evitarse sin dificultad y peligro,
si no somos demasiado activos por nosotros mismos en nuestros ejercicios internos,
sino que miramos a Dios,
y pensamos más en Él que en nosotros mismos y en nuestras propias obras;
y en otro sentido, si buscamos mantenernos con toda sencillez,
inocencia y apertura en la presencia de Dios, tal como somos,
y como Él nos forma y coloca.

"`¡Oh, Dios! ¿Es posible que una criatura racional, incluso un alma creyente,
pueda disimular delante de Tu ojo que todo lo ve?
¡Quién lo podría creer,
si la melancólica experiencia no lo probara con demasiada frecuencia! ¡Ay,
miserable obra del yo,
por la que las almas sinceras permanecen mayormente en su propia luz,
de modo que son incapaces de percibir la insensatez de ese comportamiento asumido! ¡Señor,
libéralas a todas de esa obra,
y a Tu siervo también! ¡Mediante Tu luz y juicio estrictos,
quita todas esas arrugas y cubiertas de nuestros corazones;
ata las manos y los pies de nuestra imperfecta obra del yo;
examina minuciosamente lo más profundo de nuestras
almas con la espada de dos filos de tu Palabra viva;
y expón desnudas y abiertas nuestras entrañas y lo más íntimo de nuestras almas ante
la luz de Tu semblante sanador! ¡Haznos hijos sencillos y pacíficos delante de Ti,
y colócanos Tú mismo en esa forma y figura en la que prefieres vernos,
hasta que por Tu Espíritu todos seamos transformados de gloria a gloria,
en la imagen original de Tu semejanza!
Amén`"

VIII.
Cuando observamos algo bueno en otros, o cuando leemos o escuchamos algo,
o de algún modo recibimos luz y percepción sobre
alguna buena disposición o estado de la vida interior,
y fijamos nuestra imaginación fuertemente sobre eso, sin la guía y gracia de Dios,
y por decirlo así, nos establecemos en eso antes de que Dios nos introduzca allí,
no tenemos la realidad ni la sustancia de ese bien o estado particular,
sino únicamente la forma de él.

Todo lo que vemos, leemos,
oímos o consideramos con deseos ardientes y fuertes sentimientos de devoción,
imprime su forma o imagen en nuestras mentes, pero no su sustancia, a menos que la fe,
como el deseo hambriento interior del alma, se apodere al mismo tiempo de la sustancia.
De ahí,
que aquel que se relaciona frecuentemente con personas
piadosas y disfruta de la compañía de ellas,
a menudo asuma inconscientemente muchas de sus expresiones, hábitos,
comportamientos y opiniones, lo cual no siempre es inapropiado,
pero no deja de ser sólo una forma, pretensión e imitación,
si él no posee al mismo tiempo la sustancia interior de ello.

De igual manera, a veces podemos leer sobre otros,
o sobre estados de la vida interior mucho más elevados que en el que caminamos,
o sobre aquellos en los que el Señor aún no nos ha introducido,
y formarnos una concepción, imagen o idea de ellos.
Si esto es hecho con frecuencia y con fuertes sentimientos de devoción,
encontraríamos que lo leído está tan profunda y vívidamente
impreso y expresado dentro de nosotros,
que podríamos ser fácilmente conducidos a imaginar
que poseemos la sustancia de dichos estados,
cuando en realidad, sólo tendríamos la imagen de ellos.
En este sentido, por ejemplo, una persona que aún no está muerta a sí misma,
o es bastante novata, podría engañarse peligrosamente a sí misma,
si leyera mucho sobre la oración pasiva o sobre estados exaltados.
Y por el contrario,
aquella a quien Dios le concede este noble don de oración (ya sea como un anticipo,
o de una manera más permanente) y le da sentarse a Sus pies con María,
podría causarse a sí misma mucha angustia inútil o dañina,
si lee con ferviente devoción sobre la oración activa.
Igualmente, una persona que disfruta mucha devoción dulce y sensible,
podría imaginarse en el estado contemplativo;
y una persona contemplativa podría confundirse y angustiarse,
si oyera o leyera mucho de pruebas severas,
dolorosos sufrimientos y dispensaciones purificadoras.

Por lo tanto,
no es provechoso para alguien que no está bien establecido en el estado
o en la senda por la que Dios planea conducirlo particularmente,
leer gran cantidad y variedad de libros y relacionarse con todo tipo de personas,
por buenas y excelentes que sean; pero le es provechoso,
mantenerse principalmente con aquellos buenos hombres, por cuyo medio recibe poder,
unción y gracia para la devoción y recogimiento; tales como los que, en cierta medida,
concuerdan con su vocación particular y con la manera en que es guiado,
al entrar en la mente, por decirlo así, sin compulsión y con secreto deleite,
haciendo así suficientemente evidente, que son adecuados para él,
al menos en ese momento.
Porque aunque la persona debe amar a todos los hijos
de Dios y puede relacionarse con ellos,
y aunque no se le prohíbe leer otros libros que traten del camino interior,
aun así es bueno hacerlo con moderación, y sin fuertes sentimientos de devoción,
para que la mente no se perturbe, se inquiete ni se llene de imágenes.
El que camina a través de un desierto por un camino desconocido,
no debe mirar siempre a un lado, ni querer examinar cada recoveco,
si desea evitar desviarse.

IX. Cuando recibimos en nuestras mentes alguna impresión, vivificación, dulzura,
unción y paz de Dios en particular, o cualquier otra gracia y comunicación divina,
y buscamos retenerla o incrementarla por nuestros propios esfuerzos,
o incluso a partir del amor al yo;
o cuando nos esforzamos por avivarla dentro de nosotros usando nuestras propias fuerzas,
o nos esforzamos por experimentar algo de ese tipo; todo es una producción nuestra,
que sólo obstaculiza nuestro progreso, y aunque llegáramos a tener éxito en ello,
según nuestras propias ideas, aun así todo lo que se lograra sería algo meramente humano,
no divino; una imagen, una sombra y no la realidad.

"`¡Enséñame, oh Señor, a vivir en completa rendición y dependencia infantil en Ti,
para que pueda recibir con humilde agradecimiento lo que das; pero sin apoderarme,
desear, ni tratar de retener lo que Tú no das, ni me permites conservar.
Oh, que pueda ser en Tu mano como cera blanda,
que se deja moldear a tu placer en todas las formas,
y no coge otra forma sino la que el amo le da.
Seré como Tú me hagas, y no de otra manera,
y gustosamente continuaré desprovisto de eso que Tú no das,
o que después de habérmelo dado, lo quitas de nuevo,
para que yo pueda descansar sólo en Ti y en Tú sagrado beneplácito!`"

X+++.+++ Sólo lo que pasa en el espíritu, en lo profundo del alma; lo que ahí es hecho,
sufrido, experimentado y disfrutado, es, propiamente hablando, sustancial,
ya que procede directamente de Dios,
y ocurre en la parte más noble y esencial del hombre; pero todo lo demás,
todo lo que pasa en los poderes del alma, los sentidos internos o externos, etc.,
por muy bueno, útil y necesario que sean en su tipo y en su época,
cuando es comparado con lo anterior, sólo es la forma y no el poder.

¡Cuán buenos y provechosos, sí, cuán necesarios son, con frecuencia,
las tiernas y sensibles dulzuras, refrigerios y deleites en las cosas buenas y divinas,
y en otros dones de gracia similares,
para alejarnos de los falsos goces del pecado y de los placeres transitorios
de este mundo! ¡Pero cuán obstructivas y dañinas son estas cosas buenas y útiles,
cuando nos complacemos en ellas y no le devolvemos realmente a Dios todo;
cuando nos detenemos ahí y deseamos erigir nuestros tabernáculos en un lugar tan agradable;
cuando no consideramos estas cosas como dones de Dios, sino como Dios mismo;
cuando consideramos el palpable placer que disfrutamos en
el recibimiento de estas expresiones de la bondad divina,
como la unión real y esencial con Él! ¿No es esto también tomar la sombra por la sustancia,
o al menos, la flor por el fruto; abrazar a Lea en lugar de abrazar a Raquel?
(Génesis 29:
25-27) Eso que es palpable tiene ciertamente alguna
semejanza con lo que es realmente espiritual,
pero no son por ello, una y la misma cosa.

Finalmente:
También podemos observar sobre este tema,
que todos los actos internos de oración y devoción, de recogimiento, humillación,
rendición, adoración y amor, etc.,
en la medida en que proceden únicamente de nosotros--es decir,
todo lo que no es Dios ni Su obra en nosotros,
cuando se ve en su propia luz--son algo hecho por el yo y sólo una forma,
pero no la sustancia de la piedad.

Cuando una persona,
al pasar por muchas pruebas y caminos de humillación es en alguna medida purificada,
y por lo tanto,
se le permite experimentar en su centro la pura y sustancial operación de Dios,
todo lo que había hecho o experimentado previamente,
incluso su más interna y sencilla actividad en comunión con Dios,
a pesar de la gracia que cooperó con ello, se manifiesta sensual, impuro e imperfecto,
como algo simulado y no real, y como algo humano, mezclado y sin valor.
Sin embargo, lo que precedió a este estado no debe ser rechazado completamente como malo,
ni menospreciado;
mucho menos debe ser considerado así con respecto a otras almas buscadoras,
que quizás no hayan experimentado operaciones similares puramente divinas.
Porque el alma que tiene estas experiencias mayores y sustanciales,
no considera las anteriores como buenas en su tipo y género,
sino como lo que son en comparación con la sublimidad
y pureza de la operación sustancial de Dios,
la cual el hombre experimenta en ese momento, y con referencia a la cual,
como se dijo antes, todo le parece mezquino e insustancial.
Tal juicio es bueno y apropiado para sí mismo, pero no siempre es bueno y útil para otros.

Es difícil de creer cuán débil, sin valor y defectuoso es todo lo que hacemos,
incluso lo que es más interno y espiritual,
en la medida en que procede de nosotros mismos.
Por lo tanto, es muy aconsejable que una persona devota, en su interacción con Dios,
aprenda gradualmente a dejar de hacer sus obras carnales,
para que pueda guardar el Sabat del Señor,
y le permita trabajar en él por medio de Su Espíritu.
Y cuando al avanzar más en la experiencia de la operación pura de influencia divina,
perciba un desagrado y disgusto secretos en sus propias obras, y por el contrario,
una pacífica inclinación hacia la pasividad interior,
debe rendirse a esta guía de la Sabiduría divina, sin temer ningún peligro.

Pero para que una persona que no ha crucificado sus pasiones y deseos,
no tome de esto ocasión para un estado de apatía religiosa y falsa vacuidad,
puede hacerse referencia a lo que ya se ha dicho en los párrafos anteriores,
y también se puede observar la siguiente regla general,
excepto en un extraordinario estado de sufrimiento: Tan pronto como Dios obra,
nosotros debemos ser pasivos, y cuando no somos conscientes de Su operación,
debemos esperarla, como se dijo antes,
en una estado de sagrada calma y solemnidad en Su presencia.
Sin embargo,
no es aconsejable estar completamente tranquilos en tales momentos y no hacer nada.
Podemos, o más bien, debemos obrar en dichos momentos,
cuando la gracia nos dé la libertad de hacerlo, pero según requiera nuestro estado,
con total sencillez y fervor, con el corazón y afectos,
mansa y rendidamente en la presencia de Dios, y listos,
al menor indicio o conciencia de Su operación, a ser sumisos y hacerle sitio a Él.

"`Oh, Señor, Tú, todo suficiente e infinito Ser, supremo Ser, único Ser, sí, más que Ser;
sólo Tú puedes decir con verdad: _Yo Soy._
Y este '`Yo Soy`' es tan ilimitado e indudablemente verdadero,
que no se puede encontrar ningún juramento que coloque la verdad más allá de toda duda,
que cuando sale de Tu boca esta palabra: '`Yo Soy`', '`Vivo Yo`'`".

"`¡Sí, amén! ¡Tú eres!
Mi espíritu se inclina delante de Ti, y mi alma confiesa desde lo profundo, que Tú eres.
¡Cuán feliz me considero de que Tú seas,
y de que no puedas dejar de ser! ¡Cuán bendito soy al saber que Dios es,
y que puedo hacer esta confesión: Dios es! ¡Escuchen ustedes todas las criaturas,
Dios es! ¡Me gozo, oh Dios, en que Tú eres;
me deleito en que Tú eres! ¡Qué bendición y felicidad es que Tú seas tan bueno, que eres,
y que seas quién eres!
Preferiría no ser yo y que las cosas no fuesen, a que Tú no fueses`".

"`¿Pero qué soy yo y qué son todas las cosas?
¿Soy yo realmente, y es todo realmente?
¿Qué es este _yo_?
¿Qué es este todo?
Nosotros somos, sólo porque Tú eres y porque Tú quieres que seamos;
pobres y diminutos seres, que en comparación Contigo y en la presencia de tu Ser,
somos una forma y una sombra, e indignos de ser llamados un ser.
Mi ser, y el de todas las cosas, se desvanece delante de Tu Ser, por decirlo así,
mucho más pronto y en mayor grado, que ante el pleno resplandor del sol,
el cual es tan sobrepasado por la luz mayor que es como si no existiera.
¡Ojalá Tú me vencieras y me aniquilaras de esa manera,
y que al verte fuera yo desbancado, y por decirlo así, extinguido! ¡Tu grandeza,
mi pequeñez; Tu inmensa luz, mi parpadeante luz; sí,
mi oscuridad! ¡Tu más pura operación, mi obra defectuosa; Tu todo, mi nada!`"

"`Yo sólo soy una forma, una miserable sombra cuando Tú no estás en mí,
y yo no estoy en Ti; cuando Tú no eres la base y el ser de mi ser.
Todo lo que sé y todo lo que contemplo, no es más que una insignificancia sin vida,
creada por mí mismo; o al menos, una imagen incierta, una forma y sombra transitorias,
si Tú no me iluminas y si no me concedes contemplarte.
¡Oh, Tú, única verdad sustancial!
Todo lo que busco, todo lo que amo, todo lo que poseo es sólo una sombra y semejanza,
pero no realidad, si no te busco, no te amo y no te poseo.
¡Tú eres el único bien sustancial, el gozo, el deleite y la gloria de mi alma!
Todas mis obras, sí, cada movimiento y esfuerzo de mis poderes internos y externos,
son sombra y no sustancia, a menos que Tú mismo seas el origen y motor de ellos.
¡Sí, Tú, bien original, único y esencial, y vida infinitamente fecunda!`"

"`¿Pero qué digo?
Sin Ti, yo no sólo soy una forma y una sombra, sino un miserable y horrible monstruo;
y cuando obro por mí mismo, todas mis obras, por muy buenas y santas que puedan parecer,
son odiosas; más aún, pecaminosas ante Tus ojos, no sólo porque proceden de mí,
que soy completamente pecaminoso y corrupto, sino también porque busco,
complazco y me exalto en todas las cosas,
bajo los más plausibles pretextos y apariencias,
y me atribuyo la gloria de lo que más justamente te pertenece.
¡Oh, que cosa tan espantosa es el yo!
Me aborrezco con razón, cuando me contemplo ante la directa presencia de Tu pureza.
Me invade el yo; soy egoísmo puro;
todos mis movimientos internos y externos son egoístas; todas mis virtudes,
al proceder de mí, son egoístas e impuras ante Tus ojos`".

"`¡Ojalá yo no existiera más, ni tuviera en _mí mismo,_ ni vida, ni entendimiento,
ni voluntad, ni pensamiento, ni ningún otro movimiento; y que Tú, mi Dios, mi Jesús,
fueras y obraras todo en mí! Haz que aquello, oh Señor, que Tú no hablas ni obras en mí,
permanezca en silencio y cese para siempre.
Condena y destruye en mí todo lo que no eres Tú,
y lo que no es de Ti. Toma completa posesión del lugar que ahora ocupo yo,
y haz en mí y a través de mí, lo que sea agradable a Tus ojos.
Haz que yo no exista más, sino que sólo Tú seas todo en todo; y así,
llévame completamente fuera de mí mismo, y de todo lo que me pertenece, a Ti, oh mi Dios,
mi origen y mi fin.
Entonces, ya no estaré en un estado de inexistencia y apariencia,
sino en un estado de realidad, y seré liberado de todo mal,
para la gloria eterna de Tu nombre.
Amén.`"
