== La Verdadera Sabiduría o La Comunión con Dios y con Nosotros Mismos

"`Piensa que Dios y tú mismo están solos en el mundo;
y así poseerás gran paz de corazón`". --Thomas a Kempis

=== I. La Verdadera Sabiduría

Nada es por naturaleza más desconocido para nosotros que Dios y nosotros mismos.
Estamos ocupados e interesados en otros objetos, y en cosas irrelevantes e innecesarias;
pero nos olvidamos de Dios y de nuestras propias almas.

El hombre se ha vuelto tan falto de entendimiento por su triste caída,
que se ha apartado por completo de Dios,
tanto con sus afectos como con sus intereses y ocupaciones,
todo lo cual está enteramente dirigido a cosas externas, vanas y sin valor.
En efecto, esta insensatez y distracción de los sentidos llega a tal punto,
que como consecuencia de su ardiente y constante dedicación y atención a los insignificantes
intereses fuera de él--que no contribuyen en nada a su mejora o verdadera felicidad,
sino que incluso son un impedimento para dicha felicidad
y peligrosos para él--se olvida y descuida por completo,
para su desgracia temporal y eterna, no sólo de Dios sino también de sí mismo; o sea,
descuida su alma y el bienestar de ella.

¿No es sorprendente ver cómo criaturas racionales,
sumergen y entierran tan miserablemente sus nobles
facultades en las cosas visibles de este mundo?
Y aunque generalmente saben y reconocen que éstas son transitorias,
y que con toda seguridad deberán abandonar eventualmente,
aun así se dejan absorber tanto por el deseo, disfrute,
cuidado y consideración de tales vanidades, que se tambalean como borrachos o locos,
y se imaginan que han logrado una gran hazaña cuando
todo sucede según su deseo en el mundo.

Cada necio tiene su propio juguete y fantasía necia.
Un hombre se ocupa del honor y de la dignidad, otro del dinero y de la propiedad,
un tercero del placer y de la gratificación de los sentidos.
Piensan y hablan de comprar y vender, de casas y jardines,
de muebles y prendas de vestir, de comer y beber, y de todas las novedades que suceden;
y esto no puramente porque lo requiera la necesidad, y sin darle mucha importancia,
como razonablemente debería ser el caso, sino con toda su atención,
incluso como si fueran asuntos de la mayor importancia.

Sus corazones y cabezas, sus bocas y manos,
están llenas de cosas externas desde la mañana hasta la noche.
Lo único en que nunca piensan es en Dios y en el estado de sus almas,
al menos no de la manera en que deberían. Y sus acciones claramente evidencian,
que no consideran tales temas tan importantes y necesarios como otras cosas,
porque no se dejan tiempo ni espacio para ellos.
De hecho, a menudo emprenden actividades vanas o sin valor a propósito,
o recurren a compañías ligeras y alegres;
y a estas cosas y a otras similares las llaman "`matar el
tiempo`". Porque como las pobres criaturas ignoran la gran,
única e importante obra y asunto para el cual se les ha dado esta vida,
también son inconscientes de lo altamente necesario
que es para nosotros cada momento de ella.
Dicen que deben distraerse un poco, ¡pero ay,
la mente ya está tan lamentablemente distraída y desviada,
que es mucho más necesario que se sienten tranquilamente,
aparten todo su empeño y atención de las cosas externas,
y se dediquen por una vez a la consideración de sí mismas!

Por esta razón también,
aunque la gracia de Dios se anuncia internamente en la criatura con sus reprensiones,
aun así la constante confusión y desviación de la mente hacia objetos externos,
no le permiten llegar a ser verdaderamente seria con ella misma, como debería,
a fin de examinar el estado del alma con severa atención
y sinceridad en la presencia de Dios,
ni interesarse por lo único que servirá a la hora de necesidad y muerte.
¡Ah, qué conmoción experimentarán esos pobres espíritus,
cuando eventualmente cierren para siempre los ojos a todo objeto amado;
cuando despertados por la severa voz de la muerte,
lleguen finalmente al momento de la reflexión,
abran los ojos y experimenten demasiado tarde,
que el mundo con todos sus deseos se ha desvanecido como una sombra,
y que de todas sus muy preciadas baratijas y deliciosos sueños,
no les quedan más que imágenes vacías y perturbadoras!
En este estado lamentablemente ciego e inconsciente, pasa su vida casi todo el mundo:
grandes y pequeños, ricos y pobres, instruidos e iletrados.

Incluyo también a los instruidos de este mundo^
footnote:[Aquí se hace referencia a aquellos sabios,
que mediante la árida especulación y los fecundos esfuerzos de su razón pervertida,
pretenden adquirir sin la iluminación divina, el conocimiento de Dios y Su verdad,
y pierden su tiempo en aprender e investigar tantas sutilezas inútiles,
opiniones innecesarias, acontecimientos externos y una variedad de ciencias menores,
que no sirven para nada en relación con lo principal.
Sin embargo, la verdadera erudición y los eruditos que son al mismo tiempo piadosos,
mansos y humildes de corazón, deben ser altamente estimados.
Véase Kempis, libro I, cap.
2 y 3.]; es decir,
a los que entre ellos se destacan de otros por su dedicación
al estudio de las cosas espirituales y divinas.
Éstos, en su mayoría, no son más sabios,
y continúan tan igualmente ciegos y apartados de Dios, y tan ignorantes de sí mismos,
como los demás,
aun cuando todo lo que hacen es supuestamente con
referencia a Dios y a la salvación de las almas.
¡Cuán vanas y poco provechosas, e incluso perjudiciales,
son la mayor parte de sus actividades! ¡Sólo hay que ver la palabrería innecesaria
y los preámbulos elocuentes que hacen antes de llegar a un punto!
Me parece tan absurdo, o incluso más,
que si una persona que tiene la intención de viajar a Roma,
imaginara que primero debe estudiar todos los viajes y travesías, no sólo a Roma,
sino a todas partes del mundo,
y que luego formara un concepto detallado de ellos en su memoria,
pero que al mismo tiempo, nunca emprendiera su viaje,
imaginando que ha hecho mucho progreso en él,
aunque permaneció sentado en casa tranquilamente.

Ocurre a menudo, que muchas cosas buenas entran en la cabeza,
pero no en el corazón ni en la práctica.
Es como si estas cosas buenas no tuvieran relación con sus vidas,
y que sólo necesitaran saber y hablar de ellas.
Por lo tanto, a pesar de todo su trabajo, investigación,
debate y meditación sobre las cosas divinas, nunca llegan a conocerse a sí mismas,
y mucho menos a conocer a Dios;
sino que están constantemente corriendo alrededor
del exterior de sí mismas y de las cosas,
mientras que por los múltiples y violentos esfuerzos del entendimiento natural,
y la continua distracción de la mente,
la intención se vuelve más y más diversificada y absorbida en sus imaginaciones,
de manera tal,
que el individuo se vuelve cada vez más incapaz de prestar atención a su propio corazón,
a Dios, y a las operaciones internas de Su Gracia.
Hacen mucho ruido y discuten acerca de la cáscara,
mientras que los simples se llevan tranquilamente la semilla.
Sin embargo, estos personajes piensan que actúan más sabiamente que los demás,
y que de esta manera han empleado bien su tiempo y fuerzas.
Pero ¡ay!,
cuando sus estudios y ocupaciones más importantes
y serios se ven con calma en la presencia de Dios,
¿qué es todo esto sino vanidad de vanidades, y aflicción de espíritu;
viendo que no sirve de nada en cuanto a la verdadera santificación y comunión con Dios?

El Altísimo se ríe de toda las imaginaciones artificiales de los sabios de este mundo.
Y ellos mismos, cuando la muerte y el juicio los llamen,
finalmente deberán lamentar con vergüenza y dolor la insensatez de haber gastado
el valioso tiempo de su corta vida en tantas cosas innecesarias e infantiles,
y de haber perturbado y consumido sus nobles facultades mentales,
las cuales fueron dadas por Dios para objetos mucho más elevados.^
footnote:[El erudito Hugo Grotius es un ejemplo de esto, quien,
a pesar de ser considerado una figura destacada en filosofía, teoría política,
derecho y campos asociados durante el siglo XVII, exclamó en su lecho de muerte:
"`¡He gastado toda mi vida empleándome ingeniosamente en cosas
sin importancia!`". Se dice que sus últimas palabras fueron:
"`Entendiendo muchas cosas, he logrado nada`". --Nota del Editor.]
Ojalá se vuelvan sabios, y con arrepentimiento busquen olvidar lo que han aprendido,
con tanta pérdida de tiempo, para no conocer más que a Cristo y a éste crucificado.

Pero para acercarnos un poco más al punto.
¡Cuán lejos y ajenos a Dios y a sus propios corazones,
están la mayor parte de los que son llamados! ¡Cuán mal vigilamos nuestros propios corazones!
¡Qué poco nos quedamos en casa para para estar en compañía de Dios y de nosotros mismos,
para dejar de lado todo lo demás, y hacer de esto nuestro única,
constante y principal ocupación! ¡Oh,
cuán lamentable es que nos dejemos seducir y desviar tan fácilmente y de tantas maneras,
por la sutileza del adversario, de la gran obra hacia otros asuntos y puntos menores;
de Dios y de nuestro interior, hacia otros objetos y a lo que es externo!

¡Con cuánta frecuencia dejamos vagar nuestros pensamientos y sentidos
hacia cosas innecesarias (no diré vanas y malvadas)! ¡Cuán a menudo sumergimos
y enredamos nuestras mentes en las preocupaciones externas de la vida
presente! ¡Cuán inquisitivos somos para oír y hablar de todo lo que sucede,
y de lo que hace tal o cual persona, que rara vez nos concierne,
ni puede beneficiarnos! ¡Qué lamentable es la perniciosa costumbre
que tienen las personas bien intencionadas de reunirse,
hablar y juzgar a otros con tanta prontitud y frecuencia!
¿Y qué otra cosa puede resultar de todo esto,
sino inquietud, oscuridad y frialdad de corazón, desenfreno de pensamientos,
irreverencia y alejamiento de Dios y de lo interno?
¡Ah, me temo que muchas personas, como consecuencia de esta trivialidad,
están tan poco familiarizadas con Dios y consigo mismas,
que saben mejor lo que hacen otras cien,
que lo que pasa en su propio corazón y es obrado en él por Dios!

¡Oh, cuán indispuestos estamos a volvernos a nosotros mismos!
Si hay algunos que han recibido un poco de Luz de Dios,
para percibir en cierta medida la corrupción universal
que reina en sí mismos y en los demás,
o poseen algún entendimiento o impresión de alguna verdad en particular,
la sutil serpiente inmediatamente se apresura a desviar la mente de sí misma,
al exterior, hacia otros.
Así entonces, el individuo emplea esa Luz y esa Gracia,
que sólo se le concedió para que pudiera conocerse y enmendarse a sí mismo,
para considerar a los demás y olvidarse de sí mismo; para juzgar a otros,
ser celoso contra otros, y esforzarse por convertir a otros,
mientras él mismo permanece dentro de su propia miseria y corrupción,
generalmente sin ser consciente de ello.
Porque mientras ve y juzga todo tan aguda y minuciosamente en los demás,
le parece que él mismo no corre mucho peligro.
Junto con esto, hay una variedad de pretextos aparentemente correctos para actuar así;
tales como, que debe dejar brillar su luz y emplear su talento,
que es celoso de la gloria de Dios y está bajo la obligación de reprender el pecado, etc.
Mientras tanto, no percibe la intención del adversario,
que sólo busca dirigir la mente hacia afuera y envolverla en distracción y desenfreno.

También hay otros, que deseosos de asegurar sus propósitos,
utilizan una variedad de medios externos y devociones externas.
Ellos oran, escuchan, leen, meditan, se asocian con gente buena y cosas por el estilo;
todo lo cual sería bueno y provechoso,
si tales ejercicios sólo fueran empleados en la manera y con el fin apropiados.
Pero muchos ponen tanto énfasis en los medios,
que pierden de vista el fin y lo descuidan por completo.
Porque, aunque Dios ha instituido y nos ha concedido tan excelentes ayudas,
para que por medio de ellas dejemos de entretener nuestros
sentidos con cosas externas y nos volvamos a nosotros mismos,
a nuestro interior, y a Su verdadera adoración en Espíritu y Verdad; aun así,
tales ayudas se han convertido en un verdadero impedimento para muchos,
porque se aferran tanto a ellas, que sus sentidos se mantienen en constante distracción,
y las influencias de la gracia son agotadas.
¡Y cómo podrían aquellos, cuyos sentidos y razón están en continua acción y agitación,
alcanzar un conocimiento cabal de sí mismos y tener comunión con Dios,
dado que no buscan, ni siquiera en sus oraciones,
alcanzar verdadera tranquilidad y recogimiento de corazón,
sino que tienen constantemente tantas cosas que hacer,
que decir y de las que quejarse con Dios, que el Señor, por así decirlo,
no tiene tiempo ni espacio para decirles una palabra en respuesta.
(Salmo 85:8)

Otra estratagema del gran engañador para obstaculizar y
refrenar a los bien intencionados de la única cosa necesaria,
es cuando los incita a un esfuerzo,
investigación y especulación inmoderados de la razón presuntuosa,
por medio de lo cual a menudo se enredan en toda clase de disputas inútiles en la teoría,
ceremonias externas, consideraciones de menor importancia,
o en sutiles argumentaciones y opiniones en particular.
Así pues, éstos suelen buscar, sin dirección e iluminación divina,
desentrañar y comprender con su razón los misterios más profundos;
y muchos a menudo admiran su propia luz y progreso,
cuando encuentran o aceptan alguna nueva idea,
por medio de la cual su alma no mejorará en absoluto,
ni tendrá ninguna importancia en el día final.
En efecto, hay muchos que consagran toda su atención y dedicación a tales cosas,
desperdiciando así imperceptiblemente sus fuerzas y su precioso día de gracia.
Porque como todo lo que hacen parece apuntar a lo que es espiritual,
no se observa el peligro; a lo cual se añade,
que la razón encuentra su vida y placer en tales ocupaciones,
que resultan más fáciles para la naturaleza, que seguir a Jesús, el Salvador,
de corazón y renunciando a todas las demás cosas.

Y así, un hombre es mantenido en un estado de distracción, desorden,
variedad y confusión mental, más obvio en uno y más convincente en otro,
aunque ellos mismos no suelan considerarlo así,
e incluso parezcan ser individuos muy piadosos ante los demás. El Altísimo
sabe cuán raros son aquellos que se vuelven verdaderamente sobrios,
y se vuelven a sí mismos;
los que procuran apartar su corazón y sus mentes
de todo lo que existe y ocurre fuera de ellos,
para poder caminar y tener comunión a solas con Dios en el Espíritu.
De ahí que la generalidad de las almas despiertas,
o bien viven en un estado de fría y falsa seguridad, o en un celo falso y piedad externa,
o continuamente lamentándose y quejándose sin hacer verdadero progreso en santificación;
y en lugar de disfrutar de una placentera libertad y profunda paz en comunión con Dios,
continúan internamente oprimidas por una pesada esclavitud.
Tampoco es de extrañar, que para muchos en sus lechos de enfermos y moribundos,
Dios y la eternidad les parezcan algo tan extraño, oscuro y terrible;
ya que sus mentes han estado fijas en cosas externas
y se han familiarizado muy poco con Dios y la eternidad.
¡Oh, la lamentable ceguera de la raza humana!

Pero bienaventurados y verdaderamente sabios son aquellos,
que con todo su corazón sólo se ocupan en la única cosa necesaria,
y sin abundar en palabras ni detenerse con los demás,
procuran vivir aquí como si estuvieran a solas con Dios en el mundo.
Este es el camino más corto y más fácil para alcanzar la completa,
genuina y cotidiana santidad y paz.
Pero habiendo percibido el lamentable abandono de este hermoso ejercicio en otros,
y para no olvidarme de mí mismo mientras escribo, y actuar tan tontamente como ellos,
me dirigiré ahora a mi propia alma,
y me daré algunos consejos adicionales sobre cómo deseo caminar con el Señor,
por medio de Su gracia, en el futuro.
Sin embargo,
me alegraría que cada lector los considerara y utilizara
como si sólo le concernieran a él;
y al actuar así, ciertamente nos irá bien a todos.

=== II. Consejos para el Alma

¡Por tanto, despídete eternamente alma mía, y tú que lees esto,
de las vanidades de este mundo, las cuales dentro de poco se desvanecerán como un sueño!

Todo lo que el mundo te pueda ofrecer no merece una sola mirada.
¿Qué posee ahora el hombre rico (Lucas 16:19, etc.) de su pompa y placeres?
¿Y de qué te servirían,
suponiendo que hubieras disfrutado de treinta o cuarenta
años de gratificación y esplendor mundanos?

¡Vanidad de vanidades!
En vano buscas fuera de ti lo que necesitas; es en tu interior, en tu corazón,
donde se encuentra el verdadero bien, tu gloria y felicidad.

Cierra tu corazón y tus sentidos contra todo lo que es y ocurre fuera de ti;
todos son asuntos ajenos que no te conciernen.
No prestes mucha atención a las cosas externas,
ni dejes que sea un obstáculo para ti eso que no
puede ayudarte en tu viaje hacia la eternidad.
Pasa a través de todo sin ser conmovido, como un extranjero y peregrino, cuyo corazón,
pensamientos y ciudadanía están en el cielo.

Procura convertirte en un niño pequeño e inocente en tu interior,
que no encuentra falta en nada,
y deja a todo el mundo actuar y hablar de él lo que quiera (incluso en su presencia),
sin prestar atención, ni dejarse perturbar por ello.

Aprecia el verdadero recogimiento hacia adentro, según el Espíritu te enseña,
y acostúmbrate a vivir y a permanecer dentro de ti mismo,
aunque por naturaleza estés inclinado a vivir y a moverte fuera de ti.
Que tu constante ocupación sea permanecer contigo mismo,
y así caminar con el Señor en lo secreto de tu espíritu,
como si estuvieras solo con Él en el mundo.

Para este fin vino y habitó en la carne tu Salvador Jesús,
para poder ayudarte a salir de tu carne y guiarte a casa, a Dios,
y a la comunión con Él. Él no tuvo aquí nada propio; sólo estuvo de paso.
Así como salió del Padre y vino a este mundo, también estaba deseoso de dejar el mundo,
e ir a Su Padre (Juan 16:8). Síguelo en este sentido.

Él te ha reconciliado de nuevo con Dios por medio de Su sangre, a ti,
que estabas bajo la maldición. Él te ha abierto Su corazón paternal,
y ahora está a la puerta de tu corazón,
y te ruega de mil maneras diferentes que te reconcilies con Dios (2 Corintios 5:20),
y recibas a este mejor amigo en tu corazón.

El Salvador te busca a ti y busca tu amistad tan cordial y sinceramente,
que murió por ti, para que, ya sea que estés despierto o dormido,
puedas vivir en íntima comunión con Él (1 Tesalonicenses 5:10). Por lo tanto,
recibe esta verdad con una fe sencilla;
y considera a Dios como el amigo confidencial y secreto de tu alma,
cuyas delicias son con los hijos de los hombres,
y está dispuesto a caminar contigo en espíritu, y a tener comunión contigo.

Los ojos de tu Dios están sobre ti; Él piensa incesantemente en ti.
Por lo tanto, que los pensamientos más íntimos de tu corazón se dirijan también hacia Él,
y no divagues en tus sentidos ni entre las cosas creadas.
Recuerda que todo tu tesoro y tu mejor amigo está en tu corazón,
y que con gusto estará en comunión contigo.
Por tanto, ¿por qué saldrías corriendo y lo dejarías solo?

¡Ah, quién no estaría dispuesto a olvidar toda cosa creada por causa de un Dios así!

Que parezca para ti,
como si estuvieras viajando en compañía de un amigo amable y querido,
a través de una tierra extranjera y una región desértica.
Haz todo,
sufre todo y asiente a todo lo que te ocurra en este mundo,
por amor cordial a este amigo íntimo de tu alma, sea poco o mucho.

Niega tu yo, por amor a Él, y muere a todo deseo de la carne y de los sentidos.
Sí, muere a tu engreída, ocupada y autocomplaciente razón,
y a los apegos secretos y deleites falsos en cualquier otra cosa fuera de Dios.
Que ningún deseo o pecado sea tan querido para ti,
ni haya nada tan firmemente aferrado en tu corazón,
como para no querer desprenderte de ello inmediatamente y de buena gana,
por amor al Señor.

Aunque otros sean ricos y de renombre, distinguidos y eruditos, vivan en placer,
despreocupación y alegría; aunque alguno ponga su gratificación y comodidad en esta cosa,
y otro en aquella; con todo, que sólo Dios sea suficiente para ti.
Lo que para otros es un bien transitorio y una necesidad de la criatura,
que para ti eso lo sea el Dios inmutablemente todo suficiente en tu corazón.

Por amor a Él, niega tu propia voluntad, tu amor al yo,
y la complacencia del yo en todas las cosas.
En pocas palabras, niégate a ti mismo dondequiera que aparezcas.

¡Oh, cuánto de este yo encontrarás,
cuando te hayas acostumbrado a permanecer cerca de ti mismo y cerca de tu Dios!

No le prestes mucha atención a tu cuerpo, no tiene valor alguno, es alimento de gusanos.
Es corrupto, lleno de propensiones y deseos malos,
que a menudo oscurecen y obstruyen el espíritu.
Debes considerar tu cuerpo de tal manera, y actuar tan reservadamente hacia él,
como lo hace un amo con su siervo.
Gobiérnalo sabiamente, y no le des, bajo pretexto de necesidad,
más de lo que es apropiado.
Aquel que estima su cuerpo y busca muchas cosas para su conveniencia,
jamás estará verdaderamente retirado, ni tendrá su mente puesta en lo espiritual.

No hagas mucha bulla cuando te pase algún inconveniente,
sufrimiento o decepción. Procura, con la gracia de Dios,
soportar todos los sufrimientos externos e internos con serenidad,
paciencia y mansedumbre, por amor a tu Salvador.
Sí, abraza la cruz y toda clase de adversidad, y ámala cordialmente;
porque nada es más provechoso para ti que morir a tu yo y desprenderte de todo,
para acercarte a Dios.

Morir continuamente al mundo y a ti mismo, y vivir así con Dios en lo secreto,
es la verdadera imitación de Cristo.
En esto consiste la suma y la sustancia del cristianismo.
Esto debe ser lo único importante para ti, tu única y diaria ocupación aquí en la tierra,
el único objetivo que debes tener continuamente a la vista en todas las cosas,
y a lo que todo lo demás debe ser dirigido.
Ejercítate en este asunto prioritario con sencillez y sin hacer grandes rodeos ni preparativos.

Recibe y utiliza todo lo que pueda ayudarte en esto, sea lo que sea,
con humildad y gratitud.
Pero no te enredes en nada.
No te apegues a nada.
No te contentes con nada que no sea el cumplimiento de este vital propósito.
Deja que Marta se afane por muchas cosas;
ésta es la única necesaria y siempre lo será. Y ésta es la única
que puede servir de ayuda y consuelo en tiempos de angustia y muerte,
cuando todo lo demás, por muy atractivo que parezca, te sea quitado.
Por tanto, haz que todo se dirija directamente a esta única cosa.

Lo que sepas, oigas o veas de lo que es de Dios,
llévalo inmediatamente de la cabeza al corazón; es decir,
procura hacerlo útil sólo para ti, mientras te esfuerzas por ejercitarte en ello,
o ser despertado y fortalecido por ello,
pero no sólo para saberlo y hablarle a otros al respecto.

Todo lo que te suceda en el mundo, ya sea interna o externamente, recíbelo con sencillez,
como de parte del Señor,
sin considerar el instrumento o las circunstancias
que lo acompañen. Sólo busca avanzar en lo principal,
en y mediante todas las cosas; es decir, avanzar en conocer y hacer morir tu yo,
y en la comunión con Dios.

No hagas mucha algarabía respecto a tu piedad, tu autonegación,
tus sentimientos o experiencias internas.
Deja que tu secreto permanezca entre tú y tu Dios.

Que sea suficiente para ti que Dios sepa lo que hay en tu corazón,
porque generalmente es demasiado para nosotros saber el bien que hay en nuestro interior;
ya que a menudo deja de ser bueno, cuando somos capaces de verlo en nosotros mismos.

El que vive en silenciosa atención a su corazón, en secreto con Dios, muere mil muertes,
y a menudo disfruta indescriptible deleite y bienaventuranza,
sin hacer mucho ruido al respecto.

No busques ser visto ni conocido por los demás. Esfuérzate por vivir en este mundo--tanto
como tu posición y vocación lo permitan--como un peregrino o un extranjero,
de quien se sabe, oye o habla poco, y que además,
sólo desea conocer y aceptar nada más sino a su Dios,
y no habla con nadie tan alegremente como con su Dios.
Teme cuando eres conocido y alabado; pero al contrario,
regocíjate cuando eres olvidado y despreciado,
porque de esta manera se bloquea el camino hacia muchos peligros y distracciones,
y ganas mucho más tiempo y oportunidad para permanecer
en tu interior y caminar a solas con Dios.

Sólo procura estar bien internamente con Dios;
entonces poco importará como te vaya en otros aspectos,
o lo que otros piensen o hablen de ti.

No te asocies innecesariamente mucho con los hombres de este mundo;
pero cuando estés con ellos y debas hacerlo,
procura mantenerte en tu interior como si estuvieras a solas con Dios.
Sé cercano a muy pocos, y sólo a los que encuentres útiles para fortalecer,
animar y motivar tu progreso en lo principal,
no sea que bajo la apariencia de ser algo bueno,
seas atraído a salir de Dios y de tu interior,
y tus amigos te roben tu pequeño y precioso tiempo.
Relaciónate únicamente con Dios y contigo mismo.

Quebranta gustosamente tu voluntad, para seguir lo que otro piensa que es correcto,
cuando no es contrario a Dios.
¡Ah, cuánto más fácil, pacífico y provechoso es obedecer que mandar!

Si tu condición y vocación no lo requieren,
no te detengas a observar o juzgar la vida y conducta de los demás. Aquel
que busca rectificar y enmendar todo lo que está mal en el mundo,
sólo se involucra en mucha perturbación y distracción,
y a menudo no es útil ni para sí mismo ni para los
demás. "`Ten cuidado de ti mismo`". ¡Oh,
cuán pacíficamente puede vivir un alma,
que no tiene necesidad de mirar mucho a otros ni pensar en ellos!

No obstante, ama a todos los hombres, sé amable con todos, y haz bien a todos,
en concordancia con tus circunstancias y capacidades internas y externas;
pero al mismo tiempo, continúa en temor santo y recogimiento interno,
para que tu mente no se distraiga, ni te enredes en múltiples asuntos.
Ama en particular a todos los piadosos y estímalos a todos,
incluso a los más humildes de ellos, de todo corazón, como mejores que tú mismo.

Ama la verdad y lo que es bueno,
y agradece a Dios por ello dondequiera que lo encuentres; no obstante,
no te detengas para sólo observarlo en los demás,
sino esfuérzate por ser bueno también. Ama también
a los que no caminan en todas las cosas como tú,
deja que cada uno siga su propio camino.
¿Qué a ti?
Sigue a Jesús.

No pienses mal de tu hermano, no juzgues, no te apresures,
haz la mejor interpretación de todo.
Si puedes enmendar sus evidentes faltas, hazlo con mansedumbre y con temor santo,
y regresa inmediatamente con humildad a ti mismo, en tu corazón. ¡Qué retirarte,
alma mía, sea para ti un asunto tan serio e importante,
que te haga dedicarte a ello con todo tu corazón!
Trabaja desde la mañana hasta la noche en eso,
y que internamente te parezca como si no tuvieras nada más que hacer en el mundo.

No permitas que nada irrelevante e innecesario detenga tu progreso.
El que busca "`guardar con toda diligencia su corazón`",
y seguir a Jesús en constante negación de sí mismo, encuentra tanto que hacer y sufrir,
que no le queda tiempo para ocuparse de otros asuntos.

Realiza lo que tengas que hacer externamente, en la medida de lo posible, sin deseo,
preocupación, ni ansiedad.
Hazlo todo únicamente con el fin de cumplir la voluntad del Señor con humildad;
porque de esta manera lo haces para el Señor y no
te perjudicará en lo que es verdaderamente necesario.

No dejes que tu atención se dirija con demasiado ardor, o más de lo necesario,
hacia tu empleo externo, para que hagas tu trabajo en un estado de tranquilidad,
y al mismo tiempo, guardes tu corazón y continúes con el Señor. ¡Ah,
cuán vano e insignificante es todo lo demás,
lo que se hace en el mundo sin Dios! ¿Cuánto consuelo o
provecho tendrás de todo tu trabajo a la hora de la muerte?
Sí, ¿qué te consolará en todas las dificultades de esta vida,
si no te esfuerzas siempre y en todas las cosas, por tener a Dios como tu amigo?

Pronto deberás partir de aquí y no volverás a ser visto.
De todo lo que tienes y ves en este mundo, nada podrás llevarte contigo al salir de él;
todos los hombres te abandonarán y tú deberás separarte de ellos, entonces,
tendrás que tratar sólo con Dios.
Esfuérzate, por lo tanto, en esta única cosa de ahora en adelante:
en abandonar todo lo que deberás abandonar entonces.

Actúa y camina con Dios de aquí en adelante, como si estuvieras solo con Él. ¡Oh,
cuán feliz es el que vive así,
en tranquilo recogimiento con su Dios y sólo busca conocerlo a Él y conocer la eternidad!
Para él, la muerte no vendrá como un ladrón en la noche,
ni tendrá que temer presentarse delante de Dios.
Porque así como vivió aquí para el Señor, así también morirá para el Señor;
y así como su vida aquí estaba escondida con Cristo en Dios, así también,
cuando Cristo su vida se manifieste, él también será manifestado con Él en gloria.
(Colosenses 3:3-4)

=== III. El Ejemplo de Cristo

Aquel que contempla con mente devota y tranquila la vida y conducta de Jesucristo,
desde el pesebre hasta Su muerte en la cruz, encontrará impresos y expresados en ello,
de una manera muy vívida y perfecta, los pasos que debemos seguir.
A continuación los señalaré brevemente.

El salvador Jesús, quien sin pecado, pudo haber vivido en este mundo con honor, riqueza,
alegría y placeres, rehusó hacerlo para darnos un ejemplo; y en su lugar,
escogió la crítica,
la pobreza y la aflicción. Dejó a Herodes y a los fariseos en posesión de sus estados,
dignidad, riquezas y comodidades,
y vivió la mayor parte de Su tiempo con Sus humildes y menospreciados padres
en Nazaret--un lugar muy despreciado y miserable--como un insignificante artesano,
tan completamente escondido y tranquilo,
que el mundo apenas sabía que un hombre llamado Jesús vivía en Nazaret.
Él pudo haber brillado en todas las cosas; no le faltaba entendimiento, sabiduría,
dones ni poder divino.
Pudo haber escrito las más excelentes obras sobre todas la ciencias espirituales y naturales,
que todo el mundo habría admirado y por las que muchos miles, según nos parece,
se habrían convertido.
Pero no se pretendía que brillara, ni Él lo deseaba.
Incluso en Su vida pública, trató en lo posible, de mantener ocultos sus milagros,
Su dignidad y gloria divinas,
y huyó de dondequiera y cuandoquiera que lo alababan y honraban.

Consideró Su vida aquí en la tierra como un paso a través de ella.
Él dijo: "`He venido al mundo; otra vez dejo el mundo,
y voy al Padre,`" (Juan 16:28). Su única preocupación
era ocuparse de la obra de Su Padre,
sin inquietarse por otros asuntos, para los cuales no había venido al mundo.
Incluso, así como en el corto tiempo de Su vida pública,
frecuentemente se apartaba de la gente para orar en secreto,
y a veces pasaba noches completas en soledad y oración a Dios,
así también es fácil suponer, que en Su larga vida oculta en Nazaret,
esta no dejó de ser Su ocupación más querida, constante e importante.
David y Pedro nos dicen,
que el Salvador se ejercitaba continuamente en caminar delante de Dios,
y en regocijarse internamente en Su Padre celestial.

Ellos lo presentan diciendo: "`A Jehová he puesto siempre delante de mí;
porque está a mi diestra no seré conmovido.
Por tanto, mi corazón se alegra, y se goza mi gloria, etc.`"
(Hechos 2:25-26). Y Su Padre no lo dejó solo,
porque Él se ocupaba de dirigir Sus ojos al Padre,
y en hacer siempre lo que era agradable ante Sus ojos,
entregando constantemente Su voluntad a la voluntad de Su Padre,
y tomando voluntaria y gozosamente sobre Sí los más dolorosos sufrimientos,
por amor a Él.

También dejó que los escribas y fariseos discutieran sobre sus opiniones particulares,
y se arrastraran bajo el peso de sus devociones externas y ordenanzas humanas,
y en contraste, les enseñó por medio de palabra y conducta, la única cosa necesaria,
de la cual seguían desprovistos.
Y así como no se mezcló en los debates inútiles de los sabios de la época,
tampoco intervino en otras cosas para las que no había sido enviado.
"`¿Quién me puso por juez o partidor sobre vosotros?`"
(Lucas 12:14), fue Su respuesta, cuando trataron de arrastrarlo a otros asuntos;
sin embargo, "`anduvo haciendo el bien a todos,`" (Hechos 10:38).

Él amó a los que eran sencillos, pobres y menospreciados,
y se relacionó con ellos alegremente cuando tenían deseos de buscar a Dios.
Él también fue imparcial en Su amor; la mujer samaritana fue tan querida para Él,
como lo era Nicodemo, que era un erudito de la ley;
y no menos queridas fueron aquellas personas, que en ese momento,
no se habían convertido aún en Sus seguidores, (Lucas 9:49-50). Incluso,
reprendió a Sus discípulos por enojarse contra los
que actuaban inapropiadamente (Lucas 9:54-55);
ni tampoco condenó al mayor de los pecadores,
(Juan 8:11). Meditó y practicó día y noche con infatigable diligencia,
la única obra para la que había venido; Su corazón y Su mente estaban tan llenos de ella,
que lo que veía y oía de las cosas externas,
sólo servía para conducirlo a las que eran espirituales,
de modo que inmediatamente aprovechaba la ocasión para hablar de ellas, (Juan 4:10).

Su doctrina fue congruente con Su vida.
Su doctrina consistía en que debíamos velar y orar siempre, y sin cesar;
en que debíamos seguirle mediante la negación de
nosotros mismos y tomando nuestra cruz diaria,
sin preocuparnos demasiado por los demás; en que una sola cosa era necesaria;
aparte de la cual, de nada le serviría al hombre ganar el mundo entero.

¡Que Jesucristo, el verdadero Pastor de nuestras almas,
quien nos ha redimido de la tierra y nos ha comprado con Su preciosa sangre,
pero que también, habiendo sufrido por nosotros,
nos ha dejado un ejemplo para que sigamos Sus pasos,
obre en nosotros por medio de Su Espíritu, para que la mente que estaba en Él,
esté también en nosotros.
Es decir, para despojarnos por medio de un profundo trato de la cruz,
de todo amor a nosotros mismos y a las cosas creadas,
para poder pasar los pocos días de nuestra peregrinación
en verdadera abstinencia de todo disfrute transitorio,
muertos al pecado, alejados del mundo y de nosotros mismos,
pero conociéndolo y relacionándonos con Él y en paz eterna;
y podamos seguirle ciegamente, como extranjeros y peregrinos,
y avanzar tranquilamente con Él, a través del desierto de este mundo,
hasta alcanzar nuestro verdadero y eterno hogar!

¡Sí, Señor Jesús, vuélvenos de nuevo a Ti, Tus ovejas perdidas y errantes,
y regresaremos a Ti!
Amén.
