== Breves Instrucciones Sobre Cómo Buscar a Dios y la Luz de Su Rostro

[.blurb]
=== "`Los que a Él miraron fueron alumbrados; y sus rostros no fueron avergonzados.`" Salmos 34:5

¡Oh, hombre, incluso tú que lees esto,
detente un momento y considera seriamente el noble propósito por el que fuiste creado,
y por el que Dios te ha colocado en este mundo!
No fuiste creado para el tiempo ni para las cosas creadas,
sino para Dios y para la eternidad, y para ocuparte en Dios y en la eternidad.
Estás en el mundo con el fin de que nuevamente busques a Dios y Su beatificante rostro
(del que te has vuelto por causa del pecado y te has aferrado a las cosas creadas),
a fin de que seas completamente santificado e iluminado, y de que Dios tenga gozo,
deleite, paz y placer en ti, y tú en Dios.

Sólo en esto reside tu salvación y bienestar, tanto temporal como eterna,
que nada fuera de Dios puede darte.
Los objetos externos de este mundo escasamente satisfacen a tu hombre exterior,
durante el corto período de tu afanosa vida.
Pero internamente,
tienes un hambre que no puede ser saciada y una mente que no puede ser satisfecha,
sino por un objeto todo suficiente e infinitamente digno de amor,
el cual es únicamente Dios.

¡Por lo tanto, oh alma,
si posees un deseo sincero de buscar y encontrar otra vez a tu Dios y Su rostro,
ten cuidado de no comenzar de manera inapropiada!

Dios es espíritu y está cerca de tu espíritu;
de ahí que no tengas que correr de aquí para allá,
ni distraerte con múltiples y variados ejercicios,
mucho menos con razonamientos y reflexiones que sólo sirven para confundirte.
Esta más bien sería la manera de alejarte aún más de Dios,
y de hacerte menos apto para el conocimiento de Él y de Su verdad.

Sólo busca ser conformado en tu mente a Dios; entonces,
infalible y fácilmente lo encontrarás y lo conocerás. Así como el que
desea contemplar y disfrutar del sol debe colocarse en su luz,
así también debes asemejarte a Dios para disfrutar verdadera comunión con Él. Esta eterna
e inaccesible luz sólo se ve en su propia luz (Salmo 36:9). Dios es un Ser espiritual,
eterno, ilimitado, sencillo, manso, sereno y beatificante.
Ahora, cuánto más alcances internamente estas cualidades,
más te aproximarás a Dios y más capacitado serás de Su manifestación y comunicación.

Dios es un Ser apartado y espiritual, ajeno a este mundo material,
a los sentidos y a la razón. Por lo tanto, si quieres encontrarlo y ver Su rostro,
debes también mantenerte, con tu espíritu, amor, afecto y deseos de tu corazón,
tanto como sea posible, separado y alejado del mundo y de todo lo que hay en el mundo.
No admitas voluntariamente ningún objeto creado dentro de ti,
ni fijes tu amor y afectos sobre ninguna cosa creada fuera de ti.
Evita toda distracción y ejercicio innecesarios de tus sentidos y razón.
Considera tu parte externa y racional como si fuera de otra persona,
y continúa en espíritu con tus deseos y afectos dirigidos hacia Dios dentro de ti.
Familiarízate con Él en lo más recóndito de tu espíritu
y no te preocupes por lo que ocurre externamente.

Dios mora en Sí mismo, en la eternidad.
Él es siempre el mismo; con Él no hay ni pasado ni futuro, sino un eterno ahora.
Por lo tanto, si tú deseas acercarte a Dios y tener comunión con Él,
evita toda reflexión innecesaria del pasado o del futuro, todos los razonamientos,
preocupaciones y búsquedas, y como un niño inocente,
permanece con tu mente y sentido en el momento presente con el Señor,
y deja que Él te cuide y te guíe.

Dios es un Ser universal, indivisible e ilimitado, y la razón no lo puede comprender.
Él no es esto ni aquello en particular, sino uno y todo.^
footnote:[Que no se suponga que esto es otra cosa que razón sólida.
El significado es que las excelencias particulares de una criatura pueden ser divididas,
medidas, limitadas y comprendidas; pero Dios es un Ser extremadamente simple.
Él no es una perfección particular,
sino todo lo bueno y toda perfección en una unidad
indivisible e incomprensible.]
Por lo tanto,
para conocer a Dios y acercarte a Él,
debes desprenderte suavemente de todas tus opiniones peculiares,
de todas tus imágenes y pensamientos infantiles y limitados de Dios,
someter tu razón a la sencillez de la fe,
y entrar con tu espíritu en una universalidad ilimitada y una serena extensión de mente,
sin objetos y reflexiones particulares, especialmente en el tiempo de oración.

Dios es la sencillez y la pureza mismas;
por esta razón nadie puede encontrarlo o verlo si no es
de corazón limpio y puro (Mateo 5:8). Por lo tanto,
procura, de igual manera, ser puro y sencillo en todas las cosas.
Sé recto y sincero en todas las cosas y en todo lugar, en tus actos, conversaciones,
pensamientos y deseos.
Que el ojo puro de tu mente mire directamente a Dios
y lo tenga por objeto en todas las cosas,
sin ningún motivo secundario, impuro o egoísta, alejado de toda hipocresía,
disimulo o formalismo, ya sea burdo o refinado.
Que todos tus pensamientos y actos sean tales que estén dispuestos
a ser examinados por el sol radiante de la Divina presencia,
y si algo falso o impuro se levanta dentro de ti contra tu voluntad,
déjalo manifiesto con sinceridad y tranquilidad delante de la Divina presencia,
y desaparecerá.

Dios es un Ser manso y amable: "`Dios es amor; y el que permanece en amor,
permanece en Dios, y Dios en él`" (1 Juan 4:16). Sé, pues, también manso,
amable y bondadoso en toda tu conducta y comportamiento.
Que todas las fuerzas airadas y discordantes de tu naturaleza
sean suavizadas por el Espíritu del amor de Jesús,
que la dureza de tu carácter sea apaciguada,
y tu obstinada voluntad del yo sea doblegada y hecha dócil;
y cada vez que algo de la naturaleza opuesta se levante en ti,
sumérgete inmediatamente en el dulce elemento de la mansedumbre y el amor.

Dios es un Ser apacible y mora en una eternidad serena.
Por tanto, tu mente debe llegar a ser como un arroyo claro y silencioso,
en el que la gloria de Dios pueda reflejarse y mostrarse.
Por ello debes evitar, interna y externamente, toda perturbación,
confusión e irritación. No hay nada en el mundo por lo que merezca la pena preocuparse,
incluso tus faltas pasadas deben humillarte, pero no perturbarte.
Dios está en Su santo templo, que todo dentro de ti calle delante de Él;^
footnote:[Ver Habacuc 2:20]
que callen tus labios, callen tus deseos y pensamientos,
calle todo lo que se refiere a tu propia actividad.
¡Oh,
cuán provechoso y precioso es un espíritu manso y
tranquilo ante los ojos de Dios! (1 Pedro 3:4).

Dios es un Ser feliz, satisfecho y lleno de alegría. Procura, pues,
adquirir un espíritu gozoso y pacífico.
Evita toda preocupación ansiosa, irritación,
murmuración y melancolía que oscurecen la mente y
te incapacitan para interactuar con Dios.
Aléjate mansamente de estas cosas cuando estás consciente de algo así, en ti.

Que tu corazón esté apartado y cerrado a todo el mundo y a todas las cosas creadas,
pero enteramente familiarizado y abierto a Dios.
Vigila estrictamente sobre ti mismo, sobre tus malos deseos,
sobre tu amor al yo y sobre la voluntad del yo; pero con respecto a Dios,
sé verdaderamente libre, como un niño afectuoso y confiado.
Considéralo como el amigo de tu corazón y no pienses
de Él nada sino lo que es puramente bueno.
Aunque todo lo que te rodea caiga en confusión,
y aunque tu cuerpo tenga dolor y esté sufriendo,
y tu alma experimente sequedad y angustia; que tu espíritu permanezca impasible,
plácido y sereno, elevado por encima de todas las cosas mudables,
y deleitándose en y con Dios internamente,
y también en lo que a Él le plazca permitir externamente.

Si te esfuerzas en ejercitarte de esta manera,
tu mente gradualmente se conformará más a Dios,
y también será cada vez más capaz de encontrar sustancialmente
a este todo suficiente y sumamente amable Bien,
y de contemplar Su beatificante rostro.

=== Con referencia a esto, añadiré las siguientes importantes observaciones:

_Primera._
Debido a que los objetos y ocupaciones externas--especialmente mientras
no estamos bien versados y establecidos en este ejercicio--causan mucha
distracción y estorban a la mente en mayor o menor grado,
y la apartan de su estado apropiado;
es altamente útil y necesario dedicar de vez en cuando durante cada día, un corto tiempo,
especial y deliberadamente,
para despojarnos completamente de todos los objetos visibles y reflexiones,
con el fin de recogernos en la presencia de Dios,
y entrar en el estado de ánimo requerido, con la ayuda de la gracia;
cada uno según lo permitan su estado y sus circunstancias externas.

_Segunda._
Por encima de todo,
debemos creer y estar firmemente persuadidos de que
todo depende de la misericordia de Dios,
y "`no del que quiere; ni del que corre`" (Romanos 9:16). Por lo tanto,
no debemos esperar encontrar y ver a Dios por nuestra propia diligencia,
mucho menos por nuestros propios esfuerzos y afanes mentales.
Nuestra actividad al acercarnos a Dios debe ser un
acto o inclinación completamente interno,
suave, tranquilo y pacífico de nuestra voluntad, nuestro amor y nuestro corazón,
que depende principalmente de la influencia divina
y de la secreta atracción del amor de Dios,
a la que debemos sencillamente atender y seguir,
y delante de la cual toda nuestra actividad debe cesar y ser silenciada.
Cuando percibimos que el Señor quiere elevarnos y recogernos,
calmarnos o tranquilizarnos,
o sentimos en el centro del alma un profundo sentimiento de satisfacción,
reverencia filial por Su presencia, o algo semejante,
debemos rendirnos sin temor a Su operación y continuar pasivos en Sus manos,
con toda sencillez y abstracción.

Con el tiempo, entonces, experimentarás que no sólo tienes un hombre exterior, un cuerpo,
sentidos y razón, que pertenecen a esta vida y a los objetos del tiempo,
sino también un hombre interior,
un espíritu noble que tiene su raíz y fundamento en la eternidad;
y que tales facultades del espíritu--independientemente de todo lo que es y sucede
en el mundo--son capaces de disfrutar y contemplar a Dios y las cosas eternas,
de manera sustancial, para su completo y verdadero deleite y reposo.

Entonces, tu amor, tu corazón, el ardiente deseo de tu alma,
cuando se vacíen de todas las cosas,
llegarían finalmente--y este es el propósito mismo para el cual
hemos sido creados y redimidos--a absorber y poseer el Bien Supremo,
la infinita Deidad, en su ilimitada capacidad.
Con todas las fuerzas de tu amor reunidas en una, abrazarías a este eterno Amor,
a este beatificante Ser, de la manera más tierna y cordial,
como un niño inocente a su bondadosa madre,
y lo estrecharías contra tu corazón con la más pura familiaridad,
y serías a su vez felizmente abrazado por Él. Podrías encerrarte, por decirlo así,
con este Amigo íntimo en tu alma, en lo más íntimo de tu ser, en el centro de tu corazón,
muy, muy lejos de cualquier criatura.
En esta dulce soledad,
a través de la bienaventurada proximidad de este todo suficiente Ser,
también llegarías a ser, en alguna medida, todo suficiente; es decir,
estarías tan perfectamente satisfecho, deleitado y contento con tu Dios,
que por toda la gloria, riquezas y placeres del cielo y de la tierra,
no echarías una mirada hacia afuera,
ni los estimarías dignos de una inclinación de tu amor, sino que, en secreto,
arderías como un serafín en el más puro amor de tu Dios,
y bajo la influencia de esta suave llama de amor,
te convertirías completamente en bondad, mansedumbre y amabilidad; sí, en amor mismo.

Tu puro entendimiento, el ojo de tu mente,
se volvería hacia dentro y se apartaría de cualquier otro objeto.
Se iluminaría, fortalecería y elevaría en espíritu por la luz de eterna sabiduría,
para poder permanecer como un querubín, con el rostro inclinado,
y contemplando el rostro de Dios, la Sabiduría misma, el espejo sin mancha.
En esta luz conocerías la luz, es decir, la verdad;
y esta misma gloria del Señor se reflejaría, a su vez,
en tu centro claro y sereno (2 Corintios 3:18). Tu rostro sin forma y desnudo,
y el rostro descubierto y beatificante de tu Dios, se encontrarían,
saludarían y abrazarían con los más afectuosos saludos.
Fijarías tu mirada sencilla, como un inocente y pequeño infante,
firme y gozosamente sobre el rostro de Dios, y Él, a su vez,
como un Padre fiel y afectivo, mantendría Su mirada dirigida hacia ti,
por medio de la cual serías completamente santificado y transformado en la imagen misma,
de gloria a gloria.

Tu mente, o capacidad intelectual, abstraída de todo gozo,
consuelo y deleite de la criatura, sería llenada del gozo más puro y más íntimo,
y de la más profunda paz.
Todo tu deleite, gozo y dicha estarían en Dios, y Dios, a su vez,
tendría Su gozo y beneplácito en ti.
Él reposaría y moraría en ti, como en Su sereno trono de paz; y tu espíritu,
que por tanto tiempo se había extraviado,
como un huérfano desterrado en una tierra extraña,
volvería a reposar dulcemente en su verdadero reposo y hogar,
y se recostaría en el regazo de Dios, en imperturbable paz,
ocultándose en la quietud de la eternidad.
En este infinito reino de paz,
vivirías intacto e imperturbable por las tempestades de los afectos,
apartado de todos los perturbadores gozos, aflicciones,
temores y esperanzas que pudieran asaltar tu espíritu desde fuera.
Y así, te convertirías en un cielo claro del siempre bendito Dios trino,
en el que Él habitaría, y que Él llenaría de Su luz, amor y toda virtud divina,
y en el que Él se glorificaría en el tiempo y en la eternidad.

Por tanto, no actúes más con insensatez, oh, tú, noble criatura e imagen del eterno Dios,
haciendo que tu espíritu real (no diré divino) y sus nobles facultades,
sean tan vergonzosamente esclavizadas por las cosas viles, miserables,
vanas e indignas de esta creación, por medio de los deseos de los ojos,
los deseos de la carne y la vanagloria del mundo.
Porque Dios ha enviado a Su Hijo para redimirte de esa esclavitud,
y para elevar de nuevo tu espíritu a la gloriosa libertad de los hijos de Dios.
Recuerda, que en lo que se refiere a tu parte superior, tú eres un hijo de la eternidad;
Dios mismo es tu Padre y tu hogar, y allí debes vivir y morar.
El mundo debe ser para ti una tierra de destierro, y tu cuerpo, una prisión y purgatorio.
¡Alza, pues, las puertas eternas de tus facultades mentales por encima de lo natural,
de los sentidos y de la razón, para que el Rey de gloria, el Dios de los ejércitos,
pueda entrar en ti!
