== Sobre la Oración Interna

La oración interna o espiritual es el acercamiento del alma a Dios,
en el nombre de Jesús, y la permanencia en Su presencia.

Para entender apropiadamente este acercamiento y ponerlo en práctica,
es especialmente necesario--como base irrevocable
de todo el asunto--que por la gracia poseamos,
atesoremos y ejercitemos una profunda impresión de la inmediata
proximidad de la presencia de nuestro Dios,
y reflexionemos en cuán cerca se ha acercado Él a nosotros,
en Su amorosa bondad hacia el hombre, en el nombre de Su Hijo Jesucristo;
y que este mismo acercamiento de Dios a nosotros,
es el fundamento y la causa procuradora de nuestro acercamiento a Él.

Dios está esencialmente presente con nosotros, de una manera que no podemos comprender.
Él llena el cielo y la tierra; en Él vivimos, nos movemos y somos.
Él también está cerca de nuestros pensamientos, inclinaciones,
deseos e intenciones más secretos;
lo más íntimo de nuestra alma yace abierto ante Su presencia.

Pero Dios, como Espíritu,
está especialmente cerca de nuestros espíritus y de los más secretos rincones
del corazón. Este espíritu nuestro no pertenece a este mundo,
ni a los objetos temporales, fue creado sólo para Dios; por lo tanto,
es capaz de disfrutar verdadera comunión con Él. Puede, y debería,
ser el templo y la residencia sagrada de la Deidad.
Su ocupación es contemplar, amar y disfrutar a este benefactor Ser y reposar en Él;
para este fin fue creado, para esto posee capacidad.
Dios, como Espíritu,
está cerca de nuestros espíritus y sólo allí puede ser buscado y hallado.

Este hermoso y adorable Ser, no sólo está presente con nosotros como Dios,
sino también como nuestro Dios en Cristo Jesús, como Dios con nosotros,
como nuestro Redentor, Salvador y verdadero amigo de nuestras almas;
que tiene cuidado de nosotros, que se acuerda de nosotros en amor,
que mediante Sus persuasiones nos atrae a Él,
que está dispuesto a morar en nosotros y a permanecer con nosotros eternamente,
independientemente de nuestra indignidad y miseria,
si tan sólo abrimos y rendimos nuestros corazones a Él. Esta es una verdad grande,
evangélica y fundamental, que debemos grabar profundamente en nuestra mente,
y nunca permitir que se nos prive de ella,
porque incluye en sí todo el fundamento de nuestra redención
y salvación. Voy a demostrar brevemente esto.

El hombre caído, en lo que respecta a su parte interna,
yace atado en tinieblas y en el abismo infernal.
Estas tinieblas y este abismo los lleva con él durante la vida,
y es lo que encuentra en la muerte, cuando muere fuera de Cristo.
Durante este estado, Dios y Su reino de amor están lejos de él,
y fuertemente cerrados contra él.

Dios, en Su bienaventurada eternidad, tuvo compasión de él;
compasión--que en Su amorosa bondad--manifestó en la encarnación,
sufrimientos y muerte de Su Hijo.
Cuando Jesucristo, nuestro querido Redentor, derramó Su sangre por nosotros,
las compuertas de la tierna misericordia de Dios hacia el hombre fueron abiertas,
de modo que Dios está ahora inexplicablemente cerca de nuestros corazones,
en el nombre de Su Hijo Jesús. Por Su muerte, el velo ha sido rasgado,
no sólo en el templo en Jerusalén,
sino que también se ha abierto el camino a una eternidad de paz y bienaventuranza,
de manera que la bondad, gracia,
amor y comunión con Dios permanecen abiertos en los corazones de los más viles pecadores,
si tan sólo van a Él; sí,
este amigo cercano del hombre está incluso de antemano con nosotros.
Está a la puerta de nuestros corazones y llama de diversas maneras; nos espera,
y no desea nada más que el pecador se vuelva a Él y viva.
Su mensaje a nosotros es hoy: "`Arrepentíos,
porque el reino de los cielos se ha acercado`",
y "`teniendo libertad para entrar en el Lugar Santísimo por la
sangre de Jesucristo...acerquémonos`" (Hebreos 10:19-22).

Ahora bien,
la verdadera oración espiritual consiste en este acercamiento o aproximación. No estoy
haciendo aquí alusión al primer acercamiento de un pecador arrepentido a Dios,
en su conversión inicial, en la que se vuelve de manera general a Dios y se entrega a Él,
con la sincera determinación de vivir de ahora en
adelante sólo para Aquel que murió por él,
y se levantó de nuevo.
Presupongo necesariamente este paso preliminar y feliz, y no hablo de él aquí,
sino que me refiero a la perseverante continuación de ese acercamiento,
en un alma entregada a Dios.

Aquellos que son realmente persuadidos por Él y se entregan a Él,
no pueden descansar satisfechos con la dedicación
general que hicieron en su primer despertar;
y aunque reconocen esta primera conversión--cuando ha sido genuina--como
un memorial eterno de la infinita misericordia de Dios,
no pueden contentarse con ella, sino que con el paso del tiempo,
observan una inclinación latente por medio de la
cual son más y más alejados de todas las demás cosas,
y conducidos y exhortados a poner sus afectos en Dios.
Perciben que se requiere de ellos algo noble, cabal y completo;
sus corazones les dicen de parte de Dios,
que Él desea tenerlos sólo y totalmente para Él. En algunos,
este sentimiento es claro y poderoso; en otros, débil, oscuro y general,
según el estado de la mente sea estable o confuso.
¡Feliz el individuo que reconoce dentro de él este llamado divino y santo,
y se rinde a él infantil e incondicionalmente!

Esta inclinación latente a la que hago alusión arriba,
surge de la inmediata proximidad de Dios a nosotros en el nombre de Jesús. Porque Dios,
que es el amor mismo, toca nuestros espíritus con Su amor, como un imán atrae el hierro.
Él nos atrae a Sí mismo, y de ahí que nuestros espíritus sientan tal impulso y tendencia,
que no puedan descansar satisfechos con algo que no sea Dios.
Si prestamos la debida atención a esto y continuamos internamente recogidos,
quitando cada obstáculo del camino del espíritu--mediante
el ejercicio de la negación al yo--y seguimos este impulso,
entregándonos completamente en las manos de Dios, este principio,
como un poder impulsador, conducirá al alma a Dios por medio del amor,
tal como un arroyo fluye hacia el océano, y como una piedra que pende en el aire,
cae a la tierra que es su centro de atracción. El ejercicio de
la oración interna es permanecer en esta inclinación fundamental,
y por este medio, acercarnos y entregarnos a Dios en Cristo Jesús,
mientras negamos y abandonamos todo lo demás.

Entonces, nuestros espíritus se convierten en templos,
en los que la gloria de Dios--como en el Lugar Santísimo--está cerca de nosotros.
El altar es el nombre de Jesús; el sacrificio: nuestro corazón, nuestra voluntad,
nuestro todo.
El amor de Dios que enciende nuestros deseos en pos de Él, mediante Su secreta operación,
es el fuego eterno, cuyas llamas son la verdad y la sinceridad.
En la medida que el mundo, la corrupción y el yo permanezcan en nosotros,
en esa misma medida todavía queda humedad en la madera y en la ofrenda,
la cual es gradualmente secada por la llama.
Esta llama es lo que previamente denominé como inclinación amorosa,
que se manifiesta a sí misma en las almas de los principiantes,
y en aquellos que caminan por los sombríos senderos del sufrimiento y de la aflicción,
por medio de profundos suspiros y gemidos.
Si el alma es obediente, se manifiesta a sí misma por medio de un gentil:
"`¡Abba Padre!`", o por algo más de naturaleza familiar, que asciende como un grato olor.
Finalmente, forma la base de una paz permanente,
por medio de la cual el corazón y la mente son guardados
en Cristo Jesús. Cuanta más humedad permanezca,
más ferozmente arde el fuego y más humo produce.
Después, arde más claramente y menos intensamente,
hasta que se convierte en un calor divino, internamente tranquilo y delicioso.

Termino con las hermosas palabras de David en el Salmo 65:4,
donde elogia así la oración interna: "`Cuán bienaventurado es aquel que Tú escoges,
y acercas a Ti, para que more en Tus atrios.
Seremos saciados con el bien de Tu casa, Tu santo templo`".
