== Importantes Reglas de Conducta

[.chapter-subtitle--blurb]
Dirigidas a una Sociedad de Cristianos que Viven Juntos

¡Qué la bendición de Jesús, el Salvador, sea con ustedes,
para que sus corazones puedan ser llenados de gracia y paz celestial,
tanto aquí como en el porvenir, para la gloria de Su nombre!
Amén.

Atiendan con sentimientos de sencillez, devoción y buena voluntad,
y no meramente por hábito,
la exhortación que ahora se les dirigirá en el nombre del Señor,
y de todo corazón. Pero que cada uno se examine también a sí mismo por medio de ella,
y no la considere a la ligera.

Recuerden que su hogar y sus corazones deben ser morada del Altísimo
Señor. El Señor Jesús mismo será administrador y sostén de ustedes,
y Sus ángeles santos sus compañeros.
Por tanto, juzguen ustedes mismos con qué devoción, serenidad,
sencillez y sinceridad deben conducirse, tanto interna como externamente,
en la sagrada presencia del Señor, si desean que Él permanezca con ustedes y en ustedes,
y si ustedes desean continuar participando en Su favor y bendición divinos,
tanto en lo que se refiere al cuerpo como al alma.

El llamado de ustedes es que sinceramente abandonen el mundo y su espíritu--que
mueran continuamente a la naturaleza corrupta y a toda la vida del yo,
y conversen noche y día con Dios en sus corazones,
en el ejercicio de la verdadera oración. ¡Cuán santa y bendita es la vocación de ustedes!
Entréguense a ella afectuosamente y con gran fidelidad.
Este es el objetivo, que también sea la constante ocupación de ustedes.

No oren sólo en determinados tiempos, sino dondequiera que se encuentren.
Y cada vez que se reúnan,
esfuércense por mantenerse en un estado de ferviente deseo hacia Dios y en Su presencia;
como si cada uno de ustedes estuviera solo en la casa con Dios,
pero sin mucho demostraciones y gestos externos.
Y cuando alguno desee conversar con otro, ya sea en el trabajo o en otras ocasiones,
que primero piense en su propia mente: "`Mi hermano o hermana está orando,
no debo perturbar`",
para evitar en la medida de lo posible toda conversación innecesaria,
incluso de cosas espirituales.

De nuevo, oren mucho hablen poco.
¡Oh, permítanme recomendarles especialmente ese silencio sagrado,
gentil y pacífico que Dios y todos Sus santos tanto aman!
El espíritu de locuacidad es la plaga de toda sociedad religiosa;
es la extinción de la devoción, produce confusión en la mente,
y es un abuso del tiempo y una negación de la presencia divina.
El amor, la obediencia o la necesidad deben influir la lengua al hablar,
o de lo contrario, debe continuar en silencio.
Aún en las cosas espirituales,
edifíquense unos a otros más por un caminar santo que por una multitud de palabras.
Dios sólo habita en las almas pacíficas y la lengua debe
estar en paz también. ¡He aquí el fruto sagrado del silencio!
Da tiempo, fuerza, recogimiento, oración, libertad, sabiduría,
la compañía de Dios y un estado de ánimo bendito y pacífico.

Ámense sinceramente unos a otros como hijos de Dios,
y crean que son amados por los otros, aunque no se manifieste nada de ello,
o se manifieste incluso lo contrario.
Que cada uno sea de antemano con su hermano, genuinamente amable, atento y sumiso,
como si lo hiciera para el Señor con toda sinceridad.
Lleven los unos las cargas de los otros, de cuerpo y alma, como si fueran propias.
Estén siempre dispuestos a servirse unos a otros con alegría y sincera humildad,
y a lavarse mutuamente los pies, por decirlo así,
o en los oficios más humildes y laboriosos.

Recuerden las importantes palabras de Jesús: "`No vine para ser servido,
sino para servir`". Por lo tanto, bajo la conciencia de su propia indignidad,
nadie debe esperar ser servido por los demás; y según este sentimiento,
no debemos creer que alguna criatura nos muestra
demasiada amabilidad o nos agravia demasiado.
Que cada uno realmente piense de sí mismo, que es el más infiel, el más miserable,
el más inadecuado, el más bajo de todos; y por lo tanto,
debería desear razonablemente ser poco considerado y ser olvidado por todo el resto.
Estén dispuestos a ceder los unos a los otros en todas las cosas.
Que cada uno se humille ante el otro por amor al Señor;
por este medio se obtendrán y preservarán el fervor y la paz en el corazón.

Eviten toda sospecha.
No presten oído entre ustedes al acusador de los hermanos,
y no permitan que se albergue la ira o la amargura en sus pechos.
Den la mejor interpretación de todo lo que pueda
parecer ofensivo para ustedes o para otros.
Sólo miren lo que es bueno en otros, a fin de que puedan amarlo,
agradecerle a Dios por ello e imitarlo.
Pero no señalen sus debilidades, o si ustedes las observan,
encomiéndelas a Dios en oración, y olvídenlas de nuevo inmediatamente,
a menos que sea deber de ustedes recordarlas.
Si alguien es sorprendido en una falta o pecado contra su hermano,
que vaya inmediatamente y confiese su culpa en genuina humildad.
Por este medio, Satanás será pisoteado bajo sus pies, el amor mutuo será confirmado,
y el favor de Dios se dirigirá doblemente hacia ustedes.

No busquen más que la moderada satisfacción de las necesidades del cuerpo,
y tengan cuidado del sutil engaño de las riquezas.
¿Qué tenemos que ver con la basura venenosa del mundo?
¿Acaso no hemos sido redimidos de la tierra y llamados a la eternidad?
¡Oh, amen y ejerciten esa estimable virtud de la pobreza interna y externa de Jesús,
quien tiene cuidado de nosotros!
Amen, por amor al Señor, eso que es pequeño, insignificante, despreciable,
desagradable y gravoso en todo,
para que internamente vivan sin estorbos en comunión con Dios,
y externamente se gocen en la compañía los unos con los otros.

Huyan de todo egoísmo, como la más grande peste de la vida social.
Que nadie desee algo que no estaría dispuesto a concederle a su hermano,
incluso más rápido que a sí mismo; porque somos llamados a negarnos a nosotros mismos.
Que nadie posea nada, grande o pequeño, sea lo que sea,
de lo que no estaría dispuesto a desprenderse rápidamente y dárselo a su hermano.
Si no nos despojamos así de todo lo que consideramos propio,
todavía somos idólatras y no verdaderos siervos de Dios,
y debemos continuar privados de una noble, pura y pacífica libertad de espíritu,
y de un acercamiento sin obstáculos a Dios.

Cada uno de ustedes crea que el lugar de su actual morada,
su estado y su ocupación es el que Dios le ha designado,
y en el que al presente Él desea que le siga sirviendo;
que es el más adecuado para su avance en la verdadera santidad,
que no se debe abandonar--ni siquiera desear abandonar--sin
un claro conocimiento de la voluntad divina.
Esto compondrá sus mentes y los despojará de mil escrúpulos innecesarios,
reflexiones perjudiciales y distracciones de pensamiento, con los que, de otro modo,
el tentador podría atormentarlos.
Esto los hará ver con otros ojos, no sólo su morada, estado y ocupación,
sino también sus dificultades,
decepciones y cualquier otra cosa con la que se puedan topar,
recibiéndolo todo como de la mano del Señor,
y soportándolo con más alegría. Esto también fomentará
en gran medida el amor y la paz entre ustedes.

Cada uno considere bien, y por gracia quede profundamente impresionado,
con el objetivo por el que Dios lo llevó individualmente a dicha morada, que es,
para que Le sirva en ella y sea ejercitado en la santificación. Ustedes
no han sido situados ahí para que vivan tranquilamente y a gusto,
según la carne y la voluntad propia,
y para servir a Dios según sus propios caprichos e ideas;
sino para que la carne sea crucificada con sus afectos
y pasiones--para que entreguen al juicio y a la muerte,
la naturaleza carnal, la sensualidad, la razón,
la voluntad del yo y el amor al yo--y así caminen en directa oposición a ustedes mismos,
y amen a Dios con pureza y fervor.
Por esta razón el Señor los ha llevado a esta casa,
para que se esfuercen por ella en unión de corazón y alma,
y se asistan unos a otros en oración y en vida santa;
porque cuando dos o tres se reúnen en el nombre de Jesús, ahí está Él en medio de ellos.
Cada uno preste atención a cómo se ejercita en este particular,
y por ninguna razón lo olvide cuando Dios se proponga ejercitarlo en ello; sino más bien,
aproveche ansiosamente cada objetivo y oportunidad
que la bondadosa mano de Dios le presente,
para exponer,
atacar y destruir lo arriba mencionado y otros síntomas de su natural
depravación. Reciban con agrado la hora en la que Dios les envía
a un querido amigo para ayudarlos a vencer al adversario.
Amen a dicha persona muy cordialmente.
Aquel que no resuelve perder seriamente su propia vida, no merece el nombre de Cristiano,
y no vivirá ahí ni en ningún otro lugar en paz,
sino que se confundirá tanto a sí mismo como a otros.

Cuídense de una mente y disposición disipadas.
En tal estado, serán atacados por mil tentaciones combinadas y opuestas.
Si quieren evitar cometer faltas y provocar disturbios,
hablen escasamente y no determinen nada, mientras sus mentes estén así de distraídas;
porque en ese momento están en una luz falsa y en la confusión de la naturaleza.
Vivan retirados en el centro de sus corazones con Dios como niños inocentes,
quienes a pesar de que son incapaces de razonar, poseen mucho amor y afecto;
y como tales, beban de los pechos del amor divino.
Entonces, les parecerá que todo es bueno y está bien tal como viene,
y lo que hagan o digan los demás. Así llegarán a
ser todo mansedumbre y bondad unos para con los otros.
En confianza filial hacia su Padre celestial,
tendrán buen ánimo y experimentarán que Sus mandamientos no son difíciles.

Que Dios mismo os conceda gracia, sabiduría y fortaleza en todas las cosas,
para que con verdad se pueda decir de ustedes: "`Mirad cuán bueno y cuán delicioso es,
que los hermanos vivan juntos en armonía;
porque allí envía el Señor la bendición y la vida eterna.`"
Amén.
