== Sobre la Fe y la Justificación

[.chapter-subtitle--blurb]
Muchos poseen la palabra de verdad, pero no tienen la verdad de la palabra.

La fe es una convicción interna de la verdad de cosas invisibles y futuras,
relacionadas con nosotros.
Aquel que cree desde su corazón que hay un Dios vivo y omnisciente en el cielo,
y que Su palabra es verdad, está en posesión de la fe salvadora.

"`Muy bien`", dirán muchos, "`si eso es todo, todo está bien conmigo,
porque yo he creído esto desde mi juventud`". ¿Pero realmente lo
crees de corazón? Este creer de corazón es obra del Espíritu Santo.
Prueba y muéstrame tu fe por medio de tus obras.
"`¿Qué obras?`", podrían decir algunos, "`nos salva la fe, las obras no`". Cierto,
pero la fe y las obras van juntas, y andan juntas en las mismas pisadas; de lo contrario,
no creemos realmente lo que decimos o pensamos que creemos.
Por ejemplo, si yo le dijera a una persona severamente herida: "`¡Amigo,
tu herida es peligrosa,
ve inmediatamente a un médico!`" ¿Cómo sé que ha creído mi advertencia?
Porque realmente va al médico y se pone bajo su cuidado.
Dile a cualquiera que muere de hambre: "`¡Mira,
allá hay un hombre rico que da gustosamente a todo el que le pide!`" ¿Cómo sabes que
te creyó? Porque realmente se apresura a ver al hombre rico y le suplica ayuda.
Si alguien nos dijera que la casa de nuestro vecino
está en llamas y nos pide que corramos a apagarlas,
pero nos quedamos sentados a pesar de las noticias y no vamos al lugar,
es evidente que no le creímos, porque si le hubiéramos creído,
nos habríamos apresurado inmediatamente a salvar lo que pudiéramos.

"`¡Cuántas obras hacen las personas`", dice el mundo, "`cuánto trabajo se toman;
como si pudieran merecer el cielo por su piedad!`" ¡Sí, mi amigo, si tú creyeras,
también te apresurarías a salvar tu alma, porque tú eres ese hombre gravemente herido,
ese hombre empobrecido, y la morada de tu alma ya está en llamas!

En consecuencia,
la fe es el fundamento y fuente principal de todas las buenas obras y acciones santas.
(Hebreos 11)

Pero la fe justificadora no puede ser esa fe,
por medio de la cual yo simplemente creo que soy justificado.
La fe justificadora consiste en que un pobre y humillado pecador,
creyendo que puede encontrar perdón, ayuda y salvación sólo en Cristo, va a Él,
hambriento y sediento (Juan 6:35),
Lo acepta como es ofrecido en el evangelio (Juan 1:12), y para este fin,
se encomienda y se entrega a Él con esta fe,
a la que la justificación está inseparablemente conectada.
Sin embargo, Dios le da la seguridad de su perdón, en un mayor o menor grado,
más temprano o más tarde, según sea Su complacencia, y según sea útil para el alma.
No obstante, no sólo es necesario creer una vez, sino _sin interrupción;_ por lo tanto,
debemos estar cimentados en la fe, debemos mantenernos en la fe,
a través de muchos cambios, cruces y pruebas,
y así nuestra justificación será más confirmada y más gloriosa (1 Pedro 1:6-7;
2 Pedro 1:10)

La justificación, según las Escrituras y la experiencia, es propiamente cuádruple;
lo cual, al ser rara vez distinguido suficientemente,
es la causa de muchos malentendidos y controversias.

_La primera Justificación_ toma lugar externamente y es, sin embargo,
el fundamento de todas las demás; a saber, cuando Cristo como nuestro fiador,
se presentó delante del severo tribunal de la insultada Majestad en el cielo,
durante Sus sufrimientos en el Getsemaní y en la cruz,
y en virtud de Sus méritos y perfecta expiación,
fue absuelto y justificado en nuestro lugar ante el tribunal.
Cristo mismo habla de esta justificación:
"`Cercano está el que me justifica`" (Isaías 50:8).
"`Del juicio fue quitado`" (Isaías 53:8). Pablo dice:
Cristo "`fue justificado en el Espíritu`" (1 Timoteo 3:16). Ver también Romanos 6:7,10.

Ahora bien, así como Adán no cayó únicamente por sí mismo,
pues al ser el gran progenitor de la raza humana, nuestra cabeza común,
todos sus descendientes cayeron con él también;
tampoco Cristo se presentó únicamente por Sí mismo.
Él fue nuestro representante general, la planta de renombre, el hombre Zemach,^
footnote:["`El varón cuyo nombre es el Renuevo`" Zacarías 6:12-13.]
la cabeza patriarcal de todos los redimidos; y así como Él se levantó justificado,
todos los redimidos fueron justificados con Él. Al ser justificado Él,
quien es nuestro Mediador y Fiador, así también nosotros.
Y esto es tan cierto y tan verdadero, que todos los verdaderos creyentes pueden decir,
que si uno murió y fue justificado por todos,
entonces todos murieron y todos fueron justificados.
Al que no conoció pecado, por nosotros lo hizo pecado,
para que nosotros fuésemos hechos justicia de Dios en Él. (2 Corintios 5:21)

En virtud de esta justificación en nuestro lugar,
Dios pasa por alto el tiempo de ignorancia (Hechos 17:30),
pero ahora les manda a todos los hombres en todo lugar que se arrepientan,
y le ofrece a todo hombre, a través de la resurrección de Cristo, fe y justificación.^
footnote:["`...por cuanto ha establecido un día en el cual juzgará al mundo con justicia,
por aquel varón a quien designó,
dando fe a todos con haberle levantado de los muertos.`"]
Él externamente
les suplica e invita a los hombres por medio de sus mensajeros,
e internamente por medio de Su Espíritu, diciendo:
"`Reconciliaos con Dios`". "`Arrepentíos, porque el reino de los cielos se ha acercado`".

¡Oh, alma mía, adora,
admira y asómbrate ante este abismo de amor divino! ¡Así me ha amado Dios,
antes de que existiera un átomo de mi ser!

¡Qué gracia! ¡Él dio a Su hijo por mí! Contemplo a Aquel que no conoció pecado,
de pie ante el tribunal de la justicia divina por mis crímenes y por mis deudas,
que Él tomó sobre Sí como propios, y pagó el precio de todos mis pecados,
y los del mundo entero.
Lo contemplo en la cruz borrando el acta que había en mi contra.
Lo contemplo, después de haber entrado con Su propia sangre al lugar santo,
regresar con una liberación completa y válida, y con la eterna redención,
mientras que al mismo tiempo me ofrece Su gracia y salvación. ¡Entonces, ven alma mía,
mientras puedas,
y ama Al que te amó primero y te ha dado a conocer este gran misterio de Su voluntad,
en el que incluso los ángeles anhelan mirar!

_La segunda justificación_ toma lugar en el corazón
y conciencia de un humilde y cargado pecador,
que viene a Cristo con un deseo ardiente de misericordia;
mientras que eso que ha sido cumplido externamente y para él,
le es apropiado por el Espíritu Santo; a saber, que por causa de Cristo,
todos sus pecados le son perdonados, se le concede un corazón limpio,
una mejor esperanza y libre acceso a Dios.

Cuando una mujer miserablemente pobre y arrestada por deudas,
se convierte en la esposa de un hombre rico, todas las deudas de ella pasan a ser de él,
y ella queda absuelta en el juicio.
Las posesiones de su esposo ahora le pertenecen a ella; pero a partir de ese momento,
el corazón y la voluntad de ella, ¡es más!, todo lo que ella es y tiene,
ya no le pertenecen, sino a su esposo.
De igual manera, la fe verdadera y viva nos une a Cristo, no meramente en idea,
sino en realidad, y así somos justificados por gracia, sin obras.
Pero tan pronto como el alma, como la mujer pobre, se une por fe a Él,
entonces sucede lo que está escrito: "`Inclínate ante Él,
porque Él es tu señor,`" (Salmo 45:11). Él se vuelve nuestro, con todo lo que Él es;
y nosotros nos volvemos de Él, con todo lo que poseemos,
(Lucas 15:31). Desde ese momento, estamos en el camino y en el estado de salvación,
y desde ese momento también, en el camino y en el estado de santificación, (Efesios 2:10;
Tito 2:6,8,14).

Esta justificación es el fundamento y comienzo de la piedad en Jesucristo,
quien por este mismo propósito murió por todos, "`para que los que viven,
ya no vivan para sí, sino para aquel que murió y resucitó por ellos`". (2 Corintios 5:15)

Aunque esta justificación puede ser considerada como un procedimiento judicial, aun así,
debemos ser cuidadosos de no medir las obras de Dios con algún criterio humano.
Ante un tribunal humano,
la hipocresía puede engañar exitosamente y un ladrón puede ser perdonado,
quien todavía retiene una propensión tan ladrona como antes.
Con Dios el caso es diferente.
Su sentencia judicial es una palabra poderosa que crea lo que pronuncia;
tranquiliza la conciencia,
y al mismo tiempo renueva el corazón. Cuando Él justifica al impío,
también lo hace justo.

Por tanto, el alma penitente tiene un fundamento de confianza en su interior,
en el cual puede valientemente perseverar y proseguir.
La certeza absoluta del perdón de pecados puede acompañarla en mayor o menor grado,
antes o después, o faltar por completo, según el beneplácito de Dios.
Esta seguridad no es absolutamente necesaria para la justificación;
pero un fruto inseparable y la prueba más segura de la justificación
es la sinceridad de corazón en Cristo,
el odio a todo pecado reconocido,
y un sincero deseo y amor a Aquel que nos ha amado y perdonado.
Si falta este fruto, también falta la justificación.

Esta justificación mantiene continuamente su lugar,
a lo largo de todo el camino de la piedad.
Es, y sigue siendo, el fundamento de principio a fin;
porque los pecados y las imperfecciones continúan surgiendo,
y cuando los hijos pecan por debilidad,
son de nuevo reconciliados con el Padre a través de la intercesión de Cristo.
(1 Juan 2:1) Un crecimiento en la santificación,
también descubre más y más las corrupciones de la carne y del espíritu, del amor al yo,
de la vanidad, la secreta confianza en los dones, buenas obras, etc.,
y así nuestra santidad misma, interna y externa,
requiere justificación. Nuestras mejores vestiduras deben
ser lavadas y emblanquecidas en la sangre del Cordero.
(Apocalipsis 7:14)

_La tercera justificación_ de la que hablan las Sagradas Escrituras,
es principalmente esa por la que somos reconocidos
como justos ante la vista de los demás,
y no es otra cosa que santificación,
en el sentido de que da testimonio mediante sus innegables frutos,
de que estamos en posesión de esa fe que nos justifica ante los ojos de Dios.
'`Muéstrame tu fe por tus obras`', dice el apóstol Santiago.
(Santiago 2:18). La fe que justifica nos une a Cristo--como nuestra Cabeza y Vid,
o fundamento de una nueva vida--y ésto debe manifestarse o justificarse a sí mismo.

La santificación y sus frutos no justifican ante
el tribunal de la ofendida Majestad en los cielos.
Incluso el hombre según el corazón de Dios debe orar aquí:
"`Y no entres en juicio con tu siervo;
porque no se justificará delante de ti ningún ser humano`" (Salmo 143:2), pero aun así,
justifican ante el tribunal de la iglesia.
Los verdaderos creyentes siguen la santidad y hacen lo bueno con gusto,
pero no son justificados por este motivo delante de Dios (1 Corintios 4:4);
no pueden presentar esto delante de Dios para así recibir justificación,
ni aquí ni en el futuro; los verdaderos creyentes no lo hacen,
sino que lo olvidan (Mateo 6:3;
25:27). Pero Dios no es injusto para olvidarlo (Hebreos
6:10). Las obras no van delante de ellos,
como para abrirles las puertas del cielo, sino que los siguen (Apocalipsis 14:13);
y comerán el fruto de su trabajo (Isaías 3:10). Los
que están en Cristo Jesús no vienen a condenación,
sino que son justificados en Cristo Jesús,
según la sentencia judicial del divino beneplácito (Mateo 24:34; Romanos 2:7).

Sin embargo, la santidad con sus frutos, puede dar testimonio con la conciencia,
de la justificación ante los ojos de Dios recibida por gracia.
Si nuestro corazón no nos condena,
sino que nos absuelve y atestigua que poseemos un amor operativo,
entonces podemos descansar satisfechos y tener buen ánimo.
Pero este no es el tribunal más alto;
tampoco el corazón es siempre infalible e imparcial, sea al acusar o excusar.
Por lo tanto, debemos seguir orando con David, aunque nuestro corazón nos excuse:
"`Examíname, oh Dios, y conoce mi corazón; pruébame y conoce mis pensamientos;
y ve si hay en mí camino de perversidad,
y guíame en el camino eterno`". (Salmo 139:23-24)

De esta manera, el hombre es justificado por obras y no sólo por fe,
(Santiago 2:14). "`El que hace justicia es justo, como él es justo`" (1 Juan 3:7);
el que piensa lo contrario se engaña a sí mismo.
El que está en Cristo Jesús mediante una fe verdadera,
evidencia por medio de sus pensamientos,
palabras y obras el fundamento sobre el cual está. A través de la genuina conversión,
somos injertados en Cristo; y por lo tanto,
también somos plantados en la casa de la iglesia de Dios,
para que florezcamos en los atrios de ese templo, cuya belleza es la santidad.
(Salmo 96:9)

Sí, el caminar santo e irreprochable de los creyentes,
debería también justificarlos ante los ojos del mundo,
como cartas de Cristo conocidas y leídas por todos.
(2 Corintios 3:2)

¡Ay,
querido Salvador! ¡Cuánto te deshonran a Ti y a Tu nombre
las personas que se llaman a sí mismas por Tu nombre,
y sin embargo, no dejan ver en ellos nada que sea digno de Tu nombre, de Tu Espíritu,
ni de Tu doctrina!
Con toda la jactancia que hacen de Tus méritos,
pisotean vergonzosamente Tu sangre y Tus méritos bajo sus pies.
¿Puede ser Tu pueblo,
los que te sirven sólo a veces con sus labios y a Tus enemigos diariamente en sus corazones?
¿Pueden ser Tus hijos aquellos que evidencian por sus acciones,
que no poseen Tu naturaleza divina ni en la más pequeña medida?
¿Son ellos las ramas vivas de la verdadera Vid,
que no llevan más que uvas silvestres y frutos corruptos?
¡Oh, no, querido Salvador!
El que comete pecado nunca Te ha visto, nunca Te ha conocido.
Un corazón engañoso se jacta falsamente de pecado perdonado.
Cristo no es ministro de pecado.
No te conocen los que se apropian así de Tus méritos y de Tu justicia,
mientras pecan y hacen uso de ellos como de un manto para sus pecados.

_La cuarta justificación_ es la que deseo que yo y los demás conozcamos,
más por experiencia que por una simple descripción de ella.
Puede ser llamada la justificación inherente y final
ante el tribunal del Beneplácito divino.
La justificación, comúnmente llamada así,
y la santificación fluyen juntas en dicho Beneplácito,
y alcanzan su plenitud en Él. El fin indiscutible de todos
los caminos de Dios con el hombre caído es,
que Dios, a través de la restauración del hombre,
puede ser glorificado nuevamente y convertirse en _Todo en Todos._

En la segunda y tercera justificación y santificación, el hombre aparece como culpable,
avergonzado y completamente degradado; mientras que, por el contrario,
Dios y la gracia gratuita en Cristo son altamente exaltados y glorificados.
La vida natural y pecaminosa del hombre (además de la cual no posee nada),
con todas las corrupciones de la carne y del espíritu, son manifestadas,
negadas y matadas; y Cristo y el reino de Su gracia, se levantan en su lugar.
El hombre, con todos sus propios intentos de piedad, santidad, fidelidad y devoción,
por muy latentes que sean, poco a poco se avergüenza delante de Dios;
siente que debe dejarle a Cristo la obra y la operación de su espíritu dentro de él;
que debe darle cabida a Cristo, hacerle espacio,
y dejarle obrar y vivir en él. En resumen, que debe decrecer y que Cristo debe crecer,
hasta que pueda decir con verdad: "`Ya no vivo yo,
Cristo vive en mí`" (Gálatas 2:20). Cristo mismo es hecho para él sabiduría, justicia,
santificación y redención, no sólo objetivamente y por apropiación,
sino también inherentemente, en virtud de Su morada misericordiosa en él.

Entonces, Dios aprueba otra vez Su propia bondad, la que Él ha implantado en el alma,
es decir, lo que Cristo ha obrado en el corazón por medio de Su Espíritu.
Dios declara bueno el estado de gracia del individuo (Romanos 8:16; Hebreos 11: 5),
su santidad, belleza y virtudes porque son de Cristo.
Sus obras Lo complacen porque son hechas en Dios (Juan 3:21). Entonces,
Dios descansa con deleite en las obras de Sus manos, como en el principio, (Génesis 2:2).

Pero antes de que este pueda ser el caso, es necesaria mucha negación al yo;
y antes de que Cristo pueda tener la preeminencia en todas las cosas,
es necesario mucho abandono de nosotros mismos, para ser hallados completos en Cristo.
Pablo estaba justificado y santificado, y estaba en Cristo,
y sin embargo proseguía adelante (Filipenses 3),
deseaba ser hallado aún más completo en Cristo, no teniendo su propia justicia, etc.
De esta manera, Jehová mismo se convierte finalmente en nuestra justicia,
en el pleno sentido de la palabra (Jeremías 23:6), y somos capaces de decir:
"`Ciertamente en Jehová está la justicia y la fuerza`" (Isaías 45:24).

¡Sí, amén! ¡Que tú lo seas todo y yo nada! ¡Este, mi Dios, es el objetivo de mi deseo;
hacia esto tienden todos Tus tratos con nosotros los hombres;
hacia esto conducen todos Tus caminos y todos Tus juicios! ¡No hay nadie bueno, o santo,
o justo, sino sólo Tú! Los santos en el cielo y todos en la tierra,
sólo son santos por medio de Ti,
y porque Tu morada en ellos les comunica algo de Tu bondad y santidad.
Toda nuestra justicia, toda la bondad que podemos poseer fluye de Ti, su fuente original,
y debe regresar a Ti sin mezcla.
¡Sólo Tu eres grande y excelso, mi Dios!
Déjame yacer aquí y en la eternidad a Tus pies, y decir:
"`¡Al que está sentado en el trono, y al Cordero, sea la alabanza, la honra,
la gloria y el poder, por los siglos de los siglos.
Amén!`"

De esta cuádruple justificación, muchos le prestan atención solamente a las dos primeras,
pero no en la conexión esencial de ellas con el desarrollo
de la verdadera santidad y unión con Dios en Cristo.
Los que desean mejorar en esto, a veces consuelan a todos con el evangelio;
y otras veces exigen de las personas una vida santa, sin señalarles, como deberían,
a Cristo, quien es el único que puede santificar.

Muchos hombres bien intencionados,
que ven el lamentable abuso de la doctrina de la
justificación (a menudo promovida con bastante descuido),
son llevados a negar las dos primeras, o al menos, la segunda,
y desean que todo lo que las Sagradas Escrituras dicen de la justificación,
se entienda simplemente a partir de la tercera y de la cuarta.
Tampoco son pocos los que no quieren oír nada de las últimos dos tipos de justificación,
fácilmente pasan por alto la segunda, y le prestan atención solamente a la primera,
y de una manera muy imperfecta y superficial.

Así dividen y desmiembran las personas a Cristo y Su palabra,
cada una tomando lo que le conviene y concuerda con ella;
mientras que muy pocas Lo reciben completamente,
tal como es ofrecido a nosotros en el evangelio.

Ojalá que éste no sea nuestro caso, sino que seamos de una y la misma mente;
aferrándonos afectuosamente al Cristo crucificado por nosotros como nuestra justificación,
y al Cristo que habita y vive en nosotros como nuestra santificación.
Y por fe y amor permanecer en Él hasta el fin,
para que finalmente podamos decir: "`Somos hechos partícipes de Cristo`" (Hebreos 3:14).
